ngageoint/hootenanny

hoot-services/src/main/java/hoot/services/writers/review/ReviewItemsSynchronizer.java, hoot-services/src/test/java/hoot/services/review/ReviewTestUtils.java, hoot-services/src/test/java/hoot/services/writers/review/ReviewItemsSynchronizerTest.java
=> Prevent services tests from setting non-test review records to resolved

hoot-core/src/main/cpp/hoot/core/io/OgrOptions.h, hoot-core/src/main/cpp/hoot/core/io/OgrWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/ShapefileWriter.cpp
1. refs #64 Shapefile export doesn't maintain foreign characters
=> Fix foreign character export in SHP

hoot-core/src/main/cpp/hoot/core/io/OgrReader.cpp
1. refs #4399 No translation for Mercator_Auxiliary_Sphere to Proj.4
I added another WKT hard coded conversion to a valid EPSG code.
=> Add another web mercator conversion

hoot-core/src/main/cpp/hoot/core/elements/Relation.h, hoot-core/src/main/cpp/hoot/core/util/ElementConverter.cpp, plugins/mgcp.js, plugins/tds61.js
@bwitham: could you review and merge this please.
@mv003348: Should be ready build again after Brandon reviews & merges.
=> #120 TDSv61 & MGCP export errors

hoot-services/src/main/java/hoot/services/controllers/ingest/CustomScriptResource.java
=> Remove '(Hootenanny Default)' from translations

hoot-core-test/hoot-core-test.pro, hoot-core-test/src/test/cpp/hoot/core/visitors/RemoveElementsVisitorTest.cpp, hoot-core-test/src/test/resources/visitors/RemoveElementsVisitorInput.osm, hoot-core-test/src/test/resources/visitors/RemoveElementsVisitorOutput.osm, hoot-core-test/src/test/resources/visitors/RemoveElementsVisitorRecursiveOutput.osm
1. refs #114 
@mingjiesu Do you mind reviewing this one?  Very short...just added some unit test coverage.  thanks.
=> add unit test for RemoveElementsVisitor

scripts/DeployTomcat.sh, scripts/SetupOsmApiDB.sh, scripts/makeOsc.sh
@jasonsurratt As discussed yesterday, the hardcoded paths are gone.
=> 225 Remove hardcoded directory paths from scripts

plugins/mgcp.js, plugins/tds61.js, plugins/translate.js
@jasonsurratt Ready for review & merge
1. refs #227 Added a function to chop a datetime attribute to 20
characters.
=> Added a function to chop a datetime attribute down to 20 characters for export

patches/geos-3.4.2-centos6.7.patch
1. refs redmine 7510 Upgrade geos on Patty - I added a patch for GEOS
that lets hoot work w/ GEOS 3.4.2 on CentOS 6.7
=> Add patch for GEOS v3.4.2

hoot-core-test/src/test/resources/cmd/slow/ServiceDbTest.sh.stdout, hoot-core/src/main/cpp/hoot/core/conflate/match-graph/ConstrainedMatches.cpp
Refs #166 
Updated ConstrainedMatches::EPSILON and updated the ServiceDbTest results.  It was the only test that was effected.
=> Add EPSILON to optimization code

plugins/mgcp.js, plugins/mgcp_rules.js, plugins/tds40.js, plugins/tds40_rules.js, plugins/tds61.js, plugins/tds61_rules.js
@bmarchant Can you have a look at this and merge it.
The ticket (#271) has a simple OSM file and a shell script to test the text chopping.
=> Validate the length of text attributes on export

hoot-core-test/src/test/cpp/hoot/core/TestUtils.cpp, hoot-core-test/src/test/cpp/hoot/core/TestUtils.h, hoot-core-test/src/test/cpp/hoot/core/conflate/highway/HighwaySnapMergerTest.cpp, hoot-core-test/src/test/cpp/hoot/core/filters/BuildingCriterionTest.cpp, hoot-core-test/src/test/resources/cmd/slow/ConflateExactTest.sh.stdout, hoot-core/src/main/cpp/hoot/core/conflate/MatchThreshold.cpp, hoot-core/src/main/cpp/hoot/core/conflate/highway/HighwaySnapMerger.cpp, hoot-core/src/main/cpp/hoot/core/conflate/highway/HighwaySnapMerger.h
https://github.com/ngageoint/hootenanny/issues/296
@bmarchant Do you mind doing this one?  Was a fairly simple fix for method parameters that were accidentall swapped.  thanks.
=> Review note provides no context or information other than 'Highway'

configure.ac, m4/ax_lib_gdal.m4
1. refs #340 Hoot links to the wrong gdal if multiple in the path
=> Add gdal path to rpath.

Makefile.old
Refs #342 
Updated Makefile.old to add three `conf/*.rf` files to the hoot archive.
Added:
`BuildingModel.rf`
`HighwayModel.rf`
`PoiModel.rf`
Also added a few comments to document the build process
=> Added conf/*.rf files to the archive to reduce build time

hoot-js/hoot-js.pro, scripts/TranslationServer.js
=> Updates to Translation Bugs

scripts/SetupOsmApiDB.sh
1. refs #363 Better OsmApiDb check
please test
=> Better OsmApiDb check

plugins/MassNh.js, plugins/etds.js, plugins/etds61.js, plugins/etds61_osm.js, plugins/etds_osm.js, plugins/mgcp.js, plugins/mgcp_rules.js, plugins/tds40.js, plugins/tds40_rules.js, plugins/tds61.js, plugins/tds61_rules.js, plugins/translate.js
The export translations now check for integer values and truncate Real numbers to Int's where appropriate.
Example output is on #29 
@bwitham Like to have a look and merge?
=> Error converting to LongInt

hoot-core-test/src/test/resources/cmd/slow/BadJavaScriptTranslation.sh.stdout, hoot-js/src/main/cpp/hoot/js/JavaScriptTranslator.cpp, hoot-js/src/main/cpp/hoot/js/util/HootExceptionJs.cpp
1. refs #352 Removed _checkerror and added more error information
=> Replace JavaScriptTranslator::_checkError with v8 equivalent 

Makefile.old
=> Create a separate tarball for docs when running archive

test-files/cmd/slow/ConflationStatsReportTest.sh
=> #407 sort csr output files list

hoot-core-test/src/test/cpp/hoot/core/ops/CalculateStatsOpTest.cpp, hoot-core/src/main/cpp/hoot/core/ops/CalculateStatsOp.cpp, test-files/cmd/slow/ConflateCmdStatsAllDataTypesTest.sh.stdout, test-files/cmd/slow/ConflateCmdStatsGenericRiversTest.sh.stdout, test-files/cmd/slow/ConflateCmdStatsToyBuildingsTest.sh.stdout, test-files/cmd/slow/ConflateCmdStatsToyTest.sh.stdout
Refs #191 
Added untagged feature count and removed them from the unconflated count.
=> Stats show untagged nodes as unconflated

VagrantProvision.sh
1. refs #430 
@brianhatchl Something I noticed in #429.  If this isn't a valid solution, feel free to reject.  thanks.
=> Remove postgres 9.5 instead of 9.4

Makefile.old
=> Only include javadoc in archive if it exists

hoot-core/src/main/cpp/hoot/core/ops/CalculateStatsOp.cpp
Refs #360 
While working on 360 and before deciding it was OBE, made a quick fix to remove redundant code.
=> Remove redundant code

conf/conflationHorizontalOps.json
=> Alpha shape buffer exposed in Adv. Opts.

conf/ConfigOptions.asciidoc, hoot-core-test/src/test/cpp/hoot/core/ops/CookieCutterOpTest.cpp, hoot-core/src/main/cpp/hoot/core/ops/CookieCutterOp.cpp, hoot-core/src/main/cpp/hoot/core/ops/CookieCutterOp.h
=> Remove cookie.cutter.output.buffer

plugins/mgcp.js, scripts/ConvertMGCPSchema.py
1. refs #454 Renamed F_CODE to FCODE in the MGCP export
As above.
=> Renamed F_CODE to FCODE in the MGCP export

hoot-cmd/src/main/cpp/hoot/cmd/main.cpp, hoot-core/src/main/cpp/hoot/core/Hoot.cpp, hoot-core/src/main/cpp/hoot/core/Hoot.h, hoot-js/hoot-js.pro, hoot-test/src/main/cpp/hoot/test/main.cpp
1. refs #457 HootJs contains CPP Unit Tests
2. Libraries will error out now if they fail to load, but the file
exists.
=> Make library loading more robust

hoot-core/src/main/cpp/hoot/core/Factory.cpp, hoot-core/src/main/cpp/hoot/core/Hoot.cpp, hoot-js/src/main/cpp/hoot/js/HelloWorld.cpp
=> HootJs will not be loaded twice

test-files/cmd/slow/ServiceDbTest.sh
=> Fix create duplicate user bug

test-files/bbox_test.sql
This avoids the hstore => deprecation warning and the test still passes.
=> #453, comment out hstore extension

test-files/cmd/slow/ServiceDbTest.sh
=> remove background execution of hoot convert commands

hoot-services/src/main/resources/db/changelogs/017-IncrementUserIdSequence.xml, test-files/cmd/slow/ServiceDbTest.sh
=> 478 ServiceDbTest.sh may attempt to create the same user twice

VagrantProvision.sh
* force removal of file on symbolic link
=> Remove LocalHoot.json if exists (#464)

VagrantProvision.sh
Changes to Vagrantprovision.sh that were changed on develop branch.  Please determine if they should be made on release as well.
Including @brianhatchl for additional context as needed.
=> VagrantProvision.sh update for release branch

test-files/cmd/slow/ConflationStatsReportTest.sh, test-files/cmd/slow/ConflationStatsReportTest.sh.stdout, test-files/cmd/slow/Osm2OgrTranslation.sh
=> Standardize sort order in cmd line tests

scripts/exportrenderdb.sh
=> suppress expected error when creating renderdb on postgis 1.5

scripts/HootServicesUiRpmPostInstall.sh, scripts/HootServicesUiRpmPostUninstall.sh
refs https://github.com/ngageoint/hootenanny-rpms/issues/22
=> databases and upload/ingest folders preserved in rpm remove

hoot-js/src/main/cpp/hoot/js/conflate/js/ScriptMatchCreator.cpp
=> Fixed bad reference to shared pointer

scripts/DeleteAllTables.sh
1. refs #498 Added quotes around the renderDb name in DeleteAllTables.sh
@brianhatchl Could you have a look at this and merge please.
=> Added quotes around the renderDb name in DeleteAllTables.sh

hoot-core-test/hoot-core-test.pro, hoot-core-test/src/test/cpp/hoot/core/io/ElementSorterTest.cpp, hoot-core/src/main/cpp/hoot/core/io/ElementSorter.cpp, hoot-core/src/main/cpp/hoot/core/io/ElementSorter.h
1. refs #556 
Very simple change to add a test that verifies ElementSorter
@mingjiesu Thanks for reviewing.
=> Add test for ElementSorter

scripts/DeleteAllTables.sh, scripts/RecreateDatabase.sh
1. refs #563 Added $DB_PORT to Hoot scripts
@bwitham Can you have a look at this and merge please
=> Added $DB_PORT to Hoot scripts

plugins/mgcp.js, plugins/mgcp_rules.js, plugins/tds40.js, plugins/tds40_rules.js, plugins/tds61.js, plugins/tds61_rules.js, test-files/MGCPv3/LAQ040-output.osm
Fixed bridges in MGCP & TDS.
https://github.com/DigitalGlobe/dgis-devops/issues/125
@bmarchant Could you have a look at this and merge please.
=> MGCP bridge tag user question

VagrantProvision.sh
refs #579 
removed all references to `vagrant` username with `$username`
=> Standardize all uses of the vagrant user by using the  variable

plugins/tds40.js, plugins/tds61.js
1. refs #491 Added checks for Junctions that are not points.
@bmarchant This runs the files in the ticket cleanly. Can you have a look and merge please.
=> Added checks for Junctions that are not points.

hoot-services/src/main/java/hoot/services/controllers/wfs/WfsManager.java
2) Refactoring of _createFeatureStore() to log exceptions recorded by the Deegree implementation of WFS.  This activity is related to issue #546
=>  log exceptions recorded by the Deegree implementation of WFS

conf/schema/highway.json, plugins/mgcp.js, plugins/tds40.js, plugins/tds61.js
refs #583 
Updated translation files to add highway=road to BH070 FCODE and ford=yes
=> Fords not conflating

scripts/jenkins/ConfigureUbuntu1404VagrantEnvironment.sh
=> Maintain vagrant state in the parent directory

test-files/ui/Makefile
1. refs #654
This makes the nightly on Selma run.
@brianhatchl over to you.
=> Use the TOMCAT_PORT environment variable if it is set.

plugins/mgcp.js, plugins/mgcp_rules.js, test-files/MGCPv3/LAN010-output.osm, test-files/MGCPv3/LAQ040-output.osm
Carrying on from the work on fords.
@bmarchant Can you have a look at this please.
=> MGCP Translation: Tweak bridges, cuts, embankments etc

test-files/ui/features/clip.feature, test-files/ui/features/step_definitions/custom_steps.rb
> Merge pull request #367 from ngageoint/343
> Update to select all (#365)
=> Submodule hoot-ui a2829a6..2af5f55:

scripts/jenkins/ConfigureUbuntu1404VagrantEnvironment.sh
=> Fixed Jenkins Vagrant destroy conditional

plugins/mgcp_rules.js
1. refs #543
Moved one of the MGCP RST values to the output only list
@bwitham Easy fix. Ready to test. NOTE: I haven't un-commented the lines in the hoot-tests MassNh & Samoa Makefiles in the develop branch.
=> Error exporting data to MGCP fgdb/shp

hoot-rnd/hoot-rnd.pro
=> 582 Configure test is failing in nightly

scripts/jenkins/ConfigureTestUbuntu1404VagrantEnvironment.sh
=> Removed "-werror from configure test vagrant configuration

hoot-services/src/main/java/hoot/services/controllers/info/AboutResource.java, hoot-services/src/main/java/hoot/services/info/BuildInfo.java, hoot-services/src/main/java/hoot/services/info/CoreDetail.java, hoot-services/src/main/java/hoot/services/info/ErrorLog.java, hoot-services/src/main/java/hoot/services/info/ServicesDetail.java, hoot-services/src/main/java/hoot/services/info/VersionInfo.java, hoot-services/src/test/java/hoot/services/controllers/info/AboutResourceTest.java, hoot-services/src/test/java/hoot/services/nativeInterfaces/INativeInterfaceStubImpl.java, hoot-services/src/test/resources/hoot/spring/CoreServiceContext.xml
@bwitham 
Brandon,
Could you please review my changes?  They are related to the incorrect parsing of Hootenanny Core version when `hoot version` command returned more output than expected.  
Thank you
Dmitriy
=> 657 Hoot Services: Improve parsing of Hoot version in AboutResource.java

hoot-services/src/main/java/hoot/services/db/DataDefinitionManager.java
@bwitham
Could you please review mu changes? This changes are to address several Fortify findings, whereby JDBC resources were not being properly de-allocated in all cases.
Thank you!
=> 699 Fix resource deallocation in DataDefinitionManager.java

VagrantBuild.sh
1. refs #724
@bwitham  As discussed.
=> Added mkdir commands into VagrantBuild.sh

Makefile.old, VagrantProvision.sh, docs/Makefile
1. refs #706 
@brianhatchl Can you have a look and merge please
=> Fixed node temp directory errors

test-files/ui/features/basemap_ingest.feature, test-files/ui/features/step_definitions/custom_steps.rb
refs: https://github.com/ngageoint/hootenanny-ui/issues/293
=> add basemap-ingest cucumber test

hoot-services/src/main/java/hoot/services/controllers/info/ErrorLogResource.java, hoot-services/src/main/java/hoot/services/controllers/job/JobResource.java, hoot-services/src/main/java/hoot/services/controllers/osm/MapResource.java, hoot-services/src/main/java/hoot/services/info/ErrorLog.java, hoot-services/src/main/java/hoot/services/models/osm/Map.java, hoot-services/src/main/java/hoot/services/validators/job/JobFieldsValidator.java, hoot-services/src/test/java/hoot/services/controllers/ingest/FileUploadResourceTest.java, hoot-services/src/test/java/hoot/services/controllers/job/JobResourceTest.java, hoot-services/src/test/java/hoot/services/controllers/ogr/TranslatorResourceTest.java, hoot-services/src/test/java/hoot/services/controllers/osm/ChangesetResourceUploadAllTest.java, hoot-services/src/test/java/hoot/services/controllers/osm/MapResourceTest.java, hoot-services/src/test/java/hoot/services/db/DataDefinitionManagerTest.java, hoot-services/src/test/java/hoot/services/info/ErrorLogTest.java, hoot-services/src/test/java/hoot/services/osm/OsmResourceTestAbstract.java, hoot-services/src/test/java/hoot/services/utils/HootCustomPropertiesSetter.java, hoot-services/src/test/java/hoot/services/validators/job/JobFieldsValidatorTest.java, hoot-services/src/test/resources/hoot/services/info/catalina.out, hoot-services/src/test/resources/hoot/services/validators/job/services_fields_metadata.json
Fixed most of disabled (ignored) unit tests to increase code coverage and improve code quality.
@bwitham @treycaldwell,
Can one of you guys please review my changes.  Thank you!
=> 452 Fix or remove skipped services tests

test-files/ui/features/conflate_with_stats.feature, test-files/ui/features/step_definitions/custom_steps.rb
refs: https://github.com/ngageoint/hootenanny-ui/issues/332
=> add layer stats cucumber test

test-files/ui/features/bulk_import_multidelete.feature, test-files/ui/features/step_definitions/custom_steps.rb
Cuke test will bulk import dcpoi_clip and  mapcruzin_clip, then select both and delete
=> Cucumber bulkimport and multiselect delete

hoot-services/src/main/java/hoot/services/controllers/job/ClipDatasetResource.java
refs https://github.com/ngageoint/hootenanny-ui/issues/262
=> create renderdb for clip dataset operation

hoot-services/src/main/java/hoot/services/db/DbUtils.java, hoot-services/src/main/java/hoot/services/utils/ResourcesCleanUtil.java, test-files/ui/features/review_bookmarks.feature
Run submodule update to get hoot-ui changes.
Hoot-ui changes: https://github.com/ngageoint/hootenanny-ui/pull/469
=> #501 deleteBookmarksById

test-files/ui/features/step_definitions/custom_steps.rb, test-files/ui/features/translation_ingest_edit.feature
https://github.com/ngageoint/hootenanny-ui/issues/291
Be sure to either submodule update or use ui branch 291 when reviewing.
=> Translation ingest/edit/save Cucumber Test

test-files/ui/features/step_definitions/custom_steps.rb, test-files/ui/features/wfs_export.feature
refs https://github.com/ngageoint/hootenanny-ui/issues/292
=> add cucumber test for wfs export

test-files/ui/features/manually_resolve_reviews.feature, test-files/ui/features/step_definitions/custom_steps.rb
refs https://github.com/ngageoint/hootenanny-ui/issues/495
=> add feature add and edit to conflation review

test-files/cmd/slow/eTDSTranslationAssistantTest.sh
=> Test contains unnecessary lines, commented out

conf/ConfigOptions.asciidoc, hoot-core-test/hoot-core-test.pro, hoot-core-test/src/test/cpp/hoot/core/visitors/RemoveEmptyReviewRelationsVisitorTest.cpp, hoot-core/hoot-core.pro, hoot-core/src/main/cpp/hoot/core/conflate/ReviewMarker.cpp, hoot-core/src/main/cpp/hoot/core/conflate/ReviewMarker.h, hoot-core/src/main/cpp/hoot/core/ops/AddHilbertReviewSortOrderOp.cpp, hoot-core/src/main/cpp/hoot/core/visitors/RemoveEmptyReviewRelationsVisitor.cpp, hoot-core/src/main/cpp/hoot/core/visitors/RemoveEmptyReviewRelationsVisitor.h, hoot-rnd/src/main/cpp/hoot/rnd/conflate/poi-polygon/PoiPolygonMerger.cpp
=> 839 - Review relations being written with no members when running train-poi-building.child testa

hoot-core/src/main/cpp/hoot/core/visitors/RemoveEmptyReviewRelationsVisitor.cpp, hoot-js/src/main/cpp/hoot/js/conflate/js/ScriptMatchCreator.cpp, rules/PoiGeneric.js
=> 834 - Running PoiPolygon matching with PoiGeneric.js results in ways being passed to PoiGeneric.js matchScore

plugins/mgcp.js, plugins/tds40.js, plugins/tds61.js
=> Stop "hoot=<layername>" getting into the not used tags list

hoot-core-test/hoot-core-test.pro, hoot-core-test/src/test/cpp/hoot/core/filters/BuildingWayNodeCriterionTest.cpp, hoot-core/hoot-core.pro, hoot-core/src/main/cpp/hoot/core/filters/BuildingWayNodeCriterion.cpp, hoot-core/src/main/cpp/hoot/core/filters/BuildingWayNodeCriterion.h, test-files/filters/BuildingWayNodeCriterionTest.osm
=> 854 - Add BuildingWayNodeCriterion for use in train-poi-building test

conf/conflateAdvOps.json, test-files/ui/features/advanced_options.feature, test-files/ui/features/step_definitions/custom_steps.rb
- Show selected advanced options as "Custom ...": https://github.com/ngageoint/hootenanny-ui/issues/429
- Add the element cache options to advanced UI settings: https://github.com/ngageoint/hootenanny-ui/issues/409
- Advanced Options CSS Updates: https://github.com/ngageoint/hootenanny-ui/issues/486
=> Advanced Conflation Options Updates

hoot-core/src/main/cpp/hoot/core/conflate/highway/HighwayMatch.cpp, test-files/cases/unifying/highway-5534/Expected.osm, test-files/cases/unifying/highway-578/Expected.osm, test-files/cases/unifying/highway-search-radius-1/Expected.osm, test-files/cmd/glacial/ServiceOsmApiDbAllDataTypesConflateTest/output.osm, test-files/cmd/slow/ConflateCmdHighwayExactMatchInputsTest/output.osm, test-files/cmd/slow/ConflateCmdTest/output.osm, test-files/cmd/slow/ServiceDbTest.sh.stdout, test-files/cmd/slow/csr/csr.osm
Refs #425 
Updated the review text to use some of the extractors to give more relevant review explanations.
=> Improve highway review explanation text

test-files/ui/features/measure_tool.feature, test-files/ui/features/step_definitions/custom_steps.rb, test-files/ui/features/support/mouse_click.rb
refs https://github.com/ngageoint/hootenanny-ui/issues/490
=> Add cucumber test for meaure tool

hoot-core/src/main/cpp/hoot/core/algorithms/linearreference/WaySublineMatchString.cpp
=> Fix bad QString formatting

test-files/ui/features/clip.feature, test-files/ui/features/step_definitions/custom_steps.rb
refs https://github.com/ngageoint/hootenanny-ui/issues/506
=> add step to change layer color

scripts/CreateJsConfigCode.py
1. refs #893
@brianhatchl python edit is done. Ready to test/merge.
=> Swapped "getHootConfig" for "hoot.get" to simplify things

test-files/ui/features/clip.feature, test-files/ui/features/step_definitions/custom_steps.rb
#568 
Use the hoot-ui submodule associated with this branch, or use branch 522 for hoot-ui.
=> Updated Clip Cucumber Test (use this hoot-ui branch)

scripts/ConvertGGDMv30Schema.py
1. refs #911 
Trying this as part of the Epic
=> Fix name/value ordering

test-files/ui/features/clip.feature, test-files/ui/features/z_conflate_export_osm_api_db.feature
> Merge pull request #594 from ngageoint/584
=> Submodule hoot-ui 5cd3c45..55974f1:

Makefile.am, Makefile.old, scripts/jenkins/TestDevelop.sh, scripts/jenkins/TestInitialNightly.sh
1. refs #928 
@sputnam Over to you for testing
@brianhatchl Is there an overlap between "ui-test" and "ui-coverage"?
=> Split the "test-all" and "coverage" targets in the Jenkins test scripts

test-files/ui/features/translation_ingest_edit.feature
=> Hoot UI 586 cucumber test

test-files/ui/features/clip.feature, test-files/ui/features/resolve_all_reviews.feature
=> attempt to make some cuke fixes to avoid false positive failures #945

test-files/ui/features/manually_resolve_reviews.feature, test-files/ui/features/osm_tds_switcher.feature, test-files/ui/features/step_definitions/custom_steps.rb
Fixes issues with cucumber tests failing on hootenanny-ui branch 624
=> Update cucumber tests to fix issue with hootenanny-ui branch 624

conf/ConfigOptions.asciidoc, plugins/SchemaTools.js, plugins/emgcp.js, plugins/emgcp_osm.js, plugins/etds40.js, plugins/etds40_osm.js, plugins/etds61.js, plugins/etds61_osm.js, plugins/mgcp.js, plugins/tds40.js, plugins/tds61.js, plugins/translate.js, translations/OSM_to_english.js, translations/OSM_to_englishMGCP.js, translations/OSM_to_englishTDS.js, translations/OSM_to_englishTDS61.js
1. refs #954 
The schema switcher should now get partial translations and the not used tags are prefaced by "OSM:"
=> Modified to/from english to do partial translations

plugins/mgcp.js, plugins/mgcp_rules.js, plugins/tds40.js, plugins/tds40_rules.js, plugins/tds61.js, plugins/tds61_rules.js, test-files/MGCPv3/AAL015-output.osm, test-files/MGCPv3/AAL020-output.osm, test-files/MGCPv3/LAN010-output.osm, test-files/MGCPv3/LAP010-output.osm, test-files/MGCPv3/LAP030-output.osm, test-files/MGCPv3/LAP050-output.osm, test-files/MGCPv3/LAQ040-output.osm, test-files/MGCPv3/LBH140-output.osm, test-files/MGCPv3/PAL015-output.osm, test-files/cmd/slow/MgcpTranslationTest.sh.stdout, test-files/translation_assistant/cali-test-tdsv40.osm, test-files/translation_assistant/cali-test-tdsv61.osm
Fixed how this tag is translated. This does work in the schema-switcher as well.
@brianhatchl Can you have a quick look and merge please.
=> Fix "source" tag translations

.gitignore, hoot-services/src/main/java/hoot/services/controllers/ingest/FileUploadResource.java, hoot-services/src/main/java/hoot/services/controllers/job/ExportJobResource.java, hoot-services/src/main/java/hoot/services/utils/MultipartSerializer.java, scripts/osm2ogrscript, test-files/ui/features/bulk_import_multidelete.feature, test-files/ui/features/import_export_delete_osm_dataset.feature, test-files/ui/features/manage_tab.feature
=> Issue #963: Expose pbf as available import/export format

hoot-rnd/hoot-rnd.pro
1. refs #1020 hoot-rnd.pro contains test files in the wrong section
=> Move test files into cppunit section

conf/ConfigOptions.asciidoc, hoot-core/src/main/cpp/hoot/core/io/OsmWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmWriter.h, test-files/ui/features/egd_plugin.feature, test-files/ui/features/step_definitions/custom_steps.rb, translations/OSM_to_englishMGCP.js, translations/OSM_to_englishTDS.js, translations/OSM_to_englishTDS61.js
For the Translation Server.
@brianhatchl Can you test and make sure you are happy with it.
=> Add "schema" attribute to some OSM files

plugins/mgcp.js, test-files/MGCPv3/AAL015-output.osm, test-files/MGCPv3/PAL015-output.osm, test-files/cmd/slow/MgcpTranslationTest.sh
=> Added religion tags to MGCP buildings where appropriate

plugins/mgcp.js, plugins/mgcp_rules.js
=> Fixed AC000 vs AL010 and reservoirs

test-files/ui/features/osm_tds_switcher.feature, test-files/ui/features/step_definitions/custom_steps.rb
https://github.com/ngageoint/hootenanny-ui/issues/730
=> add a cuke test step to confirm fix for hoot-ui 730

test-files/ui/features/highlight_features.feature
refs https://github.com/ngageoint/hootenanny/pull/105
=> fix a bad merge that happened in highlight cucumber PR

hoot-services/src/main/java/hoot/services/controllers/job/ConflationResource.java
=> Add ability to run OSM API db conflation with a Tasking Manager grid bounds

conf/ConfigOptions.asciidoc
related to ngageoint/hootenanny-ui#765
=> element.cache.size.* should be int, not long

test-files/ui/features/check_version.feature
Based on ngageoint/hootenanny-ui#711
This test will open the version pop up, check that there are 3 versions (core, webservices, and id editor), and check that the hoot user guide gets downloaded.
@sisskind let me know if there's anything I'm missing.
=> Cucumber test to check version + user guide download

test-files/ui/features/bulk_import_multidelete.feature, test-files/ui/features/import_export_delete_osm_dataset.feature, test-files/ui/features/import_export_delete_shp_dataset.feature, test-files/ui/features/import_gdb_zip_dataset.feature, test-files/ui/features/import_geonames_dataset.feature, test-files/ui/features/manage_tab.feature, test-files/ui/features/paste_attributes.feature, test-files/ui/features/review_bookmarks.feature
Once this passes, will test/merge ngageoint/hootennanny-ui#759
=> Cucumber test change for Bulk Import updates

test-files/ui/features/check_layer_load.feature
https://github.com/ngageoint/hootenanny-ui/issues/718
=> Cucumber test to check for duplicate layer load

plugins/mgcp.js, plugins/mgcp_rules.js, plugins/tds40.js, plugins/tds61.js, scripts/ConvertMGCPSchema_XML.py, test-files/MGCPv3/AAL020-output.osm, translations/PrintOsmDocs.js
A bit of scope creep from the original #1077
=> MGCP Translation fixes

VagrantProvision.sh, node-mapnik-server/package.json
=> issues with vagrant package versions

conf/ConfigOptions.asciidoc
Reverts ngageoint/hootenanny#1110
=> Revert "element.cache.size.* should be int, not long"

VagrantProvision.sh, renderdb-export-server/config.json, renderdb-export-server/init.d/centos-rpm, renderdb-export-server/init.d/renderdb-export-server, renderdb-export-server/server.js
part of adding renderdb-export-server to hoot rpms
https://github.com/ngageoint/hootenanny-rpms/issues/91
=> Add init.d script for renderdb-export-server

translations/RenderDb.js, translations/RenderDb_to_MGCP.js, translations/RenderDb_to_TDS40.js, translations/RenderDb_to_TDS61.js
=> Fixed tag splitting in RenderDb export scripts

VagrantProvision.sh
* Meant to solve issue with chromedriver 2.14 and updated version of chrome browser for cucumber tests
This will have to be updated if chromedriver version goes to 0.2.25, although the outcome in the current state will just continuously update to latest version of chromedriver.
=> Update chromedriver to 2.24.x or beyond

hoot-core/src/main/cpp/hoot/core/cmd/PrintOsmDocsCmd.cpp, plugins/fcode_common.js, plugins/mgcp_rules.js, plugins/tds40.js, plugins/tds40_rules.js, plugins/tds61_rules.js, scripts/ConvertMGCPSchema_XML.py, scripts/ConvertTDSv40Schema.py, scripts/ConvertTDSv61Schema.py
Also, I fixed the print-tags command.  It was not accepting the optional script argument.
1. refs #1183
=> Translation cleanup to support the GIFD translation

hoot-core-test/src/test/cpp/hoot/core/conflate/poi-polygon/extractors/PoiPolygonAddressScoreExtractorTest.cpp, hoot-core-test/src/test/cpp/hoot/core/conflate/poi-polygon/extractors/PoiPolygonNameScoreExtractorTest.cpp, hoot-core-test/src/test/cpp/hoot/core/conflate/poi-polygon/extractors/PoiPolygonTypeScoreExtractorTest.cpp
refs #1204 
Can't dereference an empty smart pointer
=> Fix for broken devel branch

test-files/ui/features/osm_tds_switcher.feature
=> update cucumber tests for refactored schema switcher

plugins/mgcp.js, plugins/mgcp_rules.js, plugins/tds40.js, plugins/tds61.js
@bmarchant Ready for test with your dataset. It passes on my box.
=> Fix MGCP failure with bad FCODEs

hoot-core-test/src/test/cpp/hoot/core/conflate/poi-polygon/PoiPolygonMatchTest.cpp
refs #1177 
Enable PoiPolygonMatchTest and reset OsmMap counters
=> Fix PoiPolygonMatchTest::missTest pt 2

Makefile.old, plugins/fcode_common.js, plugins/mgcp.js, plugins/tds40.js, plugins/tds61.js
1. refs #1220 
Hydrocarbons fixes as per VGI #199
=> Hydrocarbons and other small changes.

docs/user/Hootenanny-id.asciidoc
https://github.com/DigitalGlobe/VGI-team-repo/issues/82
=> Include warning RE: drop downs in docs

hoot-core/src/main/cpp/hoot/core/cmd/ConflateCmd.h, hoot-core/src/main/cpp/hoot/core/util/Settings.cpp
=> 1269 - throw exception on invalid core setting passed in

test-files/cmd/quick/PrepareForValidationTest.sh.stdout, test-files/prepare_validation/poi1_validation.osm
Refs #1252 
PrepareForValidationTest
Fixed the POI validation source file and the test output so that the test actually passes instead of the output being ignored.
=> Fix PrepareForValidationTest

VagrantProvision.sh
- only run java 8 steps if `java -version` isn't 1.8.0_112
- only install rvm if `ruby -v` isn't 2.3.0
- remove some commented out lines
- make some steps quiet
- fix use of LATEST_RELEASE to update chromedriver
- avoid error removing folder if it doesn't exist
=> some addition steps to make provision avoid re-running steps

plugins/mgcp_rules.js, plugins/tds40.js, plugins/tds61.js, test-files/NFDD_TDSv4/nfdd.osm, test-files/NFDD_TDSv61/NFDDv61.osm
1. refs #1294  && VGI #199
Fixed typo in translation script.
@mschicker Can you check and merge please.
=> Hydrocarbons: Fixed typo in translation

test-files/ui/features/review_layer_no_inputs_loaded.feature
=> Dataset change for review_layer_no_inputs_loaded

test-files/ui/features/paste_attributes.feature, test-files/ui/features/step_definitions/custom_steps.rb
=> use another approach to verify tag is in table for paste_attributes.feature

conf/conflateAdvOps.json
https://github.com/ngageoint/hootenanny-ui/issues/644
https://github.com/ngageoint/hootenanny-ui/issues/818
=> Add Frechet, PoiPolygon to Advanced Options

test-files/ui/features/paste_attributes.feature, test-files/ui/features/step_definitions/custom_steps.rb
=> use another approach to verify tag is in table

scripts/makeetl
=> remove `reporting` hoot convert option

conf/ConfigOptions.asciidoc, hoot-core/src/main/cpp/hoot/core/cmd/ConvertCmd.cpp, hoot-core/src/main/cpp/hoot/core/io/ApiDbReader.cpp, hoot-core/src/main/cpp/hoot/core/io/HootApiDbReader.cpp, hoot-core/src/main/cpp/hoot/core/io/HootApiDbWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmReader.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmReader.h, hoot-core/src/main/cpp/hoot/core/io/OsmWriter.cpp
See #1315 
Hoot:status is now being handled better.
=> Fix hoot:status handling

test-files/ui/features/resolve_all_reviews.feature, test-files/ui/features/step_definitions/custom_steps.rb
refs https://github.com/ngageoint/hootenanny-ui/issues/722
=> add steps to exercise Symbology.js in cucumber test

scripts/jenkins/TestPullRequest_core.sh
References issue #1363.
I'd like to test this on the build stack and see if it runs to completion without hanging.
=> Include ConflatePoiStats in core tests

VagrantProvision.sh, scripts/AWSProvision_CentOS_RHEL_6_5.sh, scripts/AWSProvision_CentOS_RHEL_7.sh, scripts/InstallHoot-CentOS-RHEL.sh
Refs #1335
Simple change to use the latest FGDB API
=> Upgrade the ESRI FileGDB library

scripts/jenkins/TestInitialNightly.sh
=> Remove exclude for core test that was hanging on Jenkins

VagrantProvision.sh, scripts/tomcat8/ubuntu/tomcat8_install.sh, test-files/ui/Makefile
Refs #1374 
Fixes many warnings and ugliness of the output of the `vagrant up` command.  See comments in the code for what they fixed or eliminated.
=> Clean up the vagrant up process

VagrantProvision.sh, scripts/developer/MakeHootRamDisk.sh
1. setup distcc except for the LocalConfig.pri for minimal effort in turning it on in a new vm
2. removed pgadmin, as its a gui tool and not needed by vagrant
=> distcc related vagrant changes

hoot-services/src/main/java/hoot/services/controllers/osm/element/ElementResource.java, hoot-services/src/main/java/hoot/services/models/osm/Element.java, hoot-services/src/main/java/hoot/services/models/osm/Node.java, hoot-services/src/main/java/hoot/services/models/osm/Relation.java, hoot-services/src/main/java/hoot/services/models/osm/Way.java, hoot-services/src/test/java/hoot/services/controllers/osm/changeset/ChangesetResourceUploadModifyTest.java
=> hoot service modify changesets now increment element versions

VagrantProvision.sh
Added `w3m` to line 69 of VagrantProvision.sh.
=> Added w3m to provisioning

plugins/fcode_common.js, plugins/mgcp.js, plugins/tds40.js, plugins/tds61.js
1. refs #1495 
Try to assign a weather restriction based on the road type and surface material.
=> Derive WTC/ZI016_WTC info on export

hoot-core-test/src/test/cpp/hoot/core/ops/CalculateStatsOpTest.cpp, tbs/src/main/cpp/tbs/stats/SampleStats.cpp, tbs/src/main/cpp/tbs/stats/SampleStats.h, tgs/src/main/cpp/tgs/BigContainers/BigMapStl.h
1. refs #1358 
@bmarchant  Small change but it is one of the errors from trying "-std=c++11"
=> Fixed isNAN,  getting ready for c++11

conf/core/ConfigOptions.asciidoc, hoot-core-test/src/test/cpp/hoot/core/conflate/poi-polygon/extractors/PoiPolygonNameScoreExtractorTest.cpp, hoot-core-test/src/test/cpp/hoot/core/schema/OsmSchemaTest.cpp, hoot-core/src/main/cpp/hoot/core/conflate/poi-polygon/PoiPolygonReviewReducer.cpp, hoot-core/src/main/cpp/hoot/core/conflate/poi-polygon/extractors/PoiPolygonNameScoreExtractor.cpp, hoot-core/src/main/cpp/hoot/core/conflate/poi-polygon/extractors/PoiPolygonNameScoreExtractor.h, hoot-core/src/main/cpp/hoot/core/schema/OsmSchema.cpp, hoot-core/src/main/cpp/hoot/core/schema/OsmSchema.h, hoot-js/src/main/cpp/hoot/js/schema/OsmSchemaJs.cpp, hoot-js/src/main/cpp/hoot/js/schema/OsmSchemaJs.h, rules/PoiGeneric.js, rules/lib/HootLib.js, test-files/cases/hoot-js/poi/poi-generic-34/Config (copy).conf, test-files/cases/hoot-js/poi/poi-generic-34/Config.conf, test-files/cases/hoot-js/poi/poi-generic-34/Expected.osm, test-files/cases/hoot-js/poi/poi-generic-34/Input1.osm, test-files/cases/hoot-js/poi/poi-generic-34/Input2.osm, test-files/cases/hoot-js/poi/poi-generic-34/README.txt
=> 1409 - add option to bypass poi type matching if both names are present

scripts/database/SetupOsmApiDB.sh
=> Add database name to the psql call

hoot-services/src/main/java/hoot/services/controllers/conflation/ConflateCommand.java, hoot-services/src/test/java/hoot/services/controllers/conflation/ConflateCommandTest.java, test-files/ui/features/manually_resolve_reviews.feature
=> add conflate options to restore hoot:status tags, create cuke test to confirm

hoot-core/src/main/cpp/hoot/core/io/ApiDbReader.cpp
Refs #1532 
Try to parse the status string from text if from number fails.
=> tag hoot:status is being stripped from features in conflation result

hoot-core/src/main/cpp/hoot/core/visitors/RemoveInvalidMultilineStringMembersVisitor.cpp
Refs #1533
Updated visitor to leave multilinestrings that are the only member of a review relation that aren't a one-for-one match with a way (i.e. the multilinestrings are in-fact multi-line).
=> Error conflating Port au Prince datasets with multilinestring relation remover

hoot-services/src/main/java/hoot/services/controllers/ingest/BasemapCommand.java
https://github.com/ngageoint/hootenanny/issues/1435
=> Don't use explicit path to gdal2tiles.py but rely on $PATH instead

hoot-services/src/main/java/hoot/services/controllers/export/ApplyChangesetCommand.java, hoot-services/src/main/java/hoot/services/controllers/export/DeriveChangesetCommand.java, hoot-services/src/main/java/hoot/services/controllers/export/ExportCommand.java, hoot-services/src/test/java/hoot/services/controllers/export/ExportResourceTest.java
https://github.com/ngageoint/hootenanny/issues/1552
=> Refactored getConflateMap() of ExportCommand to take mapId instead of mapName

hoot-core-test/src/test/cpp/hoot/core/io/ServiceHootApiDbTest.cpp, hoot-core/src/main/cpp/hoot/core/io/ApiDb.h, hoot-core/src/main/cpp/hoot/core/io/HootApiDb.cpp, hoot-core/src/main/cpp/hoot/core/io/HootApiDb.h, hoot-core/src/main/cpp/hoot/core/io/HootApiDbReader.cpp, hoot-core/src/main/cpp/hoot/core/io/HootApiDbWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiDbBulkWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiDbReader.cpp, hoot-core/src/main/cpp/hoot/core/util/DbUtils.cpp, hoot-core/src/main/cpp/hoot/core/util/DbUtils.h, hoot-hadoop/src/main/cpp/hoot/hadoop/convert/WriteOsmSqlStatementsDriver.cpp, hoot-hadoop/src/main/cpp/hoot/hadoop/convert/WriteOsmSqlStatementsReducer.cpp
=> add pg version debug logging

hoot-core-test/src/test/cpp/hoot/core/io/ServiceOsmApiDbBulkWriterTest.cpp, hoot-core-test/src/test/cpp/hoot/core/io/ServiceOsmApiDbChangesetSqlWriterTest.cpp, hoot-core-test/src/test/cpp/hoot/core/io/ServiceOsmApiDbReaderTest.cpp, hoot-core-test/src/test/cpp/hoot/core/io/ServiceOsmApiDbTest.cpp, hoot-core-test/src/test/cpp/hoot/core/io/ServiceOsmChangesetSqlFileWriterTest.cpp, hoot-core-test/src/test/cpp/hoot/core/io/ServicesDbTestUtils.cpp, hoot-core-test/src/test/cpp/hoot/core/io/ServicesDbTestUtils.h, hoot-core/src/main/cpp/hoot/core/io/ApiDb.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiDbBulkWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiDbReader.h, hoot-hadoop/hoot-hadoop.pro, hoot-hadoop/src/test/cpp/hoot/hadoop/convert/ServiceWriteOsmSqlStatementsDriverTest.cpp
1. refs #1554 - also, dont suppress osm api db test script output in debug
=> add more pg version debug logging - pt2

VagrantProvision.sh
Add AWK filtering to the database checking
=> Add filtering to database config

hoot-services/src/main/webapp/WEB-INF/web.xml
Most of the changes here are in UI commit https://github.com/ngageoint/hootenanny-ui/commit/012bee61529f50c6ff4ac57a83b8ff836a9c548e.
But had to be tested here because of a service change.
=> dg imagery plugin now uses single evwhs service

VagrantProvision.sh, hoot-core-test/src/test/cpp/hoot/core/test/ConflateCaseTest.cpp, hoot-core/src/main/cpp/hoot/core/conflate/highway/HighwaySnapMerger.cpp, hoot-rnd/src/main/cpp/hoot/rnd/conflate/network/EdgeMatchSetFinder.cpp, hoot-rnd/src/test/cpp/hoot/rnd/conflate/network/ConflictsNetworkMatcherSettingsOptimizer.cpp, tgs/src/main/cpp/tgs/Optimization/FitnessFunction.h, tgs/src/main/cpp/tgs/Optimization/SimulatedAnnealing.cpp, tgs/src/main/cpp/tgs/Optimization/SimulatedAnnealing.h, tgs/src/test/cpp/tgs/Optimization/SimulatedAnnealingTest.cpp
I'd like to merge develop into release to make new Release Candidate.  The last Release Candidate was never really viable due to the jdk issue that arose.  We could fix that in release but an whole new candidate seem easier.
=> Merge develop into release to make a new Release Candidate

hoot-services/src/main/java/hoot/services/controllers/export/ExportCommand.java, hoot-services/src/main/java/hoot/services/controllers/ingest/ImportCommand.java, test-files/ui/features/import_export_delete_shp_dataset.feature, test-files/ui/features/import_gdb_zip_dataset.feature, test-files/ui/features/step_definitions/custom_steps.rb, test-files/ui/features/translation_assistant.feature
=> fix path to custom scripts

test-files/ui/features/translation_assistant.feature
=> give a longer delay in this cuke test

hoot-services/src/main/java/hoot/services/controllers/export/CalculateTilesCommand.java, hoot-services/src/main/java/hoot/services/controllers/export/ExportResource.java, hoot-services/src/test/java/hoot/services/controllers/export/CalculateTilesCommandTest.java
=> Address issues with calc-tiles service

test-files/ui/features/support/env.rb
=> Increase selenium read_timeout to avoid jenkins failure

scripts/HootEnv.sh
=> 1414 - remove cloudera from setup env

Vagrantfile
1. refs #585 Add KVM support to vagrantfile
=> Add KVM support to vagrantfile

test-files/ui/features/conflate_average.feature
See this ticket: https://github.com/ngageoint/hootenanny-ui/issues/344
=> Cucumber test for average conflation

test-files/ui/features/command_detail_modal.feature
Add some steps with longer waits to ensure that the conflation
has completed and the review feature has been loaded
=> This test seems to fail a lot on jenkins

Makefile.old
1. refs #1567 
Very small.
@bmarchant Can you review please.
=> Add Missing to make archive

test-files/ui/features/folder_conflation_advanced_options.feature
See this issue: https://github.com/ngageoint/hootenanny-ui/issues/721
=> Cucumber test for Conflate.js functionality

test-files/ui/features/command_detail_modal.feature, test-files/ui/features/support/hooks.rb
skip core
skip centos
skip rpm
=> Another modal fix

scripts/jenkins/centos67/TestPullRequest_core.sh, scripts/jenkins/centos67/VagrantBuild_CentOS67.sh
Created CentOS test pull request script to run --glacial commands
Jenkins, we are going to see if this works
[skip ci]
After looking (and changing) the skip words a bit, this should work
=> Update tests to run glacial with excludes for CentOS

Makefile.old, plugins/test/ElementMergeServer.js
updates tests
refs #1699 
skip centos
skip ui
skip rpm
=> ensure plugin mocha tests run

conf/services/DefaultTranslations.json
refs #1704 
Added a menu option to the UI.
=> Added GGDMv30 to the DefaultTranslations list

hoot-core/src/main/cpp/hoot/core/io/OgrWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/OgrWriter.h, plugins/geonames_rules.js, plugins/ggdm30.js, plugins/ggdm30_rules.js, plugins/mgcp.js, plugins/mgcp_rules.js, plugins/tds40.js, plugins/tds40_rules.js, plugins/tds61.js, plugins/tds61_rules.js, test-files/GGDMv30/GGDMv30.osm, test-files/MGCPv3/LBH140-output.osm, test-files/TDSv40/TDSv40.osm, test-files/TDSv61/TDSv61.osm, test-files/cmd/quick/ConvertGeoNames.sh.stdout, test-files/cmd/slow/MgcpTranslationTest.sh, test-files/translation/MgcpTranslated.osm
#1684 & #1685 in the same branch
=> Add HootId to ogrWriter.cpp and translation fixes

docs/developer/HootenannyBuild.asciidoc, docs/developer/HootenannyDeveloperIDESetup.asciidoc, docs/developer/HootenannyTroubleshooting.asciidoc, docs/install/HootenannyTroubleshooting.asciidoc, docs/install/Tuning.asciidoc, hoot-services/src/main/java/hoot/services/command/ExternalCommandManagerImpl.java, hoot-services/src/main/java/hoot/services/command/ExternalCommandRunner.java, hoot-services/src/main/java/hoot/services/command/common/UnTARFileCommand.java, hoot-services/src/main/java/hoot/services/command/common/UnZIPFileCommand.java, hoot-services/src/main/java/hoot/services/command/common/ZIPDirectoryContentsCommand.java, hoot-services/src/main/java/hoot/services/command/common/ZIPFileCommand.java, hoot-services/src/main/java/hoot/services/controllers/export/ExportResource.java, hoot-services/src/main/resources/applicationContext.xml, hoot-services/src/main/webapp/WEB-INF/web.xml
Updates to Hoot services' documentation.
https://github.com/ngageoint/hootenanny/issues/1427
=> Update Hoot's Documentation  

docs/user/Hootenanny-id.asciidoc, hoot-services/src/main/java/hoot/services/controllers/nodejs/TranslationServiceResource.java, templates/report/csr-default.js, test-files/ui/features/import_export_delete_osm_dataset.feature
Related: https://github.com/ngageoint/hootenanny-ui/pull/913
=> Correct spelling of OpenStreetMap

scripts/HootEnv.sh
1. refs #1740 
skip ui
skip rpms
=> Add flag to enabled ccache w/ PCH

plugins/geonames_rules.js
refs #1754 
Fixed tourism=museum
Also fixed the develop branch of fouo translations as well
=> Fixed tourism=museum

test-files/ui/features/translation_ingest_edit.feature
refs #1752
skip core
skip rpm
skip centos
=> update UI and update failing cucumber test

translations/RenderDb.js
refs #1764 
Add filtering and support for hoot:id to the RenderDB.js translation file
skip ci
=> Added hoot:id and filtering to the RenderDB.js file

node-export-server/server.js
refs #1760
accepts osm xml payload
skip ci (no tests exercise the node-export-server)
=> Add a POST handler for input datasource to node-export-server

test-files/ui/features/clip.feature
=> Update clip tool test

conf/services/DefaultTranslations.json, hoot-core/src/main/cpp/hoot/core/io/OgrUtilities.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmGeoJsonReader.cpp, node-export-server/server.js, plugins/gifd_d4.js, plugins/gifd_d4_rules.js, translations/GIFD_D4.js, translations/RenderDb.js
Refs #1767 
Read GeoJSON with IDs that contain xxxx/###### format. Use the OsmGeoJsonReader class for reading GeoJSON.
=> Fix loading of mapedit-overpass GeoJSON

node-export-server/server.js
also include debug tags for OSM schema to ogr formats
so osm ids will be preserved.
skip ci
=> add a job endpoint to track status, return job hash

conf/services/DefaultTranslations.json, plugins/geonames_rules.js, plugins/wpi_rules.js, translations/WorldPortIndex.js
@jasonsurratt  Ready for you to test
=> World Port Index translation

test-files/ui/features/bulk_import_multidelete.feature, test-files/ui/features/review_layer_no_inputs_loaded.feature
Submodule hoot-ui e467398..aa737fb:
> Improve UI of bulk import
=> Change title of Bulk Import Form

scripts/jenkins/Jenkinsfile
=> Enhancements to Jenkinsfile for more stages, notifications

VagrantProvisionCentOS7.sh, scripts/util/Centos7_only_core.sh
refs #1821
skip ui
skip rpms
skip ci
=> Fixed wrong RPM name

node-export-server/config.json, node-export-server/server.js
=> Node export file hash fix and other changes to export server

plugins/mgcp_rules.js
=> Added DB030

scripts/jenkins/Jenkinsfile
=> Fix --diff with core tests

hoot-rnd/src/main/cpp/hoot/rnd/conflate/multiary/MultiaryReviewCommand.cpp, hoot-rnd/src/test/cpp/hoot/rnd/conflate/multiary/MultiaryReviewCommandTest.cpp
=> Implement correct hash calculation in MultiaryReviewCommand

hoot-core/src/main/cpp/hoot/core/io/ApiDb.h, hoot-core/src/main/cpp/hoot/core/io/HootApiDbWriter.cpp
Refs #1830
Made ending transactions and closing api databases more fault tolerant.
=> Successful Jenkins builds hiding errors

plugins/fcode_common.js, plugins/ggdm30.js, plugins/mgcp.js, plugins/tds40.js, plugins/tds61.js
refs #1836 
Changed the translation.
=> Fixed the Dragons Teeth translation

test-files/ui/features/step_definitions/custom_steps.rb
=> fix test step to work with cucumber gem 3.0.1

VAGRANT.md, test-files/ui/features/step_definitions/custom_steps.rb, test-files/ui/features/translation_assistant.feature, test-files/ui/features/translation_ingest_edit.feature
Tests should pass now. Also update the readme with relevant information.
skip rpm
skip core
=> Update translations cuke test

plugins/fcode_common.js, plugins/ggdm30_rules.js, plugins/mgcp_rules.js, plugins/tds40_rules.js, plugins/tds61_rules.js
refs #1850 
@bmarchant It's just a One Line Change........
=> Tweaked the translation for FCODE BH155

node-export-server/server.js
=> don't use RenderDb translation for export to OSM in xml format

plugins/TranslationServer.js
=> Translation Server, map Vertex to Point when getting schema

scripts/jenkins/Jenkinsfile
Identified during the release process that we weren't updating the hoot-ui submodule appropriately in the new pipeline as code Jenkinsfile.
=> Merge submodule fix in release into develop

hoot-core/src/main/cpp/hoot/core/conflate/polygon/MultiPolygonCreator.cpp, hoot-core/src/main/cpp/hoot/core/io/OgrWriter.cpp, hoot-core/src/main/cpp/hoot/core/schema/OsmSchema.cpp, hoot-core/src/main/cpp/hoot/core/util/ElementConverter.cpp, hoot-core/src/main/cpp/hoot/core/util/MetadataTags.h
Refs #1856 
Fixed MultiPolygonCreator to update ends of polygon
Added boundaries to recognized relation types
Fixed up formatting in places.
=> Multipolygon relations not exporting from OSM as complete polygons

conf/core/ConfigOptions.asciidoc, hoot-core-test/src/test/cpp/hoot/core/conflate/poi-polygon/PoiPolygonMatchTest.cpp, hoot-core-test/src/test/cpp/hoot/core/conflate/poi-polygon/PoiPolygonMergerCreatorTest.cpp, hoot-core-test/src/test/cpp/hoot/core/visitors/SetTagVisitorTest.cpp, hoot-core/src/main/cpp/hoot/core/conflate/poi-polygon/PoiPolygonMatch.cpp, hoot-core/src/main/cpp/hoot/core/conflate/poi-polygon/PoiPolygonMatch.h, hoot-core/src/main/cpp/hoot/core/conflate/poi-polygon/PoiPolygonMatchCreator.cpp, hoot-core/src/main/cpp/hoot/core/conflate/poi-polygon/extractors/PoiPolygonAddressScoreExtractor.cpp, hoot-core/src/main/cpp/hoot/core/conflate/poi-polygon/extractors/PoiPolygonAddressScoreExtractor.h, hoot-core/src/main/cpp/hoot/core/visitors/SetTagVisitor.cpp, hoot-core/src/main/cpp/hoot/core/visitors/SetTagVisitor.h, test-files/cases/unifying/poi-polygon/Config.conf, test-files/cases/unifying/poi-polygon/poi-polygon-10/Config.conf, test-files/cases/unifying/poi-polygon/poi-polygon-10/Expected.osm, test-files/cases/unifying/poi-polygon/poi-polygon-10/Input1.osm, test-files/cases/unifying/poi-polygon/poi-polygon-10/Input2.osm, test-files/cases/unifying/poi-polygon/poi-polygon-10/README.txt, test-files/visitors/SetTagVisitorTest-runAddNewTest.osm, test-files/visitors/SetTagVisitorTest-runAppendValueTest.osm, test-files/visitors/SetTagVisitorTest-runElementFilterTest.osm, test-files/visitors/SetTagVisitorTest-runOverwriteExistingTest.osm, test-files/visitors/SetTagVisitorTest.osm
1. refs #1874 - add option to promote generic points to POIs if they have a valid address
2. refs #1874 - make the match/review evidence threshold configurable
3. refs #1874 - add an element type visitor to SetTagVisitor
=> poi/poly changes to support CO use case

conf/core/ConfigOptions.asciidoc, docs/user/OsmApiDb.asciidoc, hoot-core-test/src/test/cpp/hoot/core/io/ServiceOsmApiDbBulkInserterTest.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiDbBulkInserter.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiDbBulkInserter.h
=> make setval sql output optional --> 1833

conf/core/ConfigOptions.asciidoc, docs/user/OsmApiDb.asciidoc, hoot-core-test/src/test/cpp/hoot/core/io/ServiceOsmApiDbBulkInserterTest.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiDbBulkInserter.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiDbBulkInserter.h
=> make setval sql output optional --> develop

plugins/.gitignore, plugins/rules2validation.js, plugins/validation_mocks.js
=> Add node script to generate validation mappings json for JOSM

hoot-core/src/main/cpp/hoot/core/elements/Relation.h, hoot-core/src/main/cpp/hoot/core/util/ElementConverter.cpp, hoot-core/src/main/cpp/hoot/core/util/MetadataTags.h
Refs #1947 
Set restriction relations to use GEOS_GEOMETRYCOLLECTION geometry type instead of failing to export
=> ogr2osm export of restriction relations failing

plugins/ggdm30.js, plugins/mgcp.js, plugins/tds40.js, plugins/tds61.js, plugins/test/TranslationServer.js
Refs: #1953 
Slight mixup between Cables and Powerlines
=> Fixed powerlines

hoot-core/src/main/cpp/hoot/core/util/Factory.cpp, hoot-core/src/main/cpp/hoot/core/util/Factory.h
Address potential memory leak in core/util/Factory
=> Convert bare pointer to smart pointer in core/util/Factory

pretty-pipes/pp-lib/src/main/cpp/pp/Factory.cpp, pretty-pipes/pp-lib/src/main/cpp/pp/Factory.h
Refs #1932 
Explanation of branch name: I accidentally named a previous branch 1932, when it should have been 1922!
=> Convert naked pointer to smart pointer in PrettyPipes factory

Vagrantfile
Also cleaned up some formatting
=> Add vsphere provider to vagrantfile

hoot-services/src/main/java/hoot/services/command/ExternalCommandRunnerImpl.java, hoot-services/src/main/java/hoot/services/controllers/export/ExportCommand.java, hoot-services/src/main/java/hoot/services/controllers/export/ExportOSMCommand.java, hoot-services/src/main/java/hoot/services/controllers/export/ExportParams.java
https://github.com/DigitalGlobe/VGI-team-repo/issues/581
=> Export options

hoot-core-test/src/test/cpp/hoot/core/io/OsmXmlReaderTest.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmXmlReader.cpp
=> Fix for gzip -k on CentOS

plugins/ggdm30.js, plugins/mgcp.js, plugins/tds40.js, plugins/tds61.js
Refs: #2028
I don't know why the name on the commit is dorked up. My name is on the commit in #2028
=> Added code to drop invalid 2nd/3rd features

scripts/database/DeleteAllTables.sh, test-files/cmd/glacial/ServiceExportOsm.sh
=> One file fixed.

test-files/cmd/glacial/OptimizeConflateSettingsCmd/static-tests/highway-001/Expected.osm, test-files/cmd/glacial/OptimizeConflateSettingsCmd/static-tests/highway-001/Input1.osm, test-files/cmd/glacial/OptimizeConflateSettingsCmd/static-tests/highway-001/Input2.osm, test-files/cmd/glacial/OptimizeConflateSettingsCmd/static-tests/highway-001/README.txt, test-files/cmd/glacial/OptimizeConflateSettingsCmd/static-tests/highway-002/Expected.osm, test-files/cmd/glacial/OptimizeConflateSettingsCmd/static-tests/highway-002/Input1.osm, test-files/cmd/glacial/OptimizeConflateSettingsCmd/static-tests/highway-002/Input2.osm, test-files/cmd/glacial/OptimizeConflateSettingsCmd/static-tests/highway-002/README.txt, test-files/cmd/glacial/OptimizeConflateSettingsCmd/static-tests/highway-003/Expected.osm, test-files/cmd/glacial/OptimizeConflateSettingsCmd/static-tests/highway-003/Input1.osm, test-files/cmd/glacial/OptimizeConflateSettingsCmd/static-tests/highway-003/Input2.osm, test-files/cmd/glacial/OptimizeConflateSettingsCmd/static-tests/highway-003/README.txt, test-files/cmd/glacial/OptimizeConflateSettingsCmdTest.sh
=> shorten runtime for optimize conflate settings cmd test

plugins/ggdm30.js, plugins/mgcp.js, plugins/tds40.js, plugins/tds61.js
Using this area as a test: https://download.bbbike.org/osm/extract/planet_-64.7186,18.3418_-64.3724,18.5439.osm.gz
Compare the difference in O2S_A layers. This fixes the Island problem.
=> Add in missing Islands

hoot-services/src/main/java/hoot/services/controllers/conflation/ConflateCommand.java, hoot-services/src/test/java/hoot/services/controllers/conflation/ConflateCommandTest.java
=> Don't output conflate score tags by default in services

configure.ac
Refs #2124 
Moved configure.ac from GEOS 3.5.0 to 3.6.1
=> Update configure to GEOS 3.6.1

hoot-core/src/main/cpp/hoot/core/cmd/DiffConflateCmd.cpp
=> Add some special differential stats

Makefile.old, plugins/ggdm30.js, plugins/mgcp.js, plugins/tds40.js, plugins/tds61.js
refs: VGI #1285
Added code to check for other tags to populate the SDV/ZI001_SDV/ZI001_SDD attribute.
@mschicker Please review this since you love Javascript so much.
=> Added options for SDV/ZI001_SDV/ZI001_SDD

hoot-services/src/main/java/hoot/services/utils/DbUtils.java, hoot-services/src/test/java/hoot/services/utils/DbUtilsTest.java
As the title says. Includes a JUnit Brian wrote.
=> 2135 - Fix deleting tables under Maps table.

conf/services/conflateAdvOps.json, test-files/ui/features/advanced_options.feature, test-files/ui/features/advanced_options_invalid_input.feature
Need to do this as a temporary solution until [ui 969](https://github.com/ngageoint/hootenanny-ui/issues/969) has been completed.
=> temp add rubber sheet ui options back in

hoot-core-test/src/test/cpp/hoot/core/algorithms/WayMatchStringMergerTest.cpp
refs: #2188 
@bmarchant Could you review this please.
=> Fixed path in unit test

scripts/tomcat/CopyWebAppsToTomcat.sh, scripts/tomcat/centos7/tomcat8_install.sh
Fixes #2210 by setting the group to `tomcat` when using `sudo` to deploy the web application files.
=> Fix Tomcat Deployment

VagrantProvisionVars.sh, scripts/chrome/driver-install.sh
Fixes #2234, upgrades to ChromeDriver 2.36.
=> Upgrade to ChromeDriver 2.36

test-files/ui/features/support/hooks.rb
=> Use updated cucumber API syntax in hooks file.

scripts/jenkins/Jenkinsfile
Remove hadoop provisioner.  Solves #2249
=> Remove hadoop provisioner

hoot-core/src/main/cpp/hoot/core/io/OsmGeoJsonReader.cpp, test-files/io/GeoJson/BostonSubsetRoadBuilding.osm
Refs #2271
Added checks to update relation types in GeoJson reading code, also fixed some tab issues.
=> GeoJson GBDX files are failing to translate

VagrantProvisionVars.sh
=> Update ChromeDriver to 2.37.

hoot-core/src/main/cpp/hoot/core/conflate/RemoveRoundabouts.cpp, hoot-core/src/main/cpp/hoot/core/conflate/Roundabout.cpp, test-files/cases/hoot-rnd/roundabouts/rcase-003/Expected.osm, test-files/cases/hoot-rnd/roundabouts/rcase-003/README.txt
=> Handle double-roundabout situation

hoot-core/src/main/cpp/hoot/core/conflate/Roundabout.cpp, hoot-core/src/main/cpp/hoot/core/conflate/Roundabout.h, test-files/cases/hoot-rnd/roundabouts/rcase-001/Expected.osm, test-files/cases/hoot-rnd/roundabouts/rcase-002/Expected.osm, test-files/cases/hoot-rnd/roundabouts/rcase-003/Expected.osm
Fix situation where one of the roads entering the roundabout wouldn't conflate, but the rest would.
Refs #2269
=> Improve roundabout conflation

hoot-core/src/main/cpp/hoot/core/conflate/SmallWayMerger.cpp, hoot-core/src/main/cpp/hoot/core/conflate/SmallWayMerger.h, hoot-core/src/main/cpp/hoot/core/conflate/splitter/CornerSplitter.cpp, hoot-core/src/main/cpp/hoot/core/conflate/splitter/DualWaySplitter.cpp, hoot-core/src/main/cpp/hoot/core/conflate/splitter/DualWaySplitter.h, hoot-core/src/main/cpp/hoot/core/conflate/splitter/IntersectionSplitter.cpp, hoot-core/src/main/cpp/hoot/core/conflate/splitter/IntersectionSplitter.h, test-files/cases/hoot-rnd/network/conflicts/highway-012/Expected.osm, test-files/cases/hoot-rnd/network/conflicts/pap-002/Expected.osm, test-files/cases/hoot-rnd/network/iterative/highway-012/Expected.osm, test-files/cmd/glacial/NetworkConflateCmdInputReverseTest/output.osm, test-files/cmd/glacial/NetworkConflateCmdTest/output.osm, test-files/cmd/glacial/RubberSheetConflateTest/output.osm, test-files/cmd/glacial/ServiceOsmApiDbHootApiDbRafahConflateTest/output.osm, test-files/cmd/glacial/serial/ServiceOsmApiDbHootApiDbRafahConflateTest.sh.stdout, test-files/cmd/slow/ConflateAverageTest/output.osm
Refs #2232 
Updated `SmallWayMerger` to pass on parent ID.  Also removed `preserveUnknown1` code from the `CornerSplitter`, `DualWaySplitter`, and `IntersectionSplitter`.
=> More less destructive splitting/way creation - SmallWayMerger

hoot-js/src/main/cpp/hoot/js/v8Engine.cpp, hoot-js/src/main/cpp/hoot/js/v8Engine.h
=> Last instance of the depricated auto_ptr removed

plugins/ggdm30.js, plugins/mgcp.js, plugins/tds40.js, plugins/tds61.js, plugins/test/TranslationServer.js
Stopped "amenity=ferry_terminal" being turned into a building (AL013/AL015)
@maxgrossman Give this a run and see if it fixes your issue.
refs: 2345
=> Fixed AQ080 & MGCP AQ125

plugins/ggdm30.js, plugins/tds40.js, plugins/tds61.js
refs: #2343 
Drop the religion tag when appropriate.
=> Stop religion tags stomping on denominations

hoot-core/src/main/cpp/hoot/core/algorithms/optimizer/IntegerProgrammingSolver.cpp
Refs #2001 
Changed the GLPK heuristic to run the conflation more stable
=> Figure out why core tests are randomly failing

conf/schema/leisure.json, conf/schema/man_made.json
refs: #2348 
@maxgrossman For you.
=> Fix Line vs Area for some features

hoot-services/src/test/java/hoot/services/command/ExternalCommandRunnerImplTest.java, hoot-services/src/test/java/hoot/services/jerseyframework/HootServicesSpringTestConfig.java
This is needed if you don't have postgres on the box with hoot.
=> Make the services test use ENV variables

hoot-core-test/src/test/cpp/hoot/core/index/metric-hybrid/RFqHybridTreeTest.cpp, hoot-core/src/main/cpp/hoot/core/algorithms/linearreference/WaySubline.cpp, hoot-core/src/main/cpp/hoot/core/algorithms/zindex/LongBox.cpp, hoot-core/src/main/cpp/hoot/core/algorithms/zindex/ZCurveRanger.cpp, hoot-core/src/main/cpp/hoot/core/cmd/AddOsmPbfHeaderCmd.cpp, hoot-core/src/main/cpp/hoot/core/conflate/frechet/FrechetDistance.cpp, hoot-core/src/main/cpp/hoot/core/conflate/match-graph/MatchGraph.cpp, hoot-core/src/main/cpp/hoot/core/conflate/network/NetworkMatch.cpp, hoot-core/src/main/cpp/hoot/core/conflate/network/OsmNetworkExtractor.cpp, hoot-core/src/main/cpp/hoot/core/elements/NodeData.cpp, hoot-core/src/main/cpp/hoot/core/manipulators/WayMatchSet.h, hoot-core/src/main/cpp/hoot/core/schema/ImplicitTagUtils.cpp, hoot-core/src/main/cpp/hoot/core/util/GeometryPainter.cpp, hoot-js/src/main/cpp/hoot/js/util/HootExceptionJs.cpp, hoot-rnd/src/test/cpp/hoot/rnd/conflate/opt/AbstractRegressionTestFitnessFunction.cpp, hoot-rnd/src/test/cpp/hoot/rnd/conflate/opt/PertyTest.cpp, hoot-rnd/src/test/cpp/hoot/rnd/conflate/opt/ReleaseTest.cpp, tgs/src/main/cpp/tgs/DelaunayTriangulation/DelaunayTriangulation.cpp, tgs/src/main/cpp/tgs/FeatureExtraction/GeneticAlgorithm.cpp, tgs/src/main/cpp/tgs/FeatureSelection/CfsSubsetEvaluator.cpp, tgs/src/main/cpp/tgs/RStarTree/Box.cpp, tgs/src/main/cpp/tgs/RStarTree/HilbertRTree.cpp, tgs/src/main/cpp/tgs/RandomForest/DataFrame.cpp, tgs/src/test/cpp/tgs/FeatureExtraction/CalculatorGenomeNodeTest.cpp
Refs #2371
Lots of minor changes to fix errors found by SonarCube.  Best way to understand each change is to click on the commit for the description and the related changes, one by one.
=> Fix SonarCube findings for Hootenanny

plugins/mgcp.js
=> Somehow missed a line in the translation

hoot-core/src/main/cpp/hoot/core/conflate/network/NetworkMerger.cpp
=> Make dogleg review message consistent

plugins/TranslationServer.MD, plugins/TranslationServer.js, plugins/package-lock.json, plugins/package.json, plugins/test/MostEnglishName.js, plugins/test/SchemaTools.js, plugins/test/TranslationServer.js
also update markdown API doc
mark some new methods deprecated
refs #2376
=> Remove to English translation dependency from translation server

hoot-core/src/main/cpp/hoot/core/algorithms/WayMatchStringSplitter.cpp, hoot-core/src/main/cpp/hoot/core/algorithms/WaySplitter.cpp, hoot-core/src/main/cpp/hoot/core/algorithms/linearreference/WaySubline.cpp, hoot-core/src/main/cpp/hoot/core/conflate/network/NetworkMatchCreator.cpp, hoot-core/src/main/cpp/hoot/core/conflate/poi-polygon/PoiPolygonMerger.cpp
Refs #2404 
Removed untrue 'assert' statements that cause tests to fail in DEBUG but pass in RELEASE.
=> Nightly Regression

plugins/translate.js
refs: #2364 
If the first character of the tag name is "#" then the tag will only be modified if it already exists.
@sisskind and @maxgrossman   Over to you. See [ UI Ticket #1089](https://github.com/ngageoint/hootenanny-ui/issues/1089)
=> Added a Modify option to the Tag Override function

hoot-core/src/main/cpp/hoot/core/conflate/polygon/MultiPolygonCreator.cpp
=> Fix way ordering when making a multipolygon

hoot-core/src/main/cpp/hoot/core/conflate/merging/SmallWayMerger.cpp, hoot-core/src/main/cpp/hoot/core/elements/Way.cpp, hoot-core/src/main/cpp/hoot/core/elements/Way.h
=> Address some "Critical" and "Major" SonarQube findings

plugins/mgcp_rules.js
refs: #2432 
Removed the length validation for the TXT field.
=> Removed the TXT length validation

VagrantProvisionVars.sh
=> Upgrade to ChromeDriver 2.40

hoot-core/src/main/cpp/hoot/core/ops/CalculateStatsOp.cpp
=> Add check for unknown elements, preventing a null-ptr deref.

hoot-core-test/src/test/cpp/hoot/core/TestUtils.cpp, hoot-core-test/src/test/cpp/hoot/core/algorithms/WayJoinerTest.cpp, test-files/algorithms/wayjoiner/WayJoinerConflateExpected.osm
=> Fix an inconsistency in test execution between serial and parallel

conf/core/ConfigOptions.asciidoc, hoot-core/src/main/cpp/hoot/core/io/OgrUtilities.cpp, hoot-core/src/main/cpp/hoot/core/io/OgrWriter.cpp
refs: #2478 
@bmarchant Could you review this please.
=> Added CSV options to the OGR Reader

conf/schema/use.json
refs: #2485
Added an internal schema entry
=> Added the first of many schema geometry fixes

conf/schema/use.json
refs: #2490 
Yet another use=* issue
=> Fixed another use=* issue

node-export-server/package-lock.json, node-export-server/server.js
=> update node-export-server for --trans

conf/schema/use.json
=> Another use=* issue

VagrantProvisionVars.sh
Fixes #2494, use latest stable version of RVM.
=> Upgrade to RVM 1.29.4.

conf/schema/leisure.json, conf/schema/use.json, hoot-core/src/main/cpp/hoot/core/schema/OsmSchema.cpp
refs: #2503 
Now we wait for Jenkins.....
=> Blanket fix for use=*

docs/commands/changeset-apply.asciidoc, hoot-core-test/src/test/cpp/hoot/core/io/OsmApiChangesetTest.cpp, hoot-core/src/main/cpp/hoot/core/cmd/ApplyChangesetCmd.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangeset.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangeset.h, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangesetElement.h, hoot-core/src/main/cpp/hoot/core/io/OsmApiNetworkRequest.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiWriter.cpp, test-files/io/OsmChangesetElementTest/ToyTestASplit1.osc, test-files/io/OsmChangesetElementTest/ToyTestASplit1.response.xml, test-files/io/OsmChangesetElementTest/ToyTestASplit2.osc, test-files/io/OsmChangesetElementTest/ToyTestASplit2.response.xml, test-files/io/OsmChangesetElementTest/ToyTestASplit3.osc, test-files/io/OsmChangesetElementTest/ToyTestASplit3.response.xml, test-files/io/OsmChangesetElementTest/ToyTestASplit4.osc, test-files/io/OsmChangesetElementTest/ToyTestASplit4.response.xml
Refs #2448 
Added option to changeset-apply to take multiple files via command line.
Increased upload speed by 4-7% ordering uploads node/way/relation.
Fixed Sonar issues.
Updated documentation.
=> Add "write changeset to OSM API Db" as a Hootenanny command

hoot-core/src/main/cpp/hoot/core/cmd/ApplyChangesetCmd.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangeset.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangeset.h, hoot-core/src/main/cpp/hoot/core/io/OsmApiNetworkRequest.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiNetworkRequest.h, hoot-core/src/main/cpp/hoot/core/io/OsmApiWriter.cpp
Refs #2356 
Fixed errors with unknown relations that caused them to not be pushed to the OSM API.  Cleaned up some network request code.
=> Write changeset files to OSM API database through the API

plugins/tds61.js
=> Add line to update array length after it changes.

conf/core/ConfigOptions.asciidoc, test-files/ui/features/advanced_options.feature, test-files/ui/features/advanced_options_invalid_input.feature
=> Increase element cache sizes

hoot-core/src/main/cpp/hoot/core/io/OgrWriter.cpp, test-files/cmd/slow/o2sTranslationTest.sh.stdout
refs: #2554 
@brianhatchl Could you give it a run please.
=> Fixed field length error on export

conf/core/ConfigOptions.asciidoc, docs/commands/count-features.asciidoc, hoot-core/src/main/cpp/hoot/core/cmd/CountFeaturesCmd.cpp, hoot-core/src/main/cpp/hoot/core/visitors/AverageNumericTagsVisitor.cpp, hoot-core/src/main/cpp/hoot/core/visitors/AverageNumericTagsVisitor.h, hoot-core/src/main/cpp/hoot/core/visitors/SumNumericTagsVisitor.h
also adds AverageNumericTagsVisitor
=> fix bug with count-features handling of configs for criterion/visitors

hoot-services/src/main/java/hoot/services/controllers/job/JobResource.java, hoot-services/src/main/java/hoot/services/controllers/jobs/JobsResource.java, hoot-services/src/main/java/hoot/services/jobs/JobsStatusesManager.java, hoot-services/src/main/java/hoot/services/jobs/JobsStatusesManagerImpl.java, hoot-services/src/main/java/hoot/services/models/db/JobStatus.java, hoot-services/src/main/java/hoot/services/models/db/QJobStatus.java, hoot-services/src/main/webapp/WEB-INF/web.xml, hoot-services/src/test/java/hoot/services/controllers/info/ErrorLogTest.java, hoot-services/src/test/java/hoot/services/controllers/jobs/JobsResourceTest.java
Add a jobs resource to hoot-services
refs #2565
* impl 'hoot-services/jobs/recent'
* Reports jobs in last 12 hours (or last 10 jobs if result is less than 10)
* impl tests for associated JobsResource class
* refactor ErrorLogTest#testGetErrorLog to remove character counting since log content is volatile
=> 2565, based on 2568

conf/schema/tourism.json
=> Add linestring to tourism=attraction

docs/algorithms/DifferentialConflation.asciidoc, docs/commands/conflate.asciidoc
=> Add some documentation for tag-diff algorithm and functionality

hoot-core-test/src/test/cpp/hoot/core/io/ElementCacheLruTest.cpp, hoot-core/src/main/cpp/hoot/core/io/ElementCacheLRU.cpp, hoot-core/src/main/cpp/hoot/core/io/ElementCacheLRU.h
refs #2594
Now it takes constant time to figure out which item is least recently used, instead of n time. Also added another unit test.
=> Update ElementCacheLRU class

hoot-core/src/main/cpp/hoot/core/conflate/DiffConflator.cpp, test-files/cmd/slow/DiffConflateCmdTest/output.osm, test-files/cmd/slow/DiffConflateCmdTest/output.tags.osc, test-files/cmd/slow/DiffConflateCmdTest/output_unified.osc, test-files/cmd/slow/DiffConflateCmdTest/output_unified.osm, test-files/conflate/diff/input1.osm, test-files/conflate/diff/input2.osm
=> Update tag-diff merge algorithm to keep the "old name" as alt_name.

test-files/ui/features/bulk_import_multidelete.feature
refs #2612
* refactor bulk_import_multidelete layer names to contain '_Cucumber'
=> UI Test layers should match '%Cucumber%'

hoot-services/src/main/java/hoot/services/controllers/job/JobResource.java, hoot-services/src/main/java/hoot/services/controllers/jobs/JobsResource.java, hoot-services/src/main/java/hoot/services/jobs/JobsStatusesManager.java, hoot-services/src/main/java/hoot/services/jobs/JobsStatusesManagerImpl.java, hoot-services/src/main/java/hoot/services/models/db/JobStatus.java, hoot-services/src/main/java/hoot/services/models/db/QJobStatus.java, hoot-services/src/main/webapp/WEB-INF/web.xml, hoot-services/src/test/java/hoot/services/controllers/info/ErrorLogTest.java, hoot-services/src/test/java/hoot/services/controllers/jobs/JobsResourceTest.java
=> 2565 redo: add /jobs resource

conf/services/DefaultTranslations.json, plugins/ggdm30_rules.js, plugins/gifd_d4_rules.js, plugins/translate.js, translations/UFD_to_Osm.js
=> UFD Translator

.gitignore, scripts/cover/coverGcov.sh, scripts/sonar/sonar-scan.sh, sonar-project.properties
Created `sonar-projects.properties` file and moved some static configuration settings to it including rule exclusions.  Updated scan and coverage scripts to output coverage files to a separate folder.  Also added scan folders and files to the `.gitignore` file.
=> Added exclusions to Sonar properties file

Makefile.am, Makefile.old
refs #2641 
Add 'core' target to Makefile
=> Makefile updates

.circleci/config.yml
=> Use the latest container releases in CircleCI configuration.

hoot-core/src/main/cpp/hoot/core/io/OsmApiChangeset.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangeset.h, hoot-core/src/main/cpp/hoot/core/io/OsmApiWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiWriter.h
Refs #2651 
Auto-fix version information on OSM API uploads.
=> Auto-fix some OSM API changeset issues

hoot-core/src/main/cpp/hoot/core/algorithms/ExpectationIntersection.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmPbfWriter.cpp, tbs/src/main/cpp/tbs/stats/TDistribution.cpp
=>  Remove side-effects from right hand of && or || operators

scripts/sonar/sonar-install.sh
=> Update the SonarQube download URL

plugins/ggdm30.js, plugins/ggdm30_rules.js, plugins/tds40.js, plugins/tds40_rules.js, plugins/tds61.js, plugins/tds61_rules.js, plugins/test/mall_motor_vehicle.js
=> Fixed toilets and malls

hoot-core/src/main/cpp/hoot/core/io/DataConverter.cpp, hoot-core/src/main/cpp/hoot/core/io/OgrUtilities.cpp, hoot-core/src/main/cpp/hoot/core/io/OgrWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/ScriptTranslatorFactory.cpp, test-files/cmd/slow/AppendFGDBTest.sh
With the newer version of GDAL, we need to specify GDAL_OF_UPDATE when we open an existing dataset for writing.
@bwitham Could you review this for me please.
=> Append to dataset now appends

hoot-core/src/main/cpp/hoot/core/io/ApiDb.h, hoot-services/src/main/resources/db/changelogs/021-ReviewBookmarksConstraints.xml
refs #2642
* add migration to enhance review_bookmarks foreign key
* update hoot-core db version
=> hoot-core deleteMap can fail when

Makefile.hoot
=> Fix UI 2.0 Makefile Target

plugins/ggdm30_rules.js, plugins/mgcp_rules.js, plugins/tds40_rules.js, plugins/tds61_rules.js
refs: #2731 
Added this to help CWS
=> Added barrier=city_wall

plugins/TranslationServer.js
=> OSM with missing nodes fails geometry type handling for closed ways

plugins/ElementMergeServer.js, plugins/test/ElementMergeServer.js
refactor check for supported methods to occur before payload is read
=> add support for OPTIONS request to elementmerge

hoot-services/src/main/java/hoot/services/controllers/ogr/ExtractAttributesResource.java
=> only include shp file ref for translation assistant extract attributes

node-export-server/package-lock.json, node-export-server/package.json, node-export-server/server.js
=> update node-export-server npm deps to avoid vulnerabilities

hoot-services/src/main/java/hoot/services/controllers/auth/OAuth1Resource.java, hoot-services/src/main/java/hoot/services/controllers/osm/map/FolderResource.java, hoot-services/src/main/java/hoot/services/controllers/osm/map/MapResource.java
refs #2788
* remove requirement for users to own destination folder for map/move
* add logging to oauth routine
=> bugfix: allow users to move data to a public folder

VagrantBuild.sh, scripts/jenkins/Jenkinsfile
Some builds are still getting hung up.  Hopefully this will shed some light on the issue.
=> Turn on verbose builds in develop

plugins/TranslationServer.js
=> Remove debug statement

conf/services/conflateAdvOps.json
* Add to the ui adv opts:
* RemoveDuplicateRelationMembersVisitor
* RelationCircularRefRemover
* RemoveEmptyRelationsOp
=> Missing UI adv cleaning opts 12/18/18

scripts/jenkins/Jenkinsfile
Attempt to fix check for cron trigger in Jenkins pipeline.
=> Fix cron trigger check and change cron time to early in the morning

docs/HootenannyConfigOptions.asciidoc, hoot-core/src/main/cpp/hoot/core/util/Settings.cpp
Since these options were already available but not documented, this is the documentation update.
=> Update documentation for command line options, appending and removing.

conf/core/ConfigOptions.asciidoc, plugins/MassNh.js, plugins/TranslationServer.js, plugins/ggdm30.js, plugins/gifd_d4.js, plugins/mgcp.js, plugins/tds40.js, plugins/tds61.js, plugins/test/TranslationServer.js, plugins/test/bridge_aqueduct.js, plugins/test/bulk_translate.js, plugins/test/facility.js, plugins/test/line-to-area-cases.js, plugins/test/marketplace.js, plugins/test/measurement_fields.js, plugins/test/runway.js, translations/UFD_to_Osm.js
refs: #2813 
Turn UUID's off on import with: `-D ogr.add.uuid=false`
=> Added an option to not add a uuid on import

.circleci/config.yml, VagrantProvisionVars.sh
Fixes #2820 and uses latest version of the Maven cache.
=> Update ChromeDriver to 2.45

plugins/ggdm30.js, plugins/tds61_rules.js
refs: #2834 
Also, fixed a typo in the GGDM30 translator.
=> Fixed an FGDB layer name error

hoot-core/src/main/cpp/hoot/core/visitors/AddRef1Visitor.h, hoot-js/src/main/cpp/hoot/js/visitors/ElementVisitorJs.cpp
to fix js call in train-highways.child
=> Change AddRef1Visitor from ElementVisitor to ElementOsmMapVisitor

conf/services/conflateAdvOps.json, conf/services/conflationAttributeOps.json, hoot-services/src/main/java/hoot/services/HootProperties.java, hoot-services/src/main/java/hoot/services/controllers/conflation/AdvancedConflationOptionsResource.java, hoot-services/src/main/resources/conf/hoot-services.conf.in
refs #2842
also adds "Remove Unmatched Secondary Features" advanced option
used by Attribute conflation and update ui submodule
=> Add Attribute conflation type

rules/PolygonBuilding.js
=> Make generic building merge functions like other generic merge functions

conf/services/conflationAttributeOps.json
=> Use Unify road engine for Attribute conflation

hoot-core/src/main/cpp/hoot/core/algorithms/WayJoiner.cpp, hoot-core/src/main/cpp/hoot/core/conflate/highway/HighwayTagOnlyMerger.cpp, test-files/cases/unifying/highway-2888/Config.conf, test-files/cases/unifying/highway-2888/Expected.osm, test-files/cases/unifying/highway-2888/Input1.osm, test-files/cases/unifying/highway-2888/Input2.osm, test-files/cases/unifying/highway-2888/README.txt, test-files/cmd/glacial/NetworkConflateCmdInputReverseTest/output.osm
Fixes a bug where the secondary layer was unable to pass road tags to the primary layer; see test case unifying/highway-2888
=> Attribute Conflation tag merge fix #1

scripts/core/ServiceOsmApiDbHootApiDbConflate.sh, test-files/cmd/glacial/serial/RndServiceNodeDensityTilesCmdTest.sh
Refs #2881 
Re-enable a failing test and delete a previously removed command line option.
=> Re-enable unit test

Makefile.hoot, docs/developer/HootenannyTests.asciidoc
=>  Added docs as prerequisite to ui-test target

hoot-core/src/main/cpp/hoot/core/algorithms/FrechetDistance.cpp, hoot-core/src/main/cpp/hoot/core/util/Settings.cpp, test-files/cmd/quick/ConflateUnknownOptionTest.sh, test-files/cmd/quick/ConflateUnknownOptionTest.sh.stderr
Refs #2859 
Includes test script.
Trying this again targeting the develop branch.
=> Throw an error when trying to remove an unknown option

hoot-core/src/main/cpp/hoot/core/ops/MapCropper.cpp, hoot-rnd/src/main/cpp/hoot/rnd/cmd/NodeDensityTilesCmd.cpp
Refs #2657 
Remove the only bug in the code base.  Was also fixing other issues but reverted it and left the alphabetized `#include` list.
=> Sonar qube fixes

hoot-core-test/src/test/cpp/hoot/core/io/OsmApiChangesetTest.cpp, hoot-core-test/src/test/cpp/hoot/core/io/OsmApiWriterTest.cpp, hoot-core/src/main/cpp/hoot/core/io/HootNetworkRequest.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangeset.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangeset.h, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangesetElement.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangesetElement.h, hoot-core/src/main/cpp/hoot/core/io/OsmApiWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiWriter.h
Refs #2865 
Added in more conflict resolution code. Most notably checking error messages and finding the single element reported and splitting it out.
=> More conflict resolution

hoot-services/src/main/java/hoot/services/controllers/osm/map/FolderResource.java, hoot-services/src/main/java/hoot/services/controllers/osm/map/MapResource.java
=> change 401 to 403 where valid

hoot-rnd/src/main/cpp/hoot/rnd/schema/ImplicitTagRawRulesDeriver.cpp, hoot-rnd/src/main/cpp/hoot/rnd/schema/ImplicitTagRulesDatabaseDeriver.cpp
Updated implicit tag code to check if files exist before sorting and removed debug code.
=> Follow up to failing develop build in sorting code

.gitignore, Makefile.hoot, scripts/core/CreateConfigAsJSON.py
@maxgrossman & @brianhatchl  Does this work for you?
=> ConfigOptions as JSON

test-files/cases/network/conflicts/pap-001/Expected.osm, test-files/cases/network/conflicts/pap-001/Input1.osm, test-files/cases/network/conflicts/pap-002/Expected.osm, test-files/cases/network/conflicts/pap-002/Input1.osm, test-files/cases/network/conflicts/pap-003/Expected.osm, test-files/cases/network/conflicts/pap-003/Input1.osm, test-files/cases/network/conflicts/pap-004/Expected.osm, test-files/cases/network/conflicts/pap-004/Input1.osm, test-files/cases/network/conflicts/pap-005/Expected.osm, test-files/cases/network/conflicts/pap-005/Input1.osm, test-files/cases/network/conflicts/pap-006/Expected.osm, test-files/cases/network/conflicts/pap-006/Input1.osm, test-files/cases/network/conflicts/pap-007/Expected.osm, test-files/cases/network/conflicts/pap-007/Input1.osm, test-files/cases/network/conflicts/pap-008/Expected.osm, test-files/cases/network/conflicts/pap-008/Input1.osm, test-files/cases/network/conflicts/pap-009/Expected.osm, test-files/cases/network/conflicts/pap-009/Input1.osm, test-files/cases/network/conflicts/pap-010/Expected.osm, test-files/cases/network/conflicts/pap-010/Input1.osm, test-files/cases/roundabouts/rcase-001/Expected.osm, test-files/cases/roundabouts/rcase-001/Input1.osm, test-files/cases/roundabouts/rcase-002/Input1.osm, test-files/cases/roundabouts/rcase-003/Input1.osm, test-files/cases/unifying/building-5/Expected.osm, test-files/cases/unifying/building-5/Input1.osm
Refs #3004 
Updated the bad data inputs that have bad 'osm;osm' values so that the expected outputs are good.
=> Repeated 'source' and 'attribution' values from WayJoiner

VagrantProvisionCentOS7.sh, scripts/util/Centos7_only_core.sh, test-files/cmd/glacial/RndPertyScoreCmdTest.sh, test-files/cmd/glacial/RndPertyScoreCmdTest.sh.stdout
=> Swapped the bc program for a funky awk script

hoot-core/src/main/cpp/hoot/core/io/ApiDb.cpp
Refs #3059 
Simplification of ApiDb::unescapeTags() using Qt5s QRegularExpression.
No other changes since there was no additional performance gain in relation to #2976
=> Simplified AbiDb::unescapeTags() with QRegularExpression

hoot-core-test/src/test/cpp/hoot/core/io/ServiceHootApiDbTest.cpp, hoot-core-test/src/test/cpp/hoot/core/io/ServiceHootApiDbWriterTest.cpp, hoot-core-test/src/test/cpp/hoot/core/io/ServicesDbTestUtils.cpp, hoot-core-test/src/test/cpp/hoot/core/io/ServicesDbTestUtils.h, hoot-core/src/main/cpp/hoot/core/io/OgrWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/OgrWriter.h
Commit deff726 fixes #2934 
Commit 8766075 refs #2545 to fix/improve ogr writer
=> compareRecords consolidation, IncludeCircularErrorTags support in OgrWriter

scripts/jenkins/Jenkinsfile
A recent update to Jenkins plugins changed the behavior of the build status.  We need to update our messages to get the right status.
=> Enhance slack status message

Makefile.am, Makefile.hoot, VagrantBuild.sh, scripts/jenkins/Jenkinsfile, scripts/jenkins/TestPullRequest_ui.sh, scripts/tomcat/CopyWebAppsToTomcat.sh
Comment out `ui2x` until it is fixed in another branch.
=> Removing 2x from build until fixed.

Makefile.am, Makefile.hoot, VagrantBuild.sh, scripts/jenkins/Jenkinsfile, scripts/jenkins/TestPullRequest_ui.sh, scripts/tomcat/CopyWebAppsToTomcat.sh
Reverts ngageoint/hootenanny#3110
=> Revert "Removing 2x from build until fixed."

hoot-core/src/main/cpp/hoot/core/ops/BuildingOutlineUpdateOp.cpp, hoot-core/src/main/cpp/hoot/core/ops/BuildingOutlineUpdateOp.h
Refs #3024 
Consolidated duplicated code into one function.
=> Consolidate duplicated building unioning code in BuildingOutlineUpdateOp::_createOutline

hoot-core/src/main/cpp/hoot/core/io/OsmXmlChangesetFileWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmXmlChangesetFileWriter.h
Refs #2942 
Consolidated redundant tag writing in OsmXmlChangesetFileWriter
=> OsmXmlChangesetFileWriter has redundant tag writing code that can be consolidated

hoot-core/src/main/cpp/hoot/core/algorithms/merging/BuildingPartPreMergeCollector.h, hoot-core/src/main/cpp/hoot/core/conflate/highway/HighwaySnapMerger.cpp, hoot-core/src/main/cpp/hoot/core/ops/GeometryModifierOp.cpp, hoot-core/src/main/cpp/hoot/core/ops/MapCropper.cpp, hoot-core/src/main/cpp/hoot/core/ops/NamedOp.cpp, hoot-core/src/main/cpp/hoot/core/ops/NamedOp.h, hoot-core/src/main/cpp/hoot/core/visitors/AddMeasurementTagsVisitor.cpp, hoot-core/src/main/cpp/hoot/core/visitors/BuildingHeightVisitor.cpp, hoot-core/src/main/cpp/hoot/core/visitors/ToEnglishTranslationVisitor.h, hoot-core/src/main/cpp/hoot/core/visitors/geometrymodifiers/CollapsePolyGeoModifierAction.cpp, hoot-core/src/main/cpp/hoot/core/visitors/geometrymodifiers/CollapsePolyGeoModifierAction.h, hoot-core/src/main/cpp/hoot/core/visitors/geometrymodifiers/GeometryModifierAction.h, hoot-core/src/main/cpp/hoot/core/visitors/geometrymodifiers/GeometryModifierVisitor.cpp, hoot-core/src/main/cpp/hoot/core/visitors/geometrymodifiers/GeometryModifierVisitor.h, hoot-core/src/main/cpp/hoot/core/visitors/geometrymodifiers/WayToIntersectionGeoModifier.cpp, hoot-core/src/main/cpp/hoot/core/visitors/geometrymodifiers/WayToIntersectionGeoModifier.h, hoot-core/src/main/cpp/hoot/core/visitors/geometrymodifiers/WayToPolyGeoModifierAction.cpp, hoot-core/src/main/cpp/hoot/core/visitors/geometrymodifiers/WayToPolyGeoModifierAction.h, hoot-core/src/main/cpp/hoot/core/visitors/poi-polygon/PoiPolygonMatchVisitor.h, tgs/src/main/cpp/tgs/RStarTree/HilbertRTree.h
Refs #2657 
Squashed the SonarQube bug
De-smelled the last 30 days of code
Fixed some code to the coding standard
=> Fix SonarQube bug and recent code smells

hoot-rnd/src/test/cpp/hoot/rnd/conflate/network/IterativeNetworkMatcherTest.cpp, hoot-rnd/src/test/cpp/hoot/rnd/conflate/network/SingleSidedNetworkMatcherTest.cpp, hoot-rnd/src/test/cpp/hoot/rnd/conflate/network/VagabondNetworkMatcherTest.cpp, test-files/conflate/network/IterativeNetworkMatcherTestExpected.osm, test-files/conflate/network/SingleSidedNetworkMatcherTestExpected.osm, test-files/conflate/network/VagabondNetworkMatcherTestExpected.osm
Refs #3114
Added expected final map output for all test to test-files and compare test output.
=> Fixes for Network Matcher Tests

plugins/dnc.js, plugins/ggdm30.js, plugins/mgcp.js, plugins/tds40.js, plugins/tds61.js
=> Removed a geometry check from villages, hamlets etc

docs/algorithms/AlphaShape.asciidoc, docs/algorithms/ApproachesAndAssumptions.asciidoc, docs/algorithms/FourPassConflation.asciidoc, docs/algorithms/Places.asciidoc, docs/algorithms/ServicesScalability.asciidoc, docs/algorithms/Techniques.asciidoc, docs/algorithms/UnifyingConflation.asciidoc, docs/developer/HootenannyWebArchitecture_Intro.asciidoc
=> Fix broken image links

scripts/database/SetupOsmApiDB.sh
=> Fix Shell Logic

docs/user/CommandLineExamples.asciidoc, hoot-core/src/main/cpp/hoot/core/ops/CalculateStatsOp.cpp, hoot-core/src/main/cpp/hoot/core/schema/TagDistribution.cpp, hoot-core/src/main/cpp/hoot/core/schema/TagDistribution.h, test-files/cmd/slow/TagDistributionCmdTest.sh.stdout
Also reformatted the command line examples
=> Reformat tag-distribution command output

docs/algorithms/Evaluation.asciidoc, docs/algorithms/PoiToPoiConflation.asciidoc, docs/user/Hootenanny-id.asciidoc, docs/user/Introduction.asciidoc, docs/user/OldDocs.asciidoc, docs/user/SchemaFiles.asciidoc
Fixed broken links in user docs.
=> 3192 Fix broken links in user docs

hoot-services/src/main/java/hoot/services/controllers/conflation/ConflateCommand.java, hoot-services/src/main/java/hoot/services/controllers/conflation/UpdateMapTagsCommand.java, test-files/ui/features/review_bookmarks.feature
=> Parse stats out of stdout without suppressing log messages

Vagrantfile
=> Investigate Jenkins test time vs cost

hoot-core-test/src/test/cpp/hoot/core/io/ServiceHootApiDbReaderTest.cpp, hoot-core-test/src/test/cpp/hoot/core/io/ServiceOsmApiDbReaderTest.cpp, hoot-core-test/src/test/cpp/hoot/core/ops/MapCropperTest.cpp, hoot-core/src/main/cpp/hoot/core/io/DataConverter.cpp, hoot-core/src/main/cpp/hoot/core/io/OgrReader.cpp, hoot-core/src/main/cpp/hoot/core/ops/MapCropper.cpp, hoot-core/src/main/cpp/hoot/core/util/GeometryUtils.cpp, hoot-core/src/main/cpp/hoot/core/util/GeometryUtils.h
Consolidates duplicated bounds atring reading code between `GeometryUtils`, `OgrReader`, and `MapCropper`
=> Bounds reading code consolidation

hoot-services/src/main/java/hoot/services/controllers/ingest/ImportResource.java, hoot-services/src/main/java/hoot/services/geo/BoundingBox.java
=> 3195. ImportResource will now accept target folder id

hoot-services/src/main/java/hoot/services/HootProperties.java, hoot-services/src/main/java/hoot/services/controllers/grail/PullApiCommand.java, hoot-services/src/main/java/hoot/services/controllers/grail/PullOverpassCommand.java, hoot-services/src/main/resources/conf/hoot-services.conf.in
also log url for overpass and rails api command requests
fixes #3265
=> make http request timeout configurable

scripts/HootCompletion.sh
While working on #3149 I found that I couldn't find (or remember) some of the command line options and config files and command completion wasn't helping me.  It needed an update.  So I updated it to recognize default -C config files and all -D config options.  Also added some other testing options.
=> Hootenanny Command Line Completion

hoot-services/src/main/java/hoot/services/controllers/export/ExportResource.java, hoot-services/src/main/java/hoot/services/controllers/osm/map/FolderResource.java, hoot-services/src/main/java/hoot/services/controllers/osm/map/MapResource.java, hoot-services/src/main/java/hoot/services/models/osm/Map.java, hoot-services/src/main/java/hoot/services/utils/DbUtils.java, test-files/ui/Makefile, test-files/ui/features/translation_ingest_edit.feature
=> Enforce user map visibility on export

hoot-services/src/main/java/hoot/services/command/ExternalCommand.java, hoot-services/src/main/java/hoot/services/controllers/export/ExportCommand.java
=> handle -C vs -D options correctly

hoot-services/src/main/java/hoot/services/controllers/ingest/ImportCommand.java, hoot-services/src/main/java/hoot/services/controllers/ingest/ImportResource.java, hoot-services/src/main/java/hoot/services/controllers/ingest/ImportResourceUtils.java, hoot-services/src/main/java/hoot/services/controllers/ingest/UploadClassification.java, hoot-services/src/test/java/hoot/services/controllers/ingest/ImportResourceUtilsTest.java
=> Adding GeoPackage import

hoot-services/src/main/java/hoot/services/controllers/osm/map/MapResource.java, hoot-services/src/main/java/hoot/services/models/osm/Map.java
=> New endpoint for Node, way, relation and changeset ids

hoot-core-test/src/test/cpp/hoot/core/ops/CookieCutterOpTest.cpp, hoot-core-test/src/test/cpp/hoot/core/ops/DuplicateWayRemoverTest.cpp, hoot-core-test/src/test/cpp/hoot/core/ops/UnconnectedWaySnapperTest.cpp, hoot-rnd/src/test/cpp/hoot/rnd/conflate/multiary/MultiaryPoiMergeCacheTest.cpp, test-files/ops/UnconnectedWaySnapper/runSnapTestOut.osm, test-files/ops/UnconnectedWaySnapper/runStaticSnapTestOut.osm
Refs #3313 
A few tests fail in sequential mode that needed a different reset type.  This also fixes almost all of the unit test failures when all tests are run sequentially instead of in parallel.
=> Random Unit Test Failures

hoot-services/src/main/java/hoot/services/models/osm/Relation.java, hoot-services/src/test/java/hoot/services/controllers/osm/OSMTestUtils.java, hoot-services/src/test/java/hoot/services/controllers/osm/changeset/ChangesetResourceUploadCreateTest.java
=> Fixes #3316 issue where changeset upload cant find relation

hoot-services/src/main/java/hoot/services/controllers/osm/user/UserResource.java, hoot-services/src/main/java/hoot/services/models/db/Users.java, hoot-services/src/main/java/hoot/services/models/osm/User.java, hoot-services/src/test/java/hoot/services/controllers/osm/user/UserResourceTest.java
=> Add user/details endpoint and migrate path to api/0.6

hoot-services/src/main/java/hoot/services/controllers/grail/DeriveChangesetCommand.java, hoot-services/src/main/java/hoot/services/controllers/grail/GrailParams.java, hoot-services/src/main/java/hoot/services/controllers/grail/GrailResource.java, hoot-services/src/main/java/hoot/services/utils/DbUtils.java
added option to changeset derive to ignore deletes for differential conflate
ref #3345
=> Fixed #3345. fix bug with changeset derive for diff conflate

node-export-server/server.js
=> update hoot translation class name

hoot-services/src/main/java/hoot/services/models/osm/Way.java, hoot-services/src/test/java/hoot/services/controllers/osm/map/MapResourceTest.java
=> removed code that would add nodes from way to the xml response

hoot-services/src/main/java/hoot/services/controllers/osm/map/MapResource.java, hoot-services/src/main/java/hoot/services/controllers/review/RandomReviewableQuery.java, hoot-services/src/main/java/hoot/services/controllers/review/ReviewableItem.java, hoot-services/src/main/java/hoot/services/controllers/review/ReviewableQuery.java, hoot-services/src/main/java/hoot/services/models/osm/Element.java, hoot-services/src/main/java/hoot/services/models/osm/Relation.java, hoot-services/src/main/java/hoot/services/models/osm/Way.java, hoot-services/src/test/java/hoot/services/controllers/osm/element/ElementResourceTest.java
=> Fix bugs with full element resource for relation and way

hoot-core/src/main/cpp/hoot/core/io/ApiDb.h, hoot-services/src/main/java/hoot/services/controllers/export/ExportResource.java, hoot-services/src/main/java/hoot/services/controllers/grail/GrailParams.java, hoot-services/src/main/java/hoot/services/controllers/grail/GrailResource.java, hoot-services/src/main/java/hoot/services/controllers/grail/PushToDbCommand.java, hoot-services/src/main/java/hoot/services/controllers/grail/UpdateDbCommand.java, hoot-services/src/main/java/hoot/services/job/Job.java, hoot-services/src/main/java/hoot/services/job/JobRunnable.java, hoot-services/src/main/java/hoot/services/job/JobStatusManagerImpl.java, hoot-services/src/main/java/hoot/services/jobs/JobsStatusesManagerImpl.java, hoot-services/src/main/java/hoot/services/models/db/JobStatus.java, hoot-services/src/main/java/hoot/services/models/db/QJobStatus.java, hoot-services/src/main/java/hoot/services/utils/DbUtils.java, hoot-services/src/main/resources/db/changelogs/028-AddJobStatusParent.xml
=> refresh grail data after upload and prevent upload of stale data

hoot-services/src/main/java/hoot/services/controllers/grail/GrailResource.java
=> Fixed #3389. turn off refresh rails data for differential push

conf/services/grailOverpassQuery.oql
=> Fixed #3391. fixed overpass query due to seeing duplicate nodes

hoot-services/src/main/java/hoot/services/controllers/grail/GrailResource.java, hoot-services/src/main/java/hoot/services/controllers/grail/PullOverpassCommand.java
=> Fixed #3398 update getPublicOverpassCommand to use GRAIL_OVERPASS_QUERY

conf/services/conflationTypes.json
=> add differential options

hoot-services/src/main/java/hoot/services/controllers/conflation/ConflateCommand.java
=> make sure matcher/merger defined on conflation options when filtering

conf/services/conflationTypes.json
This is my preference.  Lemme know what you think.
=> reorder advanced options for ui display

hoot-services/src/main/java/hoot/services/controllers/export/ExportCommand.java, hoot-services/src/main/java/hoot/services/controllers/export/ExportParams.java, hoot-services/src/main/java/hoot/services/controllers/export/ExportResource.java, hoot-services/src/main/java/hoot/services/utils/DbUtils.java
=> Fixed #3236. Export folder will recursively include subfolders

hoot-core-test/src/test/cpp/hoot/core/io/ServiceHootApiDbTest.cpp, hoot-core/src/main/cpp/hoot/core/conflate/poi-polygon/PoiPolygonMatch.cpp, hoot-core/src/main/cpp/hoot/core/io/HootApiDb.cpp, test-files/cases/unifying/poi-polygon/poi-polygon-2/Expected.osm, test-files/cases/unifying/poi-polygon/poi-polygon-3/Expected.osm, test-files/cases/unifying/poi-polygon/poi-polygon-4/Expected.osm, test-files/cases/unifying/poi-polygon/poi-polygon-auto-merge-10/Expected.osm, test-files/cases/unifying/poi-polygon/poi-polygon-auto-merge-13/Expected.osm, test-files/cases/unifying/poi-polygon/poi-polygon-auto-merge-14/Expected.osm, test-files/cases/unifying/poi-polygon/poi-polygon-auto-merge-3/Expected.osm, test-files/cases/unifying/poi-polygon/poi-polygon-auto-merge-4/Expected.osm, test-files/cases/unifying/poi-polygon/poi-polygon-auto-merge-5/Expected.osm, test-files/cases/unifying/poi-polygon/poi-polygon-auto-merge-6/Expected.osm, test-files/cases/unifying/poi-polygon/poi-polygon-auto-merge-9/Expected.osm, test-files/cases/unifying/poi-polygon/poi-polygon-keep-closest-match-only-10/Expected.osm, test-files/cases/unifying/poi-polygon/poi-polygon-keep-closest-match-only-3/Expected.osm, test-files/cases/unifying/poi-polygon/poi-polygon-keep-closest-match-only-4/Expected.osm, test-files/cases/unifying/poi-polygon/poi-polygon-keep-closest-match-only-5/Expected.osm, test-files/cases/unifying/poi-polygon/poi-polygon-keep-closest-match-only-9/Expected.osm, test-files/cmd/glacial/PoiPolygonConflateCombinedTest/output1.osm, test-files/cmd/glacial/PoiPolygonConflateStandaloneTest/output1.osm, test-files/cmd/glacial/serial/ServiceChangesetReplacement.sh.off
Also fixes a bug where Hoot API DB map URL's with a map name in them were not being processed correctly.
=> 3443 - Make poi/poly review note more descriptive

hoot-core/src/main/cpp/hoot/core/algorithms/changeset/ChangesetCreator.cpp
Simple change, no unit tests were affected.
=> Move chaneset stats from INFO to STATUS

hoot-core/src/main/cpp/hoot/core/io/OsmApiDbSqlChangesetFileWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiDbSqlChangesetFileWriter.h, hoot-core/src/main/cpp/hoot/core/io/OsmXmlChangesetFileWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmXmlChangesetFileWriter.h, test-files/cmd/slow/DeriveChangesetCmdTest/changeset-1.osc, test-files/cmd/slow/DeriveChangesetCmdTest/changeset-10.osc, test-files/cmd/slow/DeriveChangesetCmdTest/changeset-2.osc, test-files/cmd/slow/DeriveChangesetCmdTest/changeset-3.osc, test-files/cmd/slow/DeriveChangesetCmdTest/changeset-4.osc, test-files/cmd/slow/DeriveChangesetCmdTest/changeset-8.osc, test-files/cmd/slow/DeriveChangesetCmdTest/changeset-9.osc, test-files/cmd/slow/DiffConflateCmdTest/output.osc, test-files/cmd/slow/DiffConflateCmdTest/output.tags.osc, test-files/cmd/slow/DiffConflateCmdTest/output_unified.osc, test-files/cmd/slow/DiffConflateTagChangeDifferingGeometriesTest/output.tags.osc, test-files/io/OsmXmlChangesetFileWriterTest/changeset.osc
Refs #3469 
Could be a replacement for #3470 done in the core instead of only in the UI.
=> Make circular error a debug tag for changeset derive

test-files/cmd/slow/ConflateCmdStatsAllDataTypesTest.sh.stdout, test-files/cmd/slow/ConflateCmdStatsToyBuildingsTest.sh.stdout, test-files/cmd/slow/StatsFileTest.sh.stdout, translations/tds40.js, translations/tds61.js, translations/test/facility.js, translations/test/mall_motor_vehicle.js, translations/test/school_grounds.js, translations/translate.js
=> fixed #3425. fixed issue where school grounds wasnt getting tagged properly

node-export-server/package-lock.json, node-export-server/package.json, translations/package-lock.json, translations/package.json
=> npm update on node-export and translations

hoot-rnd/src/main/cpp/hoot/rnd/util/TileUtils.cpp, hoot-services/src/main/java/hoot/services/controllers/export/ExportParams.java, hoot-services/src/main/java/hoot/services/controllers/export/ExportResource.java
=> fixes for running node-density-tiles

hoot-core-test/src/test/cpp/hoot/core/io/OsmApiReaderTest.cpp, hoot-core-test/src/test/cpp/hoot/core/io/OsmApiReaderTestServer.cpp, hoot-core-test/src/test/cpp/hoot/core/io/OsmApiReaderTestServer.h, hoot-core-test/src/test/cpp/hoot/core/io/OsmApiWriterTest.cpp, hoot-core-test/src/test/cpp/hoot/core/io/OsmApiWriterTestServer.cpp, hoot-core-test/src/test/cpp/hoot/core/util/HttpTestServer.cpp, hoot-core-test/src/test/cpp/hoot/core/util/HttpTestServer.h, hoot-core/src/main/cpp/hoot/core/io/OsmApiReader.cpp, hoot-core/src/main/cpp/hoot/core/io/ParallelBoundedApiReader.h, hoot-test/src/main/cpp/hoot/test/ProcessPool.cpp, hoot-test/src/main/cpp/hoot/test/main.cpp
Updated error handling for unit tests.
Refactored HTTP test servers.
Refactored unit test harness.
=> Updated test server and error handling.

hoot-core-test/src/test/cpp/hoot/core/algorithms/BufferedLineSegmentIntersectorTest.cpp, hoot-core-test/src/test/cpp/hoot/core/io/ObjectInputStreamTest.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmPbfWriter.cpp, hoot-js/src/main/cpp/hoot/js/conflate/matching/ScriptMatchCreator.cpp
While running `valgrind` on `HootTest` I came across a list of possible memory leaks.  Here are a few of them.
=> Fix memory leaks

hoot-services/src/main/java/hoot/services/controllers/conflation/ConflateCommand.java
=> use TASK_BBOX input as convert.bounding.box

.circleci/config.yml, Makefile.hoot, VagrantProvisionVars.sh, conf/core/ConfigOptions.asciidoc, docs/install/HootenannyInstall.asciidoc, hoot-core/src/main/cpp/hoot/core/algorithms/string/WeightedWordDistance.cpp, scripts/util/Centos7_only_core.sh, scripts/yum/hoot-repo.sh, test-files/cmd/quick/ConfigOptionsCmdTest/ConfigOptions.asciidoc
Fixes #3182; use updated format for S3 URLs.
=> Update S3 URLs to the new format.

translations/schema2josmpreset.js
=> adding tds70 to build script

translations/TranslationServer.js, translations/test/TranslationServer.js
=> TDSv70 translation server fixes

hoot-services/src/main/java/hoot/services/controllers/grail/GrailResource.java, hoot-services/src/main/java/hoot/services/utils/DbUtils.java
minor code cleanup to better reuse grail param
ref #3412
=> Fixed #3412. Modified grail pull to send folder id 

hoot-services/src/main/java/hoot/services/controllers/grail/PullOverpassCommand.java
=> Fixed #3592. null check added for pull overpass custom query

hoot-services/src/main/java/hoot/services/controllers/ingest/ImportCommand.java
=> 3591 no need to check format type when using translation

hoot-core/src/main/cpp/hoot/core/algorithms/changeset/ChangesetCreator.cpp, hoot-js/src/main/cpp/hoot/js/schema/JavaScriptSchemaTranslator.cpp, hoot-rnd/src/main/cpp/hoot/rnd/algorithms/changeset/ChangesetReplacementCreator.cpp, sonar-project.properties
Refs #2657
Fixed sonar 'bugs' and other misc code smells
=> Sonar bugs

hoot-services/src/main/java/hoot/services/controllers/grail/GrailResource.java
=> Fixed #3601. fix grail pull count query showing 0 features

hoot-core/src/main/cpp/hoot/core/io/OsmXmlReader.cpp
BBox keep connected ways was never changing in setConfiguration()
=> Used passed in config options in setConfiguration

hoot-core-test/src/test/cpp/hoot/core/algorithms/splitter/MultiLineStringSplitterTest.cpp, hoot-core-test/src/test/cpp/hoot/core/ops/ManualMatchValidatorTest.cpp, hoot-core/src/main/cpp/hoot/core/algorithms/FrechetDistance.h, hoot-core/src/main/cpp/hoot/core/algorithms/perty/PertyTestRunner.h, hoot-core/src/main/cpp/hoot/core/conflate/DiffConflator.cpp, hoot-core/src/main/cpp/hoot/core/conflate/network/EdgeMatchSetFinder.cpp, hoot-core/src/main/cpp/hoot/core/elements/OsmUtils.cpp, hoot-core/src/main/cpp/hoot/core/elements/Tags.h, hoot-core/src/main/cpp/hoot/core/index/metric-hybrid/Node.h, hoot-core/src/main/cpp/hoot/core/scoring/MapComparator.cpp, hoot-js/src/main/cpp/hoot/js/util/LogJs.cpp, hoot-rnd/src/main/cpp/hoot/rnd/cmd/CropRandomCmd.cpp, sonar-project.properties, tgs/src/main/cpp/tgs/RandomForest/MultithreadedRandomForest.h, tgs/src/main/cpp/tgs/RandomForest/RandomForest.h
=> Most recent code smells 201911

conf/schema/man_made.json, translations/UFD_to_OSM.js, translations/dnc_rules.js, translations/fcode_common.js, translations/geonames_core.js, translations/geonames_rules.js, translations/ggdm30.js, translations/gifd_d4_core.js, translations/gifd_d4_rules.js, translations/mgcp.js, translations/mgcp_rules.js, translations/tds40_rules.js, translations/tds61_rules.js, translations/tds70_rules.js
refs: #3643
From today's meeting.
=> Fix UFD issues

docs/commands/changeset-derive-replacement.asciidoc, hoot-core/src/main/cpp/hoot/core/conflate/UnifyingConflator.h, hoot-core/src/main/cpp/hoot/core/elements/ElementVisitor.h, hoot-core/src/main/cpp/hoot/core/elements/OsmMap.cpp, hoot-core/src/main/cpp/hoot/core/elements/OsmMap.h, hoot-core/src/main/cpp/hoot/core/ops/CopyMapSubsetOp.cpp, hoot-core/src/main/cpp/hoot/core/ops/CopyMapSubsetOp.h, hoot-core/src/main/cpp/hoot/core/ops/OsmMapOperation.h, hoot-js/src/main/cpp/hoot/js/conflate/matching/ScriptMatchCreator.cpp, hoot-js/src/main/cpp/hoot/js/conflate/merging/ScriptMergerCreator.h, hoot-rnd/src/main/cpp/hoot/rnd/algorithms/changeset/ChangesetReplacementCreator.h
some minor stuff done during #3645, the bulk of which was abandoned
=> Doc updates and cleanup 11/19/20

hoot-services/src/main/java/hoot/services/controllers/job/JobResource.java, hoot-services/src/main/java/hoot/services/controllers/job/JobStatusResponse.java, hoot-services/src/main/java/hoot/services/controllers/jobs/JobHistory.java, hoot-services/src/main/java/hoot/services/controllers/jobs/JobsResource.java, hoot-services/src/main/java/hoot/services/jobs/JobsStatusesManager.java, hoot-services/src/main/java/hoot/services/jobs/JobsStatusesManagerImpl.java, hoot-services/src/test/java/hoot/services/controllers/jobs/JobsResourceTest.java
refs #3639
remove unused /recent endpoint
=> add paging, sorting, filtering to jobs history

hoot-services/src/main/java/hoot/services/controllers/osm/user/UserResource.java
=> Fixed #3658. add sorting and filtering for 'osm/user/all' endpoint

hoot-core/src/main/cpp/hoot/core/cmd/ChangesetApplyCmd.cpp, hoot-core/src/main/cpp/hoot/core/io/HootNetworkRequest.cpp, hoot-core/src/main/cpp/hoot/core/io/HootNetworkRequest.h, hoot-core/src/main/cpp/hoot/core/io/OsmApiWriter.cpp
Refs #3660 
Updated IP address removal and changed `LOG_ERROR` to `LOG_STATUS` for `OsmApiWriter` errors.
=> Changeset upload STATUS messages

node-export-server/.gitignore, node-export-server/server.js, node-export-server/test/server.js, node-export-server/test/test_overpass.json, node-export-server/test/test_overpass.osm
if post is from overpass, see if it looks like a geojson or osm file and add correct file extension accordingly. For all other sources, it will just do a .osm extension
closes #3662
=> update post handler to add correct file extension

docs/developer/HootenannyGrailNotes.asciidoc
=> Fixed #3675. document how changeset is marked as stale

sonar-project.properties
Ignore the cognitive complexity and the MISRA macro rules because they don't matter in this case.
=> More ignore rules for sonar

hoot-services/src/main/java/hoot/services/controllers/grail/GrailResource.java
refs https://github.com/ngageoint/hootenanny-ui/issues/1682
=> handle derive changeset add only case where only single input

translations/translation_assistant.js
Changed the translation assistant so that if the layername does not match and there is only one translation, it will get used.
=> Changed the translation assistant so that it uses the first translation.

translations/ggdm30.js, translations/ggdm30_rules.js, translations/mgcp.js, translations/mgcp_rules.js, translations/tds40.js, translations/tds40_rules.js, translations/tds61.js, translations/tds61_rules.js, translations/tds70.js, translations/tds70_rules.js, translations/translate.js
=> Translation fixes

hoot-services/src/main/java/hoot/services/controllers/grail/UpdateDbCommand.java, hoot-services/src/main/java/hoot/services/controllers/osm/map/DeleteMapResourcesCommand.java, hoot-services/src/main/java/hoot/services/controllers/osm/map/DeleteMapResourcesCommandFactory.java, hoot-services/src/main/java/hoot/services/controllers/osm/map/DeleteOlderMapsCommand.java, hoot-services/src/main/java/hoot/services/controllers/osm/map/DeleteOlderMapsCommandFactory.java, hoot-services/src/main/java/hoot/services/controllers/osm/map/FolderResource.java, hoot-services/src/main/java/hoot/services/controllers/osm/map/MapResource.java, hoot-services/src/main/java/hoot/services/controllers/osm/user/UserResource.java, hoot-services/src/test/java/hoot/services/controllers/osm/changeset/ChangesetDbWriterTest.java, hoot-services/src/test/java/hoot/services/job/JobStatusManagerImplTest.java
I don't know how this happened but these java files didn't get their copyrights updated from here https://github.com/ngageoint/hootenanny/pull/3682
=> Somehow copyright issues from services got into the repo.

scripts/cover/coverGcov.sh
Coverage parsing was failing.  Removed files not in the `$HOOT_HOME` directory from the coverage list and updated the `sed` commands to be more specific.
=> Updated coverage scripts to fix failure in Jenkins pipeline

LocalConfig.pri.orig, VagrantBuild.sh, scripts/jenkins/Jenkinsfile
Added debug build flag to Jenkins to get more info on the intermittent crash.  Once fixed this can be turned off in the `Jenkinsfile`.
=> Setup Jenkins to run a debug build.

hoot-services/src/main/java/hoot/services/utils/DbUtils.java, hoot-services/src/test/java/hoot/services/utils/DbUtilsTest.java, hoot-services/src/test/java/hoot/services/utils/MapUtils.java
=> fix bug with delete stale maps

hoot-services/src/main/java/hoot/services/controllers/osm/map/FolderResource.java, hoot-services/src/main/java/hoot/services/controllers/osm/map/MapResource.java, hoot-services/src/main/java/hoot/services/controllers/osm/user/UserResource.java, hoot-services/src/main/java/hoot/services/models/osm/Map.java, hoot-services/src/main/java/hoot/services/utils/DbUtils.java, hoot-services/src/test/java/hoot/services/controllers/job/JobResourceTest.java, hoot-services/src/test/java/hoot/services/controllers/osm/map/MapResourceTest.java, hoot-services/src/test/java/hoot/services/utils/MapUtils.java
=> Allow admins to view and delete others private data

hoot-services/src/main/java/hoot/services/controllers/job/JobResource.java, hoot-services/src/main/java/hoot/services/controllers/osm/user/UserResource.java, hoot-services/src/main/java/hoot/services/job/JobStatusManagerImpl.java, hoot-services/src/main/java/hoot/services/utils/DbUtils.java
=> Allow admins to see log and cancel all users running jobs

translations/UFD_to_OSM.js, translations/translate.js
refs: #3707
I forgot to push this earlier this week.
=> place_of_worship fix

hoot-core-test/src/test/cpp/hoot/core/io/OsmApiChangesetTest.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangeset.cpp
Updating closed changeset recognition code and added unit test code.
=> Changeset Closed error

scripts/jenkins/Jenkinsfile
There don't appear to be any glacial services tests anymore, but if there ever are again this ensures they get run on Jenkins.
=> update jenkinsfile to run services-test-all

hoot-services/src/main/java/hoot/services/job/JobRunnable.java, hoot-services/src/main/java/hoot/services/utils/DbUtils.java
=> fix bug with setting conflicted upload changeset job status

hoot-services/src/main/java/hoot/services/controllers/osm/map/FolderResource.java, hoot-services/src/main/java/hoot/services/utils/DbUtils.java
=> Fixed #3747. on folder move, moved folder should inherit visibility

conf/services/conflationTypes.json, scripts/services/CreateConflationTypeGroups.py
=> resolving template string adv opt default values

conf/core/ConfigOptions.asciidoc, conf/services/conflationTypes.json, hoot-core/src/main/cpp/hoot/core/algorithms/rubber-sheet/RubberSheet.cpp, hoot-core/src/main/cpp/hoot/core/algorithms/rubber-sheet/RubberSheet.h, hoot-core/src/main/cpp/hoot/core/cmd/ConflateCmd.cpp, hoot-core/src/main/cpp/hoot/core/cmd/CountCmd.cpp, hoot-core/src/main/cpp/hoot/core/io/DataConverter.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmMapReaderFactory.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmMapWriterFactory.cpp, hoot-core/src/main/cpp/hoot/core/ops/NamedOp.cpp, hoot-core/src/main/cpp/hoot/core/util/Settings.cpp, hoot-core/src/main/cpp/hoot/core/visitors/RemoveDuplicateAreaVisitor.cpp, test-files/cmd/slow/CountCmdTest.sh, test-files/cmd/slow/CountCmdTest.sh.stdout
Saw a ~5 million feature map spend 14+ hours in rubber sheeting with no signs of finishing (rubber sheeting runs by default with Network roads). I don't see the rs alg being updated any time soon. The lengthy runtime added by rubber sheeting far outweights the small benefits it provides.
=> 3764 - Add an max upper linear feature limit for rubbersheeting

translations/fcode_common.js, translations/ggdm30_rules.js, translations/mgcp.js, translations/mgcp_rules.js, translations/tds40_rules.js, translations/tds61_rules.js, translations/tds70_rules.js
=> Thicket fixes

hoot-services/src/main/java/hoot/services/controllers/grail/GrailResource.java, hoot-services/src/main/java/hoot/services/controllers/grail/PullOverpassCommand.java
Also have to import cert into java keystore on the deployed server:
`sudo keytool -import -alias PublicOverpassMirror -keystore /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.242.b08-0.el7_7.x86_64/jre/lib/security/cacerts -file PublicOverpassMirror.der`
=> This lets us use the public overpass mirror with self signed cert

Vagrantfile
=> Initial port forwarding fix

VagrantBuild.sh, hoot-core-test/src/test/cpp/hoot/core/io/OsmApiReaderTest.cpp, hoot-core-test/src/test/cpp/hoot/core/io/OsmApiReaderTestServer.cpp, hoot-core-test/src/test/cpp/hoot/core/io/OsmApiWriterTest.cpp, hoot-core-test/src/test/cpp/hoot/core/io/OsmApiWriterTestServer.cpp, hoot-core-test/src/test/cpp/hoot/core/util/HttpTestServer.cpp, hoot-core/src/main/cpp/hoot/core/auth/HootServicesLoginManager.cpp, hoot-core/src/main/cpp/hoot/core/io/HootNetworkRequest.h, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangeset.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiReader.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiWriter.h, hoot-core/src/main/cpp/hoot/core/io/ParallelBoundedApiReader.cpp, hoot-core/src/main/cpp/hoot/core/language/HootServicesLanguageDetectorClient.cpp, hoot-core/src/main/cpp/hoot/core/language/HootServicesLanguageInfoClient.cpp, hoot-core/src/main/cpp/hoot/core/language/HootServicesTranslatorClient.cpp, hoot-core/src/main/cpp/hoot/core/util/HootNetworkUtils.h, hoot-core/src/main/cpp/hoot/core/util/OsmApiUtils.h
Make the changeset apply command more robust so that it doesn't hang at the end in some instances.
Closes #3793
=> "Core dump" of Changeset Apply commands

hoot-core-test/src/test/cpp/hoot/core/io/OsmApiWriterTest.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangeset.cpp, test-files/io/OsmChangesetElementTest/ChangesetErrorFixErrors.osc, test-files/io/OsmChangesetElementTest/ChangesetMergeExpected.osc, test-files/io/OsmChangesetElementTest/DeleteSplit1.osc, test-files/io/OsmChangesetElementTest/DeleteSplit3.osc, test-files/io/OsmChangesetElementTest/DeleteSplit4.osc, test-files/io/OsmChangesetElementTest/RetryConflictExpected-error.osc
Closes #3837 
Undoes https://github.com/ngageoint/hootenanny/pull/3657
=> Removed if-unused from changeset-apply

scripts/jenkins/Jenkinsfile
=> Disable sonar scans on PRs temporarily

hoot-services/src/main/java/hoot/services/HootProperties.java, hoot-services/src/main/java/hoot/services/controllers/grail/ApplyChangesetCommand.java, hoot-services/src/main/java/hoot/services/controllers/grail/PushToDbCommand.java, hoot-services/src/main/resources/conf/hoot-services.conf.in
=> changeset apply options now config properties

hoot-js/src/main/cpp/hoot/js/schema/JavaScriptSchemaTranslator.cpp, test-files/cmd/slow/MgcpTranslationTest.sh, translations/fcode_common.js, translations/mgcp.js, translations/mgcpDump.js, translations/mgcp_rules.js
* Re-arrange the file to keep TRD3 and TRD4 separate
* Remove stuff that is not TRD3 or TRD4. I have no idea how these got in there from TDS
* Add the script to dump the translation as a csv
=> MGCP Tweaks and fixes

conf/core/GrailIngest.conf, hoot-services/src/main/java/hoot/services/controllers/grail/PushToDbCommand.java
=> move hardcoded opts to external conf file, add opt for preserve version

hoot-core/src/main/cpp/hoot/core/io/HootNetworkRequest.cpp, hoot-core/src/main/cpp/hoot/core/io/HootNetworkRequest.h
Added timeout to `HootNetworkRequest` so HTTP requests don't potentially hang forever.
=> Network Request timeout

hoot-services/src/main/java/hoot/services/controllers/export/ExportResource.java, hoot-services/src/main/java/hoot/services/utils/DbUtils.java
to include original, diff-error, diff-remaining and debug
osc upload traffic
refs https://github.com/ngageoint/hootenanny-ui/pull/1745
=> add ability to download zip of osc files from upload job

conf/core/GrailIngest.conf, hoot-services/src/main/java/hoot/services/controllers/grail/GrailResource.java, hoot-services/src/main/java/hoot/services/controllers/grail/PullApiCommand.java, hoot-services/src/main/java/hoot/services/controllers/grail/PullConnectedWaysCommand.java, hoot-services/src/main/java/hoot/services/controllers/grail/PullOverpassCommand.java, hoot-services/src/main/java/hoot/services/utils/MultipartSerializer.java
grail pull may request from internal servers with self-signed certs
=> Use https connection with no hostname verifier for self signed certs

hoot-js/src/main/cpp/hoot/js/schema/JavaScriptSchemaTranslator.cpp, translations/TranslationServer.js, translations/test/TranslationServer.js
refs: #3879
Added the ability to read a json file and add translations from translations-local to the TranslationServer
=> Add translations from translations-local to the Translation Server

hoot-services/src/main/java/hoot/services/controllers/grail/GrailResource.java, hoot-services/src/main/java/hoot/services/controllers/grail/PullApiCommand.java, hoot-services/src/main/java/hoot/services/controllers/job/JobResource.java, hoot-services/src/main/java/hoot/services/job/JobRunnable.java, hoot-services/src/main/java/hoot/services/job/JobStatusManagerImpl.java
=> read error response body and propagate error to UI

hoot-services/src/main/java/hoot/services/controllers/grail/GrailResource.java, hoot-services/src/main/java/hoot/services/controllers/grail/MergeOsmFilesCommand.java
=> mark OOB connected ways with 'hoot:change:exclude:delete' tag

docs/commands/conflate.asciidoc, hoot-core/src/main/cpp/hoot/core/algorithms/rubber-sheet/RubberSheet.cpp, hoot-core/src/main/cpp/hoot/core/criterion/InBoundsCriterion.cpp, hoot-core/src/main/cpp/hoot/core/ops/SuperfluousNodeRemover.h, test-files/cmd/glacial/serial/ServiceGrailDiffTest.sh, test-files/cmd/glacial/serial/ServiceGrailDiffTest.sh.off
Couldn't reproduce #3923 but these changes are some cleanup and logging mods that were helpful during debugging
=> Cleanup as a result of #3923

test-files/cases/network/conflicts/highway-3885/Config.conf, test-files/cases/network/conflicts/highway-3885/Expected.osm, test-files/cases/network/conflicts/highway-3885/Input1.osm, test-files/cases/network/conflicts/highway-3885/Input2.osm, test-files/cases/network/conflicts/highway-3885/README.txt, test-files/cases/unifying/highway-3829/Config.conf
The road classification after merge problem identified after the #3842 merge has since been corrected inadvertantly by other changes. This adds a test for it.
=> 3885 - Add test for changes requested after #3842

hoot-services/src/main/java/hoot/services/controllers/grail/GrailResource.java, hoot-services/src/main/java/hoot/services/controllers/grail/MergeOsmFilesCommand.java
=> Fixed #3925 . fixed error in MergeOsmFilesCommand when no merge files exist

translations/mgcp.js, translations/mgcp_rules.js
refs: #3934
Removed non-valid AP020 from TRD4 FCODE list
=> Fixed AP020 issue

hoot-services/src/main/java/hoot/services/controllers/osm/map/MapResource.java
=> Fixed#3863. nodecount endpoint fixed for hoot2

hoot-services/src/main/java/hoot/services/controllers/conflation/ConflateCommand.java, hoot-services/src/test/java/hoot/services/controllers/conflation/ConflateCommandTest.java
=> fixed #3958. sort matcher and merger for conflate before sending to core

hoot-services/src/main/java/hoot/services/controllers/grail/DeriveChangesetReplacementCommand.java
simple mistake on my part
fixes #4009
=> derive changeset replacement adv_options param should be a list

hoot-core-test/src/test/cpp/hoot/core/io/OsmApiReaderTest.cpp, hoot-core-test/src/test/cpp/hoot/core/io/OsmApiWriterTest.cpp, scripts/jenkins/Jenkinsfile
Turn off Sonar for PRs and move OsmApiReader/Writer tests to slow tests.
=> Fix broken builds

conf/core/NodeExport.conf
=> ignore duplicate ids in node-export config

translations/RenderDb.js
fixes #4047
also consolidates duplicate tag mappings
=> add image metadata fields to renderdb export

hoot-core/src/main/cpp/hoot/core/io/OsmApiWriter.cpp
Instead of trying to push the "remaining" changeset to the API, fail those elements (because they'll all most likely fail anyway) and stop all processing threads.
=> Take option 2 and fail the 'remaining' at the 99% error

hoot-core/src/main/cpp/hoot/core/schema/MetadataTags.h, hoot-core/src/main/cpp/hoot/core/visitors/AddUserIdVisitor.cpp, hoot-core/src/main/cpp/hoot/core/visitors/AddUserIdVisitor.h
Added a small element visitor.
=> Add user and id as tags 

hoot-core/src/main/cpp/hoot/core/ops/AddHilbertReviewSortOrderOp.cpp
Cut and replace leaves in all refs to missing relation members by design. This means that some of the ops and visitors need element null checks added to them.
=> 4092 - Prevent AddHilbertReviewSortOrderOp from accessing a missing element

conf/schema/barrier.json, conf/schema/highway.json, conf/schema/natural.json, conf/schema/sport.json, conf/schema/transport.json, hoot-core-test/src/test/cpp/hoot/core/schema/ImplicitTagRulesDatabaseDeriverTest.cpp, hoot-core/src/main/cpp/hoot/core/algorithms/changeset/ChangesetReplacementCreator.cpp, hoot-core/src/main/cpp/hoot/core/conflate/review/ReviewMarker.cpp, rules/Poi.js, translations/test/TranslationServer.js
Added items to schema JSON conf files that were referenced in `Poi.js` but missing in the schema.
=> 4091 - Add missing POI schema references

hoot-josm/src/main/cpp/hoot/core/jni/JavaEnvironment.cpp, hoot-josm/src/main/cpp/hoot/core/jni/JavaEnvironment.h, hoot-josm/src/main/cpp/hoot/core/josm/ops/JosmMapValidatorAbstract.cpp
Use Meyers Singleton for JavaEnvironment class
=> Memory leak in JavaEnvironment class

hoot-core/src/main/cpp/hoot/core/io/OsmApiChangeset.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangeset.h, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangesetElement.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangesetElement.h
Replaces https://github.com/ngageoint/hootenanny/pull/3979
`const` Qube findings PR without the changes to the qube configuration.
=> Replace PR 3979

hoot-core/src/main/cpp/hoot/core/io/OsmApiChangeset.cpp, hoot-core/src/main/cpp/hoot/core/util/LogGeneric.cpp
Refs #4113 
Fixed logging issue and upload crash when element pointer is NULL on error.
Closes #4113
=> Grail - Cut & Replace: Upload Changeset Error

hoot-services/src/main/java/hoot/services/controllers/grail/GrailResource.java
=> fixed #4133. fixed upload changeset error. input 1 and 2 tags file name

scripts/valgrind/Jenkinsfile, scripts/valgrind/unit_tests.sh, test-files/valgrind_error_count_expected.log
Artifact archiving wasn't working.  Had to SCP the files from the VM to the Jenkins machine so that they were visible to the archiving process.  Updated expected results with new tests and updated numbers from the most recent build.
=> Updated valgrind jenkins test

hoot-services/src/main/java/hoot/services/controllers/grail/GrailResource.java
=> Fixed #4140. fixed issue where reference.osm file was not being merged

hoot-services/src/main/java/hoot/services/controllers/grail/GrailResource.java
=> Fixed #4166. cut & replace advanced options fix

scripts/valgrind/Jenkinsfile
update syntax on Jenkinsfile for hootenanny_valgrind to pass in jenkins on post stages
=> valgrind jenkinsfile syntax test

hoot-services/src/main/java/hoot/services/controllers/grail/GrailResource.java, hoot-services/src/main/java/hoot/services/controllers/grail/PullOverpassCommand.java, hoot-services/src/main/java/hoot/services/controllers/grail/WaitOsmUpdate.java, hoot-services/src/main/java/hoot/services/controllers/grail/WaitOverpassUpdate.java, hoot-services/src/main/java/hoot/services/utils/DbUtils.java
=> Fixed #4194. added command to wait for osm sync

conf/core/ConfigOptions.asciidoc, hoot-core/src/main/cpp/hoot/core/io/ApiDb.cpp, hoot-core/src/main/cpp/hoot/core/io/ApiDb.h, hoot-core/src/main/cpp/hoot/core/io/ApiDbReader.cpp, hoot-core/src/main/cpp/hoot/core/io/TableType.h, hoot-services/src/main/resources/db/changelogs/031-AddWayNodeIndex.xml
Closes #4192 
Adds a node ID index to `current_way_nodes`.
=> Improve performance for hootapidb bbox queries involving large numbers of nodes

hoot-core/src/main/cpp/hoot/core/algorithms/alpha-shape/AlphaShape.cpp, hoot-core/src/main/cpp/hoot/core/algorithms/alpha-shape/AlphaShape.h, hoot-core/src/main/cpp/hoot/core/algorithms/alpha-shape/AlphaShapeGenerator.cpp
Search for minimal alpha value that meets criteria using a binary search
Closes #4085
=> Speed up auto alpha selection

hoot-core-test/src/test/cpp/hoot/core/algorithms/alpha-shape/AlphaShapeGeneratorTest.cpp, hoot-core/src/main/cpp/hoot/core/algorithms/alpha-shape/AlphaShape.cpp, hoot-core/src/main/cpp/hoot/core/algorithms/alpha-shape/AlphaShape.h, hoot-core/src/main/cpp/hoot/core/algorithms/alpha-shape/AlphaShapeGenerator.cpp, hoot-core/src/main/cpp/hoot/core/util/GeometryUtils.cpp, hoot-core/src/main/cpp/hoot/core/util/GeometryUtils.h, hoot-core/src/main/cpp/hoot/core/util/PolygonCompare.cpp, hoot-core/src/main/cpp/hoot/core/util/PolygonCompare.h
Optimize the straggler geometry creation and merge with the larger alpha geometry once later.  This does change one test a little but is fine.
=> Optimize AlphaShape generation "stragglers" code

hoot-services/src/main/java/hoot/services/controllers/grail/GrailResource.java, hoot-services/src/main/java/hoot/services/controllers/grail/WaitOverpassUpdate.java, hoot-services/src/main/java/hoot/services/job/JobRunnable.java, hoot-services/src/main/java/hoot/services/job/JobType.java, hoot-services/src/main/java/hoot/services/utils/DbUtils.java, hoot-services/src/test/java/hoot/services/controllers/jobs/JobsResourceTest.java
=> Fixed #4217. changeset derive push wait code added

VagrantProvisionCentOS7Rpm.sh
The RPM install added the deps repo but not the release repo which made it fail.
=> Fixed the Hoot Release repo problem

VagrantProvisionCentOS7Rpm.sh, Vagrantfile, docker/hoot_commandline/Dockerfile, docker/hoot_commandline/build_image.sh, docker/hoot_commandline/test_image.sh
=> Add an option to use the nightly RPMs for an install

Vagrantfile, scripts/jenkins/Jenkinsfile, scripts/valgrind/Jenkinsfile
add tags to ec2 instances started from jenkins jobs
task in association to jira ticket: https://radiantsolutions.atlassian.net/browse/VGI-1659
covers hootenanny and valgrind_hootenanny jenkins jobs
=> add nome-dev vpc tagging

hoot-services/src/main/java/hoot/services/command/ExternalCommandRunnerImpl.java
=> Fixed #4274. keep timestamp for command status panel

hoot-services/src/main/java/hoot/services/controllers/grail/GrailResource.java, hoot-services/src/main/java/hoot/services/controllers/grail/WaitOverpassUpdate.java, hoot-services/src/main/java/hoot/services/utils/DbUtils.java
=> Fixed #4287. added error checking related to overpass sync wait requests

hoot-services/src/main/java/hoot/services/controllers/grail/PullApiCommand.java
=> Fixed #4290. send error for reference pull fail due to large bbox area

hoot-services/src/main/java/hoot/services/controllers/grail/PullApiCommand.java
=> remove bbox area check for private overpass pull

hoot-services/src/main/java/hoot/services/controllers/conflation/ConflateCommand.java
=> Fixed #4319. fixed issue where network matcher was set properly

hoot-services/src/main/java/hoot/services/controllers/auth/OAuth1Resource.java
=> use explicit Accept header to ensure xml response

hoot-services/src/main/java/hoot/services/HootProperties.java, hoot-services/src/main/java/hoot/services/controllers/grail/GrailResource.java, hoot-services/src/main/resources/conf/hoot-services.conf.in
=> Fixed #4323. remove max feature count

docs/user/Hootenanny-id.asciidoc
=> Documentation edits

conf/schema/landuse.json
This keeps the features as lines and pushes them to the o2s layer
=> Added a schema entry with all geometry to landuse.js

hoot-services/src/main/java/hoot/services/controllers/grail/GrailResource.java, hoot-services/src/main/java/hoot/services/controllers/grail/WaitOverpassUpdate.java, hoot-services/src/main/java/hoot/services/utils/DbUtils.java
=> Fixed #4343. overpass sync will use feature id instead of changeset

conf/core/ConfigOptions.asciidoc, conf/schema/waterway.json, rules/Area.js, rules/CollectionRelation.js, rules/Line.js, rules/Point.js, rules/PointPolygon.js, rules/Polygon.js, rules/River.js
Changed type matching for waterways to match that done in other generic scripts based off of type score.
=> Improve type matching for waterways

hoot-core-test/src/test/cpp/hoot/core/io/OsmApiMatchFailureTest.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangeset.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangeset.h, hoot-core/src/main/cpp/hoot/core/io/OsmApiMatchFailure.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiWriter.cpp
Some changesets appeared to hang and others caused excessive repeated errors that these changes fix.
=> Updates to failure handling for changeset-apply

conf/core/ApplyChangeset.conf, conf/core/ConfigOptions.asciidoc, hoot-core/src/main/cpp/hoot/core/io/HootNetworkRequest.cpp, hoot-core/src/main/cpp/hoot/core/io/HootNetworkRequest.h, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangeset.h, hoot-core/src/main/cpp/hoot/core/io/OsmApiWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiWriter.h, hoot-core/src/main/cpp/hoot/core/io/ParallelBoundedApiReader.cpp, hoot-core/src/main/cpp/hoot/core/io/ParallelBoundedApiReader.h, hoot-rnd/src/main/cpp/hoot/rnd/auth/HootServicesLoginManager.cpp, hoot-rnd/src/main/cpp/hoot/rnd/auth/HootServicesLoginManager.h, hoot-rnd/src/main/cpp/hoot/rnd/language/HootServicesLanguageDetectorClient.cpp, hoot-rnd/src/main/cpp/hoot/rnd/language/HootServicesLanguageDetectorClient.h, hoot-rnd/src/main/cpp/hoot/rnd/language/HootServicesLanguageInfoClient.cpp, hoot-rnd/src/main/cpp/hoot/rnd/language/HootServicesLanguageInfoClient.h, hoot-rnd/src/main/cpp/hoot/rnd/language/HootServicesTranslatorClient.cpp, hoot-rnd/src/main/cpp/hoot/rnd/language/HootServicesTranslatorClient.h, hoot-services/src/main/java/hoot/services/controllers/grail/ApplyChangesetCommand.java
Added configurable timeout to `HootNetworkRequest` class and all users of that class.
Created configuration file for `changeset-apply` commands.
Updated `--stats` for changeset apply also.
=> Task 382 Cell 44 causes a timeout error

test-files/cmd/slow/MgcpTranslationTest.sh, test-files/cmd/slow/o2sTranslationTest.sh, translations/mgcp.js, translations/mgcp_rules.js, translations/tds40.js, translations/tds61.js, translations/tds70.js, translations/translate.js
refs: #4382
* Moved "untangleAttributes" to the common translate.js file
* Checks for lowercase attributes and pushes them to uppercase if required.
=> Added checking for lowercase attributes

hoot-services/src/main/java/hoot/services/controllers/grail/GrailResource.java, hoot-services/src/main/java/hoot/services/utils/DbUtils.java
=> Fixed #4392. use project id to search for timeout tasks

hoot-core-test/src/test/cpp/hoot/core/io/OsmApiReaderTestServer.cpp, hoot-core-test/src/test/cpp/hoot/core/io/OsmApiWriterTest.cpp, hoot-core-test/src/test/cpp/hoot/core/io/OsmApiWriterTestServer.cpp, hoot-core-test/src/test/cpp/hoot/core/io/OsmApiWriterTestServer.h, hoot-core-test/src/test/cpp/hoot/core/util/HttpTestServer.cpp, hoot-core-test/src/test/cpp/hoot/core/util/HttpTestServer.h, hoot-core/src/main/cpp/hoot/core/io/HootNetworkRequest.cpp, hoot-core/src/main/cpp/hoot/core/io/HootNetworkRequest.h
Updated HTTP handling for better reads and using timeouts better.
=> Better error messages for timed-out network requests

test-files/cmd/glacial/RndServiceMultiaryPoiIngestCmdTest.sh, test-files/cmd/glacial/ServiceDbEmptyTagsTest.sh, test-files/cmd/glacial/ServiceExportOsm.sh, test-files/cmd/glacial/serial/ServiceChangesetReplacement.sh.off, test-files/cmd/glacial/serial/ServiceStreamingApiDbTest.sh, test-files/cmd/quick/ServiceDbListCmdTest.sh, test-files/cmd/slow/ServiceHootApiDbConflateTest.sh, test-files/cmd/slow/ServiceHootApiDbReaderCmdTest.sh, test-files/cmd/slow/serial/ServiceDiffRoadSnapTest.sh.off
Added the DB name to psql cleanup commands in some tests
=> Added DB_NAME to test cleanup

translations/UFD_to_OSM.js
refs: #4408
Added the transportation type to tunnels
=> Fixed UFD tunnels

translations/TranslationServer.MD, translations/TranslationServer.js
=> update markdown to document current fuzzy search approach in Translation Server

translations/tds70.js, translations/tds70_rules.js
refs: #4423
Fixes for rendering - Stopped stuff going to the OTH field
=> Road fixes

node-export-server/package.json, node-export-server/server.js, node-export-server/test/server.js
=> add poly and crop query params to node-export-service

translations/ggdm30.js, translations/mgcp.js, translations/tds40.js, translations/tds61.js, translations/tds70.js
=> Tree row fixes

hoot-services/src/main/java/hoot/services/controllers/grail/GrailResource.java, hoot-services/src/main/java/hoot/services/controllers/grail/PullOverpassCommand.java
=> Fixed #4442. fixed issue where custom query for overpass wouldn't work

conf/services/grailConnectedWaysQuery.oql, hoot-services/src/main/java/hoot/services/controllers/grail/PullApiCommand.java, hoot-services/src/test/java/hoot/services/controllers/grail/PullApiCommandTest.java
=> propagate filter to connected ways query

scripts/core/osm2ogrscript, test-files/cmd/glacial/ServiceExportOsm.sh, translations/tds61.js
Fix the javascript regression failure.
=> Regression test failures

hoot-core-test/src/test/cpp/hoot/core/TestUtils.h, hoot-core-test/src/test/cpp/hoot/core/schema/OsmSchemaTest.cpp, hoot-core/src/main/cpp/hoot/core/Hoot.cpp, hoot-core/src/main/cpp/hoot/core/algorithms/WayAverager.cpp, hoot-core/src/main/cpp/hoot/core/algorithms/changeset/ChangesetTaskGridReplacer.cpp, hoot-core/src/main/cpp/hoot/core/algorithms/extractors/AttributeScoreExtractor.cpp, hoot-core/src/main/cpp/hoot/core/algorithms/extractors/EdgeDistanceExtractor.cpp, hoot-core/src/main/cpp/hoot/core/algorithms/extractors/poi-polygon/PoiPolygonTypeScoreExtractor.cpp, hoot-core/src/main/cpp/hoot/core/conflate/matching/MatchGraph.cpp, hoot-core/src/main/cpp/hoot/core/conflate/polygon/BuildingMerger.cpp, hoot-core/src/main/cpp/hoot/core/conflate/tile/NodeDensityTileBoundsCalculator.cpp, hoot-core/src/main/cpp/hoot/core/schema/PythonSchemaTranslator.cpp, hoot-core/src/main/cpp/hoot/core/schema/TagInfo.cpp, hoot-core/src/main/cpp/hoot/core/scoring/BaseComparator.cpp, hoot-core/src/main/cpp/hoot/core/scoring/DirectedGraph.cpp, hoot-js/src/main/cpp/hoot/js/util/RequireJs.cpp, hoot-rnd/src/main/cpp/hoot/rnd/cmd/MultiaryScorePoiMatchesCmd.cpp, hoot-test/src/main/cpp/hoot/test/ScriptTestSuite.cpp, tgs/src/main/cpp/tgs/RStarTree/HilbertRTree.cpp, tgs/src/main/cpp/tgs/RStarTree/RStarTreePrinter.cpp
Refs #2657 
Fixing quite a few of the security findings and bugs.  Does not cover code smells.
=> Fix qube major bugs

hoot-core/src/main/cpp/hoot/core/algorithms/rubber-sheet/RubberSheet.cpp, hoot-core/src/main/cpp/hoot/core/algorithms/rubber-sheet/RubberSheet.h, hoot-core/src/main/cpp/hoot/core/elements/OsmMap.cpp, hoot-core/src/main/cpp/hoot/core/elements/OsmMap.h, hoot-core/src/main/cpp/hoot/core/ops/CopyMapSubsetOp.cpp, hoot-core/src/main/cpp/hoot/core/ops/SearchRadiusCalculator.cpp, test-files/cmd/glacial/PowerLineConflateTest/output.osm
Added cached RubberSheet operation to the map for use in calculating search radius.
Closes #4184
=> Cache rubbersheeting result from conflate pre op to pass to search radius calc

scripts/schema/ConvertTDSv61Schema.py, scripts/schema/ConvertTDSv70Schema.py, scripts/schema/ConvertTDSv70Schema_XML.py, translations/tds70.js, translations/tds70_rules.js
=> Renamed the AEI attribute

translations/mgcp.js, translations/mgcp_rules.js, translations/test/line-to-area-cases.js, translations/translate.js
Added code to only grab translation rules for valid FCODES which stopped the wrong F_CODE being used
=> Fixed: MGCP water wells

hoot-core/hoot-core.pro, hoot-core/src/main/cpp/hoot/core/algorithms/extractors/EdgeDistanceExtractor.cpp, hoot-core/src/main/cpp/hoot/core/algorithms/extractors/EdgeDistanceExtractor.h, scripts/jenkins/Jenkinsfile, scripts/sonar/sonar-install.sh, scripts/sonar/sonar-prep-makefile.sh, scripts/sonar/sonar-scan.sh
Run sonar scan in super-debug mode '-X'
DO NOT MERGE!
=> Debug sonar failure

hoot-services/src/main/java/hoot/services/utils/DbUtils.java
=> Fixed #4498. fixed issue with parsing advanced options json

hoot-services/src/main/java/hoot/services/controllers/conflation/AdvancedConflationOptionsResource.java
=> Fixed #4506. capital in select type dropdown. lower case for adv opts

translations/TranslationServer.js
=> accept a geom param for translateFrom FCODE to OSM tags if provided

hoot-core-test/src/test/cpp/hoot/core/algorithms/WayJoinerTest.cpp, hoot-core/src/main/cpp/hoot/core/algorithms/NonIntersectionWayJoiner.cpp, hoot-core/src/main/cpp/hoot/core/algorithms/NonIntersectionWayJoiner.h, hoot-core/src/main/cpp/hoot/core/algorithms/WayJoiner.h, test-files/algorithms/wayjoiner/NonIntersectionWayJoinerExpected.osm, test-files/algorithms/wayjoiner/NonIntersectionWayJoinerInput.osm
Adding non-intersection way joiner and test, can be used to clean-up some datasets
Closes #4548
=> WayJoiner to join ways before conflation

conf/core/ConfigOptions.asciidoc, hoot-core-test/src/test/cpp/hoot/core/visitors/DataSummaryTagVisitorTest.cpp, hoot-core/src/main/cpp/hoot/core/schema/MetadataTags.h, hoot-core/src/main/cpp/hoot/core/visitors/DataSummaryTagVisitor.cpp, hoot-core/src/main/cpp/hoot/core/visitors/DataSummaryTagVisitor.h, test-files/visitors/DataSummaryTagVisitorTest/DataSummaryTagVisitorTestExpected.osm, test-files/visitors/DataSummaryTagVisitorTest/DataSummaryTagVisitorTestInput.osm
Create DataSummaryTagVisitor to summarize data after conflation
Closes #4546
=> Data Summary Post Process Operation

conf/core/ConfigOptions.asciidoc, hoot-core-test/src/test/cpp/hoot/core/ops/OffsetIntersectionMergerOpTest.cpp, hoot-core/src/main/cpp/hoot/core/ops/OffsetIntersectionMergerOp.cpp, hoot-core/src/main/cpp/hoot/core/ops/OffsetIntersectionMergerOp.h, test-files/ops/OffsetIntersectionMergerOpTest/OffsetIntersectionMergerOpTestExpected.osm, test-files/ops/OffsetIntersectionMergerOpTest/OffsetIntersectionMergerOpTestInput.osm
Created OffsetIntersectionMergerOp to merge small intersections that don't exist
Closes #4547
=> Intersection merging pre-convert operation

translations/ENCv311_to_OGR.js
=> ENC Typo fix

hoot-core/src/main/cpp/hoot/core/algorithms/splitter/DualHighwaySplitter.cpp, hoot-core/src/main/cpp/hoot/core/algorithms/subline-matching/MaximalSubline.cpp, hoot-core/src/main/cpp/hoot/core/conflate/network/ConflictsNetworkMatcher.cpp, hoot-core/src/main/cpp/hoot/core/io/DataConverter.cpp, hoot-core/src/main/cpp/hoot/core/io/HootApiDb.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmXmlChangesetFileWriter.cpp, hoot-core/src/main/cpp/hoot/core/ops/MapCropper.cpp, hoot-core/src/main/cpp/hoot/core/util/Settings.cpp, hoot-rnd/src/main/cpp/hoot/rnd/language/HootServicesLanguageDetectorClient.cpp
Removed unused assignment operations from code base
Refs #4570
=> SONAR: Unused assignments should be removed

hoot-core/src/main/cpp/hoot/core/conflate/merging/LinearMergerAbstract.cpp, hoot-core/src/main/cpp/hoot/core/conflate/merging/LinearMergerAbstract.h, hoot-core/src/main/cpp/hoot/core/conflate/poi-polygon/PoiPolygonRfClassifier.h, hoot-core/src/main/cpp/hoot/core/conflate/point/PoiRfClassifier.cpp, hoot-core/src/main/cpp/hoot/core/conflate/point/PoiRfClassifier.h, hoot-core/src/main/cpp/hoot/core/io/ApiDbSqlStatementFormatter.h, hoot-core/src/main/cpp/hoot/core/io/HootApiDbSqlStatementFormatter.h, hoot-core/src/main/cpp/hoot/core/io/OsmApiDbSqlStatementFormatter.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiDbSqlStatementFormatter.h, hoot-core/src/main/cpp/hoot/core/schema/TranslatedTagDifferencer.cpp, hoot-rnd/src/main/cpp/hoot/rnd/conflate/network/IterativeEdgeMatcher.h, hoot-rnd/src/main/cpp/hoot/rnd/conflate/network/IterativeNetworkMatcher.h, hoot-rnd/src/main/cpp/hoot/rnd/scoring/multiary/MultiaryMatchComparator.h, tbs/src/main/cpp/tbs/optimization/GoldenSectionSearch.h, tbs/src/main/cpp/tbs/optimization/LineSearch.cpp, tbs/src/main/cpp/tbs/optimization/LineSearch.h, tbs/src/main/cpp/tbs/stats/TDistribution.h
Polymorphic base class destructor should be either public virtual or protected non-virtual (15)
Added virtual destructors to base classes with virtual functions
Refs #4570
=> SONAR: Minor sonar rules to fix

hoot-core/src/main/cpp/hoot/core/algorithms/ExpectationIntersection.cpp, hoot-core/src/main/cpp/hoot/core/algorithms/changeset/ChangesetReplacementCreatorAbstract.cpp, hoot-core/src/main/cpp/hoot/core/algorithms/perty/DirectSequentialSimulation.cpp, hoot-core/src/main/cpp/hoot/core/algorithms/perty/PertyTestRunner.cpp, hoot-core/src/main/cpp/hoot/core/conflate/matching/NodeMatcher.cpp, hoot-core/src/main/cpp/hoot/core/index/OsmMapIndex.cpp, hoot-core/src/main/cpp/hoot/core/io/ApiDbReader.cpp, hoot-core/src/main/cpp/hoot/core/io/OgrWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmPbfReader.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmPbfWriter.cpp, hoot-core/src/main/cpp/hoot/core/ops/CalculateStatsOp.cpp, hoot-core/src/main/cpp/hoot/core/util/StringUtils.cpp, hoot-rnd/src/main/cpp/hoot/rnd/visitors/ImplicitTypeTaggerBase.cpp, tgs/src/main/cpp/tgs/RandomForest/InfoGainCalculator.cpp, tgs/src/main/cpp/tgs/RandomForest/RandomTree.cpp, tgs/src/main/cpp/tgs/System/SystemInfo.cpp
=> SONAR: Remove redundant casts

hoot-core/src/main/cpp/hoot/core/algorithms/LineStringAverager.cpp, hoot-core/src/main/cpp/hoot/core/algorithms/WayAverager.cpp, hoot-core/src/main/cpp/hoot/core/algorithms/extractors/AngleHistogramExtractor.cpp, hoot-core/src/main/cpp/hoot/core/algorithms/extractors/poi-polygon/PoiPolygonNameScoreExtractor.cpp, hoot-core/src/main/cpp/hoot/core/cmd/ScoreMatchesCmd.cpp, hoot-core/src/main/cpp/hoot/core/criterion/CriterionUtils.h, hoot-core/src/main/cpp/hoot/core/criterion/ParallelWayCriterion.cpp, hoot-core/src/main/cpp/hoot/core/geometry/GeometryPainter.cpp, hoot-core/src/main/cpp/hoot/core/geometry/GeometryUtils.cpp, hoot-core/src/main/cpp/hoot/core/index/KnnWayIterator.cpp, hoot-core/src/main/cpp/hoot/core/index/OsmMapIndex.cpp, hoot-core/src/main/cpp/hoot/core/io/ArffReader.cpp, hoot-core/src/main/cpp/hoot/core/io/ArffWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/OgrReader.cpp, hoot-core/src/main/cpp/hoot/core/io/OgrReader.h, hoot-core/src/main/cpp/hoot/core/io/OsmGbdxXmlWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmPbfReader.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmPbfReader.h, hoot-core/src/main/cpp/hoot/core/io/OsmPbfWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmPbfWriter.h, hoot-core/src/main/cpp/hoot/core/io/OsmXmlWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/PbfElementIterator.cpp, hoot-core/src/main/cpp/hoot/core/io/PbfElementIterator.h, hoot-core/src/main/cpp/hoot/core/schema/OsmSchema.cpp, hoot-core/src/main/cpp/hoot/core/schema/OsmSchema.h, sonar-project.properties, tgs/src/main/cpp/tgs/RStarTree/HilbertRTree.cpp, tgs/src/main/cpp/tgs/RStarTree/HilbertRTree.h, tgs/src/main/cpp/tgs/RStarTree/RStarTreeWrapper.cpp, tgs/src/main/cpp/tgs/RStarTree/RStarTreeWrapper.h
Manage memory with smart pointers instead of manually
Refs #4570
=> SONAR: Memory should not be managed manually

CONTRIBUTING.md, hoot-core/src/main/cpp/hoot/core/scoring/MatchComparator.cpp
fixes a few currently failing regression tests
=> Revert change to MatchComparator

translations/schema2josmpreset.js
=> Fixed #4608. Make a preset per geom type for josm translation

translations/schema2josmpreset.js
=> Fixed #4608. Fix bug with only grabbing first instance of fcode

hoot-core/src/main/cpp/hoot/core/algorithms/optimizer/IntegerProgrammingSolver.cpp
Update GLPK logging for TRACE and DEBUG
Closes #4630
=> GLPK Logging Displayed When Not Desirable

translations/schema2josmpreset.js
=> JOSM preset xml ordering added per geom type

.circleci/config.yml
Update to latest Docker images pushed from ngageoint/hootenanny-rpms#309.
=> CircleCI Docker Image Updates

hoot-js/src/main/cpp/hoot/js/criterion/JsFunctionCriterion.cpp, hoot-js/src/main/cpp/hoot/js/criterion/JsFunctionCriterion.h, hoot-js/src/main/cpp/hoot/js/util/PopulateConsumersJs.h, translations/test/ElementGeometryUtilsJs.js, translations/test/JsFunctionCriterion.js, translations/test/OsmMapJs.js
It shouldn't have previously been removed, as it was in use by a regression test. Added a unit test for it.
=> Fix use of `JsFunctionCriterion`

hoot-core/src/main/cpp/hoot/core/conflate/DiffConflator.cpp
Will make it easier to debug partial match removal behavior in the testing environment.
=> Logging update for diff conflate

translations/mgcp.js, translations/tds70.js
refs: #4765
Adding the same code as MGCP
=> Added OSMTAGS to TDSv7

VagrantProvisionCentOS7.sh, VagrantProvisionVars.sh, hoot-core/src/main/cpp/hoot/core/io/OsmApiWriter.cpp, test-files/cases/attribute/network/highway-2927-multiple-types-1/Expected.osm, test-files/cases/attribute/network/highway-2927-unmarked-ref-divided-road-1/Expected.osm, test-files/cmd/glacial/ConflateAverageRoadTest/output-dc-network.osm, test-files/cmd/slow/ConflateCmdStatsAllDataTypesTest.sh.stdout, test-files/cmd/slow/ConflateCmdStatsTest/all-data-types-out.osm, test-files/cmd/slow/ConflateCmdTest/output.osm, test-files/cmd/slow/ServiceHootApiDbConflateTest/output1.osm
Updates to Vagrantfile to install devtoolset-8, including temporary fix until updated boxes are available.
=> Install and use update compiler `devtoolset-8` for Hootenanny

hoot-services/src/main/java/hoot/services/controllers/conflation/AdvancedConflationOptionsResource.java, hoot-services/src/main/java/hoot/services/controllers/info/HootWaySnapCriteria.java, hoot-services/src/test/java/hoot/services/controllers/info/AdvancedOptResourceTest.java
ref #4799 
related to: https://github.com/ngageoint/hootenanny-ui/pull/1877
=> Fixed #4799. added population for snap ways list

hoot-services/src/main/java/hoot/services/controllers/ogr/ExtractAttributesCommand.java, hoot-services/src/main/java/hoot/services/controllers/ogr/ExtractAttributesResource.java, hoot-services/src/test/java/hoot/services/controllers/ogr/ExtractAttributesCommandTest.java
ref #4812 
ui ticket: https://github.com/ngageoint/hootenanny-ui/compare/1883_gpkg_support?expand=1
=> Fixed #4812. added gpkg support for TA assistant upload

hoot-core-test/src/test/cpp/hoot/core/util/SettingsTest.cpp, hoot-core/src/main/cpp/hoot/core/cmd/CountCmd.cpp, hoot-core/src/main/cpp/hoot/core/cmd/StatCmd.cpp, hoot-core/src/main/cpp/hoot/core/conflate/matching/MatchFactory.cpp, hoot-core/src/main/cpp/hoot/core/util/Factory.cpp, hoot-core/src/main/cpp/hoot/core/util/Factory.h, hoot-core/src/main/cpp/hoot/core/util/Settings.cpp, hoot-core/src/main/cpp/hoot/core/util/Settings.h, test-files/cmd/slow/OpNoNamespaceTest.sh, test-files/cmd/slow/OpNoNamespaceTest/conflate-out.osm, test-files/cmd/slow/OpNoNamespaceTest/convert-out.osm
No need to type `hoot::` in front of every op class name when executing a command anymore.
=> Add global namespace to ops read from config automatically

VagrantProvisionCentOS7.sh, scripts/HootEnv.sh, test-files/jakarta_raya_coastline.js
Set the DevToolSet path in `SetupEnv.sh` instead of .bash_profile, update the `sudo` change, and remove a comment from an older PR
=> DevToolSet maintenance

hoot-services/src/main/java/hoot/services/controllers/conflation/AdvancedConflationOptionsResource.java, hoot-services/src/main/java/hoot/services/controllers/grail/RunDiffCommand.java
=> Fixed #4828. differential option for road algorithm dropdown

hoot-services/src/main/java/hoot/services/command/ExternalCommandRunnerImpl.java, hoot-services/src/main/java/hoot/services/controllers/conflation/AdvancedConflationOptionsResource.java, hoot-services/src/main/java/hoot/services/controllers/grail/RunDiffCommand.java
=> Fixed #4836. fixed derive diff changeset to work with network algorithm

hoot-core-test/src/test/cpp/hoot/core/scoring/MatchComparatorTest.cpp, hoot-test/src/main/cpp/hoot/test/main.cpp
Report the number of failed tests, if any
=> Clean up `HootTest` output for failures

Vagrantfile
=> Fixed #4857. fixed issue with sshfs mount

hoot-core/src/main/cpp/hoot/core/algorithms/WayJoiner.cpp, test-files/cases/reference/network/highway-017/Expected.osm
The `WayJoinerAdvanced` doesn't join bridges with regular roads (desired affect) while the basic `WayJoiner` does.  This fixes that error.
=> WayJoiner bridge error

hoot-services/src/main/java/hoot/services/controllers/grail/RunDiffCommand.java
=> Fixed #4879. added bounds to derive differential changeset

hoot-core/src/main/cpp/hoot/core/conflate/DiffConflator.cpp, hoot-core/src/main/cpp/hoot/core/ops/UnconnectedWaySnapper.cpp
This is error checking that should have been added as part of #4915.
=> Add diff sec way removal criteria error checking

hoot-services/src/main/java/hoot/services/controllers/conflation/AdvancedConflationOptionsResource.java
=> Fixed #4923. add options for diff opts list

docs/algorithms/ConflationAlgsOverview.md
Fixed link to road unifying conflation algo
=> Fixed link to road unifying conflation algo

docs/user/VAGRANT.md
Cloning by SSH does not work anonymously, you need to use SSL.
=> Fixed cloning process issue desc

docs/user/VAGRANT.md
Typo fixes and a little more info for Widndows/VBoxGuest additions workaround.
=> Typo fixes and a little more info.

docs/user/CommandLineExamples.asciidoc
snap.unconnected.ways.snap.way.status => snap.unconnected.ways.snap.way.statuses
=> Fixed typo in argument

docker/hoot_commandline_nightly/Dockerfile, docker/hoot_commandline_nightly/README.md, docker/hoot_commandline_nightly/build_image.sh, docker/hoot_commandline_nightly/run_image.sh
Container to run Hoot from the nightly RPM's
=> Very basic Dockerfile for a Nightly container

docs/user/CommandLineExamples.asciidoc
This solves #4992
Corrected example for RemoveTagsVisitor so it actually works.
=> Corrected example for RemoveTagsVisitor

hoot-services/src/main/java/hoot/services/controllers/grail/GrailResource.java
=> Fixed #4997. enable createChangeset to work with custom data secondary

hoot-services/src/main/java/hoot/services/controllers/grail/GrailResource.java, hoot-services/src/main/java/hoot/services/controllers/grail/RunDiffCommand.java
ref #5010 
ui companion ticket: https://github.com/ngageoint/hootenanny-ui/pull/1907
=> Fixed #5010. added step for createChangeset to push diff tags file

translations/schema2josmpreset.js
=> include the default value in the preset

hoot-services/src/main/java/hoot/services/controllers/conflation/AdvancedConflationOptionsResource.java
=> Fixed #5019. fix display list returned for multiCombobox for /getoptions

hoot-services/src/main/java/hoot/services/controllers/ingest/ImportResource.java, hoot-services/src/main/java/hoot/services/controllers/osm/map/FolderResource.java, hoot-services/src/main/java/hoot/services/utils/DbUtils.java
=> Fixed #3081. Clean up logic for folder_map_mapping

hoot-services/src/main/java/hoot/services/HootProperties.java, hoot-services/src/main/java/hoot/services/controllers/grail/WaitOverpassUpdate.java, hoot-services/src/main/resources/conf/hoot-services.conf.in
=> make overpass sync timeout and polling interval configurable

hoot-services/src/main/java/hoot/services/controllers/export/ExportResource.java, test-files/ui/features/import_export_delete_osm_dataset.feature
=> zip changeset osc file on download

Makefile.hoot, VagrantProvisionCentOS7.sh, node-export-server/package-lock.json, node-export-server/package.json, node-export-server/server.js, node-export-server/test/server.js, translations/checkTranslations.js, translations/package-lock.json, translations/package.json, translations/test/TranslationServer.js, translations/test/basin_reservoir.js, translations/test/bridge_aqueduct.js, translations/test/bulk_translate.js, translations/test/facility.js, translations/test/line-to-area-cases.js, translations/test/mall_motor_vehicle.js, translations/test/marketplace.js, translations/test/measurement_fields.js, translations/test/pass_thru_unknown.js, translations/test/preserve_OTH.js, translations/test/preserve_unmapped.js, translations/test/runway.js, translations/test/school_grounds.js, translations/test/source_datetime_ggdm30.js, translations/test/source_datetime_mgcp.js, translations/test/source_datetime_tds40.js, translations/test/source_datetime_tds61.js, translations/test/tag1.js, translations/test/tests_to_fix.js
...for translations and node-export-server
- install mocha locally for translations vs globally in provision script
- also fix node-export-server tests and make them run as part of overall test suite
=> Update some nodejs dependencies

hoot-core-test/src/test/cpp/hoot/core/io/OsmGeoJsonReaderTest.cpp, hoot-core-test/src/test/cpp/hoot/core/io/OsmJsonReaderTest.cpp, hoot-core-test/src/test/cpp/hoot/core/visitors/ImplicitPoiTypeTaggerTest.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmGeoJsonReader.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmGeoJsonReader.h, hoot-core/src/main/cpp/hoot/core/io/OsmJsonReader.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmJsonReader.h, hoot-core/src/main/cpp/hoot/core/util/StringUtils.cpp, hoot-core/src/main/cpp/hoot/core/util/StringUtils.h, test-files/io/GeoJson/SampleObjectsReader.osm, test-files/nodes.json
Use streams inside of the JSON/GeoJSON readers so that the whole files isn't loaded multiple times.
Closes #5151
=> Large GeoJSON files over 1 GB don't load in Hoot

conf/core/ConfigOptions.asciidoc, hoot-core/src/main/cpp/hoot/core/io/OsmPbfWriter.cpp
=> Added config options to the PBF writer

hoot-core-test/src/test/cpp/hoot/core/io/OsmApiChangesetTest.cpp, hoot-core-test/src/test/cpp/hoot/core/io/OsmApiWriterTest.cpp, hoot-core-test/src/test/cpp/hoot/core/io/OsmApiWriterTestServer.cpp, hoot-core-test/src/test/cpp/hoot/core/io/OsmApiWriterTestServer.h, hoot-core/src/main/cpp/hoot/core/algorithms/ExpectationIntersection.cpp, hoot-core/src/main/cpp/hoot/core/algorithms/ExpectationIntersection.h, hoot-core/src/main/cpp/hoot/core/algorithms/FindNodesInWayFactory.cpp, hoot-core/src/main/cpp/hoot/core/algorithms/FindNodesInWayFactory.h, hoot-core/src/main/cpp/hoot/core/algorithms/FrechetDistance.cpp, hoot-core/src/main/cpp/hoot/core/algorithms/FrechetDistance.h, hoot-core/src/main/cpp/hoot/core/algorithms/zindex/ZCurveRanger.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangeset.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangeset.h, hoot-core/src/main/cpp/hoot/core/io/OsmApiWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiWriter.h, sonar-project.properties, tgs/src/main/cpp/tgs/DelaunayTriangulation/DelaunayTriangulation.cpp
Make `OsmApiWriter` verify uploads if the result is an HTTP 503 error.  Also fixed a few files with Sonar findings.
Closes #5172
=> OsmApiWriter 503 error

docker/hoot_external_command_nightly/scripts/RunCommandsAcrossContainers.sh
This PR is for Sherlock to be able to alter the default thresholds whenever executing Hoot runs for match and review values. Sherlock runs are automatically calling hoot processes.
=> Add command args to change threshold values for match/review

hoot-core/src/main/cpp/hoot/core/algorithms/alpha-shape/AlphaShapeGenerator.cpp, hoot-core/src/main/cpp/hoot/core/algorithms/merging/BuildingPartPreMergeCollector.cpp, hoot-core/src/main/cpp/hoot/core/algorithms/merging/BuildingPartPreMergeCollector.h, hoot-core/src/main/cpp/hoot/core/geometry/GeometryMerger.cpp, hoot-core/src/main/cpp/hoot/core/io/DataConverter.cpp, hoot-core/src/main/cpp/hoot/core/io/ElementTranslatorThread.cpp, hoot-core/src/main/cpp/hoot/core/io/ElementTranslatorThread.h, hoot-core/src/main/cpp/hoot/core/io/HootApiDbWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/HootApiDbWriter.h, hoot-core/src/main/cpp/hoot/core/io/OgrWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/OgrWriter.h, hoot-core/src/main/cpp/hoot/core/io/OgrWriterThread.cpp, hoot-core/src/main/cpp/hoot/core/io/OgrWriterThread.h, hoot-core/src/main/cpp/hoot/core/io/OsmApiWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiWriter.h, hoot-core/src/main/cpp/hoot/core/io/ParallelBoundedApiReader.cpp, hoot-core/src/main/cpp/hoot/core/io/PartialOsmMapWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/PartialOsmMapWriter.h, hoot-core/src/main/cpp/hoot/core/ops/BuildingPartMergeOp.cpp, hoot-core/src/main/cpp/hoot/core/schema/ScriptToOgrSchemaTranslator.h, hoot-core/src/main/cpp/hoot/core/scoring/GraphComparator.cpp, hoot-core/src/main/cpp/hoot/core/util/Factory.cpp, hoot-core/src/main/cpp/hoot/core/util/Factory.h, hoot-core/src/main/cpp/hoot/core/visitors/RemoveRef2Visitor.cpp, hoot-core/src/main/cpp/hoot/core/visitors/RemoveRef2Visitor.h, hoot-test/src/main/cpp/hoot/test/ProcessPool.cpp, hoot-test/src/main/cpp/hoot/test/ProcessPool.h
Missed moving `HootApiWriter::setIncludeDebug` to `PartialOsmMapWriter`
Changed all `QMutex` instances to `std::mutex` and fixed mutex Sonar findings.
https://github.com/ngageoint/hootenanny/pull/5171
=> Fix debug output in PartialOsmMapWriter

hoot-services/pom.xml
and the beat goes on!
https://logging.apache.org/log4j/2.x/security.html
=> update log4j2 version

hoot-services/src/main/java/hoot/services/controllers/grail/GrailResource.java
when an input can be a db layer
=> need to pass a user to conflate command

translations/schema2josmpreset.js
=> add OSMTAGS with explicit area=yes/no for ambiguous FCODEs

conf/core/ConfigOptions.asciidoc, hoot-core-test/src/test/cpp/hoot/core/algorithms/WayAveragerTest.cpp, hoot-core-test/src/test/cpp/hoot/core/conflate/poi-polygon/PoiPolygonMergerCreatorTest.cpp, hoot-core-test/src/test/cpp/hoot/core/conflate/stats/ConflateStatsHelperTest.cpp, hoot-core-test/src/test/cpp/hoot/core/io/OsmPbfWriterTest.cpp, hoot-core-test/src/test/cpp/hoot/core/scoring/GraphComparatorTest.cpp, hoot-core/src/main/cpp/hoot/core/algorithms/WayAverager.cpp, hoot-core/src/main/cpp/hoot/core/algorithms/WayAverager.h, hoot-core/src/main/cpp/hoot/core/algorithms/splitter/HighwayCornerSplitter.cpp, hoot-core/src/main/cpp/hoot/core/conflate/poi-polygon/PoiPolygonMergerCreator.cpp, hoot-core/src/main/cpp/hoot/core/conflate/poi-polygon/PoiPolygonMergerCreator.h, hoot-core/src/main/cpp/hoot/core/conflate/stats/ConflateStatsHelper.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmPbfWriter.cpp, hoot-core/src/main/cpp/hoot/core/scoring/GraphComparator.cpp, hoot-core/src/main/cpp/hoot/core/scoring/GraphComparator.h, hoot-test/src/main/cpp/hoot/test/AbstractTest.cpp, hoot-test/src/main/cpp/hoot/test/AbstractTestSuite.cpp, hoot-test/src/main/cpp/hoot/test/ConflateCaseTest.cpp, hoot-test/src/main/cpp/hoot/test/ConflateCaseTest.h, hoot-test/src/main/cpp/hoot/test/ConflateCaseTestSuite.cpp, hoot-test/src/main/cpp/hoot/test/ConflateCaseTestSuite.h, hoot-test/src/main/cpp/hoot/test/ScriptTest.cpp, hoot-test/src/main/cpp/hoot/test/ScriptTest.h, hoot-test/src/main/cpp/hoot/test/ScriptTestSuite.cpp, hoot-test/src/main/cpp/hoot/test/ScriptTestSuite.h, hoot-test/src/main/cpp/hoot/test/SimpleTestListener.cpp, hoot-test/src/main/cpp/hoot/test/TestSetup.cpp
Some times Jenkins tests hang during nightly testing.  Fail script tests when they timeout.
=> Jenkins tests are hanging

node-export-server/config.json, node-export-server/server.js
=> remove wget step, pass api url directly to hoot convert

hoot-services/src/main/java/hoot/services/controllers/grail/GrailResource.java, hoot-services/src/main/java/hoot/services/controllers/grail/PullApiCommand.java, hoot-services/src/main/java/hoot/services/controllers/grail/PullOverpassCommand.java
Logs the oql query when Hoot pulls data
=> Overpass query logging

hoot-core-test/src/test/cpp/hoot/core/io/OsmGeoJsonReaderTest.cpp, hoot-core/src/main/cpp/hoot/core/geometry/ElementToGeometryConverter.cpp, hoot-core/src/main/cpp/hoot/core/geometry/ElementToGeometryConverter.h, hoot-core/src/main/cpp/hoot/core/io/OsmGbdxJsonWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmGbdxJsonWriter.h, hoot-core/src/main/cpp/hoot/core/io/OsmGeoJsonReader.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmGeoJsonWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmGeoJsonWriter.h, hoot-core/src/main/cpp/hoot/core/io/OsmGeoJsonWriterBase.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmGeoJsonWriterBase.h, hoot-core/src/main/cpp/hoot/core/io/OsmJsonWriter.cpp, test-files/io/GeoJson/MultiObjectsReader.osm, test-files/io/GeoJson/OuterInnerTest.geojson, test-files/io/GeoJson/OuterInnerTest.osm
Fix GeoJSON writer to include `outer` and `inner` roles for `MultiPolygon` relations and fixed formatting and code smells
=> GeoJSON multipolygon relation roles

translations/mgcp.js, translations/mgcp_rules.js
Some fixes from the range of MGCP issues
=> MGCP fixes

node-export-server/server.js
with wget removed, no need to try to remove .osm file
log error on download, saw export from TM where job completed but somehow download still errored
=> Improve node export logging to show job hash

hoot-core/src/main/cpp/hoot/core/algorithms/splitter/IntersectionSplitter.cpp, hoot-core/src/main/cpp/hoot/core/geometry/RelationToMultiPolygonConverter.cpp, hoot-core/src/main/cpp/hoot/core/io/OgrUtilities.cpp, hoot-core/src/main/cpp/hoot/core/io/OgrUtilities.h, hoot-core/src/main/cpp/hoot/core/io/OgrWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/OgrWriter.h, hoot-core/src/main/cpp/hoot/core/io/OsmMapWriterFactory.cpp, hoot-core/src/main/cpp/hoot/core/util/Settings.cpp, hoot-core/src/main/cpp/hoot/core/util/SharedPtrPool.h
Clean up the `SharedPtrPool` after all of the pointers are returned, they need to be passed back to the system.
Refs #5256
=> More memory issues

translations/etds71_osm.js, translations/ggdm30_rules.js, translations/mgcp.js, translations/tds61_rules.js, translations/tds71_rules.js
=> Fixed the AC000 vs AL010 translation issue

scripts/schema/ConvertGGDMv30Schema.py, scripts/schema/ConvertMGCPSchema_XML.py, scripts/schema/ConvertTDSv40Schema.py, scripts/schema/ConvertTDSv61Schema.py, scripts/schema/ConvertTDSv70Schema.py, scripts/schema/hootLibrary.py
UI no longer wants root level property names, just an array in the json
=> UI translation assistant fields generation script update

hoot-services/src/main/java/hoot/services/jobs/JobsStatusesManagerImpl.java
fixes https://github.com/ngageoint/hootenanny-ui/issues/1955
=> Do related job filter in db query (vs filtering result)

hoot-services/src/main/java/hoot/services/controllers/ingest/CustomScriptResource.java, hoot-services/src/main/java/hoot/services/controllers/ingest/ImportResource.java
=> Distinguish editable ops from read-only for translation visibility

conf/core/ConfigOptions.asciidoc, scripts/schema/compareTrans.py, test-files/cmd/slow/TDSv40TranslationTest.sh, test-files/cmd/slow/TDSv71/TDSv71.osm, test-files/cmd/slow/TDSv71TranslationTest.sh, test-files/cmd/slow/TDSv71TranslationTest.sh.stdout, translations/tds70.js, translations/tds70_rules.js, translations/tds71.js, translations/tds71_rules.js, translations/translate.js
=> TDS71 fixes

hoot-core/src/main/cpp/hoot/core/cmd/DeDuplicateCmd.cpp, hoot-core/src/main/cpp/hoot/core/criterion/TagKeyContainsCriterion.cpp, hoot-core/src/main/cpp/hoot/core/io/ParallelBoundedApiReader.cpp, hoot-core/src/main/cpp/hoot/core/io/ParallelBoundedApiReader.h, hoot-core/src/main/cpp/hoot/core/util/FileUtils.cpp
=> Fixing random HTTP 504 error in OsmJsonReaderTest::urlTest

translations/UFD_to_OSM.js, translations/dnc_core.js, translations/ggdm30.js, translations/mgcp.js, translations/tds40.js, translations/tds61.js, translations/tds70.js, translations/tds70_rules.js, translations/tds71.js
=> Fixed the UUID issue

hoot-services/src/main/java/hoot/services/controllers/nodejs/NodejsService.java
=> Fix for redirecting nodejs logging to tomcat log

hoot-core-test/src/test/cpp/hoot/core/algorithms/changeset/ChangesetCreatorTest.cpp, hoot-core-test/src/test/cpp/hoot/core/algorithms/optimizer/SingleAssignmentProblemSolverTest.cpp, hoot-core-test/src/test/cpp/hoot/core/io/OgrReaderTest.cpp, hoot-core-test/src/test/cpp/hoot/core/io/OsmXmlChangesetFileWriterTest.cpp, hoot-core/src/main/cpp/hoot/core/algorithms/changeset/ChangesetCreator.cpp, hoot-core/src/main/cpp/hoot/core/algorithms/changeset/ChangesetReplacement.h, hoot-core/src/main/cpp/hoot/core/algorithms/changeset/TaskGridGenerator.h, hoot-core/src/main/cpp/hoot/core/algorithms/optimizer/SingleAssignmentProblemSolver.h, hoot-core/src/main/cpp/hoot/core/conflate/ConflateExecutor.cpp, hoot-core/src/main/cpp/hoot/core/conflate/DiffConflator.cpp, hoot-core/src/main/cpp/hoot/core/conflate/DiffConflator.h, hoot-core/src/main/cpp/hoot/core/conflate/matching/MatchType.h, hoot-core/src/main/cpp/hoot/core/elements/ElementType.h, hoot-core/src/main/cpp/hoot/core/io/ChangesetStatsFormat.h, hoot-core/src/main/cpp/hoot/core/io/OsmChangesetFileWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmChangesetFileWriter.h, hoot-core/src/main/cpp/hoot/core/io/OsmXmlChangesetFileWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmXmlChangesetFileWriter.h, hoot-core/src/main/cpp/hoot/core/schema/OsmSchema.cpp, hoot-core/src/main/cpp/hoot/core/schema/OsmSchema.h, tgs/src/main/cpp/tgs/RandomForest/BaseRandomForest.cpp, tgs/src/main/cpp/tgs/RandomForest/BaseRandomForest.h, tgs/src/main/cpp/tgs/RandomForest/BaseRandomForestManager.cpp, tgs/src/main/cpp/tgs/RandomForest/BaseRandomForestManager.h, tgs/src/main/cpp/tgs/RandomForest/DataFrame.cpp, tgs/src/main/cpp/tgs/RandomForest/DataFrame.h
Fix critical bug in Hootenanny and reformat affected code.
=> Critical bug was identified in Hootenanny

node-export-server/server.js, node-export-server/test/server.js
=> add method to validate export params and error gracefully

hoot-core/src/main/cpp/hoot/core/io/OgrReader.cpp
=> Handle features with unknown geometry

hoot-services/src/main/java/hoot/services/controllers/conflation/ConflateCommand.java
=> Remove single quotes in adv opt values

hoot-services/src/main/java/hoot/services/controllers/osm/map/MapResource.java
=> limit the MBR response coords to six decimal places

m4/josm.m4
=> don't hardcode java path, use JAVA_HOME

translations/ENCv311_to_OGR.js, translations/GeoNames_to_OSM.js, translations/SchemaTools.js, translations/ggdm30.js, translations/mgcp.js, translations/tds40.js, translations/tds61.js, translations/tds70.js, translations/tds71.js, translations/translate.js
=> Translations: Small fixes and cleanup

scripts/EnableCoverage.sh, scripts/jenkins/Jenkinsfile
After TestConfigure.sh runs, there is a LocalConfig.pri already, it must be updated too.
=> Fix Jenkins nightly

test-files/MGCPv3/LAP010-output.osm, test-files/MGCPv3/LAP030-output.osm, test-files/cmd/slow/ConvertCmdTest/combined_shapefile.osm, translations/checkSingleFeature.js, translations/checkTranslations.js, translations/mgcp.js, translations/mgcp_rules.js, translations/tds40.js, translations/tds70.js, translations/tds71.js, translations/test/road.js
=> Fixed the WID vs WD1 issue in MGCP

docker/hoot_external_command_nightly/Dockerfile, docker/hoot_external_command_nightly/scripts/RunCommandsAcrossContainers.sh
- Additional capability for Sherlock to execute split and translation commands have been implemented
=> Sherlock auto split and translation workflow

hoot-core-test/src/test/cpp/hoot/core/elements/RelationTest.cpp, hoot-core/src/main/cpp/hoot/core/elements/Element.h, hoot-core/src/main/cpp/hoot/core/elements/Node.cpp, hoot-core/src/main/cpp/hoot/core/elements/Node.h, hoot-core/src/main/cpp/hoot/core/elements/Relation.cpp, hoot-core/src/main/cpp/hoot/core/elements/Relation.h, hoot-core/src/main/cpp/hoot/core/elements/Way.cpp, hoot-core/src/main/cpp/hoot/core/elements/Way.h, hoot-core/src/main/cpp/hoot/core/ops/AddHilbertReviewSortOrderOp.cpp, hoot-core/src/main/cpp/hoot/core/visitors/RemoveInvalidMultilineStringMembersVisitor.cpp
Circular and self-referencing relations cause Hootenanny to crash in some instances.
Closes #5411
=> Relation issues

hoot-services/src/main/java/hoot/services/command/ExternalCommandRunnerImpl.java
The logged url will appear like this
` /vsizip//vsicurl/ftp://<basic:auth>@192.168.56.1:2121/panera-maid-rite.osm.zip `
=> Sanitize the basic auth creds in the logged hoot convert ftp/http urls

VagrantProvisionCentOS7.sh
Fixes a build failure when NodeJS gets updated
=> Fix NodeJS install issue

hoot-services/src/main/java/hoot/services/controllers/export/ExportResource.java, hoot-services/src/main/java/hoot/services/controllers/osm/map/MapResource.java, hoot-services/src/main/java/hoot/services/controllers/osm/user/UserResource.java, hoot-services/src/main/java/hoot/services/job/Job.java, test-files/ui/features/import_export_delete_osm_dataset.feature, test-files/ui/features/import_export_delete_shp_dataset.feature
Also:
- Add job status tags to delete map jobs to display map name in info column of jobs panel
- Add service endpoint to get user session id for use with josm remote control
=> Include output format in export zip file name

hoot-services/pom.xml, hoot-services/src/main/java/hoot/services/controllers/osm/changeset/ChangesetDbWriter.java, hoot-services/src/main/java/hoot/services/controllers/osm/changeset/ChangesetErrorChecker.java, hoot-services/src/main/java/hoot/services/controllers/osm/changeset/ChangesetUploadXmlValidator.java, hoot-services/src/main/java/hoot/services/models/osm/Changeset.java, hoot-services/src/main/java/hoot/services/models/osm/Relation.java, hoot-services/src/main/java/hoot/services/models/osm/Way.java, hoot-services/src/main/java/hoot/services/utils/XPathAPI.java, hoot-services/src/test/java/hoot/services/controllers/osm/OSMTestUtils.java, hoot-services/src/test/java/hoot/services/controllers/osm/capabilities/CapabilitiesResourceTest.java, hoot-services/src/test/java/hoot/services/controllers/osm/changeset/ChangesetResourceCloseTest.java, hoot-services/src/test/java/hoot/services/controllers/osm/changeset/ChangesetResourceUploadAllTest.java, hoot-services/src/test/java/hoot/services/controllers/osm/changeset/ChangesetResourceUploadCreateTest.java, hoot-services/src/test/java/hoot/services/controllers/osm/changeset/ChangesetResourceUploadDeleteTest.java, hoot-services/src/test/java/hoot/services/controllers/osm/changeset/ChangesetResourceUploadModifyTest.java, hoot-services/src/test/java/hoot/services/controllers/osm/element/ElementResourceTest.java, hoot-services/src/test/java/hoot/services/controllers/osm/map/MapResourceTest.java, hoot-services/src/test/java/hoot/services/controllers/osm/user/UserResourceTest.java
only interrogating i did was see that tests would pass. guess see if they pass here too
=> add util class to replace xalan XPathApi

hoot-services/src/main/java/hoot/services/controllers/export/ExportCommand.java, hoot-services/src/main/java/hoot/services/controllers/export/ExportParams.java
refs https://github.com/ngageoint/hootenanny-ui/pull/2008
=> add a thematic group export option

docker/hoot_external_command_nightly/scripts/RunCommandsAcrossContainers.sh
- A bug was occurring where very few building matches were appearing during conflation because the ids of the datasets were being overwritten
- Flag has been removed to keep source ids from datasets
=> Sherlock updates for conflation

translations/translate.js
Added more text replace functions.
=> Fix mangled text

node-export-server/config.json, node-export-server/server.js, translations/translationConfig.json
Same idea as the translatonServer
=> Added config file reading to the node-export server

conf/schema/landcover.json, conf/schema/schema.json, translations/checkTranslations.js, translations/translate.js
=> Fix mangled tags and other things

conf/core/ConfigOptions.asciidoc, docs/user/CommandLineExamples.asciidoc, hoot-core-test/src/test/cpp/hoot/core/io/OsmApiReaderTest.cpp, hoot-core-test/src/test/cpp/hoot/core/io/OsmJsonReaderTest.cpp, hoot-core-test/src/test/cpp/hoot/core/io/OverpassReaderInterfaceTest.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiReader.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiReader.h, hoot-core/src/main/cpp/hoot/core/io/OsmJsonReader.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmJsonReader.h, hoot-core/src/main/cpp/hoot/core/io/OverpassReaderInterface.cpp, hoot-core/src/main/cpp/hoot/core/io/OverpassReaderInterface.h, hoot-core/src/main/cpp/hoot/core/io/ParallelBoundedApiReader.cpp, hoot-core/src/main/cpp/hoot/core/io/ParallelBoundedApiReader.h
=> Make `OsmApiReader` read XML from Overpass

.gitignore, hoot-js/src/main/cpp/hoot/js/util/RequireJs.cpp
Read .js files from soft links.  Ignore all 'translations-*' files from git.
Closes #5523
=> HootJs Require Statements Failing

hoot-core-test/src/test/cpp/hoot/core/io/OsmApiReaderTest.cpp, hoot-core-test/src/test/cpp/hoot/core/ops/ImmediatelyConnectedOutOfBoundsWayTaggerTest.cpp, hoot-core/src/main/cpp/hoot/core/cmd/BoundedCommand.cpp, hoot-core/src/main/cpp/hoot/core/cmd/CropCmd.cpp, hoot-core/src/main/cpp/hoot/core/conflate/CookieCutter.cpp, hoot-core/src/main/cpp/hoot/core/criterion/InBoundsCriterion.cpp, hoot-core/src/main/cpp/hoot/core/geometry/GeometryUtils.cpp, hoot-core/src/main/cpp/hoot/core/geometry/GeometryUtils.h, hoot-core/src/main/cpp/hoot/core/io/HootApiDbReader.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiDbReader.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiReader.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmJsonReader.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmJsonReader.h, hoot-core/src/main/cpp/hoot/core/io/OsmXmlReader.cpp, hoot-core/src/main/cpp/hoot/core/ops/MapCropper.cpp, hoot-core/src/main/cpp/hoot/core/util/Boundable.cpp, hoot-core/src/main/cpp/hoot/core/util/Boundable.h
Refactor bounds input into the `Boundable` class and shared across the code base
=> Refactor bounds

hoot-core/src/main/cpp/hoot/core/io/OgrWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/OgrWriter.h, test-files/cmd/slow/ConvertCmdTest.sh, test-files/cmd/slow/ConvertCmdTest.sh.stdout, test-files/cmd/slow/ConvertCmdTest/clipped_lines.osm, test-files/cmd/slow/ConvertCmdTest/clipped_poly.osm
=> Map Cropping in OGR output

hoot-core/src/main/cpp/hoot/core/io/HootNetworkRequest.cpp, hoot-core/src/main/cpp/hoot/core/io/ParallelBoundedApiReader.cpp
Throttle `ParallelBoundedReader` requests to max_threads active downloads
Closes #5544
=> ParallelBoundedReader needs to throttle requests

node-export-server/server.js
Make it have the same functionality as hoot-services does.
=> Add translation conf files to the node-export server

hoot-core/src/main/cpp/hoot/core/io/OgrWriter.cpp
Drop geometries outside of the cropping boundary.
Refs #5509
=> Map crop should crop polygon geometry, not they way nodes and then assemble a mangled polygon

conf/core/ConfigOptions.asciidoc, hoot-core-test/src/test/cpp/hoot/core/visitors/NodesShiftVisitorTest.cpp, hoot-core/src/main/cpp/hoot/core/visitors/NodesShiftVisitor.cpp, hoot-core/src/main/cpp/hoot/core/visitors/NodesShiftVisitor.h, test-files/visitors/NodesShiftVisitorTest/applyToMapExpected1.osm, test-files/visitors/NodesShiftVisitorTest/applyToMapExpected2.osm, test-files/visitors/NodesShiftVisitorTest/applyToMapOutput2.osm
Created 'NodesShiftVisitor' to apply a predetermined shift to all nodes in a map.
Closes #5568
=> Add map shift visitor

docker/hoot_external_command_nightly/scripts/RunCommandsAcrossContainers.sh
- this PR updates a sherlock script to be able to pull data from overpass
=> sherlock owt workflow

scripts/copyright/UpdateCopyrightHeader.py, sonar-project.properties
Use date ranges for copyright headers instead of listing individual years
=> Copyright Script Update

scripts/services/CreateConflationTypeGroups.py
cherry-picking https://github.com/ngageoint/hootenanny/pull/5596/commits/96cc4dfa52e83382f0a7dd85e24f7b49a7f1e70e
=> Update advanced ops script to make poi opts unique.

HOOT_VERSION_GEN, Makefile.hoot, hoot-core/src/main/cpp/hoot/core/cmd/VersionCmd.cpp, hoot-core/src/main/cpp/hoot/core/info/Version.cpp, hoot-core/src/main/cpp/hoot/core/info/Version.h, hoot-core/src/main/cpp/hoot/core/info/VersionDefines.h.in, hoot-services/src/main/java/hoot/services/controllers/info/AboutResource.java, hoot-services/src/main/java/hoot/services/controllers/info/VersionInfo.java, hoot-services/src/test/java/hoot/services/controllers/info/AboutResourceTest.java, scripts/GenerateBuildInfoFiles.sh
https://github.com/ngageoint/hootenanny-ui/pull/2047
=> Add a commit date to the About version info

conf/core/ConfigOptions.asciidoc, hoot-core-test/src/test/cpp/hoot/core/io/ApiElementRetrievalInterfaceOpTest.cpp, hoot-core-test/src/test/cpp/hoot/core/io/ApiElementRetrievalInterfaceTest.cpp, hoot-core-test/src/test/cpp/hoot/core/ops/MissingElementRetrievalOpTest.cpp, hoot-core/src/main/cpp/hoot/core/algorithms/rubber-sheet/RubberSheet.h, hoot-core/src/main/cpp/hoot/core/io/ApiElementRetrievalInterface.cpp, hoot-core/src/main/cpp/hoot/core/io/ApiElementRetrievalInterface.h, hoot-core/src/main/cpp/hoot/core/io/DataConverter.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiReader.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiReader.h, hoot-core/src/main/cpp/hoot/core/io/OsmGeoJsonWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmGeoJsonWriter.h, hoot-core/src/main/cpp/hoot/core/io/OsmJsonWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmJsonWriter.h, hoot-core/src/main/cpp/hoot/core/io/OverpassReaderInterface.h, hoot-core/src/main/cpp/hoot/core/io/ParallelApiJob.cpp, hoot-core/src/main/cpp/hoot/core/io/ParallelApiJob.h, hoot-core/src/main/cpp/hoot/core/io/ParallelBoundedApiReader.cpp, hoot-core/src/main/cpp/hoot/core/io/ParallelBoundedApiReader.h, hoot-core/src/main/cpp/hoot/core/ops/MissingElementRetrievalOp.cpp, hoot-core/src/main/cpp/hoot/core/ops/MissingElementRetrievalOp.h, hoot-core/src/main/cpp/hoot/core/ops/OsmMapOperation.h, hoot-core/src/main/cpp/hoot/core/util/OsmApiUtils.h, test-files/ops/MissingElementRetrievalOpTest/MissingExpected.osm, test-files/ops/MissingElementRetrievalOpTest/MissingInput.osm
Created `MissingElementRetrievalOp`, unit tests, and updated other classes to be used by it.
Closes #5600
=> Create convert op that will "re-hydrate" ways and relations

hoot-core/src/main/cpp/hoot/core/conflate/highway/HighwayMatchCreator.cpp, hoot-core/src/main/cpp/hoot/core/geometry/GeometryUtils.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmMapReaderFactory.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmMapReaderFactory.h
Loading a bounds file threw hoot into an infinite loop, this is the fix
=> Bounds file infinite loop

translations/TranslationServer.js
=> make translation server more defensive when payload empty

docker/hoot_external_command_nightly/scripts/RunCommandsAcrossContainers.sh
- Capability has been added to provide a file as bounding box for Sherlock runs when pulling data down from overpass
=> add ability to provide bounding box file for sherlock capability

hoot-services/src/main/java/hoot/services/controllers/conflation/ConflateCommand.java, hoot-services/src/main/java/hoot/services/utils/DbUtils.java
vs java object since this change in #5595
=> need to get stats from stdout in db

translations/ggdm30.js, translations/ggdm30_rules.js, translations/mgcp.js, translations/mgcp_rules.js, translations/tds40.js, translations/tds40_rules.js, translations/tds61.js, translations/tds61_rules.js, translations/tds70.js, translations/tds70_rules.js, translations/tds71.js, translations/tds71_rules.js, translations/test/natural.js
Fixes for `natural=sand` and `natural=desert`
=> Soil Surface Area fixes

hoot-core/src/main/cpp/hoot/core/conflate/polygon/BuildingMerger.cpp, hoot-core/src/main/cpp/hoot/core/conflate/polygon/BuildingMerger.h, hoot-js/src/main/cpp/hoot/js/conflate/merging/AreaMergerJs.cpp, hoot-js/src/main/cpp/hoot/js/conflate/merging/AreaMergerJs.h, hoot-js/src/main/cpp/hoot/js/conflate/merging/ElementMergerJs.cpp, hoot-js/src/main/cpp/hoot/js/conflate/merging/PoiMergerJs.cpp, hoot-js/src/main/cpp/hoot/js/conflate/merging/PoiMergerJs.h, hoot-js/src/main/cpp/hoot/js/conflate/merging/RailwayMergerJs.cpp, hoot-js/src/main/cpp/hoot/js/conflate/merging/RailwayMergerJs.h, translations/test/ElementMergeServer.js
@bmarchant
```
Error: signal 11:
stack trace:
hoot::SignalCatcher::default_handler(int) +0x2d
/usr/lib64/libc.so.6 : ()+0x36400
hoot::ElementMergerJs::_merge(std::shared_ptr<hoot::OsmMap>, v8::Isolate*) +0x1f4
hoot::ElementMergerJs::merge(v8::FunctionCallbackInfo<v8::Value> const&) +0x449
/usr/lib64/libnode.so.83 : ()+0x10b6ae8
/usr/lib64/libnode.so.83 : ()+0x10b8605
v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) +0x19
/usr/lib64/libnode.so.83 : ()+0xcedbb9
```
=> Exception when merging positive id entity into negative id entity

conf/core/ConfigOptions.asciidoc, hoot-core/src/main/cpp/hoot/core/cmd/CompareCmd.cpp, hoot-core/src/main/cpp/hoot/core/scoring/BaseComparator.cpp, hoot-core/src/main/cpp/hoot/core/scoring/RasterComparator.cpp, hoot-core/src/main/cpp/hoot/core/scoring/RasterComparator.h, hoot-core/src/main/cpp/hoot/core/util/Log.cpp, hoot-core/src/main/cpp/hoot/core/util/Log.h, hoot-core/src/main/cpp/hoot/core/util/LogGeneric.h
=> Raster Compare Failure

hoot-core/src/main/cpp/hoot/core/cmd/CompareCmd.cpp, hoot-core/src/main/cpp/hoot/core/scoring/AttributeComparator.cpp, hoot-core/src/main/cpp/hoot/core/scoring/RasterComparator.cpp
=> Create fix for all building GeoJSON file comparison

hoot-core/src/main/cpp/hoot/core/cmd/AlphaShapeCmd.cpp, hoot-core/src/main/cpp/hoot/core/io/FlatGeobufWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/FlatGeobufWriter.h, hoot-core/src/main/cpp/hoot/core/io/IoUtils.cpp, hoot-core/src/main/cpp/hoot/core/io/OgrUtilities.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmMapWriterFactory.cpp, hoot-core/src/main/cpp/hoot/core/io/ShapefileWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/ShapefileWriter.h, test-files/cmd/slow/ConvertCmdTest/AllDataTypesFgb.osm, test-files/cmd/slow/ConvertCmdTest3.sh
Fix FlatGeobuf file handling by using OgrWriter
=> FCODE and Thematic FlatGeobuf files

translations/fcode_common.js, translations/ggdm30.js, translations/ggdm30_rules.js, translations/mgcp.js, translations/mgcp_rules.js, translations/tds40.js, translations/tds40_rules.js, translations/tds61.js, translations/tds61_rules.js, translations/tds70.js, translations/tds70_rules.js, translations/tds71.js, translations/tds71_rules.js
Got rid of some non-standard tags and cleaned up the translation
=> Landuse Fixes

hoot-services/src/main/java/hoot/services/controllers/grail/GrailResource.java
was changed to a hoot convert op #5593
now passes the output in the params sent to setupRailsPull
=> fix bobby magic since bug introduced when grail pull

hoot-services/src/main/java/hoot/services/controllers/osm/map/FolderResource.java
Seems to have been missed with this PR #3711
=> Add missing check to allow admins delete other users folders

hoot-services/src/main/java/hoot/services/controllers/grail/GrailResource.java, hoot-services/src/main/java/hoot/services/controllers/grail/PullApiCommand.java, hoot-services/src/test/java/hoot/services/controllers/grail/PullApiCommandTest.java
=> handle timeout and maxsize properties of overpassql in custom query

scripts/jenkins/Jenkinsfile, scripts/sonar/sonar-config.sh, scripts/sonar/sonar-install.sh, scripts/sonar/sonar-scan-mvn.sh, scripts/sonar/sonar-scan.sh, sonar-project.properties
Try removing the hoot-services scan for SonarQube
=> Fix Sonar build

docker/hoot_external_command_nightly/scripts/RunCommandsAcrossContainers.sh
Add `ogr.append.data` option to `run-translate()` function
=> Update `RunCommandsAcrossContainers.sh` to update Hoot options

docker/hoot_external_command_nightly/scripts/RunCommandsAcrossContainers.sh
- Update sherlock option to pull from overpass with more hoot command options
=> update sherlock pull from overpass

hoot-services/src/main/java/hoot/services/controllers/export/ExportCommand.java
refs: #5729
Changed it to use the name of the translation.
=> Tweaked the format for appending to an FGDB

docker/Dockerfile.core-services, docker/Dockerfile.frontend, docker/Dockerfile.postgres, scripts/jenkins/Jenkinsfile, scripts/schema/ConvertMGCPSchema_XML.py, translations/tds71.js
- MGCP append solutions: added GlobalID, FCSubtype, and GFID fields to schema to resolve missing fields issue (still experiencing write permissions issues)
- Hoot build solutions: moving the install of epel-release to its own line somehow fixes the build
- Resolved TDS attribution condition issues
=> schema updates

translations/tds71.js
- leisure=beach_resort is now a valid key:value pair in hoot TDSv71 translation
- https://maxar.atlassian.net/browse/VGI-4894
=> add specific rule for leisure=beach_resort

translations/etds71_osm_rules.js, translations/etds71_rules.js, translations/mgcp.js, translations/mgcp_rules.js, translations/tds71_schema.js, translations/tds71_thematic_schema.js
two mgcp translation fixes
https://maxar.atlassian.net/browse/VGI-4912
https://maxar.atlassian.net/browse/VGI-4911
=> fixes for aeroway=hangar and landuse=religious

translations/mgcp.js
- https://maxar.atlassian.net/browse/VGI-4918
- https://maxar.atlassian.net/browse/VGI-4919
- MGCP translation updates for barrier features that are coupled with area tags and also ones that are coupled with amenity=prison features
=> Mgcp barrier updates

translations/mgcp.js
fixes the following tickets:
https://maxar.atlassian.net/browse/VGI-4910
https://maxar.atlassian.net/browse/VGI-4925
https://maxar.atlassian.net/browse/VGI-4926
=> some mgcp fixes

translations/tds71.js
Certain geometry types for features do not allow for certain attributes. Making sure we are exporting/translating attributes that are only allowed for those specific geometry types.
https://maxar.atlassian.net/browse/VGI-5100
=> fix extranneous attrs for certain geometry types

translations/mgcp.js, translations/mgcp_rules.js
https://maxar.atlassian.net/browse/VGI-5053
https://maxar.atlassian.net/browse/VGI-5065
https://maxar.atlassian.net/browse/VGI-5067
=> a few more fixes

translations/fcode_common.js, translations/mgcp.js, translations/mgcpCartoMod.json, translations/mgcp_rules.js
- https://maxar.atlassian.net/browse/VGI-5077
- https://maxar.atlassian.net/browse/VGI-5079
- https://maxar.atlassian.net/browse/VGI-5074
- https://maxar.atlassian.net/browse/VGI-5083
- https://maxar.atlassian.net/browse/VGI-5085-
=> Mgcp issues

translations/mgcp.js, translations/mgcp_rules.js
https://maxar.atlassian.net/browse/VGI-5072
https://maxar.atlassian.net/browse/VGI-5082
https://maxar.atlassian.net/browse/VGI-5084
=> Translation updates

translations/mgcp.js, translations/mgcp_rules.js
https://maxar.atlassian.net/browse/VGI-5152
https://maxar.atlassian.net/browse/VGI-5199
https://maxar.atlassian.net/browse/VGI-5200
https://maxar.atlassian.net/browse/VGI-5201
https://maxar.atlassian.net/browse/VGI-5203
https://maxar.atlassian.net/browse/VGI-5205
Dimension stones, mineral piles, ice peaks, solid gold :sunglasses:
=> Dimension Stone

hoot-core/src/main/cpp/hoot/core/io/ApiDb.cpp, translations/RenderDb.js
This branch fixes two issues with parsing extra OSM tags on elements.
Relevant ticket: https://maxar.atlassian.net/browse/VGI-4770
=> Tag parsing fixes

hoot-services/src/main/java/hoot/services/controllers/export/ExportCommand.java, hoot-services/src/main/java/hoot/services/controllers/export/ExportParams.java
https://maxar.atlassian.net/browse/VGI-5064
Connected to this hoot-ui PR: https://github.com/ngageoint/hootenanny-ui/pull/2075
=> Filter OSM relations when exporting to non-OSM formats

translations/mgcp.js, translations/mgcp_rules.js
- https://maxar.atlassian.net/browse/VGI-5311
- https://maxar.atlassian.net/browse/VGI-5313
- https://maxar.atlassian.net/browse/VGI-5315
- https://maxar.atlassian.net/browse/VGI-5373
=> Mgcp translations
