ngageoint/hootenanny

Vagrantfile
This commit adds filemode settings so that
Hoot can write to the shared folders on an
OS X host.
Please let me know if you have any questions or deem any modification necessary - I will be happy to adjust the code.
=> Modifying Vagrantfile to work with OSX

hoot-js/src/main/cpp/hoot/js/schema/OsmSchemaJs.cpp, hoot-js/src/main/cpp/hoot/js/schema/OsmSchemaJs.h
1. refs #70 Mocha tests fail after schema changes - Now returned
undefined rather than an empty pointer.
=> Fix error in mocha tests.

hoot-js/src/main/cpp/hoot/js/JavaScriptTranslator.cpp, hoot-js/src/main/cpp/hoot/js/util/HootExceptionJs.cpp, plugins/translation_assistant.js
This pull request includes changes in translation assistant so that an error is thrown if no attributes can be translated (i.e. the translation file references doesn't match the attribute schema if the input source).
Hoot commands will now exit with an error status if the javascript translation raises an error.
=> There is no error message if a user tries to import a dataset using an invalid translation file

VAGRANT.md, Vagrantfile
Recreation of PR #33 against the develop branch.  Original PR description is as follows:
I recently switched my virtualization tools from VirtualBox to Parallels. In order to run Hoot on Parallels, I had to write a custom Vagrant provider specific to Parallels. I thought this might be useful to other Parallels users in the future. I've verified that this provider works by running vagrant up --provider=parallels. If Parallels is not installed, it should not make any difference in the provisioning process as it currently works.
This PR also contains a minor amount of documentation clean up, removing extraneous whitespace from the end of certain lines.
This might only be useful in my particular situation at the moment, so I would certainly understand if this is rejected from the main build …
=> Adding Parallels Provider

hoot-core-test/src/test/resources/cmd/quick/HelloWorld.sh, hoot-js/src/main/cpp/hoot/js/schema/TagMergerFactoryJs.cpp
1. refs #211 TagMergerFactory requires using Tag objects instead of {}
=> Simplify parameters in mergeTags with toCpp

configure.ac
1. refs #214 
@mattjdnv Can you look at this one?  This should catch the situation where someone has GDAL compiled with FGDB support and the FGDB library isn't there.
=> User ogrinfo to check for errors with format related dependent libraries

hoot-core/src/main/cpp/hoot/core/util/Log.cpp, hoot-core/src/main/cpp/hoot/core/util/LogLog4Cxx.cpp
1. refs #268 Fixed LogLog4Cxx log level for Verbose
Added Verbose to the Log4Cxx Info level.
=> Fixed LogLog4Cxx log level for Verbose

hoot-core/src/main/cpp/hoot/core/util/ElementConverter.cpp, hoot-core/src/main/cpp/hoot/core/util/ElementConverter.h, hoot-core/src/main/cpp/hoot/core/visitors/TranslationVisitor.cpp
@jasonsurratt The fix works but I'm not too happy with what we return from ElementConverter.cpp for Reviews and probably Collections as well.  Should a Review return something like "NoGeometry" instead of a "GEOS_GEOMETRYCOLLECTION" ?
=> Handle "Unknown Geometry" types during OSM ingest

hoot-core-test/src/test/resources/cmd/slow/ConflationStatsReportTest.sh
1. refs #346 Increase the size range for the csr.pdf
=> Increase size range for CSR report to 150KB-350KB

Makefile.old, conf/ConfigOptions.asciidoc, hoot-core/src/main/cpp/hoot/core/algorithms/string/WeightedWordDistance.cpp
Refs #317 
Updated Makefile to download the compressed words1.sqlite file to the /tmp folder and extract it to $HOOT_HOME/conf.  Also updated documentation to use the new location for the file.
=> Compress words1.sqlite

docs/user/Hootenanny-id.asciidoc
Refs #386 
Building documentation had three warnings.  Simple change to fix the warnings.
=> Updated the levels for "Conflation Examples" to remove warning

plugins/test/translation_assistant.js, plugins/translation_assistant.js
This effectively drops the feature from the translated output,
instead of throwing an error.
See https://github.com/ngageoint/hootenanny-ui/issues/205
=> TA should return null if no attributes could be translated to tags

hoot-core/src/main/cpp/hoot/core/util/ElementConverter.cpp, hoot-core/src/main/cpp/hoot/core/util/ElementConverter.h, hoot-core/src/main/cpp/hoot/core/visitors/CalculateAreaForStatsVisitor.cpp, hoot-core/src/main/cpp/hoot/core/visitors/TranslatedTagCountVisitor.cpp
Refs #418 
Refs ngageoint/hootenanny-ui#270
Added throwError parameter to ElementConverter::convertToGeometry functions so that statistics don't fail when certain unknown types of relations are processed.  This also allows for the function to fail in other circumstances that might require the previous behavior such as conflation of elements.
=> Conflation fails for clipped Port Au Prince data when stats are turned on

hoot-services/pom.xml.in
1. refs #435 Added quiet options to the pom.xml.in file
@bwitham This really cuts down the maven test output. Could you review and merge please.
E.g. Old version:
T E S T S
parallel='none', perCoreThreadCount=true, threadCount=2, useUnlimitedThreads=false
Running hoot.services.controllers.job.JobResourceTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.001 sec
Running hoot.services.controllers.wps.CustomScriptGetListProcessletTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.395 sec
Running hoot.services.controllers.wps.CustomScriptGetScriptProcessletTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.032 sec
Running hoot.services.controllers.wps.CustomScriptSaveProcessletTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, …
=> Added quiet options to the pom.xml.in file

Makefile.old, conf/ConfigOptions.asciidoc, conf/LocalHoot.json.in, hoot-core-test/src/test/cpp/hoot/core/io/ServicesDbReaderTest.cpp, hoot-core-test/src/test/cpp/hoot/core/io/ServicesDbTest.cpp, hoot-core-test/src/test/cpp/hoot/core/io/ServicesDbTestUtils.cpp, hoot-core-test/src/test/cpp/hoot/core/io/ServicesDbTestUtils.h
1. refs #464 - Read the DB test URLs straight from the DatabaseConfig.sh
rather than the convoluted makefile step we used before.
=> Remove the db test URLs from config

hoot-core-test/src/test/cpp/hoot/core/io/ObjectInputStreamTest.cpp, hoot-core/src/main/cpp/hoot/core/Factory.h, hoot-core/src/main/cpp/hoot/core/util/HootException.cpp, hoot-js/src/main/cpp/hoot/js/HelloWorld.cpp
ref #469 
No need to pass base class name twice!
=> Modify HOOT_FACTORY_REGISTER_BASE macro to take only one parameter (469)

Makefile.old
Modified Makefile.old to reduce the work done for 'archive' target. *.rf files were removed from the archive, and I was able to whittle the list of build items down to 'js-make' and 'services-build' and 'docs'. 
This kicks the training of the rf files down the road (to the rpm build), and saves us building the hoot binary twice (in theory).
ref #472
=> Minimize work for Makefile.old 'archive' target

scripts/mvn-build
refs #472 
Removed liquibase from the services documentation creation script
Resolves issue we were seeing where a parallel make caused a race condition
=> Updated services doc creation to ignore the liquibase commands

hoot-core/src/main/cpp/hoot/core/io/HootApiDb.cpp, hoot-core/src/main/cpp/hoot/core/io/HootApiDb.h, test-files/cmd/slow/ServiceExportRenderDbTest.sh
Now when you call HootApiDb::DeleteMap(long mapId), the associated _renderdb will also be deleted.
The tricky thing here was that Postgres won't let you DROP DATABASE within a transaction, and the test suite does a lot of that sort of thing. So a mechanism was added to allow a list of post-transaction tasks, that will be executed after a transaction, if the transaction commit was successful.
--quick test looked good.
--slow test looked good.
Conflating two datasets (through the UI) on my local VM, then deleteing the conflated dataset showed the associated _renderdb was indeed removed.
ref issue #500
=> Add render db drop to HootApiDb::deleteMap(long)

hoot-core-test/src/test/cpp/hoot/core/conflate/point/PlacesPoiMatchTest.cpp, hoot-core/src/main/cpp/hoot/core/conflate/MatchCreator.h, hoot-core/src/main/cpp/hoot/core/conflate/highway/HighwayMatchCreator.cpp, hoot-core/src/main/cpp/hoot/core/conflate/point/CustomPoiMatchCreator.cpp, hoot-core/src/main/cpp/hoot/core/conflate/point/PlacesPoiMatchCreator.cpp, hoot-core/src/main/cpp/hoot/core/conflate/polygon/BuildingMatchCreator.cpp, hoot-core/src/main/cpp/hoot/core/ops/CalculateStatsOp.cpp, hoot-core/src/main/cpp/hoot/core/ops/CalculateStatsOp.h, hoot-js/src/main/cpp/hoot/js/conflate/js/ScriptMatchCreator.cpp, hoot-rnd/src/main/cpp/hoot/rnd/conflate/poi-polygon/PoiPolygonMatchCreator.cpp, rules/LinearWaterway.js, rules/PoiGeneric.js
Modified CalcStatsOp so that it doesn't need to be changed in the future if/when new feature types are added (ref issue #487 ).
Added a "baseFeatureType" to the MatchCreator base class - the idea being that if/when new MatchCreators are written, their virtual implementation of getAllCreators (which in turn creates a Description) will associate the new MatchCreator with the type of match (POI, Highway, Waterway, etc.) it creates.
"baseFeatureType" was also added to the ScriptMatchCreator, to pull the feature types out of runtime, script-based match creators.
CalcStatsOp now simply builds a list of feature types to gather stats for, based upon the new MatchCreator::BaseFeatureType enumeration, collects stats for the types, and then loops through to generate the stats report.
=> Modified CalcStatsOp so that it doesn't need to be modified for new feature types

Makefile.old
refs #535 
Sometimes during a failed or crashed build there is a message of a `corrupt .o file` that requires a `ccache -C` command to clear it
Steps to verify:
* `make` hoot
* check ccache stats `ccache -s` (important stats are `files in cache` and `cache size`)
```
cache directory                     /home/user/.ccache
cache hit (direct)                  2466
cache hit (preprocessed)            1264
cache miss                          9121
compile failed                         2
files in cache                      1624
cache size                         820.9 Mbytes
max cache size                       1.0 Gbytes
```
* clear cache `make clean-all`
* check ccache stats again to verify that the cache is empty (`files in cache` and `cache size` are 0)
```
cache directory …
```
=> Added clean-ccache to the clean-all target to clear ccache

scripts/TestConfigure.sh
1. refs #582 Added debug output to configure test
Adding output of the configuration names to the TestConfigure script so we can find which test fails.
@jasonsurratt Can you have a quick look at this and merge please.
=> Added debug output to configure test

test-files/cmd/slow/ApplyRubberSheetCmdTest.sh, test-files/cmd/slow/ApplyRubberSheetCmdTest.sh.stdout
Comment out compare of .rs files in ApplyRubberSheetCmdTest. They seem to be slightly different on CentOS... but if we ignore the differences, and just compare the rubber-sheeted osm file at the end, it turns out OK. Also turn down the volume on output logging.
ref issue #726
=> Fix ApplyRubberSheetCmdTest on CentOS rpms build

conf/DatabaseConfig.sh.orig, hoot-core-test/src/test/cpp/hoot/core/io/ServicesDbTestUtils.cpp, hoot-services/src/main/java/hoot/services/nativeInterfaces/ProcessStreamInterface.java, hoot-services/src/main/resources/conf/hoot-services.conf.in, hoot-services/src/test/java/hoot/services/nativeInterfaces/ProcessStreamInterfaceTest.java, scripts/CleanOsmApiDB.sh, scripts/SetupOsmApiDB.sh, test-files/cmd/glacial/ServiceOsmApiDbConflateTest.sh, test-files/cmd/glacial/ServiceOsmApiDbTest.sh, test-files/cmd/slow/ServiceApplyChangesetCmdTest.sh, test-files/cmd/slow/ServiceDeriveChangesetCmdTest.sh
@mattjdnv Can you do this one?  All that's done here is separating the credentials between the hoot api and osm api db's, since they won't necessarily be the same in a production environment.  thanks.
=> 720 - completely separate hoot api and osm api db credentials

hoot-core/src/main/cpp/hoot/core/algorithms/ProbabilityOfMatch.cpp, hoot-core/src/main/cpp/hoot/core/algorithms/ProbabilityOfMatch.h
1. refs #815 Error when running HGIS Prepare for Validation and Filter
non-HGIS POIs
* Though it may not appear to be related the ProbabilityOfMatch default
instance was being instantiated during the initialization which was
calling into Settings. Since Settings weren't properly configured
yet this caused an error. Now the ProbabilityOfMatch default instance
isn't constructed until it is needed.
=> Fix initialization order error.

tgs/src/main/cpp/tgs/RandomForest/RandomForest.cpp, tgs/src/main/cpp/tgs/RandomForest/RandomTree.h
refs #948 
Updated RandomForest to reset the tree id for each new forest (i.e. all tree ids are 0-39 instead of 0-39 or 40-79 depending on the command used)
Ensure that this passes the `model-training.child/jakarta-buildings.child` test
=> Fix '--build-model' to produce output the same as '--build-rf'

test-files/ui/features/advanced_options.feature, test-files/ui/features/clip.feature, test-files/ui/features/conflate_with_stats.feature, test-files/ui/features/manually_resolve_reviews.feature, test-files/ui/features/osm_tds_switcher.feature, test-files/ui/features/resolve_all_reviews.feature, test-files/ui/features/review_bookmarks.feature, test-files/ui/features/z_conflate_export_osm_api_db.feature
* Add out of spec and preset search steps to cuke test
* Add a step to troubleshoot a cuke test failure in nightly job:
When adding a dataset the previous method can't be used becuase it
matches on the dataset name in the available dataset list
=> Add stability and improvements to schema switcher cuke test

conf/ConfigOptions.asciidoc, hoot-core/src/main/cpp/hoot/core/io/OsmWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmWriter.h
1. refs #990 
Very simple :-)
@mschicker Can you have a look at this and merge please.
@brianhatchl FYI.  We should pull this into #916
=> Added an option to remove OSM XML formatting.

tgs/tgs.pro
1. refs #1008 tgs.pro contains a test outside the cppunit section
=> Fix bad test file placement in tgs.pro

hoot-core/src/main/cpp/hoot/core/io/OsmReader.cpp
Refs #1025 
Adding -f option to make unzipping more robust.  Should fix a current Jenkins test failure and will make test more robust in the future.
=> Add -f option to unzipping of files to make more robust.

test-files/ui/features/basemap_ingest.feature, test-files/ui/features/check_layer_visbility.feature, test-files/ui/features/step_definitions/custom_steps.rb
My first cucumber test :smile:
I added a new test to check for layer visibility in two scenarios. Scenario one adds two layers, ensures the layer checkboxes are checked, and ensures that both layers are selectable on the map. Scenario two unchecks one box, makes sure that layer is not visible on the map, then does the same for the second layer. 
I also rewrote one of the steps (click background settings button) so it made more sense (background settings instead of map background button) and fixed `basemap_ingest.feature` (the only other test that step was used in) accordingly.
=> #698 - add cuke test for checking layer visibility

scripts/jenkins/TestInitialNightly.sh, test-files/ui/features/display_inset.feature, test-files/ui/features/step_definitions/custom_steps.rb, test-files/ui/features/support/capybara.rb, test-files/ui/features/support/env.rb, test-files/ui/features/support/mouse_click.rb
This test should run through the following:
Scenario 1: Toggle "/" turns inset map on, toggle "/" again turns it off
Scenario 2: Toggle inset map on/off by checking "Minimap" checkbox on/off
Scenario 3: Resizing the sidebar won't affect inset map visibility (on/off)
Had trouble coming up with a solution for testing that the inset map was not visible since it remains in the DOM even when it's not visible, but this seems to work:
<pre>
Then(/^I should not see the "([^"]*)" on the page$/) do |input| 
el = page.should have_no_css(input, :visible => true)
end
</pre>
=> #732: add cucumber test for minimap visibility

conf/conflateAdvOps.json
related to ngageoint/hootenanny-ui#765
=> Element_cache_size now 'int' type, not 'long'

test-files/ui/features/advanced_options.feature, test-files/ui/features/advanced_options_invalid_input.feature, test-files/ui/features/bulk_import_multidelete.feature, test-files/ui/features/clip.feature, test-files/ui/features/manage_tab.feature, test-files/ui/features/osm_tds_switcher.feature, test-files/ui/features/step_definitions/custom_steps.rb
From ngageoint/hootenanny-ui#723
I created a separate feature test from `advanced_options.feature` since that one is super freakin long and can probably be refactored using scenario outlines + example tables similar to this one (and yes I volunteer myself to refactor it). When that test gets refactored these two can be combined. That's what I'm thinking.
=> Cucumber test to check for invalid inputs in advanced options

hoot-core/src/main/cpp/hoot/core/algorithms/linearreference/WayString.cpp
Ref issue #1136 
This pull uses the appropriate macro for printing trace statements, removes the warnings from the tests.
=> Use appropriate macro for printing trace statements (LOG_VART)

test-files/ui/features/manage_tab.feature
This should fix the problem where this test was failing every other time at the context click to `Delete (2)` features (see https://github.com/ngageoint/hootenanny/pull/1129). Currently has a 100% pass rate for me locally (5/5).
=> add step to fix intermittent failures for manage_tab.feature test

hoot-core-test/src/test/cpp/hoot/core/io/HootApiDbTest.cpp, hoot-core/src/main/cpp/hoot/core/io/ApiDb.cpp
refs #1195 
Updated ApiDb::unescapeTags() to do a better job at reading tags that have unescaped quotes in them, also added a test to ensure it is working correctly.  Instead of using quotes to split the tags, use `=>` and un-quoted commas as delimiters (in that order).
=> OsmApiDbReader not handling nested quotes properly

test-files/ui/features/review_layer_no_inputs_loaded.feature
via ngageoint/hootenanny-ui#716, this test will:
1. Upload 2 datasets (not used in any other cuke test)
2. Conflate the 2 datasets
3. Remove the conflated layer from the map without resolving reviews
4. Delete the 2 datasets
5. Add the conflated dataset to the map
6. Ensure remaining reviews are still asked to be resolved
7. Resolve reviews
=> New Cuke Test to Add Layer With Remaining Reviews and No Inputs

plugins/TranslationServer.js, plugins/test/TranslationServer.js
Updates TranslationServer.js to allow for all geometry types in schema? request.
Related to ngageoint/hootenanny-ui#758
=> Allow for all geom types in schema request

hoot-core-test/src/test/cpp/hoot/core/io/ServiceHootApiDbTest.cpp, hoot-core-test/src/test/cpp/hoot/core/io/ServiceHootApiDbWriterTest.cpp, hoot-core-test/src/test/cpp/hoot/core/io/ServiceOsmApiDbSqlChangesetWriterTest.cpp, hoot-core/src/main/cpp/hoot/core/io/ApiDb.cpp, hoot-core/src/main/cpp/hoot/core/io/ApiDb.h, hoot-core/src/main/cpp/hoot/core/io/HootApiDb.cpp, hoot-core/src/main/cpp/hoot/core/io/HootApiDb.h, hoot-core/src/main/cpp/hoot/core/io/OsmApiDb.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiDb.h, hoot-core/src/main/cpp/hoot/core/io/OsmApiDbSqlChangesetWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmChangesetSqlFileWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/db/PostgresqlDumpfileWriter.cpp
refs #1238 
Consolidated all table names referenced in code into ApiDb functions.
Changed function names to distinguish between tables like nodes and current_nodes.
Added in other tables not listed previous (non-current)
Put SQL commands in caps for consistency.
=> HootApiDb and OsmApiDb table name duplication

hoot-rnd/src/main/cpp/hoot/rnd/conflate/network/ConflictsNetworkMatcher.cpp, test-files/cmd/slow/NetworkConflateCmdTest.sh
Enabled and fixed the NetworkConflateCmdTest by checking the iterators before incrementing it2.
=> Network conflation crashes on empty files

docs/commands/derive-changeset.asciidoc, hoot-core-test/hoot-core-test.pro, hoot-core-test/src/test/cpp/hoot/core/io/OsmChangesetTestProvider.h, hoot-core-test/src/test/cpp/hoot/core/io/OsmChangesetXmlFileWriterTest.cpp, hoot-core-test/src/test/cpp/hoot/core/io/ServiceOsmApiDbChangesetSqlFileWriterTest.cpp, hoot-core-test/src/test/cpp/hoot/core/io/TestOsmChangesetProvider.h, hoot-core/src/main/cpp/hoot/core/io/OsmChangesetSqlFileWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmChangesetSqlFileWriter.h, hoot-core/src/main/cpp/hoot/core/io/OsmChangesetXmlFileWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmChangesetXmlFileWriter.h, test-files/io/OsmChangesetXmlFileWriterTest/changeset-001.split.osc, test-files/io/OsmChangesetXmlFileWriterTest/changeset.osc, test-files/io/OsmChangesetXmlFileWriterTest/changeset.split.osc, test-files/io/ServiceOsmApiDbChangesetSqlFileWriterTest/changeset.osc.sql, test-files/io/ServiceOsmApiDbChangesetSqlFileWriterTest/changeset.split.osc.sql
Refs #1100 
Split changesets that are more than `changeset.max.size` into multiple files.  Updated documentation and unit tests.  The investigation into this resulted in the follow-on work of #1320
=> OsmChangesetXmlFileWriter doesn't honor changeset.max.size

test-files/ui/features/review_bookmarks.feature
>stale element reference: element is not attached to the page document
(Session info: chrome=49.0.2623.87)
(Driver info: chromedriver=2.14.313457 (3d645c400edf2e2c500566c9aa096063e707c9cf),platform=Linux 3.13.0-107-generic x86_64) (Selenium::WebDriver::Error::StaleElementReferenceError)
features/review_bookmarks.feature:85:in `And I should see "Cucumber Bookmark 2" bookmark first and "Cucumber Bookmark 1" bookmark second'
=> attempt to fix cuke test failing on jenkins

hoot-core-test/src/test/cpp/hoot/core/io/ServiceHootApiDbTest.cpp, hoot-core/src/main/cpp/hoot/core/io/ApiDb.cpp
I found that there were tags in the data contained text that wasn't parsing correctly.  So I updated the `ApiDb::unescapeTags` function to do a better job of parsing tags that contain special characters such as `"` and `=>` that have special meaning in the tags string.
=> Fix import OSM partially failed

hoot-core/src/main/cpp/hoot/core/conflate/MarkForReviewMergerCreator.cpp, hoot-core/src/main/cpp/hoot/core/conflate/MarkForReviewMergerCreator.h, hoot-core/src/main/cpp/hoot/core/conflate/UnifyingConflator.cpp, hoot-core/src/main/cpp/hoot/core/conflate/highway/HighwayMatchCreator.cpp, hoot-core/src/main/cpp/hoot/core/conflate/highway/HighwayRfClassifier.cpp, hoot-core/src/main/cpp/hoot/core/conflate/highway/HighwaySnapMergerCreator.cpp, hoot-core/src/main/cpp/hoot/core/conflate/poi-polygon/PoiPolygonMatchCreator.cpp, hoot-core/src/main/cpp/hoot/core/conflate/poi-polygon/PoiPolygonMergerCreator.cpp, hoot-core/src/main/cpp/hoot/core/conflate/polygon/BuildingMatch.cpp, hoot-core/src/main/cpp/hoot/core/conflate/polygon/BuildingMatchCreator.cpp, hoot-core/src/main/cpp/hoot/core/conflate/polygon/BuildingMergerCreator.cpp, hoot-hadoop/src/main/cpp/hoot/hadoop/conflate/ConflateReducer.cpp, hoot-hadoop/src/main/cpp/hoot/hadoop/fourpass/TileOpReducer.cpp, hoot-js/src/main/cpp/hoot/js/PluginContext.cpp, hoot-js/src/main/cpp/hoot/js/conflate/js/ScriptMatchCreator.cpp, hoot-js/src/main/cpp/hoot/js/conflate/js/ScriptMatchCreator.h, hoot-js/src/main/cpp/hoot/js/conflate/js/ScriptMerger.cpp, hoot-js/src/main/cpp/hoot/js/conflate/js/ScriptMergerCreator.cpp, hoot-rnd/src/main/cpp/hoot/rnd/conflate/network/NetworkMergerCreator.cpp, rules/Area.js, rules/LineStringGeneric.js, rules/LineStringGenericTest.js, rules/LinearWaterway.js, rules/PoiGeneric.js, rules/PolygonBuilding.js, rules/PolygonBuildingTest.js, rules/PolygonGeneric.js, rules/lib/HootLib.js, test-files/cmd/slow/PoiPolygonConflateCombinedTest.sh, test-files/cmd/slow/PoiPolygonConflateCombinedTest.sh.stdout
1. refs #1388 - Change generic script init function to an optional calculateSearchRadius function, since thats all it was being used for anyway
2. refs #1388 - Cache the search radius calculated by generic scripts and set it on match candidate checkers if they are reset during merging
=> fix for #1388 - unnecessary search radius calculations during conflation

hoot-services/src/main/java/hoot/services/controllers/osm/MapResource.java
This change is useful because now the ui code doesn't have to lookup what mapid each tile xml response belongs to and can just parse it out instead.
=> add mapid attribute to osm xml responses

hoot-core/src/main/cpp/hoot/core/algorithms/optimizer/IntegerProgrammingSolver.h
Updated `IntegerProgrammingSolver` to eliminate race condition that causes unify to fail on regressions tests intermittently.  Turn on the `binarize` option in the `glp_iocp` options class to accomplish this.  In testing I was able to reproduce the failure consistently, and adding this option caused the calculations to complete before accessing the vector data.
=> glpk throws assert intermittently during nightly regression tests

VagrantProvision.sh
Esri repo changed structure so our vagrant builds that download the source zip aren't functioning correctly. This change was part of the v1.5 release. So I'm going to upgrade from v1.4 to v1.5 while I'm at it.
=> Fix FGDB build

VagrantProvision.sh
Removed `w3m` from line 69 of `VagrantProvision.sh` after testing the effects of `make archive` on provisioning with and without `w3m`.
=> Remove w3m from provisioning

Makefile.old, VagrantProvision.sh
Updated instances of 'which mocha' to 'hash mocha' to remove the warning for both CentOS and Ubuntu builds
=> Remove build warnings 'no mocha'

hoot-core/src/main/cpp/hoot/core/io/OgrReader.cpp, hoot-core/src/main/cpp/hoot/core/io/OgrUtilities.cpp, hoot-core/src/main/cpp/hoot/core/io/OgrUtilities.h, hoot-core/src/main/cpp/hoot/core/io/OgrWriter.cpp
Updated OgrReader/Writer to use the Open FGDB driver for reading and ESRI FGDB driver for writing for performance reasons.
=> Use GDAL FGDB driver for read operations

hoot-core-test/src/test/cpp/hoot/core/test/ConflateCaseTest.cpp, hoot-rnd/src/main/cpp/hoot/rnd/conflate/network/EdgeMatchSetFinder.cpp
Ref #1566 
```
test-files/cases/hoot-rnd/network/conflicts/highway-025
```
Was failing when run with the --trace switch (maps do not match)
I tracked this down to invocation of a non-const function within a LOG_VART(...) statement. The function call was modifying the map, and producing different output, only when run in TRACE mode!
--
Fix error reporting in ConflateCaseTest.cpp (it was ambiguous before)
Comment out a few trace statements that were causing a test failure (and added appropriate warnings)
=> Fix hoot network conflicts test highway-025 when running with trace logging

hoot-hadoop/src/main/cpp/hoot/hadoop/OsmMapMapper.cpp, hoot-hadoop/src/main/cpp/hoot/hadoop/OsmMapReducer.cpp
Refs #1586 
Add missing includes when '--without-stxxl' is specified, side effect from previous issues of removing namespaces in headers and rearranging includes.
=> Fix hoot_ubuntu1404_nightly_develop_configure

hoot-core/src/main/cpp/hoot/core/conflate/DuplicateWayRemover.cpp
Refs #1518 
Fix the use of Relation::replaceElements for CentOS builds
=> DuplicateWayRemover - Merge tags only in overlapping sections

hoot-core-test/src/test/cpp/hoot/core/ops/FindIntersectionsOpTest.cpp, hoot-core-test/src/test/cpp/hoot/core/ops/ReprojectToPlanarOpTest.cpp, hoot-core-test/src/test/cpp/hoot/core/ops/WaySplitterOpTest.cpp, hoot-rnd/src/test/cpp/hoot/rnd/conflate/network/EdgeMatchSetFinderTest.cpp, hoot-rnd/src/test/cpp/hoot/rnd/conflate/network/IterativeNetworkMatcherTest.cpp, hoot-rnd/src/test/cpp/hoot/rnd/conflate/network/SingleSidedNetworkMatcherTest.cpp, hoot-rnd/src/test/cpp/hoot/rnd/conflate/network/VagabondNetworkMatcherTest.cpp
Refs #1610 
In certain circumstances that we weren't testing for some of the unit tests were failing.  The fixes were simple, just reset the environment before some of the tests and create the `tmp` directory if it doesn't exist for the others.
=> EdgeMatchSetFinderTest tests fail on clean Ubuntu VM in quick tests

VagrantProvision.sh, VagrantProvisionCentOS7.sh, VagrantProvisionUbuntu1604.sh, hoot-core-test/src/test/cpp/hoot/core/ops/FindIntersectionsOpTest.cpp, hoot-core-test/src/test/cpp/hoot/core/ops/ReprojectToPlanarOpTest.cpp, hoot-core-test/src/test/cpp/hoot/core/ops/WaySplitterOpTest.cpp, hoot-rnd/src/test/cpp/hoot/rnd/conflate/network/EdgeMatchSetFinderTest.cpp, hoot-rnd/src/test/cpp/hoot/rnd/conflate/network/IterativeNetworkMatcherTest.cpp, hoot-rnd/src/test/cpp/hoot/rnd/conflate/network/SingleSidedNetworkMatcherTest.cpp, hoot-rnd/src/test/cpp/hoot/rnd/conflate/network/VagabondNetworkMatcherTest.cpp, scripts/tomcat/tomcat8/ubuntu/tomcat8_install.sh, scripts/tomcat/tomcat8/ubuntu/tomcat8_uninstall.sh, test-files/ui/features/support/env.rb
Refs #1605 
While helping a user install Hootenanny on a bare metal Ubuntu 14.04 it suggested:
> f you want to install it without a VM, I would suggest the using the commands from the VagrantProvision.sh script.
> https://github.com/ngageoint/hootenanny/blob/master/VagrantProvision.sh
> 
> A simple search for the vagrant user and group and replace with your user/group and then executing that script will setup your Ubuntu machine to be able to build and run Hootenanny.
Which is all true but a pain.  So I changed the Vagrant provision scripts to use the current user as the user to install it as.  This works great with both base boxes as one logs in as `vagrant` and the other `ubuntu` so the Vagrant provisioning works great.  It also works on a VM where I installed a clean copy of Ubuntu …
=> Hoot is "hard to install"

.gitignore, Makefile.old, conf/models/BuildingModel.sha1sum, conf/models/HighwayModel.sha1sum, conf/models/PoiModel.sha1sum
Refs #232 
This is some of the code from an old issue to speed up the generation of the random forests.  The `.rf` files are now checked in and there is code in the `Makefile` to check if the files are out of sync.  If they are, then they are rebuilt.  If not then they are skipped.  For 99.9% of all builds they should be in sync.  The only time they shouldn't is when we tune the models.
=> RF File Hashes

Vagrantfile
Refs #1686 
Add aws vagrant provider.  Run with the following:
```
vagrant up --provider aws
```
Machine that makes the vagrant call needs to have the appropriate environment variables set.
=> Add aws vagrant provider

Vagrantfile
I found with 16GBs disk, the aws image was failing under certain test conditions.  Increasing to 32 GBs.
=> Increase AWS provider diskspace

VagrantProvisionCentOS7.sh
This PR streamlines the install process on CentOS 7 by no longer installing every TeX package (`tex*`), and replaced with what is necessary to successfully run `make docs`:
* `texlive`
* `texlive-collection-fontsrecommended`
* `texlive-collection-langcyrillic`
* `tex-fonts-hebrew`
This prevents 400+ unnecessary packages from being installed on CentOS 7.
=> Tame TeX Packages

VagrantProvision.sh, VagrantProvisionCentOS7.sh, scripts/tomcat/tomcat8/centos7/etc/systemd/system/tomcat8.service
The wonderful folks at Oracle pulled all the public downloads for the 8u144 JDK.  This PR switches us to the 8u152 JDK along with some minor tweaks to provision scripts.
Note: this is a temporary solution.  Oracle will pull this release again in January 2018 and will pull all Java 8 downloads from public distribution in September 2018.
=> Update Oracle JDK to 8u152

VagrantProvision.sh, VagrantProvisionUbuntu1604.sh
This PR adds in packages that were implicitly installed by `apt-get` only because they're recommended by the maintainer, in particular:
* `libqtwebkit-dev` (required to build `capybara-webkit` gem)
* `postgresql-contrib-9.5` (required for the hstore extension)
* `docbook-xml` and `dblatex` (used for docs)
This resolves the issue that if `apt-get` is configured to ignore recommended packages, provisioning will fail due to unmet dependencies.
=> Add Implicit Dependencies

node-export-server/server.js
=> node_export_server: bbox not valid with osm file input source

scripts/jenkins/Jenkinsfile
This PR addresses #1872 by parameterizing the Vagrant box as the `Box` parameter in the `Jenkinsfile` and replacing the occurrences of the box in Vagrant commands with `${params.Box}`.
A fix was also added in 8df4b53 to the core test stage to consolidate the environment setup in a single SSH command as that doesn't persist across separate SSH sessions (multiple `vagrant ssh` commands).
=> Parameterize Vagrant Box in Jenkinsfile

conf/schema/address.json
Refs #1885 
Fixing `abstract_address` to include `way`, ways can have the `addr:city` tag
=> Hootenanny converting linear features to poly

docker/centos7.2/Dockerfile, docker/centos7.4/Dockerfile
This PR fixes #1900 by adding `ENV` directives that properly specify the locale in the CentOS 7 `Dockerfile`s.  This eliminates the need for the `localedef` command, which was previously used to ensure the PostgreSQL database was initialized properly using the UTF-8 for its database encoding.
I built the CentOS 7.4 image using this branch:
```
docker build --rm -t local/centos7.4vagrant ./docker/centos7.4/
```
I brought up the CentOS 7.4 image, provisioning only with `VagrantProvisionCentOS7.sh`:
```
vagrant up dockercentos7.4 --provider docker --provision-with hoot
```
The provision script worked successfully; I finally confirmed PostgreSQL was using the right encoding:
```
vagrant ssh dockercentos7.4 -c 'sudo -u postgres -g postgres psql -c "SELECT datname,datcollate,datctype FROM …
```
=> Fix Locale for CentOS Docker Images

VagrantProvision.sh
Removes the trailing space from `jdk.md5`.
=> Fix MD5 Verification of JDK 

scripts/jenkins/Jenkinsfile
Conditional based on time when nightly jobs are triggered.  It's a workaround until the BUILD_CAUSE can be easily checked.
=> "Only run configuration tests during nightly job runs"

VagrantProvision.sh, VagrantProvisionCentOS7.sh, VagrantProvisionUbuntu1604.sh, VagrantProvisionVars.sh, scripts/chrome/chrome-install.sh, scripts/chrome/driver-install.sh
This PR resolves #1907 by locking the ChromeDriver version to 2.33 instead of attempting to download the latest version.  In addition:
* The installation of Chrome and ChromeDriver have been unified into common scripts: `scripts/chrome/{chrome,driver}-install.sh`. 
* Embed the version of ChromeDriver in the name of the downloaded file and check the output of `chromedriver --version` to ensure that proper version is downloaded and installed correctly.
* Use TLS when downloading ChromeDriver.
=> Consistent ChromeDriver Version

hoot-test/src/main/cpp/hoot/test/ScriptTestSuite.cpp, hoot-test/src/main/cpp/hoot/test/ScriptTestSuite.h, hoot-test/src/main/cpp/hoot/test/main.cpp
Refs #1955 
Updating script tests to hide 'Disable' message when run in parallel in all slave processes while leaving it in the master process to declutter the output.
=> Unit Test output without Hadoop in parallel clutter

hoot-core/hoot-core.pro, hoot-js/hoot-js.pro, hoot-rnd/hoot-rnd.pro, scripts/jenkins/Jenkinsfile, scripts/tomcat/tomcat8/centos7/tomcat8_install.sh, tbs/tbs.pro, test-files/ui/features/hide_map_features.feature, tgs/tgs.pro
Refs #1960 
Updated LD_LIBRARY_PATH for Tomcat, updated project dependencies so that only `HootHadoop` has `libhdfs` as a dependency, and fixed broken UI test.
=> Fix project dependencies and UI tests on CentOS 7

hoot-core/src/main/cpp/hoot/core/conflate/polygon/MultiPolygonCreator.cpp, hoot-core/src/main/cpp/hoot/core/io/OgrWriter.cpp
Refs #1988
Don't fail on unknown relation types and check NULL pointer in MultiPolygonCreator
=> Hoot crashes on NULL shared_ptr in MultiPolygonCreator

plugins/ElementMergeServer.js, plugins/TranslationServer.js, plugins/schema2josmpreset.js, plugins/test/TranslationServer.js, plugins/test/pass_thru_unknown.js
- Adds a translation server endpoint to get valid fcodes by translation and geometry.
- Adds a placeholder node script for turning translation schemas into a JOSM preset xml file.
- Adds a hoot init performance fix for ElementMergeServer.
- Adds additional mocha test for unknown tags behavior.
=> Josm preset support

hoot-core-test/src/test/cpp/hoot/core/test/ConflateCaseTestSuite.cpp, hoot-core-test/src/test/cpp/hoot/core/test/ConflateCaseTestSuite.h, hoot-rnd/src/test/cpp/hoot/rnd/conflate/opt/AbstractRegressionTestFitnessFunction.cpp, hoot-rnd/src/test/cpp/hoot/rnd/conflate/opt/CaseTestFitnessFunction.cpp, hoot-rnd/src/test/cpp/hoot/rnd/conflate/opt/RegressionTestSuite.cpp, hoot-test/src/main/cpp/hoot/test/main.cpp
Fixed --exclude duplication issue, Conflate case ignore warning in parallel, and minor cleanup
=> HootTest '--exclude' multiplies the test count and doesn't exclude correctly

test-files/cmd/slow/o2sTranslationTest.sh, test-files/o2s_ggdm.osm, test-files/o2s_tds40.osm
Refs #2021 
Fixed ordering problem and added GGDM and TDS 4.0 expected output test files that include the `source` tag.
=> CentOS 6.7 o2sTranslationTest failure

VagrantProvision.sh, VagrantProvisionUbuntu1604.sh, scripts/tomcat/tomcat8/centos7/tomcat8_install.sh
As it says in the title, fix quoting of `~/hoot` so that it's possible to provision on Ubuntu again.
=> Fix Ubuntu Provisioning Errors

hoot-js/src/main/cpp/hoot/js/PluginContext.cpp
Prior to this change, running the MergePoisTest.js node script (in node) coughs up this error
FATAL ERROR: v8::Context::Exit() Cannot exit non-entered context
1: node::Abort() [/usr/bin/node]
2: 0x1216dfc [/usr/bin/node]
3: v8::Utils::ReportApiFailure(char const*, char const*) [/usr/bin/node]
4: v8::Context::Exit() [/usr/bin/node]
5: node::Start(uv_loop_s*, int, char const* const*, int, char const* const*) [/usr/bin/node]
6: node::Start(int, char**) [/usr/bin/node]
7: __libc_start_main [/lib64/libc.so.6]
8: 0x8ad63a [/usr/bin/node]
Which I attribute to us not being careful with contexts in the PluginContext class. Adding a context exit to the PluginContext destructor allows the code exec ion to get much further along (I think), to the point where the hoot node object is destroyed, and the …
=> Add context exit to PluginContext destructor

hoot-core/src/main/cpp/hoot/core/io/OsmGeoJsonReader.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmGeoJsonReader.h
refs: #2040 
Split the _parseGeojson() function and created a _parseGeoJsonFeature() function so the we can handle files with one feature in them and files with multiple features.
Note: The diff looks funky but the code is OK.
=> Tweaked the GeoJSON parser to handle single features

VagrantProvisionCentOS7.sh, Vagrantfile, scripts/jenkins/Jenkinsfile
This adds preprovisioned hootenannt vagrant box support to the vagrantfile.  Updates to provisioning script to allow for being run twice (added checks to see if stuff was already installed).  Defaulted pipeline to use preprovisioned box, but one can rerun job and change parameter and use CentOS minimal again if they want.
=> Support for preprovisioned hootenanny vagrant box

hoot-core/src/main/cpp/hoot/core/visitors/ImplicitTaggerBase.cpp
Fixed mod operator to divide so that there isn't a divide by zero error.
=> Fix Floating Point Exception in quick tests

LocalConfig.pri.orig
=> Enable the gold linker

VagrantProvisionVars.sh
Fixes #2093.  Necessary to make provisioning work on Ubuntu again, found this trying to [recreate another issue on Ubuntu](https://github.com/ngageoint/hootenanny/issues/2023#issuecomment-360216982) similar to #2023.
=> Update Oracle JDK to 8u161 [Ubuntu-only]

node-export-server/config.json, node-export-server/package.json, node-export-server/server.js
`http://localhost:8101/export/API/OSM/Shapefile?bbox=-77.44911,37.53927,-77.44587,37.54333&overrideTags=true` will return:
```
wget -q  -O /home/vagrant/hoot/node-export-server/export_6e1e9550-f26b-11e7-aef6-0da8a3f2c6dd.osm http://192.168.33.12:3000/api/0.6/map?bbox=-77.44911,37.53927,-77.44587,37.54333 && hoot osm2ogr -D writer.include.debug.tags=true -D tags.override={"attribution":"","security:resource_owner":"","security:classification":"","security:dissemination:control:ic":"","security:dissemination:control:non_ic":"","security:releasability":"","source:":"","source:non_spatial_source:type":"","source:copywrite":""} translations/RenderDb.js "/home/vagrant/hoot/node-export-server/export_6e1e9550-f26b-11e7-aef6-0da8a3f2c6dd.osm" …
```
=> Add tag overrides as hoot export option

hoot-core/src/main/cpp/hoot/core/cmd/DeleteMapCmd.cpp, hoot-core/src/main/cpp/hoot/core/io/HootApiDb.cpp, hoot-core/src/main/cpp/hoot/core/io/HootApiDb.h
Refs #2134 
Updated the HootApiDb class to delete all sequences associated with a map on delete.
=> hoot delete-map leaves changesets_XXX_id_seq orphaned in db

hoot-core/src/main/cpp/hoot/core/io/OsmXmlReader.cpp
Refs #2153
Removing 'assert' for empty elements because element is empty when "action='delete'" is set as an attribute.
=> test-files/DcOsmRoads.osm fails to load in Debug

hoot-core-test/src/test/cpp/hoot/core/io/ServiceHootApiDbBulkInserterTest.cpp, hoot-core/src/main/cpp/hoot/core/io/HootApiDb.cpp, hoot-core/src/main/cpp/hoot/core/io/HootApiDb.h, hoot-core/src/main/cpp/hoot/core/io/HootApiDbBulkInserter.cpp, hoot-core/src/main/cpp/hoot/core/io/HootApiDbBulkInserter.h, hoot-core/src/main/cpp/hoot/core/io/HootApiDbSqlStatementFormatter.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiDbBulkInserter.cpp, test-files/io/ServiceHootApiDbBulkInserterTest/psql-offline.sql
* fixes issue parsing tag with '\\' in value in GeoFabrik Delaware data
* fixes issue where creating indexes during the Hoot API db bulk write was throwing SQL exceptions
* resulting associated issues created: #2216, #2217
=> Hoot API Database bulk writing fixes

Makefile.old
The file lib/HootJs.node gets cleared out by 'make clean' and causes 'make clean && make test' to fail in the Mocha tests.  So, make sure it gets rebuilt before running the plugins-test targer.
=> Fix plugins-test dependency issue

hoot-core/src/main/cpp/hoot/core/cmd/BaseCalculateTilesCmd.cpp
Fixes #2224 by using `$HOOT_HOME/tmp` for the temporary OSM file when converting to GeoJSON.
=> Use temporary directory for OSM file when converting to GeoJSON.

Makefile.old
Fixes #2240 by having the `archive` target depend on `services-docs` instead of `services-build`, and omitting the WAR from the archive.
=> Only include services docs in archive

Makefile.old
=> Don't copy `buildInfo.json` into the archive.

hoot-core/src/main/cpp/hoot/core/algorithms/zindex/ZCurveRanger.cpp
Refs #2277 
Explicitly use boost::make_shared
@mschicker would you take a quick look?
=> Explicitly use boost::make_shared in ZCurveRanger

hoot-core-test/src/test/cpp/hoot/core/algorithms/MaximalNearestSublineMatcherTest.cpp, hoot-core-test/src/test/cpp/hoot/core/algorithms/MaximalSublineStringMatcherTest.cpp, hoot-core-test/src/test/cpp/hoot/core/algorithms/MultiLineStringSplitterTest.cpp, hoot-core-test/src/test/cpp/hoot/core/conflate/highway/HighwayExpertClassifierTest.cpp, hoot-core-test/src/test/cpp/hoot/core/conflate/highway/HighwayMatchTest.cpp, hoot-core-test/src/test/cpp/hoot/core/conflate/highway/HighwaySnapMergerTest.cpp
Refs #2278 
Removed all `createWay` functions from individual tests and reused the `TestUtils::createWay` version.
@bwitham would you take a quick look?  Should be very simple.
=> Consolidate createWay utility function

scripts/copyright/UpdateCopyrightHeader.py
Refs #2295 
Updated copyright header python script to use 'git ls-files' to only work on files indexed by git.
@sputnam would you take a look at this for me since it is more of a DevOps script and you are a python expert?
=> Copyright Script updates files that it shouldn't

hoot-services/Makefile, scripts/jenkins/Jenkinsfile, scripts/maven/mvn-build
Adding sonar scan step to hoot pipeline.  Right now it will just scan hoot-services in the nightly run or on a rerun if specified us build parameter.  Updated services code coverage to be calculated off of jacoco instead of corbetura because sonarqube has better support for jacoco.
=> Add sonar step for hoot services

docs/commands/map-diff.asciidoc, hoot-core-test/src/test/cpp/hoot/core/io/ServiceOsmApiDbReaderTest.cpp, hoot-core-test/src/test/cpp/hoot/core/scoring/MapComparatorTest.cpp, hoot-core/src/main/cpp/hoot/core/cmd/MapDiffCmd.cpp, hoot-core/src/main/cpp/hoot/core/elements/Element.h, hoot-core/src/main/cpp/hoot/core/elements/ElementData.cpp, hoot-core/src/main/cpp/hoot/core/elements/ElementData.h, hoot-core/src/main/cpp/hoot/core/elements/Node.h, hoot-core/src/main/cpp/hoot/core/elements/NodeData.h, hoot-core/src/main/cpp/hoot/core/elements/Relation.cpp, hoot-core/src/main/cpp/hoot/core/elements/Relation.h, hoot-core/src/main/cpp/hoot/core/elements/Way.cpp, hoot-core/src/main/cpp/hoot/core/elements/Way.h, hoot-core/src/main/cpp/hoot/core/io/HootApiDbReader.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiDbReader.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmPbfReader.h, hoot-core/src/main/cpp/hoot/core/scoring/MapComparator.cpp, hoot-core/src/main/cpp/hoot/core/util/OsmUtils.cpp, hoot-core/src/main/cpp/hoot/core/util/OsmUtils.h
Ref: #2362 
It looks like the OsmApiDBReader class was mishandling timestamps from the database.
I just sort of mirrored what HootApiDBReader does, and now sample output looks much better!
=> Fix timestamps in exports from osm api db

plugins/TranslationServer.js, plugins/test/TranslationServer.js
This basically takes the logic from "populateGeometriesForSchema" that was in TM 174 (that returned a list of fcodes and allowed geometries) and brings it into the hoot translation server. Would it be better to just return a list of fcodes and then create a separate request for allowed geometries for a given fcode or is it better to get it all in one request?
=> 2367 Translation Server returns fcodes and allowed geometries 

conf/core/ConfigOptions.asciidoc, conf/services/conflateAdvOps.json, hoot-core/src/main/cpp/hoot/core/conflate/extractors/AttributeDistanceExtractor.h, hoot-core/src/main/cpp/hoot/core/conflate/extractors/ParallelScoreExtractor.cpp, hoot-core/src/main/cpp/hoot/core/conflate/extractors/ParallelScoreExtractor.h, hoot-core/src/main/cpp/hoot/core/schema/OsmSchema.cpp, hoot-core/src/main/cpp/hoot/core/schema/OsmSchema.h, hoot-js/src/main/cpp/hoot/js/schema/OsmSchemaJs.cpp, hoot-js/src/main/cpp/hoot/js/schema/OsmSchemaJs.h, rules/Railway.js, rules/lib/HootLib.js
Refs #2311 
Don't forget to merge the 2311 hoot-tests branch! (regression test)!
So... on the data I've been playing with, it scores like this:
```
|                 |        |\3=.       expected     |
|                 |        | miss  | match | review |
|/3. test outcome | miss   |   -   |    24 |     0  |
| match  |     5 |    75 |     0  |
| review |     0 |     0 |     0  |
correct: 0.721154
wrong: 0.278846
unnecessary reviews: 0
```
I suppose that leaves room for improvement... but I figure we might as well get the feature in there.
=> Add railways as conflatable feature type

scripts/ci/archive.sh
Fixes #2387.  Adds the `scripts/ci/archive.sh` script that represents the canonical RPM archive generation script for use by all CI services -- used instead of repeating the same instructions across `Jenkinsfile`, `.circleci/config.yml`, `.travis.yml`, etc.
=> Add archive creation script

hoot-core/src/main/cpp/hoot/core/io/OgrWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmXmlReader.cpp
Added debug messages for `action='delete'` elements in `OsmXmlReader` and ignore `NULL` elements in the streaming `OgrWriter` class.
=> OSM file containing "action='delete'" crashes when converted to Shapefile

Vagrantfile
Fixes #2402, uses `tomcat` user instead of `tomcat8` in EGD provisioner.
=> Use correct user for EGD provisioner

hoot-core/src/main/cpp/hoot/core/conflate/poi-polygon/PoiPolygonMerger.cpp
Refs #2404 
Many to many matches in PoiPoly fail an assert.
```
BuildingMerger(pairs).apply(map, replaced);
assert(replaced.size() > 0);
```
When the `BuildingMerger` code runs into a many-to-many case, a relation is created and nothing is pushed into the `replaced` vector.  This will cause the above assert to fail.  Instead return a NULL `ElementId`.  This is then caught in the `PoiPolygonMerger::apply` code and all of the rest of the function is skipped because nothing was merged and so tags don't need to be updated.  This was causing regression tests failures.
=> Nightly Regression

scripts/jenkins/Jenkinsfile_scan, scripts/sonar/sonar-build.sh
These changes will scan pull-requests upon creation and changes.  It will fail the scan job if any new critical or high findings are introduced in the branch.  It will also make inline comments in the pull-request diffs identifying scan results in the newly proposed code changes.
=> Add github pull-request support to sonar scan pipeline

hoot-core/src/main/cpp/hoot/core/conflate/merging/SmallWayMerger.cpp, hoot-core/src/main/cpp/hoot/core/elements/Way.cpp, hoot-core/src/main/cpp/hoot/core/elements/Way.h
The SmallWayMerger is pretty careful not to undo the work done by the IntersectionSplitter, but it was not handling the scenario where a way Ts into a looped way. Now it does!
Refs #2401
=> Prevent SmallWayMerger from merging intersections created by IntersectionSplitter

scripts/cover/coverGcov.sh, scripts/jenkins/Jenkinsfile, scripts/sonar/sonar-build.sh, scripts/sonar/sonar-scan.sh
Scans should take place for pull-requests and the nightly run of develop.  Coverage should only be calculated on the nightly run of develop.
=> Integrate sonar scanning into hoot pipeline

.circleci/config.yml
Fixes #2444.  This PR adds a CircleCI configuration to generate Hootenanny archives and upload to S3.  The archives may then be used by a separate RPM repository pipeline.  Public Docker containers from ngageoint/hootenanny-rpms are used for making the archive (`hootenanny/rpmbuild-hoot-release`) and uploading to S3 (`hootenanny/rpmbuild-repo`).
=> Enable Hoot Archive Pipeline on CircleCI

VagrantProvisionCentOS7.sh
Forgot to add this in a previous commit.  Nightly job failed because lack of lcov.
=> Add lcov to provisioning for coverage reports

.gitmodules
I'm proposing we remove the branch specifier from our submodule .gitmodules file.  As I understand it, it's only relevant when using the --remote flag with a submodule update, which causes the submodule code to update to the SHA1 of the latest commit on the branch specified.  I'm not sure that's a use case we really care that much about.
Since it's not defined how to use the branch specifier across different branches of hoot, would require fragile logic to adhere to a defined pattern, and even then could easily get changed without anyone really noticing I propose we just not use it.
I added several reviewers to get diverse opinions on this matter since it can be fairly confusing and I wanted to see if people are actively using the --remote flag with submodule update for some purpose.
=> Remove branch specifier from submodule.  Not providing much utility

scripts/jenkins/Jenkinsfile
Don't destroy the release candidate VMs to they can be tested during the release process.  Add message to notify the VM is ready for testing.
=> Add logic for release candidate VMs to Jenkinsfile

docs/install/HootenannyInstall.asciidoc
Fixes #2509.  Point to the CentOS 7 repository, and document using `yum-config-manager` to set up the package repositories.
=> Update RPM installation instructions.

hoot-core/src/main/cpp/hoot/core/io/OsmApiChangeset.cpp
Refs #2356 
Streaming the XML changeset instead of loading the entire thing at once.
=> Colorado (3.8G file) fails to load to OSM API

test-files/cmd/quick/NameFrequenciesCmdTest.sh
Fixes #2528.  Use `LC_ALL=C` instead of `LANG=C` for consistent sorting.
=> Fix language environment in name frequencies test

docs/commands/changeset-apply.asciidoc, hoot-core-test/src/test/cpp/hoot/core/io/OsmApiChangesetElementTest.cpp, hoot-core-test/src/test/cpp/hoot/core/io/OsmApiChangesetTest.cpp, hoot-core-test/src/test/cpp/hoot/core/io/OsmApiWriterTest.cpp, hoot-core/src/main/cpp/hoot/core/cmd/ApplyChangesetCmd.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangeset.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangeset.h, hoot-core/src/main/cpp/hoot/core/io/OsmApiWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiWriter.h
Refs #2518 
Added `--stats` and `--progress` options to the command line for `changeset-apply`.  Also allowed for reading `.osm` files directly as an all-create changeset.
=> Updates to 'changeset-apply' command

hoot-core/src/main/cpp/hoot/core/cmd/ConflateCmd.cpp, hoot-core/src/main/cpp/hoot/core/conflate/DiffConflator.cpp, hoot-core/src/main/cpp/hoot/core/conflate/DiffConflator.h, test-files/cmd/slow/DiffConflateCmdTest/output.tags.osc, test-files/cmd/slow/DiffConflateCmdTest/output_unified.osc
Refs #2551
These changes should stop geometries from being modified when applying the tag-diff.
They might not, however, keep your roads from turning into bicycle paths @mattjdnv .
=> Fix geometry modification in tag-differential

hoot-js/src/main/cpp/hoot/js/JavaScriptTranslator.cpp
Refs #2524 
This is kind of a band-aid: I'm not exactly sure how we are getting blank tablenames in the translation. The chunk o' code around the stuff modified in #2527 looks like it should simply remove problematic entries, so they don't continue to propagate through the system. What do you think @mattjdnv ?
=> Add handling for blank tablenames during translation

VagrantProvisionVars.sh
Fixes #2574, upgrades the ChromeDriver in preparation for Chrome 69.
=> Upgrade to ChromeDriver 2.41.

hoot-core-test/src/test/cpp/hoot/core/io/ServiceHootApiDbReaderTest.cpp, hoot-core-test/src/test/cpp/hoot/core/io/ServiceOsmApiDbReaderTest.cpp, hoot-core/src/main/cpp/hoot/core/io/ApiDbReader.cpp, hoot-core/src/main/cpp/hoot/core/io/ApiDbReader.h, test-files/io/ServiceHootApiDbReaderTest/runReadByBoundsTestInput.osm, test-files/io/ServiceHootApiDbReaderTest/runReadByBoundsTestOutput.osm, test-files/io/ServiceOsmApiDbReaderTest/runReadByBoundsTest.osm
Refs #2505 and #1856
When relations were being exported from the database the process wasn't grabbing relations that were members of relations and so forth.  This code change iterates on each relation and adds all members of the relation to the export.  If that member is a relation itself, then the process is repeated for that sub-relation.
=> Export relation with missing members mangling polygon geometry

hoot-core/src/main/cpp/hoot/core/io/OsmApiWriter.cpp
Refs #2623 
More robust error handling for when the changeset creation fails.
=> Bad changeset IDs in bulk upload

VagrantProvisionCentOS7.sh, docker/hootcore/Dockerfile, scripts/hoot-repo/yum-configure.sh
Fixes #2638.  Uses upgraded dependencies (PostGIS 2.4.4 and Tomcat 8.5.34), currently hosted in the release dependency repository.
=> Upgrade PostGIS

hoot-core-test/src/test/cpp/hoot/core/io/ServiceOsmApiDbBulkInserterTest.cpp, hoot-core/src/main/cpp/hoot/core/algorithms/changeset/ExternalMergeElementSorter.cpp, hoot-rnd/src/main/cpp/hoot/rnd/schema/ImplicitTagRawRulesDeriver.cpp, hoot-services/Makefile, test-files/ui/Makefile
Updated make process to quiet the `clean` and `clean-all` targets when requested with the `-s` flag and removed extra semi-colons for the qube.
=> Qube and Makefile updates

docs/commands/stat.asciidoc, hoot-core/src/main/cpp/hoot/core/cmd/CountCmd.cpp, hoot-core/src/main/cpp/hoot/core/cmd/StatCmd.cpp, hoot-core/src/main/cpp/hoot/core/io/ConstElementCriterionVisitorInputStream.cpp, hoot-core/src/main/cpp/hoot/core/io/ConstElementCriterionVisitorInputStream.h, hoot-core/src/main/cpp/hoot/core/io/ConstElementVisitorInputStream.cpp, hoot-core/src/main/cpp/hoot/core/io/ConstElementVisitorInputStream.h, hoot-core/src/main/cpp/hoot/core/io/ElementVisitorInputStream.cpp, hoot-core/src/main/cpp/hoot/core/io/ElementVisitorInputStream.h, test-files/cmd/slow/StatCmdTest.sh.stdout
* count and stat commands no longer have to load all input data into memory
* stat command limited to a single input, as some stats would be inaccurate across multiple inputs; alternate workflow is to concat multiple inputs into a single input with 'hoot cat' before calling 'hoot stat'
* Add some const versions of existing input streams
=> Make the count and stat commands not be memory bound

Makefile.hoot
Refs #2721 and #2641 
Make the Hoot UI 2x quiet without breaking the build.  The single quotes were causing the parameter to not function correctly.  The best way to tell that the build happened and wasn't skipped is that it modifies files in the `hoot-ui-2x` directory when it builds.
```
$ git status
#
#	modified:   hoot-ui-2x (modified content)
```
It is more than an annoyance but for now it will show that the build was successful.  We should open another ticket to fix this modification problem later.
=> Silence the Hoot UI 2x build

conf/schema/REF1.json, conf/schema/REF2.json, conf/schema/address.json, conf/schema/colour.json, conf/schema/contact.json, conf/schema/destination.json, conf/schema/ele.json, conf/schema/email.json, conf/schema/frequency.json, conf/schema/gauge.json, conf/schema/height.json, conf/schema/hoot_tags.json, conf/schema/is_in.json, conf/schema/lanes.json, conf/schema/maxspeed.json, conf/schema/metadata.json, conf/schema/name.json, conf/schema/note.json, conf/schema/source.json, conf/schema/url.json, conf/schema/website.json, conf/schema/width.json, conf/schema/wikipedia.json, hoot-core/src/main/cpp/hoot/core/schema/OsmSchema.cpp, hoot-core/src/main/cpp/hoot/core/schema/SchemaChecker.cpp
Removed geometry from schema that don't describe geometries and updated `OsmSchema::allowsFor()` code to ignore empty geometries
Refs #2693 
Merge into branch `2693` for https://github.com/ngageoint/hootenanny/pull/2734
=> Schema changes for geometries

hoot-core/src/main/cpp/hoot/core/io/DataConverter.cpp, hoot-core/src/main/cpp/hoot/core/io/ElementStreamer.cpp
* ElementStreamer now checks visitors to make sure they aren't OsmMapConsumers before allowing streaming I/O; a full map can't be passed reliably during streaming
=> Prevent OsmMapConsumer based visitor convert ops from crashing during streaming I/O

conf/core/ConfigOptions.asciidoc, hoot-core/src/main/cpp/hoot/core/io/OsmGeoJsonWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmJsonWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmXmlReader.cpp, plugins/TranslationServer.js, plugins/test/runway.js
Refs #2747 
The `OsmXmlReader` class was throwing out node elements referenced from ways that didn't exist in the OSM file so I set the translation server to set `_addChildRefsWhenMissing` to `true` always.  Also updated the JSON/GeoJSON writers to output correct JSON in these cases.  Finally updated the test to not use the `osmtogeojson` function when parsing "bad" GeoJSON.  Technically it is formed correctly but the `osmtogeojson` library doesn't play well with empty geometries.  Below is the output in GeoJSON from Hootenanny that it chokes on:
```
{
"generator":"Hootenanny",
"type":"FeatureCollection",
"bbox":[ 0,0,0,0 ],
"features":[
{
"type":"Feature",
"properties":{
"uuid":"b9efe238-98b6-445b-b4f1-b9d7647d94e4",
"aeroway":"runway"
},
"geometry":{
"type":"Polygon",
"coordinates":[ ] …
```
=> OSM with missing nodes fails geometry type handling for closed ways

Makefile.hoot, docs/developer/HootenannyTests.asciidoc, hoot-test/src/main/cpp/hoot/test/main.cpp, scripts/TestConfigure.sh, scripts/jenkins/Jenkinsfile, scripts/jenkins/TestDevelop.sh, scripts/jenkins/TestInitialNightly.sh, scripts/jenkins/TestQuick.sh, scripts/jenkins/centos67/TestPullRequest_core.sh
Removed the requirement to always provide a thread count to the `HootTest` executable with `--parallel`.  Now when a thread count is left off the test harness makes an implicit call to `nproc` (actually the equivalent from the `nproc` source code).
=> Sick of always adding $(nproc) to every HootTest call

hoot-core/src/main/cpp/hoot/core/cmd/VersionCmd.cpp, tgs/src/main/cpp/tgs/System/SystemInfo.cpp
Refs #2751 
Went through the list of libraries added in `$HOOT_HOME/VagrantProvisionCentOS7.sh` and added as many `*-devel` libraries as I could find version information in the code itself.  The rest may require some other method of getting version information.  The following were added:
* Python
* Protobuf
* OpenCv
* PostgreSQL
* LibPNG
* LibICU
* Proj4
=> Update version command to show all dependency versions

conf/services/conflateAdvOps.json, conf/services/conflationAttributeOps.json
this has many more options not exposed to the ui
doesn't make sense to expose just this one
update UI to += conflate.post.ops
=> remove conflate post ops from default, update UI with +=

hoot-core/src/main/cpp/hoot/core/util/Settings.cpp
Fixed hoot test command parsing causing it to drop other command arguments in some cases 
Refs #2922 
This actually fixes the existing original issue since it no longer does a substring comparison.
However identical parameters (which don't exist at this time) could still be parsed out.
=> Fixed hoot command line parsing issue

hoot-core/src/main/cpp/hoot/core/visitors/RemoveDuplicateAreaVisitor.cpp
Refs #2742, removal time comes down to 00m24s from 03m25s 
This took a while for rearranging a single line, but I think I have a reasonable workflow now to track down these slowdowns.
I made an attempt to speed up the regex matching by using the boost version, but that was way slower and caused the tests to fail.
There is surely more to gain but I'm still trying to understand what the code is actually doing.
=> Performance fix

Makefile.hoot, conf/core/ConfigOptions.asciidoc, hoot-core/src/main/cpp/hoot/core/algorithms/string/WeightedWordDistance.cpp, scripts/util/Centos7_only_core.sh, test-files/cmd/quick/ConfigOptionsCmdTest/ConfigOptions.asciidoc
Fixes #3002; refs ngageoint/hootenanny-rpms#250.  Use the `hoot-support` bucket instead of `hoot-rpms` for support files and improve verification of OpenNLP language file.
=> Change S3 Bucket for Support Files

scripts/sonar/sonar-scan.sh
Removed `sonar.analysis.mode` because it is causing PRs to fail:
```
ERROR: Error during SonarQube Scanner execution
ERROR: The preview mode, along with the 'sonar.analysis.mode' parameter, is no more supported. You should stop using this parameter.
ERROR: 
ERROR: Re-run SonarQube Scanner using the -X switch to enable full debug logging.
```
=> Fixed sonar scanner failure.

hoot-core/src/main/cpp/hoot/core/cmd/ConflateCmd.cpp, hoot-core/src/main/cpp/hoot/core/ops/BuildingOutlineUpdateOp.cpp, test-files/cases/attribute/unifying/building-3037-dropped-multipoly-relations-1/Expected.osm, test-files/cases/attribute/unifying/building-3037-dropped-multipoly-relations-1/Input1.osm, test-files/cases/attribute/unifying/building-3037-dropped-multipoly-relations-1/Input2.osm, test-files/cases/attribute/unifying/building-3037-dropped-multipoly-relations-1/README.txt
will cherry pick this back into develop for nightly build purposes
Changes were previously made to Attribute Conflation to remove building relations after conflation when they had already had a corresponding unioned multipoly relation created for them after conflation.  However, BuildingOutlineUpdateOp was incorrectly removing all multipoly relations, regardless of whether they had been conflated and then unioned with anything.  So, multipoly building relations were disappearing from the output.  These changes fix that.
=> Prevent Attribute Conflation from dropping multipoly building relations in output

conf/core/ConfigOptions.asciidoc, hoot-core-test/src/test/cpp/hoot/core/io/OsmApiWriterTest.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangeset.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiWriter.h
Refs #3041 
Added ability to throttle OSM API changeset uploads.
=> Throttle OSM API changeset apply speed

hoot-core/src/main/cpp/hoot/core/conflate/highway/Roundabout.cpp, hoot-core/src/main/cpp/hoot/core/ops/RemoveRoundabouts.cpp, hoot-core/src/main/cpp/hoot/core/ops/SmallWayMerger.cpp, hoot-core/src/main/cpp/hoot/core/schema/MetadataTags.h, hoot-test/src/main/cpp/hoot/test/ProcessPool.cpp, test-files/cases/roundabouts/rcase-002/Expected.osm, test-files/cases/roundabouts/rcase-003/Expected.osm
Refs #3049 
I found that when ordering of ways was reversed in roundabout unit tests that they failed.  Some even failed to restore the original roundabout.  It was a mess.  This fixes those issues.
=> Roundabout unit tests implode when IDs aren't regenerated

hoot-core/src/main/cpp/hoot/core/io/OsmXmlReader.cpp
Refs #2079 
With this change hoot throws an error when multiple way nodes with identical ids are encountered in the same osm file.
When that happened the previously saved id in the way id map was overwritten. This could also happen when loading multiple osm files with the same reader in which case it would add the ids of multiple osm maps to the internal id map causing arbitrary id mapping results leading to crashes.
Now when reusing a reader, all id maps are cleared ahead of time.
=> Throw error when encountering ways with duplicate ids and clear id maps when reusing reader

hoot-core/src/main/cpp/hoot/core/io/OsmMapWriter.h, hoot-core/src/main/cpp/hoot/core/io/OsmMapWriterFactory.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmMapWriterFactory.h, hoot-core/src/main/cpp/hoot/core/io/OsmXmlWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmXmlWriter.h
refs #3078 
When debug maps are written, override the following settings to make sure that they are included:
* Hoot ID tag
* Parent ID tag
* Debug tags
* Status as text
* Circular error
=> Turn on debugging tags with 'debug.maps.write' setting

sonar-project.properties
Refs #2657
The classes listed that are failing the "rule of 5" don't require explicit copy constructors, assignment operators, etc.  These rulings are false positives.  Turn it off.
=> Removed the 'rule of five' check from SonarQube as we are not using it.

Makefile.hoot
Recent changes to the makefile were causing errors under some build conditions.  It appears to be a race condition caused by a recent change when the compile is run with parallel threads.
=> rework conflation config scripts to remove race condition

hoot-core/src/main/cpp/hoot/core/conflate/matching/MatchFactory.cpp
Rubbersheeting with the Unifying alg was originally disabled b/c rubbersheeting was occurring, even when unselected, from the UI.  Now, some users would like to use it with the Unifying alg so removing the hardcode that disabled it.  If it still is being applied regardless, then we can open a UI bug issue to fix.
=> Remove auto-disabling of rubber sheeting when using Unify roads alg from UI

.circleci/config.yml
* Ensure qt4 is purged from archive creation container, refs ngageoint/hootenanny-rpms#259.
* Latest CentOS 7 base image and updates.
=> CircleCI Image Updates

scripts/jenkins/Jenkinsfile
Switch back to pre-provisioned box that we changed in #3121 now that the `hoot/centos7-hoot` box has been updated (including on Jenkins).
=> Use Pre-provisioned Box in Testing Again

hoot-core/src/main/cpp/hoot/core/index/ClosePointHash.h, hoot-core/src/main/cpp/hoot/core/ops/MergeNearbyNodes.cpp
Refs #3060
@bwitham I tried a bunch of stuff, but the performance gain (of factor 100 and more depending on bin/distance size) is all in line 128. Removing the sqrt made almost no difference at all. Looks like hash map lookups are extremely slow.
=> Performance fix for MergeNearbyNodes

conf/core/ConfigOptions.asciidoc, docs/user/SupportedDataFormats.asciidoc, hoot-core-test/src/test/cpp/hoot/core/io/OsmGeoJsonReaderTest.cpp, hoot-core-test/src/test/cpp/hoot/core/io/OsmJsonReaderTest.cpp, hoot-core/src/main/cpp/hoot/core/io/ElementStreamer.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmGeoJsonReader.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmGeoJsonReader.h, hoot-core/src/main/cpp/hoot/core/io/OsmJsonReader.cpp
Before this change there wasn't anyway to disambiguate an Overpass JSON URL from a GeoJSON URL.  Added a config option to specify the Overpass host in use to prevent the GeoJSON reader from trying to read from such URL's. Callers can update the config option based on their Overpass source.
=> Prevent geojson reader from reading from overpass json urls

hoot-core-test/src/test/cpp/hoot/core/io/OsmGeoJsonReaderTest.cpp, hoot-core-test/src/test/cpp/hoot/core/io/OsmJsonReaderTest.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmJsonReader.cpp
The regex used to replace large integers in JSON values to address Boost JSON parser bug was causing certain large integers embedded in JSON text values not to parse (see OsmJsonReaderTest::scrubBigIntsTest). A simple solution was to slightly relax the regex by removing a semicolon to match, as no test data has been found that needs that level of strictness. If such data exists, then a different solution would need to be found.
=> Fix for JSON parsing issue when big ints are embedded in value string

Makefile.hoot, scripts/database/SetupOsmApiDB.sh
Removed `ConfigOptions.json` from the `js-make` target to remove race condition in build.
=> Fix build race condition

hoot-core/src/main/cpp/hoot/core/io/OgrWriter.h, hoot-core/src/main/cpp/hoot/core/io/ShapefileWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/ShapefileWriter.h
Refs #3232 
Implemented Configurable in the ShapefileWriter class and cleaned up OgrWriter class a little.
=> Implement `writer.include.circular.error.tags` for shapefile writer

hoot-core-test/src/test/cpp/hoot/core/TestUtils.cpp, hoot-core-test/src/test/cpp/hoot/core/TestUtils.h, hoot-core-test/src/test/cpp/hoot/core/criterion/ConflatableElementCriterionTest.cpp, hoot-core-test/src/test/cpp/hoot/core/criterion/NonConflatableCriterionTest.cpp, hoot-core-test/src/test/cpp/hoot/core/visitors/ConflatableCriteriaVisitorTest.cpp, hoot-core/src/main/cpp/hoot/core/criterion/AreaCriterion.cpp, hoot-core/src/main/cpp/hoot/core/criterion/BuildingCriterion.h, hoot-core/src/main/cpp/hoot/core/criterion/ConflatableElementCriterion.cpp, hoot-core/src/main/cpp/hoot/core/criterion/ConflatableElementCriterion.h, hoot-core/src/main/cpp/hoot/core/criterion/ElementCriterion.h, hoot-core/src/main/cpp/hoot/core/criterion/HighwayCriterion.h, hoot-core/src/main/cpp/hoot/core/criterion/LinearWaterwayCriterion.h, hoot-core/src/main/cpp/hoot/core/criterion/NonConflatableCriterion.cpp, hoot-core/src/main/cpp/hoot/core/criterion/NonConflatableCriterion.h, hoot-core/src/main/cpp/hoot/core/criterion/PoiCriterion.h, hoot-core/src/main/cpp/hoot/core/criterion/PowerLineCriterion.h, hoot-core/src/main/cpp/hoot/core/criterion/RailwayCriterion.h, hoot-core/src/main/cpp/hoot/core/criterion/poi-polygon/PoiPolygonPoiCriterion.h, hoot-core/src/main/cpp/hoot/core/criterion/poi-polygon/PoiPolygonPolyCriterion.h, hoot-core/src/main/cpp/hoot/core/elements/Tags.cpp, hoot-core/src/main/cpp/hoot/core/elements/Tags.h, hoot-core/src/main/cpp/hoot/core/schema/MetadataTags.h, hoot-core/src/main/cpp/hoot/core/visitors/ConflatableCriteriaVisitor.cpp, hoot-core/src/main/cpp/hoot/core/visitors/ConflatableCriteriaVisitor.h, test-files/visitors/ConflatableCriteriaVisitorTest/ConflatableCriteriaVisitorTest-runBasicTest.osm
* Established a base class for `ElementCriterion` to inherit from for criterion that are used to identify conflatable features. This also cleans up the static addition of `ElementCriterion` classes to NonConflatableCriterion, thus reducing future maintenance.
* Added a visitor, `ConflatableCriteriaVisitor`, useful in debugging instances where it isn't clear which criterion is identifying a feature as a conflatable.
=> Add a conflatable criterion

VagrantProvisionCentOS7.sh, VagrantProvisionVars.sh
Fixes #3249, expand yum version locks to:
* `armadillo-8.300.0`
* `libgeotiff-1.4.2`
* `proj-4.8.0`
=> Expand yum version locks

docs/commands/changeset-derive.asciidoc, hoot-core-test/src/test/cpp/hoot/core/visitors/AddAttributesVisitorTest.cpp, hoot-core/src/main/cpp/hoot/core/cmd/DeriveChangesetCmd.cpp, hoot-core/src/main/cpp/hoot/core/elements/ExternalMergeElementSorter.cpp, hoot-core/src/main/cpp/hoot/core/elements/InMemoryElementSorter.cpp, hoot-core/src/main/cpp/hoot/core/io/ElementStreamer.cpp, hoot-core/src/main/cpp/hoot/core/io/ElementStreamer.h, hoot-core/src/main/cpp/hoot/core/io/OsmMapReaderFactory.cpp, hoot-core/src/main/cpp/hoot/core/ops/RemoveWayOp.cpp, hoot-core/src/main/cpp/hoot/core/visitors/AddAttributesVisitor.cpp, hoot-core/src/main/cpp/hoot/core/visitors/AddAttributesVisitor.h, hoot-core/src/main/cpp/hoot/core/visitors/CalculateHashVisitor.cpp, hoot-core/src/main/cpp/hoot/core/visitors/ReplaceTagVisitor.cpp, hoot-core/src/main/cpp/hoot/core/visitors/ReportMissingElementsVisitor.h, test-files/cmd/slow/DeriveChangesetCmdTest.sh, test-files/cmd/slow/DeriveChangesetCmdTest/changeset-3.osc, test-files/cmd/slow/DeriveChangesetCmdTest/changeset-4.osc
* Adds `convert.ops` to the `changeset-derive` command
* All ops must support streaming to take advantage of the non-memory bound disk element sorting that occur before changeset derivation, otherwise the in-memory sorting implementation is always used.
=> Add inline conversion opts to changeset-derive command

hoot-core-test/src/test/cpp/hoot/core/scoring/MapComparatorTest.cpp, hoot-core-test/src/test/cpp/hoot/core/visitors/ApiTagTruncateVisitorTest.cpp, hoot-core/src/main/cpp/hoot/core/cmd/DeriveChangesetCmd.cpp, hoot-core/src/main/cpp/hoot/core/criterion/HighwayCriterion.cpp, hoot-core/src/main/cpp/hoot/core/io/OgrReader.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangesetElement.cpp, hoot-core/src/main/cpp/hoot/core/schema/MetadataTags.h, hoot-core/src/main/cpp/hoot/core/schema/TagInfo.cpp, hoot-core/src/main/cpp/hoot/core/scoring/MapComparator.cpp, hoot-core/src/main/cpp/hoot/core/visitors/ApiTagTruncateVisitor.cpp, hoot-core/src/main/cpp/hoot/core/visitors/ApiTagTruncateVisitor.h, hoot-core/src/main/cpp/hoot/core/visitors/TagCountVisitor.h, hoot-services/src/main/java/hoot/services/geo/BoundingBox.java
Refs #3261 
The OSM API sets a limit on tag lengths to 255 characters, `changeset-derive` and `changeset-apply` now impose this rule on changeset operations.
=> Truncate OSM Tags Destined for OSM API Changesets

hoot-core-test/src/test/cpp/hoot/core/io/OsmApiChangesetTest.cpp, hoot-core-test/src/test/cpp/hoot/core/io/OsmApiWriterTest.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangeset.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangeset.h, hoot-core/src/main/cpp/hoot/core/io/OsmApiWriter.h, test-files/io/OsmChangesetElementTest/ChangesetErrorFixErrors.osc, test-files/io/OsmChangesetElementTest/ChangesetMergeExpected.osc, test-files/io/OsmChangesetElementTest/ToyTestAConflicts.osc, test-files/io/OsmChangesetElementTest/ToyTestASplit1.osc, test-files/io/OsmChangesetElementTest/ToyTestASplit1.response.xml, test-files/io/OsmChangesetElementTest/ToyTestASplit2.osc, test-files/io/OsmChangesetElementTest/ToyTestASplit2.response.xml, test-files/io/OsmChangesetElementTest/ToyTestASplit3.osc, test-files/io/OsmChangesetElementTest/ToyTestASplit3.response.xml, test-files/io/OsmChangesetElementTest/ToyTestASplit4.osc, test-files/io/OsmChangesetElementTest/ToyTestASplit4.response.xml
Changed order of changesets to relation/way/node and accounted for the 'precondition failed:' message.
=> Reorder changesets for HootBot

hoot-core-test/src/test/cpp/hoot/core/io/OsmJsonReaderTest.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmJsonReader.cpp
The JSON manipulation code wasn't handling overpass data correctly in the `scrubQuotes` function.  This fixes the problem.
=> Some overpass data fails to read in Hootenanny

conf/core/AttributeConflation.conf, hoot-core/src/main/cpp/hoot/core/cmd/ConflateCmd.cpp, test-files/cases/attribute/network/highway-2888-reviews-by-score/Expected.osm, test-files/cases/attribute/network/highway-2888/Expected.osm, test-files/cases/attribute/network/highway-2927-bridge-2/Expected.osm, test-files/cases/attribute/network/highway-2927-multiple-types-1/Expected.osm, test-files/cases/attribute/network/highway-2927-name-preservation-1/Expected.osm, test-files/cases/attribute/network/highway-2927-unmarked-ref-divided-road-1/Expected.osm, test-files/cases/attribute/unifying/building-3022-duplicate-relation-member-ways-1/Expected.osm, test-files/cases/attribute/unifying/building-3136-many-to-many-auto-merge-1/Expected.osm, test-files/cases/attribute/unifying/building-3184-completely-contained-1/Expected.osm, test-files/cases/attribute/unifying/highway-2888/Expected.osm, test-files/cases/attribute/unifying/highway-2927-bridge-1/Expected.osm, test-files/cases/attribute/unifying/highway-2927-bridge-2/Expected.osm, test-files/cases/attribute/unifying/highway-2927-multiple-types-1/Expected.osm, test-files/cases/attribute/unifying/highway-2927-name-preservation-1/Expected.osm, test-files/cases/attribute/unifying/highway-2927-unmarked-ref-divided-road-1/Expected.osm, test-files/cases/attribute/unifying/highway-2927-way-member-tags-1/Expected.osm
Refs #3149 
Turning on `reader.conflate.use.data.source.ids.2` for attribute conflation requires input files to be loaded in reverse order so that the secondary dataset keeps its IDs no matter the IDs in the source dataset.
=> Enable `reader.conflate.use.data.source.ids.2` for attribute conflation

scripts/jenkins/Jenkinsfile
After some conversation we've decided to halt all jobs in the jenkinsfile post step to help save resources.  A dev can still go in the workspace and restart the VM if they would like to for troubleshooting.
=> Halt VMs after jenkins runs

hoot-core/src/main/cpp/hoot/core/ops/MetadataOp.cpp
A header file was renamed and it was not updated in the branch that got merged.
=> Fixed renamed header file issue

hoot-core-test/src/test/cpp/hoot/core/test/ConflateCaseTestSuite.cpp, hoot-core-test/src/test/cpp/hoot/core/test/ConflateCaseTestSuite.h, hoot-core-test/src/test/cpp/hoot/core/util/SettingsTest.cpp, hoot-core/src/main/cpp/hoot/core/util/Settings.cpp, hoot-core/src/main/cpp/hoot/core/util/Settings.h
Refs #3191 
Removed `base.config` from `ConflateCaseTestSuite` class and implemented it for all uses of the `Settings` class, including test cases.  Also added unit test to ensure `base.config` works correctly.
=> Implement `base.config` in Settings.cpp

hoot-core-test/src/test/cpp/hoot/core/scoring/GraphComparatorTest.cpp, hoot-core/src/main/cpp/hoot/core/scoring/GraphComparator.cpp, hoot-core/src/main/cpp/hoot/core/scoring/GraphComparator.h, tgs/src/main/cpp/tgs/ProbablePath/ProbablePathCalculator.cpp, tgs/src/main/cpp/tgs/ProbablePath/ProbablePathCalculator.h, tgs/src/main/cpp/tgs/Statistics/Random.h
Made `GraphComparator` run each iteration separately so that it can be run in multiple threads.  Also had to pass `Tgs::Random` objects to the `ProbablePathCalculator` seeded with the iteration index so that tests are consistent.
=> Parallelize GraphComparator to reduce testing runtimes

hoot-core-test/src/test/cpp/hoot/core/io/OsmXmlWriterTest.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmXmlWriter.cpp, test-files/io/OsmXmlWriterTest/runChangesetIdTest.osm
Refs #3320 
Don't output the changeset ID when the element ID is negative.
=> JOSM cannot read some Hootenanny output well

hoot-core/src/main/cpp/hoot/core/cmd/CropCmd.cpp, hoot-core/src/main/cpp/hoot/core/ops/MapCropper.cpp
The `MapCropper` class is `Configurable` but the crop command wasn't passing in the `Settings` object so commands like this never worked correctly:
```
hoot crop -D crop.keep.entire.features.crossing.bounds=true ...
```
=> The crop command not passing in the -D crop.* options to the MapCropper

scripts/yum/pgdg-repo.sh
Fixes proj related errors on regression tests.  Avoids pgdg repo from installing conflicting version of proj.
=> Exclude geospatial packages from PGDG repository.

hoot-core-test/src/test/cpp/hoot/core/conflate/poi-polygon/PoiPolygonMergerCreatorTest.cpp, hoot-core-test/src/test/cpp/hoot/core/io/OsmApiWriterTest.cpp, hoot-core-test/src/test/cpp/hoot/core/io/OsmApiWriterTestServer.cpp, hoot-core-test/src/test/cpp/hoot/core/io/OsmApiWriterTestServer.h, hoot-core-test/src/test/cpp/hoot/core/io/OsmGeoJsonWriterTest.cpp, hoot-core-test/src/test/cpp/hoot/core/io/OsmPbfReaderTest.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangeset.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangeset.h, hoot-core/src/main/cpp/hoot/core/io/OsmApiWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiWriter.h, test-files/io/OsmChangesetElementTest/ToyTestAConflicts.osc
Updated `OsmApiWriter` to retry some datasets up to 5 times before failing instead of failing endlessly.
=> Hootbot fix endless retries

conf/core/ConfigOptions.asciidoc, hoot-core-test/src/test/cpp/hoot/core/algorithms/changeset/ChangesetDeriverTest.cpp, hoot-core/src/main/cpp/hoot/core/algorithms/changeset/ChangesetDeriver.cpp, hoot-core/src/main/cpp/hoot/core/algorithms/changeset/ChangesetDeriver.h, test-files/algorithms/changeset/ChangesetDeriverTest/disableRefDeleteTest-in-1.osm, test-files/algorithms/changeset/ChangesetDeriverTest/disableRefDeleteTest-in-2.osm
The original implemenation was only partially completed for an unknown reason. This option is particularly helpful when generating changesets for Differential Conflation output when you don't want to change any reference features. Given that, technically, we could implement something similar to suppress modify statements but haven't seen a use case for that yet.
=> Finish implementation for changeset.allow.deleting.reference.features option

hoot-core-test/src/test/cpp/hoot/core/io/OsmXmlChangesetFileWriterTest.cpp, hoot-core-test/src/test/cpp/hoot/core/io/ServiceOsmApiDbSqlChangesetFileWriterTest.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangeset.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangeset.h, hoot-core/src/main/cpp/hoot/core/io/OsmApiDbSqlChangesetFileWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiDbSqlChangesetFileWriter.h, hoot-core/src/main/cpp/hoot/core/io/OsmApiWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmXmlChangesetFileWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmXmlChangesetFileWriter.h
Refs #3373
Removed changeset output splitting because those splits weren't atomic and cannot be in their current state.
=> Changeset splits are non-atomic

hoot-core-test/src/test/cpp/hoot/core/io/OsmApiWriterTest.cpp, hoot-core-test/src/test/cpp/hoot/core/io/OsmApiWriterTestServer.cpp, hoot-core-test/src/test/cpp/hoot/core/io/OsmApiWriterTestServer.h, hoot-core-test/src/test/cpp/hoot/core/util/HttpTestServer.cpp, hoot-core-test/src/test/cpp/hoot/core/util/HttpTestServer.h
Refs #3291 
Testing framework changes to allow for better testing of OSM API writer so that work on 3291 can progress.  Reorganized the OsmApiWriterTestServer to be more extensible and able to be using in more tests by deriving a class and overriding the respond() function.
=> OSM API testing server updates

conf/core/ConfigOptions.asciidoc, hoot-core/src/main/cpp/hoot/core/io/DataConverter.cpp, hoot-core/src/main/cpp/hoot/core/ops/BuildingOutlineUpdateOp.h, hoot-core/src/main/cpp/hoot/core/ops/BuildingPartMergeOp.h
* Prior to this when `ogr2osm.simplify.complex.buildings` was enabled (enabled by default) and buildings were simplified during OGR to OSM ingest, the JSOM "role verification" warning would get triggered when viewing the ingested input in JOSM. Updated `BuildingOutlineUpdateOp` to run immediately after `BuildingPartMergeOp` to suppress that warning.
* Turned building simplification off by default during OGR to OSM conversion at the request of users, as it can have detrimental effects with some datasets and doesnt seem crucial to any hoot conflate scenarios we currently have. [This UI issue](https://github.com/ngageoint/hootenanny-ui/issues/1556) will yield the option to turn it on for a per-dataset ingest basis. There is still some utility being able to turn the option on with certain …
=> Change OGR to OSM building simplification behavior

VagrantProvisionCentOS7.sh, VagrantProvisionVars.sh
Since EPEL is at 7.7 and CentOS is 7.6 there is a dependency error in qt5-qtwebkit and qt5-qtwebkit-devel that must be ignored for now.
=> Fix builds

conf/core/ConfigOptions.asciidoc, docs/commands/conflate.asciidoc, hoot-core/src/main/cpp/hoot/core/cmd/ConflateCmd.cpp
file wasn't being parsed from the correct argument list position by the `conflate` command
=> fix stats file parsing bug in conflate cmd

VagrantProvisionCentOS7.sh, VagrantProvisionVars.sh, scripts/yum/hoot-repo.sh
I found archived versions of `qt-webkit-5.9.1-1` packages and added to a testing dependency repository: `el7/deps/qt5`.  I'll promote to `el7/deps/release` and revert 9080858 if tests are successful.
=> qt5-webkit version locks

Hootenanny.pro
Remove the `docs` target from the default qmake configuration.  I believe this is the root cause of the RPM pipeline failures, as it forces the docs to be built as part of the default target.  The source archives used to build the RPMs include the built documentation, and trying to regenerate causes failures due to the documentation target trying to call `git log`.
=> Remove Documenation Target

VagrantProvisionCentOS7.sh, VagrantProvisionVars.sh
Removed the `qt5-qtwebkit*` version locks since it is fixed in EPEL now.
=> Fix Jenkins Provision

conf/core/ConfigOptions.asciidoc, hoot-core/src/main/cpp/hoot/core/conflate/poi-polygon/PoiPolygonMatch.cpp, hoot-core/src/main/cpp/hoot/core/conflate/poi-polygon/PoiPolygonMatch.h, hoot-core/src/main/cpp/hoot/core/conflate/poi-polygon/PoiPolygonMatchCreator.cpp, hoot-core/src/main/cpp/hoot/core/conflate/poi-polygon/PoiPolygonReviewReducer.cpp
Using the match/miss/review thresholds for the non-additive matching was causing problems when a bad value (i.e. > 1) was passed in.  I removed these options and updated the match thresholds to all be 1 because the additive matching strategy assigns the score to 1 when it calculates the match/miss/review.
=> Poi poly match fixes

hoot-core/src/main/cpp/hoot/core/io/OsmApiReader.cpp
The `OsmApiReader` was grabbing all Overpass queries and trying to service them.  Works fine for the XML but not the JSON.  This fixes the problem and makes `OsmApiReader` a little more particular with what it tries to work on.
=> Fix Hoot Overpass URL reading

conf/core/ConfigOptions.asciidoc, conf/services/conflationTypes.json, hoot-core/src/main/cpp/hoot/core/conflate/polygon/BuildingMerger.cpp, hoot-core/src/main/cpp/hoot/core/io/OgrReader.cpp, test-files/cases/attribute/unifying/Config.conf
The new option is: `attribute.conflation.suppress.building.tag.on.multipoly.relation.constituents`; note that its turned off in AC case tests until we verify its the behavior we indeed want to avoid having to unnecessarily change a bunch of test output
=> 3486 - Remove building tag from multi-poly relation building members during Attribute Conflation

hoot-core-test/src/test/cpp/hoot/core/algorithms/RdpWayGeneralizerTest.cpp, hoot-core-test/src/test/cpp/hoot/core/algorithms/perty/PertyMatchScorerTest.cpp, hoot-core-test/src/test/cpp/hoot/core/visitors/RandomWayGeneralizerTest.cpp, hoot-core/src/main/cpp/hoot/core/algorithms/RdpWayGeneralizer.cpp, hoot-core/src/main/cpp/hoot/core/algorithms/RdpWayGeneralizer.h, hoot-core/src/main/cpp/hoot/core/visitors/WayGeneralizeVisitor.cpp, test-files/algorithms/RdpWayGeneralizerTest/runGeneralizeWayInput1NoInformationNodesTest-out.osm, test-files/algorithms/RdpWayGeneralizerTest/runGeneralizeWayInput1WithInformationNodesTest-out.osm, test-files/algorithms/perty/PertyMatchScorerTest/PertyMatchScorerTest-perturbed-out-1.osm, test-files/visitors/RandomWayGeneralizerTest/RandomWayGeneralizerTest-out-1.osm, test-files/visitors/RandomWayGeneralizerTest/RandomWayGeneralizerTest-out-2.osm, test-files/visitors/RandomWayGeneralizerTest/RandomWayGeneralizerTest-out-3.osm, test-files/visitors/RandomWayGeneralizerTest/RandomWayGeneralizerTest-out-4.osm, test-files/visitors/RandomWayGeneralizerTest/RandomWayGeneralizerTest-out-5.osm, test-files/visitors/RandomWayGeneralizerTest/RandomWayGeneralizerTest-out-6.osm, test-files/visitors/RandomWayGeneralizerTest/RandomWayGeneralizerTest-out-7.osm, test-files/visitors/RandomWayGeneralizerTest/RandomWayGeneralizerTest-out-8.osm, test-files/visitors/RandomWayGeneralizerTest/RandomWayGeneralizerTest-out-9.osm, test-files/visitors/WayGeneralizeVisitorTest/runBasicTest.osm
Apparently this had been a problem since the very beginning. `RdpWayGeneralizer` was leaving any nodes it removed from ways in the source map....now fixed.
=> 3502 - Fix orphaned nodes in way simplification

hoot-core/src/main/cpp/hoot/core/conflate/poi-polygon/PoiPolygonMerger.cpp
Calling the constructor inline and passing that object by reference doesn't seem to sit well with the DEBUG build.  Crashes every time.  Creating it on the stack and then passing the reference solves the problem.
=> Fixed inline object creation passed by reference crash in DEBUG mode.

hoot-core-test/src/test/cpp/hoot/core/conflate/matching/GreedyConstrainedMatchesTest.cpp, hoot-core-test/src/test/cpp/hoot/core/conflate/matching/OptimalConstrainedMatchesTest.cpp, hoot-core-test/src/test/cpp/hoot/core/elements/OsmMapTest.cpp, hoot-core-test/src/test/cpp/hoot/core/io/ServiceHootApiDbReaderTest.cpp, hoot-core-test/src/test/cpp/hoot/core/util/HttpTestServer.cpp, hoot-core/src/main/cpp/hoot/core/algorithms/extractors/EdgeDistanceExtractor.cpp, hoot-core/src/main/cpp/hoot/core/conflate/UnifyingConflator.cpp, hoot-core/src/main/cpp/hoot/core/conflate/merging/MergerFactory.cpp, hoot-core/src/main/cpp/hoot/core/conflate/merging/MergerFactory.h, hoot-core/src/main/cpp/hoot/core/conflate/polygon/MultiPolygonCreator.cpp, hoot-core/src/main/cpp/hoot/core/elements/OsmMap.cpp, hoot-core/src/main/cpp/hoot/core/scoring/RasterComparator.cpp, hoot-core/src/main/cpp/hoot/core/util/GeometryUtils.cpp, hoot-js/src/main/cpp/hoot/js/io/StreamUtilsJs.h, hoot-rnd/src/main/cpp/hoot/rnd/conflate/multiary/MultiaryUtilities.cpp, hoot-rnd/src/test/cpp/hoot/rnd/conflate/multiary/MultiaryHierarchicalClusterAlgorithmTest.cpp, hoot-rnd/src/test/cpp/hoot/rnd/conflate/multiary/MultiaryPoiMergeCacheTest.cpp
Make `geos::geom` take ownership of objects
`MergerFactory` now keeps track of all `MergerCreator` objects via shared pointers
Use `std::unique_ptr<char []>` to delete an array since `std::shared_ptr` uses `delete` and not `delete []`
Sneaked in a change to the `HttpTestServer` to cancel the acceptor that is currently listening to accept connections.
=> Fix the next batch of memory leaks

conf/core/ConfigOptions.asciidoc, docs/commands/score-matches.asciidoc, hoot-core-test/src/test/cpp/hoot/core/language/HootServicesLanguageDetectorClientTest.cpp, hoot-core-test/src/test/cpp/hoot/core/language/HootServicesTranslatorClientTest.cpp, hoot-core-test/src/test/cpp/hoot/core/ops/ManualMatchValidatorTest.cpp, hoot-core/src/main/cpp/hoot/core/cmd/ScoreMatchesCmd.cpp, hoot-core/src/main/cpp/hoot/core/ops/ManualMatchValidator.cpp, hoot-core/src/main/cpp/hoot/core/ops/ManualMatchValidator.h, hoot-core/src/main/cpp/hoot/core/util/StringUtils.cpp, hoot-core/src/main/cpp/hoot/core/util/StringUtils.h
Manual match IDs were originally implemented as UUIDs and currently they exist as 6 character hex. There are still some old regression tests around that use the UUIDs, so rather than spend the resources to update the input data, its easier to support the UUID on a case by case basis.
=> 3531 - Make ManualMatchValidator backward compatible with UUID manual match IDs

hoot-core/src/main/cpp/hoot/core/io/OgrWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/OgrWriter.h, hoot-core/src/main/cpp/hoot/core/ops/BuildingOutlineUpdateOp.cpp, hoot-core/src/main/cpp/hoot/core/util/GeometryUtils.cpp, tgs/src/main/cpp/tgs/DelaunayTriangulation/DelaunayTriangulation.cpp
Delaunay Triangulation `data` members weren't being deleted.
`Geometry::Union` doesn't assume ownership of memory passed in.
`OgrWriter` was leaking projection objects.
=> Valgrind memory leaks

hoot-core/src/main/cpp/hoot/core/cmd/ConflateCmd.cpp, hoot-core/src/main/cpp/hoot/core/conflate/highway/Roundabout.cpp, hoot-core/src/main/cpp/hoot/core/conflate/highway/Roundabout.h, hoot-core/src/main/cpp/hoot/core/ops/RemoveNodeByEid.cpp, hoot-core/src/main/cpp/hoot/core/ops/RemoveRoundabouts.cpp
Added a check to only remove nodes identified as extra by roundabout remove if they are unused by any ways.
=> 3530 - Prevent shared nodes from being removed from roundabouts

hoot-core-test/src/test/cpp/hoot/core/conflate/matching/GreedyConstrainedMatchesTest.cpp, hoot-core-test/src/test/cpp/hoot/core/conflate/matching/OptimalConstrainedMatchesTest.cpp, hoot-core-test/src/test/cpp/hoot/core/conflate/poi-polygon/PoiPolygonMergerCreatorTest.cpp, hoot-core/src/main/cpp/hoot/core/conflate/UnifyingConflator.cpp, hoot-core/src/main/cpp/hoot/core/conflate/UnifyingConflator.h, hoot-core/src/main/cpp/hoot/core/conflate/highway/HighwayMergerCreator.cpp, hoot-core/src/main/cpp/hoot/core/conflate/highway/HighwayMergerCreator.h, hoot-core/src/main/cpp/hoot/core/conflate/merging/MarkForReviewMergerCreator.cpp, hoot-core/src/main/cpp/hoot/core/conflate/merging/MarkForReviewMergerCreator.h, hoot-core/src/main/cpp/hoot/core/conflate/merging/MergerCreator.h, hoot-core/src/main/cpp/hoot/core/conflate/merging/MergerFactory.cpp, hoot-core/src/main/cpp/hoot/core/conflate/merging/MergerFactory.h, hoot-core/src/main/cpp/hoot/core/conflate/network/NetworkMergerCreator.cpp, hoot-core/src/main/cpp/hoot/core/conflate/network/NetworkMergerCreator.h, hoot-core/src/main/cpp/hoot/core/conflate/poi-polygon/PoiPolygonMergerCreator.cpp, hoot-core/src/main/cpp/hoot/core/conflate/poi-polygon/PoiPolygonMergerCreator.h, hoot-core/src/main/cpp/hoot/core/conflate/polygon/BuildingMergerCreator.cpp, hoot-core/src/main/cpp/hoot/core/conflate/polygon/BuildingMergerCreator.h, hoot-core/src/main/cpp/hoot/core/criterion/TagKeyContainsCriterion.h, hoot-js/src/main/cpp/hoot/js/conflate/matching/ScriptMatch.cpp, hoot-js/src/main/cpp/hoot/js/conflate/merging/ScriptMergerCreator.cpp, hoot-js/src/main/cpp/hoot/js/conflate/merging/ScriptMergerCreator.h, hoot-rnd/src/main/cpp/hoot/rnd/conflate/multiary/MultiaryPoiMergeCache.cpp, hoot-rnd/src/main/cpp/hoot/rnd/conflate/multiary/MultiaryPoiMergerCreator.cpp, hoot-rnd/src/main/cpp/hoot/rnd/conflate/multiary/MultiaryPoiMergerCreator.h
Replaced all vector<Merger*> objects with vector<MergerPtr> objects to stop memory leaks.
Also found a place where a class member wasn't being initialized.
=> Valgrind Memory Leaks - Mergers

hoot-core/src/main/cpp/hoot/core/conflate/highway/Roundabout.cpp, hoot-test/src/main/cpp/hoot/test/main.cpp
Reorganize the `HootTest` command to combine --exclude with `--all-names` and fix roundabout memory leak.
=> HootTest reorganization and memory leak fix.

hoot-core/src/main/cpp/hoot/core/visitors/AddExportTagsVisitor.cpp
I found that the `AddExportTagsVisitor` class wasn't exporting `hoot:id` when the `writer.include.debug.tags` setting was set.  The unit tests weren't catching it because of the use of `hoot diff` that ignores debug tags or the lack thereof.
=> Turn on hoot:id tag when writer.include.debug.tags=true

hoot-core/src/main/cpp/hoot/core/algorithms/WayJoiner.cpp, hoot-core/src/main/cpp/hoot/core/visitors/UpdateWayParentVisitor.cpp, hoot-core/src/main/cpp/hoot/core/visitors/UpdateWayParentVisitor.h, test-files/cmd/glacial/NetworkConflateCmdInputReverseTest/output.osm, test-files/cmd/glacial/PowerLineConflateTest/output.osm
When two ways are joined, one ID is lost.  If that happens to be a parent ID of another way there can be potential disconnects.  Added `UpdateWayParentVisitor` to update parent IDs to new ID when ways are joined.
=> Joining loses parent way IDs

hoot-core/src/main/cpp/hoot/core/elements/Element.h, hoot-core/src/main/cpp/hoot/core/elements/Node.cpp, hoot-core/src/main/cpp/hoot/core/elements/Node.h, hoot-core/src/main/cpp/hoot/core/elements/Relation.cpp, hoot-core/src/main/cpp/hoot/core/elements/Relation.h, hoot-core/src/main/cpp/hoot/core/elements/Way.h
Refs #3587 
The other PR is having some real issues with un-reproducible unit test failures.  Here is the first set of changes to commit.  Updated elements to use virtual envelope functions.
=> Split OsmMap objects into smaller maps using tiles

conf/core/ConfigOptions.asciidoc, hoot-core-test/src/test/cpp/hoot/core/io/OsmJsonReaderTest.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmJsonReader.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmJsonReader.h, hoot-core/src/main/cpp/hoot/core/visitors/ReportMissingElementsVisitor.h, test-files/cmd/glacial/serial/RndServiceChangesetReplacement.sh.off, test-files/io/OsmJsonReaderTest/elementTypeUnorderedTest-in.json, test-files/io/OsmJsonReaderTest/elementTypeUnorderedTest.osm
Child elements aren't guaranteed to come before parent elements in Overpass JSON, so remove some erroneous related checks in `OsmJsonReader` by default. Added a temporary option, `json.reader.require.strict.type.ordering`, turned off by default. The changeset replacement derivation tests blow up when is isn't enabled. #3619 will deal with fixing them and removing the config option entirely.
=> Fix json reader element type ordering bug

.circleci/config.yml, VagrantProvisionCentOS7.sh, hoot-core/hoot-core.pro, scripts/copyright/UpdateAllCopyrightHeaders.sh, scripts/copyright/UpdateDirCopyrightHeaders.sh
Substituted bash for loop with the 'parallel' command to run copyright checks in parallel.
Local the copyright updates before:
```
real	6m51.342s
user	5m34.281s
sys	1m20.441s
```
and after with directories running in parallel:
```
real	3m38.778s
user	4m25.081s
sys	1m2.945s
```
Almost a 2x speed-up.
=> Run copyright checks in parallel

hoot-core-test/src/test/cpp/hoot/core/io/OsmApiWriterTest.cpp, hoot-core/src/main/cpp/hoot/core/cmd/ChangesetApplyCmd.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangeset.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangeset.h, hoot-core/src/main/cpp/hoot/core/io/OsmApiWriter.h, test-files/io/OsmChangesetElementTest/ChangesetConflictExpected-error.osc, test-files/io/OsmChangesetElementTest/RetryConflictExpected-error.osc
When changeset uploads hang or error out, sometimes the error changeset isn't written.  Have `OsmApiChangeset` write out the error changeset each time it is updated so that errors show up for debugging.
=> Write Error file to disk as errors occur

hoot-services/src/main/java/hoot/services/controllers/export/ExportCommand.java
NOTE: This will only work if the template exists. If it doesn't then nothing happens and we get the normal export.
=> Enable the TDSv70 template in services

hoot-core-test/src/test/cpp/hoot/core/io/OsmApiChangesetElementTest.cpp, hoot-core/src/main/cpp/hoot/core/elements/ElementType.h, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangeset.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangeset.h, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangesetElement.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangesetElement.h
PR consists of two major changes (and some renaming of classes and functions).
1. Read strings from file and save them in the changeset element objects instead of using `QXmlStreamAttributes` objects as they are read from the XML stream.
2. Reduced the number of ID to ID maps to keep track of old and new IDs as negative IDs are replaced by positive IDs as the upload process goes on.
I ran a couple of tests on different sized files and the results are below.  The toy test shows some big changes and also shows the approximate minimum memory footprint (approx. 81 MB) for a `changeset-apply` operation.  The Djibouti dataset shows the memory savings in dramatic fashion.
```
ToyTestA.osc (All adds)
5.4 KB changeset file
Before:
105 MB memory usage
After:
81 MB memory usage
Djibouti-latest (All …
```
=> Changeset upload improve memory footprint

conf/core/ConfigOptions.asciidoc, hoot-core-test/src/test/cpp/hoot/core/io/OsmApiChangesetTest.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangeset.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangeset.h, hoot-core/src/main/cpp/hoot/core/io/OsmApiWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiWriter.h
An OSM API changeset (`/api/0.6/changeset/create`) can include multiple `osmChange` uploads (`/api/0.6/changeset/#id/upload`) before closing it (`/api/0.6/changeset/#id/close`).  So this opens a changeset and commits multiple uploads to it before hitting the 50k limit before closing it.  This reduces the number of changesets committed and the overhead associated with opening and closing so many changesets.
=> Keep changesets open until they near the 50k limit

hoot-core/src/main/cpp/hoot/core/io/ApiDb.h, hoot-services/src/main/java/hoot/services/controllers/conflation/ConflateResource.java, hoot-services/src/main/java/hoot/services/controllers/grail/GrailResource.java, hoot-services/src/main/java/hoot/services/job/Job.java, hoot-services/src/main/java/hoot/services/job/JobRunnable.java, hoot-services/src/main/java/hoot/services/job/JobStatusManagerImpl.java, hoot-services/src/main/java/hoot/services/models/db/JobStatus.java, hoot-services/src/main/java/hoot/services/models/db/QJobStatus.java, hoot-services/src/main/java/hoot/services/utils/DbUtils.java, hoot-services/src/main/resources/db/changelogs/029-AddJobStatusTags.xml
these extra tags get used when pushing the changeset for actions such as refreshing input1 of the job or setting the parent jobs to stale
ref #3648
=> Fixed #3648. store tags in job status such as parent job id and inputs

hoot-core-test/src/test/cpp/hoot/core/io/OsmApiWriterTest.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangeset.cpp, test-files/io/OsmChangesetElementTest/ChangesetErrorFixErrors.osc, test-files/io/OsmChangesetElementTest/ChangesetMergeExpected.osc, test-files/io/OsmChangesetElementTest/DeleteSplit1.osc, test-files/io/OsmChangesetElementTest/DeleteSplit3.osc, test-files/io/OsmChangesetElementTest/DeleteSplit4.osc, test-files/io/OsmChangesetElementTest/RetryConflictExpected-error.osc
Added 'if-unused' argument to all 'delete' sections of changesets when they are pushed to the OSM API.
=> Delete if unused in changesets

hoot-core/src/main/cpp/hoot/core/cmd/ChangesetApplyCmd.cpp
Remove IP address from changeset-apply command in the LOG_STATUS message.
=> Remove the IP address from log messages to UI

hoot-core-test/src/test/cpp/hoot/core/io/OsmApiChangesetTest.cpp, hoot-core-test/src/test/cpp/hoot/core/io/OsmApiWriterTestServer.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangeset.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangeset.h, hoot-core/src/main/cpp/hoot/core/io/OsmApiWriter.cpp
There is a difference between `cgimap` and rails port error messages.  Update the `OsmApiWriter` to recognize both of them so that error handling works better.  Also `cgimap` requires the trailing `/` in the API calls to not be there.  Both work without, so they are removed.
=> Error processing for OsmApiWriter

scripts/copyright/UpdateAllCopyrightHeaders.sh, scripts/copyright/UpdateCopyrightHeader.py, scripts/copyright/UpdateDirCopyrightHeaders.sh
Updated copyright scripts with debug mode and better year checking logic.  https://github.com/ngageoint/hootenanny/pull/3689 is failing because of bad copyright year logic.  The files are fine but the scripts are saying that they need to be updated.
=> Copyright scripts, new decade, new problems

conf/core/ConfigOptions.asciidoc, hoot-core-test/src/test/cpp/hoot/core/io/OsmXmlReaderTest.cpp, hoot-core/src/main/cpp/hoot/core/io/ApiDbReader.h, hoot-core/src/main/cpp/hoot/core/io/HootApiDbReader.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiDbReader.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiReader.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmJsonReader.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmJsonReader.h, hoot-core/src/main/cpp/hoot/core/io/OsmMapReader.h, hoot-core/src/main/cpp/hoot/core/io/OsmPbfReader.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmPbfReader.h, hoot-core/src/main/cpp/hoot/core/io/OsmXmlReader.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmXmlReader.h, test-files/io/OsmXmlReaderTest/IgnoreDuplicateMergeTest-1.osm, test-files/io/OsmXmlReaderTest/IgnoreDuplicateMergeTest-2.osm, test-files/io/OsmXmlReaderTest/IgnoreDuplicateMergeTest.osm
It was requested to allow readers to open multiple datasets that share overlapping elements, for example a way that spans both bounding boxes and is contained in both datasets.  If the elements are overlapping (checked by type and ID only) then all instances after the first are completely ignored.  There is no comparisons, conflating, or merging done, everything after the first instance is dropped.  In the use case, matching IDs indicate it is the same exact element and nothing has changed with it.  In order to enable this option add `-D map.merge.ignore.duplicate.ids=true` to the `hoot` command.
=> Merge duplicate IDs in readers

hoot-core-test/src/test/cpp/hoot/core/auth/ServicesHootServicesLoginManagerTest.cpp, hoot-core-test/src/test/cpp/hoot/core/io/ServiceHootApiDbBulkInserterTest.cpp, hoot-core-test/src/test/cpp/hoot/core/io/ServiceHootApiDbReaderTest.cpp, hoot-core-test/src/test/cpp/hoot/core/io/ServiceHootApiDbTest.cpp, hoot-core-test/src/test/cpp/hoot/core/io/ServiceHootApiDbWriterTest.cpp, hoot-core-test/src/test/cpp/hoot/core/io/ServiceOsmApiDbBulkInserterTest.cpp, hoot-core-test/src/test/cpp/hoot/core/io/ServiceOsmApiDbReaderTest.cpp, hoot-core-test/src/test/cpp/hoot/core/io/ServiceOsmApiDbSqlChangesetApplierTest.cpp, hoot-core-test/src/test/cpp/hoot/core/io/ServiceOsmApiDbSqlChangesetFileWriterTest.cpp, hoot-core-test/src/test/cpp/hoot/core/io/ServiceOsmApiDbTest.cpp, hoot-core-test/src/test/cpp/hoot/core/io/ServicesDbTestUtils.cpp, hoot-core-test/src/test/cpp/hoot/core/io/ServicesDbTestUtils.h, hoot-core-test/src/test/cpp/hoot/core/language/HootServicesLanguageDetectorClientTest.cpp, hoot-core-test/src/test/cpp/hoot/core/language/HootServicesLanguageInfoClientTest.cpp, hoot-core-test/src/test/cpp/hoot/core/language/HootServicesLanguageInfoResponseParserTest.cpp, hoot-core-test/src/test/cpp/hoot/core/language/HootServicesTranslatorClientTest.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiWriter.cpp
Quite a few of the services tests are still enabled when `--with-services` isn't provided to configure this is causing issues in the `TestConfigure.sh` script where the database isn't created but is needed for these tests.
=> Disable services tests when no services are enabled

hoot-core/src/main/cpp/hoot/core/io/HootApiDb.cpp, hoot-core/src/main/cpp/hoot/core/io/HootApiDb.h, hoot-core/src/main/cpp/hoot/core/io/SqlBulkInsert.cpp, hoot-core/src/main/cpp/hoot/core/io/SqlBulkInsert.h
Added `ON CONFLICT DO NOTHING` to bulk inserts so that conflicting IDs are ignored.
See [this](https://www.postgresql.org/docs/9.5/sql-insert.html#SQL-ON-CONFLICT) for more information.
=> Ignore duplicate IDs bulk insert

hoot-core/src/main/cpp/hoot/core/io/OsmApiDb.cpp
Using TRUNCATE TABLE instead of DELETE FROM when removing all data because it is significantly faster.
=> Use TRUNCATE instead of DELETE FROM

hoot-core-test/src/test/cpp/hoot/core/util/SettingsTest.cpp, hoot-core/src/main/cpp/hoot/core/index/ClosePointHash.cpp, hoot-core/src/main/cpp/hoot/core/ops/DuplicateNodeRemover.cpp, hoot-core/src/main/cpp/hoot/core/util/Settings.cpp, hoot-core/src/main/cpp/hoot/core/util/Settings.h, test-files/cmd/glacial/serial/ServiceChangesetReplacementAdditionalFiltersChainedTest.sh, test-files/cmd/quick/ConflateUnknownOptionTest.sh, test-files/cmd/quick/ConflateUnknownOptionTest.sh.stderr
* Validates that class inputs are either a `OsmMapOperation`, `ElementVisitor`, or `ElementCriterion` for the following opts:
* `convert.ops`
* `conflate.pre.ops`
* `conflate.post.ops`
* Moved test functionality from `ConflateUnknownOptionTest.sh` into `SettingsTest`
=> 3738 - Error out early if bad operator class names are provided for select config opts

hoot-core/src/main/cpp/hoot/core/ops/SearchRadiusCalculator.cpp
Some nasty map copying going on in `SearchRadiusCalculator` that shouldn't have been in there.
=> Make search radius calculation more memory efficient

hoot-core/src/main/cpp/hoot/core/conflate/SearchBoundsCalculator.cpp, hoot-core/src/main/cpp/hoot/core/conflate/SearchRadiusProvider.h, hoot-core/src/main/cpp/hoot/core/conflate/highway/HighwayMatchCreator.cpp, hoot-core/src/main/cpp/hoot/core/conflate/highway/HighwayMatchCreator.h, hoot-core/src/main/cpp/hoot/core/conflate/matching/MatchCreator.h, hoot-core/src/main/cpp/hoot/core/conflate/matching/MatchFactory.cpp, hoot-core/src/main/cpp/hoot/core/conflate/matching/MatchFactory.h, hoot-core/src/main/cpp/hoot/core/conflate/network/NetworkMatchCreator.cpp, hoot-core/src/main/cpp/hoot/core/conflate/network/NetworkMatchCreator.h, hoot-core/src/main/cpp/hoot/core/conflate/poi-polygon/PoiPolygonMatchCreator.cpp, hoot-core/src/main/cpp/hoot/core/conflate/poi-polygon/PoiPolygonMatchCreator.h, hoot-core/src/main/cpp/hoot/core/conflate/polygon/BuildingMatchCreator.cpp, hoot-core/src/main/cpp/hoot/core/conflate/polygon/BuildingMatchCreator.h, hoot-core/src/main/cpp/hoot/core/conflate/review/ReviewMarker.cpp, hoot-core/src/main/cpp/hoot/core/ops/AddHilbertReviewSortOrderOp.h, hoot-core/src/main/cpp/hoot/core/ops/ManualMatchValidator.cpp, hoot-core/src/main/cpp/hoot/core/ops/RemoveDuplicateReviewsOp.cpp, hoot-core/src/main/cpp/hoot/core/ops/SearchRadiusCalculator.cpp, hoot-core/src/main/cpp/hoot/core/visitors/poi-polygon/PoiPolygonMatchVisitor.cpp, hoot-js/src/main/cpp/hoot/js/conflate/matching/ScriptMatch.cpp, hoot-js/src/main/cpp/hoot/js/conflate/matching/ScriptMatchCreator.cpp, hoot-js/src/main/cpp/hoot/js/conflate/matching/ScriptMatchCreator.h
* Removes a bottleneck exposed by `RemoveDuplicateReviewsOp` where the constructor of `ScriptMatchVisitor` was called repeatedly and had several script calls which are very expensives
* This fix prevents somalia 3 and poi 6 regression tests from failing.
=> 3755 - Remove script matching memory/processing bottleneck

hoot-services/src/main/java/hoot/services/command/ExternalCommandRunnerImpl.java, hoot-services/src/main/java/hoot/services/job/JobRunnable.java
refs https://github.com/ngageoint/hootenanny-ui/issues/1729
adds some logging to see when the process terminate call is made vs when the executor receives the exit code.  For conflate commands (vs import or export) a ~30 second delay between the two has been observed.
=> add some logging around job cancel, don't show failed message

hoot-core/src/main/cpp/hoot/core/conflate/DiffConflator.cpp
The part which saves off the map to make the way snapping work in the output changeset was copying more features than it needed to.
=> 3768 - Remove unnecessary feature copying from diff conflate

conf/core/ConfigOptions.asciidoc, conf/services/conflationTypes.json, hoot-core/src/main/cpp/hoot/core/conflate/highway/HighwayMatchCreator.cpp, hoot-core/src/main/cpp/hoot/core/conflate/network/NetworkMatchCreator.cpp, hoot-core/src/main/cpp/hoot/core/conflate/poi-polygon/PoiPolygonMatchCreator.cpp, hoot-core/src/main/cpp/hoot/core/conflate/polygon/BuildingMatchCreator.cpp, hoot-js/src/main/cpp/hoot/js/conflate/matching/ScriptMatchCreator.cpp
It was the only one left that wasn't. Also exposed `error.circular.default` in the adv opts.
=> Make building search radius configurable

docs/user/CommandLineExamples.asciidoc, hoot-core/src/main/cpp/hoot/core/cmd/ConflateCmd.cpp, hoot-core/src/main/cpp/hoot/core/cmd/ConflateCmd.h, hoot-core/src/main/cpp/hoot/core/conflate/matching/MatchFactory.cpp, hoot-core/src/main/cpp/hoot/core/ops/RemoveRoundabouts.cpp, test-files/cases/attribute/network/highway-3784-roundabouts-1/Expected.osm, test-files/cases/attribute/network/highway-3784-roundabouts-1/Input1.osm, test-files/cases/attribute/network/highway-3784-roundabouts-1/Input2.osm, test-files/cases/attribute/network/highway-3784-roundabouts-1/README.txt, test-files/cases/attribute/unifying/highway-3784-roundabouts-1/Expected.osm, test-files/cases/attribute/unifying/highway-3784-roundabouts-1/Input1.osm, test-files/cases/attribute/unifying/highway-3784-roundabouts-1/Input2.osm, test-files/cases/attribute/unifying/highway-3784-roundabouts-1/README.txt
Roundabout handling involving removal/replacement is not needed in Attribute Conflation and has been removed. Prior to this change it would cause portions of reference roads to be dropped in the output.
=> 3784 - Handle roundabouts correctly in Attribute Conflation

hoot-services/src/main/java/hoot/services/job/JobRunnable.java
introduced when making sure cancelled jobs didn't call setFailed()
because exit codes are also non-zero
=> fix bug where jobs with legit error were still getting marked success

docs/commands/changeset-apply.asciidoc, hoot-core-test/src/test/cpp/hoot/core/io/OsmApiWriterTest.cpp, hoot-core/src/main/cpp/hoot/core/cmd/ChangesetApplyCmd.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangeset.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangeset.h, hoot-core/src/main/cpp/hoot/core/io/OsmApiWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiWriter.h, sonar-project.properties, test-files/io/OsmChangesetElementTest/ApplyChangesetTest-Expected-1-0001.osc, test-files/io/OsmChangesetElementTest/ApplyChangesetTest-Expected-2-0001.osc, test-files/io/OsmChangesetElementTest/ApplyChangesetTest-Expected-2-0002.osc
The `--test-apply` flag creates apply `.osc` files for each communication to the server that the `changeset-apply` would send.  These are for debugging purposes only because the files cannot be applied to the API by themselves.  Updated documentation and unit tests.
Bonus addition:  SonarCloud has a warning displayed for cached elements.  Turn off that option to make the warning go away since it isn't needed.
=> Add '--test-apply' flag to 'changeset-apply' command

hoot-services/src/main/java/hoot/services/controllers/grail/ApplyChangesetCommand.java
unescaped chars like `&` were causing parsing error on osm api side
`WARN	Bad changeset ID. Resetting network request object.`
which caused the changeset create request to be retried over and over
=> escape tags going into changeset xml

scripts/jenkins/Jenkinsfile
The core tests have been going deep into swap and slowing down unnecessarily for some time now and recently running out of memory periodically. Some of the tests require extra memory now and the overall memory will have to be increased on the test vm to run in full parallel. This solves the issue for now. We can go back and try to increase the value back to full parallel at some point in the future after looking more closely at the tests.
=> reduce core test parallel

hoot-core/src/main/cpp/hoot/core/conflate/DiffConflator.cpp, test-files/cmd/slow/serial/ServiceDiffNetworkRoadSnapTest.sh.stdout
Bug where tag diff was being calculated regardless. This change will save a ton of runtime on very large jobs running Diff w/o tags.
merge after #3810
=> 3805 - Don't calc tag diff when not running Differential Conflation w/ Tags

docs/commands/diff.asciidoc, hoot-core/src/main/cpp/hoot/core/cmd/DiffCmd.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangeset.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangeset.h, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangesetElement.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangesetElement.h, test-files/cmd/quick/DiffCmdChangesetTest.sh, test-files/cmd/quick/DiffCmdChangesetTest.sh.stdout, test-files/cmd/quick/DiffCmdChangesetTest/Failure/OsmApiWriter-000001-00002-Request--000.osc, test-files/cmd/quick/DiffCmdChangesetTest/Failure/OsmApiWriter-000001-00002-Response-200.osc, test-files/cmd/quick/DiffCmdChangesetTest/Failure/OsmApiWriter-000002-00002-Request--000.osc, test-files/cmd/quick/DiffCmdChangesetTest/Failure/OsmApiWriter-000002-00002-Response-200.osc, test-files/cmd/quick/DiffCmdChangesetTest/Failure/OsmApiWriter-000005-00002-Request--000.osc, test-files/cmd/quick/DiffCmdChangesetTest/Failure/OsmApiWriter-000005-00002-Response-200.osc, test-files/cmd/quick/DiffCmdChangesetTest/Failure/OsmApiWriter-000006-00002-Request--000.osc, test-files/cmd/quick/DiffCmdChangesetTest/Failure/OsmApiWriter-000006-00002-Response-200.osc, test-files/cmd/quick/DiffCmdChangesetTest/Success/OsmApiWriter-000001-00002-Request--000.osc, test-files/cmd/quick/DiffCmdChangesetTest/Success/OsmApiWriter-000001-00002-Response-200.osc, test-files/cmd/quick/DiffCmdChangesetTest/Success/OsmApiWriter-000002-00002-Request--000.osc, test-files/cmd/quick/DiffCmdChangesetTest/Success/OsmApiWriter-000002-00002-Response-200.osc, test-files/cmd/quick/DiffCmdChangesetTest/Success/OsmApiWriter-000003-00002-Request--000.osc, test-files/cmd/quick/DiffCmdChangesetTest/Success/OsmApiWriter-000003-00002-Response-200.osc, test-files/cmd/quick/DiffCmdChangesetTest/Success/OsmApiWriter-000004-00002-Request--000.osc, test-files/cmd/quick/DiffCmdChangesetTest/Success/OsmApiWriter-000004-00002-Response-200.osc, test-files/cmd/quick/DiffCmdChangesetTest/Success/OsmApiWriter-000005-00002-Request--000.osc, test-files/cmd/quick/DiffCmdChangesetTest/Success/OsmApiWriter-000005-00002-Response-200.osc, test-files/cmd/quick/DiffCmdChangesetTest/Success/OsmApiWriter-000006-00002-Request--000.osc, test-files/cmd/quick/DiffCmdChangesetTest/Success/OsmApiWriter-000006-00002-Response-200.osc
Add logic to the `hoot diff` command to read `.osc` files and directories of `.osc` files output from `hoot changeset-apply` to debug any upload issues that may occur.
Closes #3860
=> Add 'diff' option for changeset apply debug output

conf/core/ConfigOptions.asciidoc, hoot-core-test/src/test/cpp/hoot/core/io/ServiceHootApiDbWriterTest.cpp, hoot-core/src/main/cpp/hoot/core/io/HootApiDb.cpp, hoot-core/src/main/cpp/hoot/core/io/HootApiDb.h, hoot-core/src/main/cpp/hoot/core/io/HootApiDbWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/HootApiDbWriter.h
Adds option for preserving existing element version during an insert to an Hoot API DB table. From the command line use the option `hootapi.db.writer.preserve.version.on.insert=true`.
=> 3864 - Preserve element version in HootApiDbWriter during new element write

hoot-core-test/src/test/cpp/hoot/core/algorithms/changeset/ChangesetCreatorTest.cpp, hoot-core/src/main/cpp/hoot/core/cmd/ChangesetDeriveCmd.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmXmlChangesetFileWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmXmlChangesetFileWriter.h, test-files/algorithms/changeset/ChangesetCreatorTest/ChangesetDeriveUpdateVersion_expected.osc, test-files/algorithms/changeset/ChangesetCreatorTest/ChangesetDeriveUpdateVersion_ref.osm, test-files/algorithms/changeset/ChangesetCreatorTest/ChangesetDeriveUpdateVersion_sec.osm
Use the reference dataset's version number for modify/delete operations when deriving a changeset because that has a higher likelihood of being the most current version in the API.
Closes #3870
=> Update Changeset Derive to use the reference version number if different

hoot-core/src/main/cpp/hoot/core/algorithms/perty/PertyMatchScorer.cpp, hoot-core/src/main/cpp/hoot/core/cmd/ConflateCmd.cpp, hoot-core/src/main/cpp/hoot/core/cmd/ConvertCmd.cpp, hoot-core/src/main/cpp/hoot/core/cmd/DiffCmd.cpp, hoot-core/src/main/cpp/hoot/core/cmd/ScoreMatchesCmd.cpp, hoot-core/src/main/cpp/hoot/core/io/DataConverter.cpp, hoot-core/src/main/cpp/hoot/core/io/ElementStreamer.cpp, hoot-core/src/main/cpp/hoot/core/io/IoUtils.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmMapReaderFactory.cpp, hoot-core/src/main/cpp/hoot/core/util/ConfigUtils.cpp, hoot-core/src/main/cpp/hoot/core/util/ConfigUtils.h, test-files/cmd/quick/DuplicateNodeRemoverTest.sh, test-files/cmd/quick/DuplicateNodeRemoverTest/input.json, test-files/cmd/quick/DuplicateNodeRemoverTest/output.json
Prior to this change calls to the `convert` command with `DuplicateNodeRemover` in `convert.ops` would result in a map read error due to `map.merge.ignore.duplicate.ids=false`. This change ensures that `map.merge.ignore.duplicate.ids=true` when `DuplicateNodeRemover` is in the `convert` pipeline.
Also added the same change to the `conflate` pipeline for consistency, even though `DuplicateNodeRemover` seemed to be working there already.
=> Fix DuplicateNodeRemover in convert pipeline

conf/core/DifferentialConflation.conf, hoot-core/src/main/cpp/hoot/core/conflate/DiffConflator.cpp
When differential is run with `differential.snap.unconnected.roads` turned on, the reference map is passed in as the base for the changeset derivation, this causes every element in the reference to have a `<delete>` entry in the changeset.  This is bad.  This can be solved by setting `changeset.allow.deleting.reference.features=false` in the differential conflation configuration file.
Closes #3877
=> Differential conflation cannot contain deletes.

hoot-core/src/main/cpp/hoot/core/conflate/UnifyingConflator.cpp, hoot-core/src/main/cpp/hoot/core/conflate/poi-polygon/PoiPolygonMerger.cpp
was running the POI/Poly review cleanup in multiple merges rather than at the end of the conflate job
=> Performance fix for 3857

conf/schema/FCODE.json, translations/tds61.js, translations/tds70.js
refs: #3888
Files without F_CODE fields rely on matching the layername. This changes it from `==` to a regexp match.
=> Translations: Layername matching fix

conf/core/ConfigOptions.asciidoc, hoot-core/src/main/cpp/hoot/core/elements/ElementType.h, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangeset.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangeset.h, hoot-core/src/main/cpp/hoot/core/io/OsmApiWriter.cpp
Check the size of the element and associated elements before trying to put together a huge changeset.  Also changed `changeset.max.size` from 50k (which is the limit for `api/0.6/map`) to 10k (which is the limit for `api/0.6/changeset/<id>/upload`).
Closes #3890
=> 'changeset-apply' with huge relations fails

hoot-core/src/main/cpp/hoot/core/conflate/highway/HighwayMatchCreator.cpp, hoot-core/src/main/cpp/hoot/core/elements/Tags.cpp, hoot-core/src/main/cpp/hoot/core/elements/Tags.h, hoot-core/src/main/cpp/hoot/core/ops/SmallHighwayMerger.cpp, hoot-core/src/main/cpp/hoot/core/schema/OsmSchema.cpp, hoot-core/src/main/cpp/hoot/core/schema/TagAncestorDifferencer.h, hoot-core/src/main/cpp/hoot/core/schema/TagFilteredDifferencer.cpp, hoot-js/src/main/cpp/hoot/js/conflate/matching/ScriptMatchCreator.cpp, test-files/cases/unifying/sidewalk-3895/Expected.osm, test-files/cases/unifying/sidewalk-3895/Input1.osm, test-files/cases/unifying/sidewalk-3895/Input2.osm, test-files/cases/unifying/sidewalk-3895/README.txt
Made the tag similarity threshold required for road matching more strict when sidewalks are involved. The value may need additional tweaking. The more appropriate way to handle this would have been in the schema, but as noted in the code, due to the large amount of interrelations between highway types in the schema I couldn't get that to work. May be able to go back later and move the change to the schema instead.
Also discovered a related issue where `footway=crossing` features get snapped incorrectly and opened #3901 for it.
=> 3895 - Prevent sidewalks from conflating with roads

hoot-core-test/src/test/cpp/hoot/core/algorithms/alpha-shape/AlphaShapeGeneratorTest.cpp, hoot-core/src/main/cpp/hoot/core/algorithms/alpha-shape/AlphaShape.cpp, hoot-core/src/main/cpp/hoot/core/algorithms/alpha-shape/AlphaShape.h, hoot-core/src/main/cpp/hoot/core/algorithms/alpha-shape/AlphaShapeGenerator.cpp, hoot-core/src/main/cpp/hoot/core/algorithms/alpha-shape/AlphaShapeGenerator.h, hoot-core/src/main/cpp/hoot/core/algorithms/changeset/ChangesetCreator.cpp, hoot-core/src/main/cpp/hoot/core/algorithms/changeset/ChangesetReplacementCreator.cpp, hoot-core/src/main/cpp/hoot/core/algorithms/changeset/ChangesetReplacementCreator.h, hoot-core/src/main/cpp/hoot/core/algorithms/extractors/poi-polygon/PoiPolygonAlphaShapeDistanceExtractor.cpp
After this change, `AlphaShapeGenerator` will try a second time to generate an alpha shape if the generation fails the first time when the alpha value is too small. It will do this only if any alpha shape edge face size is larger than the initial alpha value and use the largest face size for the alpha value.
=> 3896 - Add auto-retry for Alpha Shape generation when initial alpha too small

hoot-core-test/src/test/cpp/hoot/core/io/OsmApiWriterTest.cpp, hoot-core-test/src/test/cpp/hoot/core/io/OsmApiWriterTestServer.cpp, hoot-core-test/src/test/cpp/hoot/core/io/OsmApiWriterTestServer.h, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangeset.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangeset.h, hoot-core/src/main/cpp/hoot/core/io/OsmApiWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiWriter.h, hoot-core/src/main/cpp/hoot/core/util/HootNetworkUtils.h, hoot-test/src/main/cpp/hoot/test/ProcessPool.cpp
The API can fail to create a new changeset ID for numerous reasons, permission being one, and `changeset-apply` wasn't handling these failures correctly.  Also found and fixed an issue in the unit testing framework where parallel processes didn't shutdown correctly and left the main process running forever.
Closes #3936
=> Repeated changeset create failures

hoot-core/src/main/cpp/hoot/core/algorithms/WayJoiner.cpp, hoot-core/src/main/cpp/hoot/core/algorithms/WayJoiner.h, hoot-core/src/main/cpp/hoot/core/algorithms/WayJoinerAdvanced.cpp, hoot-core/src/main/cpp/hoot/core/algorithms/WayJoinerAdvanced.h
* This combined with the previous related PR yielded ~27% default way joining performance improvement for the #3892 data. To be fair, timing from Vagrant is always suspect between runs, so it could be less.
* Also implemented progress logging for `WayJoinerAdvanced`.
=> Small runtime perf improvement tweaks

hoot-core/src/main/cpp/hoot/core/cmd/ChangesetDeriveReplacementCmd.cpp, hoot-core/src/main/cpp/hoot/core/index/OsmMapIndex.cpp
Certain datasets cause a crash in `changeset-derive-replacement`.  I was unable to track down where the node in the relation isn't update when the relation is deleted but this will fix the crash.
=> Fix changeset-derive-replacement crash

hoot-js/src/main/cpp/hoot/js/schema/OsmSchemaJs.cpp, rules/Area.js, test-files/cases/differential/area-3978/Config.conf, test-files/cases/differential/area-3978/Expected.osm, test-files/cases/differential/area-3978/Input1.osm, test-files/cases/differential/area-3978/Input2.osm, test-files/cases/differential/area-3978/README.txt
Area Conflation was trained primarily on one to one matches. There was a recent request to diff conflate some `landuse=residential` where the secondary data consisted of a lot of smaller areas that overlapped with reference areas in a many to one fashion. These changes flag those situations as reviews, which allows them to fall out of the diff output with the default config of `differential.treat.reviews.as.matches=true`.
=> 3978 - Handle many to one area matches

hoot-core/src/main/cpp/hoot/core/algorithms/linearreference/WaySubline.cpp, hoot-core/src/main/cpp/hoot/core/criterion/CollectionRelationCriterion.cpp, hoot-core/src/main/cpp/hoot/core/criterion/LinearCriterion.cpp, hoot-core/src/main/cpp/hoot/core/criterion/LinearCriterion.h, hoot-core/src/main/cpp/hoot/core/elements/ElementConverter.cpp
Turn restriction relations were being dropped during `changeset-derive-replacement` operations.  This recognizes them as linear features and allows them to be processed.
=> Fix restriction relations in changeset-derive-replacement

VagrantProvisionCentOS7.sh, hoot-core-test/src/test/cpp/hoot/core/io/OsmApiChangesetTest.cpp, hoot-core-test/src/test/cpp/hoot/core/io/OsmApiWriterTest.cpp, hoot-core-test/src/test/cpp/hoot/core/io/OsmApiWriterTestServer.cpp, hoot-core-test/src/test/cpp/hoot/core/io/OsmApiWriterTestServer.h, hoot-core-test/src/test/cpp/hoot/core/util/HttpTestServer.cpp, hoot-core-test/src/test/cpp/hoot/core/util/HttpTestServer.h, hoot-core/src/main/cpp/hoot/core/elements/OsmMap.h, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangeset.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangeset.h, hoot-core/src/main/cpp/hoot/core/io/OsmApiWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiWriter.h, test-files/cmd/quick/ServiceDbListMapsCmdTest.sh, test-files/io/OsmChangesetElementTest/ChangesetOutput-Response-1.osc, test-files/io/OsmChangesetElementTest/ChangesetOutput-Response-2.osc, test-files/io/OsmChangesetElementTest/FailWayWithNodes-error.osc, test-files/io/OsmChangesetElementTest/ToyTestAFailure.osc
When a way is to be created along with new nodes that make it up and it fails, previously the nodes were pushed to the API and there were orphaned nodes.  This holds back those nodes and puts them in the error file along with the offending way so that they are all together and no nodes are orphaned in the API database.
Closes #3970
=> Fail Nodes With Failed Ways

hoot-core/src/main/cpp/hoot/core/io/OsmApiChangesetElement.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangesetElement.h
HTML encode the keys for tags because of bad input data
Closes #3992
=> Tag keys need to be HTML encoded

hoot-core/src/main/cpp/hoot/core/ops/SmallHighwayMerger.cpp
When `ElementConverter::convertToLineString()` function fails to create the line string object in `SmallHighwayMerger` the pointer is dereferenced without checks and causes Hootenanny to crash.
=> ElementConverter::convertToLineString() failure

hoot-core/src/main/cpp/hoot/core/io/OsmApiChangeset.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangeset.h, hoot-core/src/main/cpp/hoot/core/io/OsmApiWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiWriter.h
This particular failure was because a relation failed to be created and that relation was a member of another relation that was failing to be added to a changeset and failing to be recognized as unable to send.  Now when an element fails to be created, an parent element must also fail at the same time.
=> Some datasets get into an infinite loop at 99% complete

hoot-core-test/src/test/cpp/hoot/core/io/DataConverterTest.cpp, hoot-core/src/main/cpp/hoot/core/algorithms/changeset/ChangesetCreator.cpp, hoot-core/src/main/cpp/hoot/core/cmd/ConflateCmd.cpp, hoot-core/src/main/cpp/hoot/core/io/DataConverter.cpp, hoot-core/src/main/cpp/hoot/core/io/DataConverter.h, hoot-core/src/main/cpp/hoot/core/io/IoUtils.cpp, hoot-core/src/main/cpp/hoot/core/io/IoUtils.h
Affected `convert` and `conflate` commands
=> Don't allow commands to create an output dir for a URL target

hoot-core-test/src/test/cpp/hoot/core/TestUtils.cpp, hoot-core-test/src/test/cpp/hoot/core/TestUtils.h, hoot-core-test/src/test/cpp/hoot/core/algorithms/perty/PertyTestRunnerTest.cpp, hoot-core-test/src/test/cpp/hoot/core/conflate/network/EdgeMatchSetFinderTest.cpp, hoot-core-test/src/test/cpp/hoot/core/io/OgrWriterTest.cpp, hoot-core-test/src/test/cpp/hoot/core/ops/RelationWithMostMembersOpTest.cpp, hoot-core-test/src/test/cpp/hoot/core/scoring/MatchComparatorTest.cpp, hoot-core/src/main/cpp/hoot/core/algorithms/perty/PertyMatchScorer.cpp, hoot-core/src/main/cpp/hoot/core/algorithms/perty/PertyTestRunner.cpp, hoot-core/src/main/cpp/hoot/core/io/IoUtils.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmGbdxJsonWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmGbdxXmlWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/ShapefileWriter.cpp, hoot-core/src/main/cpp/hoot/core/schema/OsmSchema.cpp, hoot-core/src/main/cpp/hoot/core/scoring/GraphComparator.cpp, hoot-core/src/main/cpp/hoot/core/util/FileUtils.cpp, hoot-core/src/main/cpp/hoot/core/util/FileUtils.h, hoot-rnd/src/main/cpp/hoot/rnd/cmd/EvalPointMovesCmd.cpp, hoot-rnd/src/test/cpp/hoot/rnd/conflate/network/IterativeNetworkMatcherTest.cpp, hoot-rnd/src/test/cpp/hoot/rnd/conflate/network/SingleSidedNetworkMatcherTest.cpp, hoot-rnd/src/test/cpp/hoot/rnd/conflate/network/VagabondNetworkMatcherTest.cpp, test-files/cmd/glacial/OptimizeNetworkConflateSettingsCmdTest.sh
When a directory doesn't exist for writing files using `FileUtils::writeFully` it currently fails.  Instead of failing, attempt to create the path before writing.  Consolidate the uses of `QDir::mkpath` and `QDir::mkdir` to all use `FileUtils::makeDir`.
=> Create path for FileUtils::writeFully

hoot-core/src/main/cpp/hoot/core/io/OsmApiChangeset.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiWriter.h, hoot-core/src/main/cpp/hoot/core/util/Settings.cpp, hoot-core/src/main/cpp/hoot/core/util/Settings.h
Hoot failed with memory corruption and double free errors in the settings class.  Update the use of regular expression objects in Qt and waiting in the `OsmApiWriter` class.
=> Settings failure error

hoot-core-test/src/test/cpp/hoot/core/TestUtils.cpp, hoot-core-test/src/test/cpp/hoot/core/visitors/MatchCandidateCountVisitorTest.cpp, hoot-core/src/main/cpp/hoot/core/conflate/highway/HighwayClassifier.h, hoot-core/src/main/cpp/hoot/core/conflate/highway/HighwayRfClassifier.h, hoot-core/src/main/cpp/hoot/core/conflate/matching/MatchFactory.cpp, hoot-core/src/main/cpp/hoot/core/conflate/matching/MatchFactory.h, tgs/src/main/cpp/tgs/RandomForest/BaseRandomForest.cpp, tgs/src/main/cpp/tgs/RandomForest/RandomForest.cpp, tgs/src/main/cpp/tgs/RandomForest/RandomForest.h
Update `MatchFactory` class to use the Meyer's Singleton pattern.  `HighwayClassifier` based classes can have a memory leak that is fixed with this change.
Found while investigating #4070
=> HighwayRfClassifier memory leak

hoot-core/src/main/cpp/hoot/core/ops/AddHilbertReviewSortOrderOp.cpp, hoot-core/src/main/cpp/hoot/core/ops/AddHilbertReviewSortOrderOp.h, hoot-core/src/main/cpp/hoot/core/visitors/RemoveInvalidReviewRelationsVisitor.cpp
In the cut and replace workflow there may be review relations with references to elements that don't exist in the data. This fix is a continuation of #4093.
=> Prevent review relations with zero or only null members from breaking AddHilbertReviewSortOrderOp

hoot-core/src/main/cpp/hoot/core/io/OsmApiWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiWriter.h, hoot-core/src/main/cpp/hoot/core/util/HootNetworkUtils.h
Give the OSM API database time to breath if it becomes unavailable and starts returning HTTP 503 errors.
=> OsmApiWriter handle HTTP 503 responses

hoot-core-test/src/test/cpp/hoot/core/io/OsmApiWriterTest.cpp, hoot-core-test/src/test/cpp/hoot/core/io/OsmApiWriterTestServer.cpp, hoot-core-test/src/test/cpp/hoot/core/io/OsmApiWriterTestServer.h, hoot-core-test/src/test/cpp/hoot/core/util/HttpTestServer.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangeset.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangeset.h, hoot-core/src/main/cpp/hoot/core/io/OsmApiWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiWriter.h, test-files/io/OsmChangesetElementTest/VersionFailure-error.osc
Closes #4110 
Version failures are mitigated by requesting the offending element and updating version/tag information.  This takes quite some time.  Since the OSM API only returns one error, this process happens for each conflicting element.  If there are a lot of them Hootenanny tries for a while and then fails reporting to the user that their data is out of date.
=> Multiple version failures can grind changeset-upload to a halt

hoot-core/src/main/cpp/hoot/core/Hoot.cpp, hoot-core/src/main/cpp/hoot/core/io/HootNetworkRequest.cpp, hoot-core/src/main/cpp/hoot/core/io/ParallelBoundedApiReader.cpp, hoot-core/src/main/cpp/hoot/core/io/ParallelBoundedApiReader.h, hoot-core/src/main/cpp/hoot/core/util/HootNetworkUtils.h
Refs #4113
While working on cut & replace errors cropped up in the `ParallelBoundedApiReader` class and weren't being handled correctly.  Mostly unrelated to the actual errors in cut & replace.
=> ParallelBoundedApiReader error processing and Qt race conditions

hoot-core-test/src/test/cpp/hoot/core/io/OsmApiChangesetTest.cpp, hoot-core-test/src/test/cpp/hoot/core/io/OsmApiMatchFailureTest.cpp, hoot-core/src/main/cpp/hoot/core/io/HootNetworkRequest.cpp, hoot-core/src/main/cpp/hoot/core/io/HootNetworkRequest.h, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangeset.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangeset.h, hoot-core/src/main/cpp/hoot/core/io/OsmApiMatchFailure.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiMatchFailure.h, hoot-core/src/main/cpp/hoot/core/io/OsmApiWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/ParallelBoundedApiReader.cpp
Reduced error message count for `changeset-apply` by not sending things we know we cannot resolve more than once.  Also reorganized some of the error code for `changeset-apply`.
=> Reduce changeset-apply errors

conf/core/ConfigOptions.asciidoc, hoot-core-test/src/test/cpp/hoot/core/algorithms/extractors/poi-polygon/PoiPolygonNameScoreExtractorTest.cpp, hoot-core-test/src/test/cpp/hoot/core/algorithms/extractors/poi-polygon/PoiPolygonTypeScoreExtractorTest.cpp, hoot-core/src/main/cpp/hoot/core/algorithms/extractors/poi-polygon/PoiPolygonNameScoreExtractor.cpp, hoot-core/src/main/cpp/hoot/core/algorithms/extractors/poi-polygon/PoiPolygonNameScoreExtractor.h, hoot-core/src/main/cpp/hoot/core/algorithms/string/MeanWordSetDistance.h, hoot-core/src/main/cpp/hoot/core/algorithms/string/MinSumWordSetDistance.cpp, hoot-core/src/main/cpp/hoot/core/algorithms/string/MinSumWordSetDistance.h, hoot-core/src/main/cpp/hoot/core/algorithms/string/StringDistanceConsumer.h, test-files/cases/reference/unifying/poi-polygon/poi-polygon-auto-merge-10/Expected.osm, test-files/cases/reference/unifying/poi-polygon/poi-polygon-auto-merge-3/Expected.osm, test-files/cases/reference/unifying/poi-polygon/poi-polygon-auto-merge-4/Expected.osm, test-files/cases/reference/unifying/poi-polygon/poi-polygon-auto-merge-5/Expected.osm, test-files/cases/reference/unifying/poi-polygon/poi-polygon-auto-merge-6/Expected.osm, test-files/cases/reference/unifying/poi-polygon/poi-polygon-auto-merge-9/Expected.osm, test-files/cases/reference/unifying/poi-polygon/poi-polygon-keep-closest-match-only-10/Expected.osm, test-files/cases/reference/unifying/poi-polygon/poi-polygon-keep-closest-match-only-3/Expected.osm, test-files/cases/reference/unifying/poi-polygon/poi-polygon-keep-closest-match-only-4/Expected.osm, test-files/cases/reference/unifying/poi-polygon/poi-polygon-keep-closest-match-only-5/Expected.osm, test-files/cases/reference/unifying/poi-polygon/poi-polygon-keep-closest-match-only-9/Expected.osm, test-files/cases/reference/unifying/poi-polygon/poi-polygon-street-num-1/Expected.osm, test-files/cmd/glacial/PoiPolygonConflateCombinedTest/output1.osm, test-files/cmd/glacial/PoiPolygonConflateStandaloneTest/output1.osm
Changing the default string comparison algorithm used for name comparisons from `MeanWordSetDistance` to `KskipBigramDistance` yields slightly better regression test scores overall.
=> Make POI/Polygon string comparer configurable and change default implementation

hoot-core-test/src/test/cpp/hoot/core/io/OsmApiChangesetElementTest.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangeset.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangeset.h, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangesetElement.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangesetElement.h, hoot-core/src/main/cpp/hoot/core/io/OsmApiWriter.cpp, test-files/io/OsmChangesetElementTest/ChangesetErrorFixErrors.osc, test-files/io/OsmChangesetElementTest/RetryConflictExpected-error.osc, test-files/io/OsmChangesetElementTest/ToyTestAConflicts.osc
In some cases, certain elements aren't getting the correct version (0) when pushing cut & replace.  Updated changeset code to not output zero for version unless it is for a create operation, default to one otherwise.
=> Cut and Replace apply can give zero value for version of modify/delete element

hoot-core/src/main/cpp/hoot/core/conflate/network/OsmNetworkExtractor.cpp, hoot-core/src/main/cpp/hoot/core/conflate/network/OsmNetworkExtractor.h, hoot-core/src/main/cpp/hoot/core/elements/OsmMap.h
`OsmNetworkExtractor::_isContiguous` crashes on an `assert` call in debug mode.  The function ran on the assumption that linear relations only consisted of ways while some data consists of relations of relations of ways.  For example a route can consist of other route relations.
=> OsmNetworkExtractor debug crash

hoot-core/src/main/cpp/hoot/core/visitors/RemoveInvalidMultilineStringMembersVisitor.cpp
Refs #4157 
Cut and replace can have relations where the member doesn't exist inside of the bbox, check existence of elements before using them.
=> Cut & Replace: Derive Changeset Failing (1594)

conf/core/ConfigOptions.asciidoc, hoot-core-test/src/test/cpp/hoot/core/io/OsmApiWriterTest.cpp, hoot-core-test/src/test/cpp/hoot/core/io/OsmApiWriterTestServer.cpp, hoot-core-test/src/test/cpp/hoot/core/io/OsmApiWriterTestServer.h, hoot-core/src/main/cpp/hoot/core/io/OsmApiWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiWriter.h, tgs/src/main/cpp/tgs/Statistics/Random.cpp
Add throttling for CGImap 'changeset-apply' operations to keep from overwhelming the database.
=> Throttle 'changeset-apply' for CGImap-backed databases

hoot-core-test/src/test/cpp/hoot/core/io/OsmApiMatchFailureTest.cpp, hoot-core-test/src/test/cpp/hoot/core/io/OsmApiWriterTest.cpp, hoot-core-test/src/test/cpp/hoot/core/io/OsmApiWriterTestServer.cpp, hoot-core-test/src/test/cpp/hoot/core/io/OsmApiWriterTestServer.h, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangeset.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangesetElement.h, hoot-core/src/main/cpp/hoot/core/io/OsmApiMatchFailure.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiMatchFailure.h, hoot-core/src/main/cpp/hoot/core/io/OsmApiWriter.cpp, hoot-core/src/main/cpp/hoot/core/util/HootNetworkUtils.h, test-files/io/OsmChangesetElementTest/ChangesetErrorFixExpected.osc, test-files/io/OsmChangesetElementTest/ChangesetErrorFixInput.osc
Add HTTP 410 handling for `changeset-apply`.  In some cases something/someone else deletes an element that `changeset-apply` is also deleting and the HTTP 410 error is emitted.  It is safe to handle this error by setting that element to successfully uploaded because both operations meant to delete the element.
Also found an instance where creating a relation had a member with a negative ID (meaning create the member too) but it wasn't found in the changeset itself so that member is removed before sending.
Closes #4168
=> Changeset Apply 410 Error

translations/ElementMergeServer.js
refs #2231
This doesn't fix getting redirecting to the tomcat log, but it does surface any error to the UI.  I think because the call to postHandler was in the on end callback, the exceptions thrown were not handled by the outer try/catch.
=> surface the element merge error to the http response

conf/services/changesetReplacement.json, conf/services/changesetReplacementOps.json
refs #4178
So this option config is not automatically generated, that's only for advanced conflation options that have default values defined in ConfigOptions.asciidoc.
=> add disable cleaning option to cut&replace

hoot-core-test/src/test/cpp/hoot/core/algorithms/changeset/ServiceChangesetReplacementGridTest.cpp, hoot-core/src/main/cpp/hoot/core/algorithms/changeset/ChangesetReplacementCreator.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiDbSqlChangesetApplier.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiDbSqlChangesetFileWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiDbSqlChangesetFileWriter.h, hoot-core/src/main/cpp/hoot/core/io/OsmXmlChangesetFileWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmXmlChangesetFileWriter.h, hoot-core/src/main/cpp/hoot/core/util/DbUtils.cpp, test-files/cmd/glacial/serial/ServiceChangesetReplacement.sh.off, test-files/cmd/glacial/serial/ServiceChangesetReplacementAdjacentCellsTest.sh.off
This helps prevent SQL errors when trying to apply some changesets. May have other benefits with real world data. I think the C&R workflow is the only one deriving and then combining multiple changesets. If arbitrarily throwing out subsequent statements ends up causing any problems, then we may have to come with a more robust way to handle the duplication of statements.
=> Prevent repeated changeset statements for the same element when using multiple changeset providers

hoot-core/src/main/cpp/hoot/core/conflate/highway/HighwayMatch.cpp, test-files/cmd/glacial/serial/ServiceChangesetReplacementRoundaboutsConflateTest/ServiceChangesetReplacementRoundaboutsConflateTest-xml-replaced.osm
Initialize the HighwayMatch::_score variable to get rid of random failures.
=> Fix random failures in unit tests

hoot-core-test/src/test/cpp/hoot/core/algorithms/changeset/ServiceChangesetReplacementGridTest.cpp, hoot-core-test/src/test/cpp/hoot/core/auth/ServicesHootServicesLoginManagerTest.cpp, hoot-core-test/src/test/cpp/hoot/core/io/ServiceHootApiDbReaderTest.cpp, hoot-core-test/src/test/cpp/hoot/core/io/ServiceHootApiDbTest.cpp, hoot-core-test/src/test/cpp/hoot/core/io/ServicesDbTestUtils.cpp, hoot-core-test/src/test/cpp/hoot/core/io/ServicesDbTestUtils.h, hoot-core/src/main/cpp/hoot/core/io/HootApiDb.cpp, hoot-core/src/main/cpp/hoot/core/io/HootApiDb.h, scripts/core/archive/ServiceOsmApiDbHootApiDbConflate.sh, test-files/cmd/glacial/RndServiceMultiaryPoiIngestCmdTest.sh, test-files/cmd/glacial/ServiceDbEmptyTagsTest.sh, test-files/cmd/glacial/ServiceExportOsm.sh, test-files/cmd/glacial/serial/ServiceChangesetReplacement.sh.off, test-files/cmd/glacial/serial/ServiceChangesetReplacementAdjacentCellsTest.sh.off, test-files/cmd/glacial/serial/ServiceConflateDiffTest.sh.off, test-files/cmd/glacial/serial/ServiceGrailDiffTest.sh.off, test-files/cmd/glacial/serial/ServiceStreamingApiDbTest.sh, test-files/cmd/glacial/serial/replacement-test-archive/ServiceBuildingReplacementTest.sh.off, test-files/cmd/glacial/serial/replacement-test-archive/ServiceBuildingStrictReplacementTest.sh.off, test-files/cmd/glacial/serial/replacement-test-archive/ServicePoiStrictReplacementTest.sh.off, test-files/cmd/glacial/serial/replacement-test-archive/ServiceRoadReplacementTest.sh.off, test-files/cmd/glacial/serial/replacement-test-archive/ServiceRoadStrictReplacementTest.sh.off, test-files/cmd/quick/ServiceDbListMapsCmdTest.sh, test-files/cmd/slow/ServiceHootApiDbConflateTest.sh, test-files/cmd/slow/ServiceHootApiDbReaderCmdTest.sh, test-files/cmd/slow/serial/ServiceDiffRoadSnapTest.sh.off, test-files/cmd/slow/serial/ServiceNodeDensityTilesCmdTest.sh
Allow admins to export other user's private data.  While working on this I noticed that there are quite a few unit tests that don't clean up after themselves.  So I updated C++ and script unit tests to clean up any users and maps used in testing.
Closes #4119
=> Allow admins to export other users private data

hoot-core/src/main/cpp/hoot/core/io/OsmApiWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiWriter.h
Updated status messages for better UI logs during changeset-apply
```
WARN   Changeset precondition failed: Relation -2 requires the relations with id in 1707699,1707700, which either do not exist, or are not visible.
WARN   Changeset precondition failed: Relation -1 requires the relations with id in 1720067,1720068, which either do not exist, or are not visible.
WARN   Changeset precondition failed: Relation -5 requires the relations with id in 383909,383910, which either do not exist, or are not visible.
```
The `WARN` messages are equivalent to the following `STATUS` messages:
```
STATUS Required precondition not met in changeset 4, moving element to manual changeset.
STATUS Required precondition not met in changeset 4, moving element to manual changeset.
STATUS Required precondition …
```
=> Update STATUS messages in changeset-apply

hoot-core-test/src/test/cpp/hoot/core/io/OsmApiWriterTest.cpp, hoot-core-test/src/test/cpp/hoot/core/io/OsmApiWriterTestServer.cpp, hoot-core-test/src/test/cpp/hoot/core/io/OsmApiWriterTestServer.h, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangeset.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangeset.h, hoot-core/src/main/cpp/hoot/core/io/OsmApiWriter.cpp
Adding handling for orphaned 'delete' nodes that aren't able to be committed correctly the until the end.
=> Fix delete nodes in changeset-apply split

hoot-core-test/src/test/cpp/hoot/core/io/OsmApiChangesetTest.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangeset.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangeset.h, test-files/io/OsmChangesetElementTest/ModifyAndDelete-Expected.osc, test-files/io/OsmChangesetElementTest/ModifyAndDelete.osc
Updating changeset-apply for OSC files that contain both modifies and deletes of the same element.
=> Update and delete same element in changeset

hoot-core-test/src/test/cpp/hoot/core/io/OgrWriterTest.cpp, hoot-core/src/main/cpp/hoot/core/io/DataConverter.cpp, scripts/jenkins/Jenkinsfile
Close `OgrWriter` before destroying it for GPKG files that sometimes don't close before destruction.
=> Random crash in GPKG translation

.circleci/config.yml, scripts/ci/python_lint.sh
Task related to https://radiantsolutions.atlassian.net/browse/VGI-1731
Overview: Find all python files in hootenanny repo, lint for runtime errors, and have circleci fail if runtime error found.
Further details: A docker image was built for sherlock python linting called zappedbyvoltz/pycodestyle, and a script was made to lint files independent on modules/version/os installed and generate a log of the lint data. I copied the script into the hootenanny repo and call it from the config.yml circleci file, then do a line count on the number of runtime errors found. If one or more are in the log, then the log is printed to stdout and the circleci job will fail.
=> Circleci lint python files in hootenanny

hoot-core/src/main/cpp/hoot/core/io/OsmApiWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiWriter.h
Don't save the changeset ID for any changeset that is empty for later reporting in log.
Closes #4262
=> Report last non-empty changeset ID in `changeset-apply`

hoot-services/src/main/java/hoot/services/controllers/grail/DeriveChangesetCommand.java, hoot-services/src/main/java/hoot/services/controllers/grail/DeriveChangesetReplacementCommand.java
This prevents connected out-of-bounds ways in the reference layer (needed for cut&replace) from being deleted in the derive changeset of a reference conflation merged output
=> Add bounds to derive changeset if task bbox is set

hoot-core/src/main/cpp/hoot/core/algorithms/changeset/ChangesetReplacementCreator6.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangeset.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangeset.h
All testing has shown that this doesn't slow down `changeset-apply`.
=> Reduce the number of relations per chunck to keep 503 errors at bay

hoot-core/src/main/cpp/hoot/core/cmd/ChangesetApplyCmd.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangeset.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangeset.h, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangesetElement.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiChangesetElement.h, hoot-core/src/main/cpp/hoot/core/io/OsmApiWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiWriter.h
Updated changeset-apply to report the ID, Type, Version, and Upload Type of the last element uploaded.
Here is a sample output STATUS message:
```
STATUS ...core/cmd/ChangesetApplyCmd.cpp( 148) Last element pushed: Type(create) Relation(84) Version(1)
```
Type can be `create`, `modify`, `delete` and `Relation` can be `Node` or `Way` like these.
```
STATUS ...core/cmd/ChangesetApplyCmd.cpp( 148) Last element pushed: Type(create) Relation(84) Version(1)
STATUS ...core/cmd/ChangesetApplyCmd.cpp( 148) Last element pushed: Type(modify) Way(190) Version(4)
STATUS ...core/cmd/ChangesetApplyCmd.cpp( 148) Last element pushed: Type(delete) Node(1234) Version(2)
```
Closes #4310
=> Output the last element uploaded in `changeset-apply` status message

hoot-core/src/main/cpp/hoot/core/conflate/poi-polygon/PoiPolygonMerger.cpp, hoot-js/src/test/cpp/hoot/js/conflate/merging/ElementMergerJsTest.cpp
I think the original logic was based on the false assumption that POIs would always come in with a 1/2 status. If they are merged beforehand with a poly, that must be true b/c core requires that POIs must always be merged into polys. However, if a POI is immediately merged beforehand with another POI, it could come into poi/poly merging with a conflated status.
=> Remove logic that prevents POIs with conflated status from being merged with polys

conf/core/AttributeConflation.conf, conf/core/DifferentialConflation.conf, conf/core/GrailDifferentialConflation.conf, conf/core/HorizontalConflation.conf, conf/core/ReferenceConflation.conf, hoot-core-test/src/test/cpp/hoot/core/io/OsmApiWriterTestServer.cpp, hoot-core/hoot-core.pro, hoot-core/src/main/cpp/hoot/core/io/OsmApiMatchFailure.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiMatchFailure.h, hoot-core/src/main/cpp/hoot/core/io/OsmApiWriter.h, hoot-core/src/main/cpp/hoot/core/io/OsmXmlReader.cpp
Refs #4333 
This PR fixes version mismatch handling in Hootenanny core but also requires a change in reference data handling in the UI.  See the issue for more info.
=> Fix Version Mismatch handling in OsmApiMatchFailure class

hoot-core/src/main/cpp/hoot/core/io/OsmApiWriter.cpp
Refs #4310 
Move _extractLastElement() to all successful uploads.
=> Output the last element uploaded in `changeset-apply` status message 2

conf/schema/building.json
Fixes misapplication of the building category; breaks jak buildings regression
=> Building schema fix

hoot-core/src/main/cpp/hoot/core/io/OsmApiWriter.cpp
Single elements aren't handled when `HTTP 410 Gone` is returned from the API.  This handles single elements and keeps them from repeating in an infinite loop.
=> Refactor HTTP_GONE to respond correctly to single deleted elements.

hoot-core/src/main/cpp/hoot/core/conflate/polygon/BuildingMerger.cpp, hoot-core/src/main/cpp/hoot/core/elements/VersionUtils.cpp, hoot-core/src/main/cpp/hoot/core/ops/AddHilbertReviewSortOrderOp.cpp, hoot-core/src/main/cpp/hoot/core/ops/FindStreetIntersectionsByName.cpp, hoot-core/src/main/cpp/hoot/core/schema/SchemaUtils.cpp, hoot-core/src/main/cpp/hoot/core/visitors/FilteredVisitor.cpp, hoot-core/src/main/cpp/hoot/core/visitors/FilteredVisitor.h
The documentation of the `FilteredVisitor::getStat` says that the pointer ownership is passed to the class but it wasn't.  Updated the documentation and created/used the shared pointer version of that function where the leaks were happening.
Closes #4458
=> FilteredVisitor memory leaks

hoot-core-test/src/test/cpp/hoot/core/algorithms/changeset/TestOsmChangesetProvider.h, hoot-core/src/main/cpp/hoot/core/algorithms/changeset/ChangesetCleaner.h, hoot-core/src/main/cpp/hoot/core/algorithms/changeset/ChangesetDeriver.h, hoot-core/src/main/cpp/hoot/core/algorithms/changeset/ChangesetProvider.h, hoot-core/src/main/cpp/hoot/core/algorithms/changeset/MemChangesetProvider.cpp, hoot-core/src/main/cpp/hoot/core/algorithms/changeset/MemChangesetProvider.h, hoot-core/src/main/cpp/hoot/core/algorithms/changeset/MultipleChangesetProvider.h, hoot-rnd/src/main/cpp/hoot/rnd/io/MultiaryIngestChangesetReader.h
Fixed MemChangesetProvider::getNumChanges() hiding function and updated all related classes.
Refs #4570
=> SONAR: Minor sonar rules to fix - Inherited functions should not be hidden

hoot-core/src/main/cpp/hoot/core/io/HootApiDbBulkInserter.h, hoot-core/src/main/cpp/hoot/core/io/HootApiDbWriter.h, hoot-core/src/main/cpp/hoot/core/io/OgrWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/OgrWriter.h, hoot-core/src/main/cpp/hoot/core/io/OsmApiDbBulkInserter.h, hoot-core/src/main/cpp/hoot/core/io/OsmGbdxXmlWriter.h, hoot-core/src/main/cpp/hoot/core/io/OsmPbfWriter.h, hoot-core/src/main/cpp/hoot/core/io/OsmPgCsvWriter.h, hoot-core/src/main/cpp/hoot/core/io/OsmXmlWriter.h, hoot-core/src/main/cpp/hoot/core/io/PartialOsmMapWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/PartialOsmMapWriter.h, hoot-rnd/src/main/cpp/hoot/rnd/io/SparkJsonWriter.h
Fixed PartialOsmMapWriter::writePartial() function hiding and updated all derived classes
Refs #4570
=> Minor sonar rules to fix - Inherited functions should not be hidden

hoot-core/src/main/cpp/hoot/core/conflate/highway/HighwayMatch.cpp, hoot-core/src/main/cpp/hoot/core/conflate/network/NetworkMatch.cpp, hoot-core/src/main/cpp/hoot/core/conflate/poi-polygon/PoiPolygonMatch.cpp, hoot-core/src/main/cpp/hoot/core/conflate/poi-polygon/PoiPolygonMerger.cpp, hoot-core/src/main/cpp/hoot/core/conflate/polygon/BuildingMatch.cpp, hoot-core/src/main/cpp/hoot/core/conflate/polygon/BuildingMerger.cpp, hoot-js/src/main/cpp/hoot/js/conflate/matching/ScriptMatch.cpp, hoot-js/src/main/cpp/hoot/js/conflate/merging/AreaMergerJs.cpp, hoot-js/src/main/cpp/hoot/js/conflate/merging/PoiMergerJs.cpp
Use the `emplace()` function instead of `insert()` for standard data structures
Refs #4568
=> SONAR: emplace should be preferred over insert

hoot-core/src/main/cpp/hoot/core/conflate/address/AddressNormalizer.cpp, hoot-core/src/main/cpp/hoot/core/conflate/address/AddressParser.cpp, hoot-core/src/main/cpp/hoot/core/geometry/ElementToGeometryConverter.cpp, hoot-core/src/main/cpp/hoot/core/ops/CalculateStatsOp.cpp, hoot-core/src/main/cpp/hoot/core/visitors/CalculateAreaForStatsVisitor.cpp, hoot-core/src/main/cpp/hoot/core/visitors/CalculateAreaForStatsVisitor.h, hoot-core/src/main/cpp/hoot/core/visitors/CalculateAreaVisitor.cpp, hoot-core/src/main/cpp/hoot/core/visitors/CalculateAreaVisitor.h
The calculation of area stats was crashing when encountering either a relation with no type or a relation of `type=site`. Now, a warning is logged instead in both cases and the offending feature excluded from the stat calculation. The `type-site` fix applies to all stats encountering this data, as well as any code attempting to convert such a feature to a geometry. The untyped relation fix currently applies only to calculating area statistics. Other callers converting such a feature to a geometry will need to be modified to not throw an error and skip the feature in question (see `CalculateAreaVisitor`).
=> Handle untyped and site relations better when calculating stats

hoot-core/src/main/cpp/hoot/core/algorithms/linearreference/LocationOfPoint.cpp, hoot-core/src/main/cpp/hoot/core/algorithms/linearreference/WayString.cpp, hoot-core/src/main/cpp/hoot/core/cmd/CompareCmd.cpp, hoot-core/src/main/cpp/hoot/core/cmd/ConvertCmd.cpp, hoot-core/src/main/cpp/hoot/core/conflate/address/AddressParser.cpp, hoot-core/src/main/cpp/hoot/core/conflate/polygon/BuildingMerger.cpp, hoot-core/src/main/cpp/hoot/core/criterion/AreaCriterion.cpp, hoot-core/src/main/cpp/hoot/core/criterion/NeedsReviewCriterion.cpp, hoot-core/src/main/cpp/hoot/core/criterion/NeedsReviewCriterion.h, hoot-core/src/main/cpp/hoot/core/io/HootApiDb.cpp, hoot-core/src/main/cpp/hoot/core/io/OgrReader.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiDbBulkInserter.cpp, hoot-core/src/main/cpp/hoot/core/ops/DuplicateWayRemover.cpp, hoot-core/src/main/cpp/hoot/core/ops/OffsetIntersectionMergerOp.cpp, hoot-core/src/main/cpp/hoot/core/ops/RemoveReviewsByEidOp.cpp, hoot-core/src/main/cpp/hoot/core/schema/AttributeCoOccurrence.cpp, hoot-core/src/main/cpp/hoot/core/schema/TagComparator.cpp, hoot-core/src/main/cpp/hoot/core/scoring/GraphComparator.cpp, hoot-core/src/main/cpp/hoot/core/scoring/MatchComparator.cpp, hoot-core/src/main/cpp/hoot/core/scoring/MatchComparator.h, hoot-core/src/main/cpp/hoot/core/scoring/RasterComparator.cpp, hoot-core/src/main/cpp/hoot/core/visitors/CountUniqueReviewsVisitor.cpp, hoot-core/src/main/cpp/hoot/core/visitors/CountUniqueReviewsVisitor.h, hoot-core/src/main/cpp/hoot/core/visitors/RemoveInvalidMultilineStringMembersVisitor.cpp, hoot-core/src/main/cpp/hoot/core/visitors/RemoveInvalidRelationVisitor.cpp, hoot-core/src/main/cpp/hoot/core/visitors/SchemaTranslationVisitor.cpp, hoot-rnd/src/main/cpp/hoot/rnd/cmd/WriteNameCountsCmd.cpp, hoot-rnd/src/main/cpp/hoot/rnd/scoring/multiary/MultiaryMatchComparator.cpp
Update static function calls using class name instead of class instance.
=> SONAR: Static members should be accessed statically

conf/core/AttributeConflation.conf, hoot-core/src/main/cpp/hoot/core/algorithms/splitter/HighwayCornerSplitter.cpp
Fixed the corner splitter configuration to use the config and always the default.
Refs #4619
=> Fix HighwayCornerSplitter to use the config file and not just the default values

hoot-core-test/src/test/cpp/hoot/core/algorithms/changeset/ServiceChangesetReplacementGridTest.cpp, hoot-core-test/src/test/cpp/hoot/core/elements/ElementComparerTest.cpp, hoot-core/src/main/cpp/hoot/core/algorithms/changeset/ChangesetDeriver.cpp, hoot-core/src/main/cpp/hoot/core/algorithms/changeset/ChangesetReplacementCreatorAbstract.cpp, hoot-core/src/main/cpp/hoot/core/algorithms/changeset/ChangesetTaskGridReplacer.h, hoot-core/src/main/cpp/hoot/core/algorithms/linearreference/WayLocation.cpp, hoot-core/src/main/cpp/hoot/core/algorithms/linearreference/WayLocation.h, hoot-core/src/main/cpp/hoot/core/elements/ElementProvider.h, hoot-core/src/main/cpp/hoot/core/elements/OsmMap.h, hoot-core/src/main/cpp/hoot/core/elements/Relation.cpp, hoot-core/src/main/cpp/hoot/core/elements/Relation.h, hoot-core/src/main/cpp/hoot/core/elements/Tags.h, hoot-core/src/main/cpp/hoot/core/io/ElementCache.h, hoot-core/src/main/cpp/hoot/core/io/ElementCacheLRU.cpp, hoot-core/src/main/cpp/hoot/core/io/ElementCacheLRU.h, hoot-core/src/main/cpp/hoot/core/ops/ElementIdRemapper.cpp, hoot-core/src/main/cpp/hoot/core/schema/MetadataTags.h, hoot-core/src/main/cpp/hoot/core/schema/ScriptSchemaTranslator.h, hoot-js/src/main/cpp/hoot/js/schema/JavaScriptSchemaTranslator.cpp, hoot-js/src/main/cpp/hoot/js/schema/JavaScriptSchemaTranslator.h, tgs/src/main/cpp/tgs/DelaunayTriangulation/DelaunayTriangulation.cpp, tgs/src/main/cpp/tgs/DelaunayTriangulation/DelaunayTriangulation.h, tgs/src/main/cpp/tgs/RStarTree/RTreeNode.cpp, tgs/src/main/cpp/tgs/RStarTree/RTreeNode.h
Remove const on return types for functions that aren't constant references
Closes #4566
=> SONAR: Remove const qualifier on return type of a function

test-files/cmd/glacial/ScoreMatchesCmdTest/output.osm
I think the test failure might actually be due to changes coming in from another branch I merged around the same time as 4646 was merged. If so, this test output change should fix the test. If not, since this test didn't original do an output diff, the output diff check may need to be removed.
=> Fix ScoreMatchesCmdTest

conf/core/ConfigOptions.asciidoc, docs/user/SupportedDataFormats.asciidoc, hoot-core/src/main/cpp/hoot/core/io/DataConverter.cpp, hoot-core/src/main/cpp/hoot/core/io/DataConverter.h, hoot-core/src/main/cpp/hoot/core/io/ElementStreamer.cpp, hoot-core/src/main/cpp/hoot/core/io/OgrWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/OgrWriter.h, hoot-core/src/main/cpp/hoot/core/io/OsmMapReaderFactory.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmMapWriterFactory.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmPbfReader.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmXmlWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmXmlWriter.h, hoot-core/src/main/cpp/hoot/core/io/PartialOsmMapWriter.cpp, hoot-core/src/main/cpp/hoot/core/schema/SchemaUtils.cpp, hoot-core/src/main/cpp/hoot/core/schema/SchemaUtils.h, hoot-core/src/main/cpp/hoot/core/visitors/SchemaTranslationVisitor.cpp, hoot-js/src/main/cpp/hoot/js/schema/JavaScriptSchemaTranslator.cpp, test-files/cmd/quick/ConvertGeoNames.sh, translations/tds70.js
Prior to this change all conversions with an OGR format as an output would run translation in a separate thread. Doing so is memory bound. This change makes running translations in separate thread optional and disabled by default (`convert.translate.multithreaded`). If both input *and* output format are OGR formats, however, multi-threaded translation is still optional but the operation will always be memory bound.
=> Run to OGR translations streaming by default

conf/schema/highway.json, hoot-core/src/main/cpp/hoot/core/cmd/ScoreMatchesCmd.cpp, hoot-core/src/main/cpp/hoot/core/conflate/matching/MatchThreshold.h, hoot-js/src/main/cpp/hoot/js/algorithms/subline-matching/SublineStringMatcherJs.cpp, hoot-rnd/src/main/cpp/hoot/rnd/conflate/matching/ScoreMatchesDiff.cpp, hoot-rnd/src/test/cpp/hoot/rnd/conflate/matching/ScoreMatchesDiffTest.cpp, test-files/cases/attribute/network/highway-2927-bridge-1/Expected.osm, test-files/cases/attribute/network/highway-2927-way-member-tags-1/Expected.osm, test-files/cmd/glacial/RndScoreMatchesDiffCmdTest.sh.stdout, test-files/cmd/glacial/RndScoreMatchesDiffCmdTest/output
changes to fix broken regression tests
* schema fix allows `gnarly-jerusalem` to pass
* fix to `MatchThreshold` init in `ScoreMatchesCmd` allows `jakarta-buildings` to pass
* river and power line tests scores adjusted downward to reflect the fact that ms relations formerly not removed were artificially inflating the correct score (in a separate hoot-tests commit)
=> Regression test fixes 4/13/21

hoot-core/src/main/cpp/hoot/core/algorithms/linearreference/WayLocation.cpp
=> Global coordinate removed

docs/commands/info.asciidoc, docs/user/CommandLineExamples.asciidoc, hoot-core/src/main/cpp/hoot/core/cmd/BaseCommand.h, hoot-core/src/main/cpp/hoot/core/cmd/InfoCmd.cpp, hoot-core/src/main/cpp/hoot/core/conflate/SuperfluousConflateOpRemover.cpp, hoot-core/src/main/cpp/hoot/core/conflate/SuperfluousConflateOpRemover.h, hoot-core/src/main/cpp/hoot/core/conflate/matching/MatchCreator.h, hoot-core/src/main/cpp/hoot/core/info/ApiEntityDisplayInfo.cpp, hoot-core/src/main/cpp/hoot/core/info/ApiEntityDisplayInfo.h, hoot-core/src/main/cpp/hoot/core/ops/UnconnectedWaySnapper.cpp, hoot-core/src/main/cpp/hoot/core/util/Factory.cpp, hoot-core/src/main/cpp/hoot/core/util/Factory.h, test-files/cmd/slow/InfoCmdTest.sh, test-files/cmd/slow/InfoCmdTest.sh.stdout
See added documentation for `hoot info --way-snap-criteria`.
=> Allow for retrieving the appropriate available way snapping criteria for a given conflate config

Makefile.am
Copy the command asciidoc files during install for Hootenanny command errors to work.  The RPM `.spec` file is installing everything in the `docs` directory that is copied over but these files aren't being copied over in the install process of the `Makefile`.
Closes https://github.com/ngageoint/hootenanny-rpms/issues/296
=> Install command help

hoot-core/src/main/cpp/hoot/core/algorithms/extractors/poi-polygon/PoiPolygonAlphaShapeDistanceExtractor.cpp, test-files/cases/reference/unifying/poi-polygon/poi-polygon-review-conflict-4331-2/Expected.osm, test-files/cmd/glacial/PoiPolygonConflateCombinedTest/output1.osm, test-files/cmd/glacial/PoiPolygonConflateStandaloneTest/output1.osm
Copying a single poly without the corresponding nodes, doesn't work right.
=> Fix PoiPolyAlphaShapeDistanceExtractor

Vagrantfile, scripts/valgrind/Jenkinsfile
`valgrind` requires a `yum update` to grab the latest `CGAL` RPM library.
=> Update hoot valgrind dependencies to run correctly

hoot-core-test/src/test/cpp/hoot/core/util/HttpTestServer.cpp, hoot-core/src/main/cpp/hoot/core/elements/OsmMap.cpp, hoot-core/src/main/cpp/hoot/core/elements/Way.cpp, hoot-core/src/main/cpp/hoot/core/index/ClosePointHash.cpp, hoot-core/src/main/cpp/hoot/core/index/ClosePointHash.h, hoot-core/src/main/cpp/hoot/core/io/OsmXmlWriter.cpp, hoot-core/src/main/cpp/hoot/core/util/DateTimeUtils.cpp, hoot-core/src/main/cpp/hoot/core/visitors/AddExportTagsVisitor.cpp, hoot-core/src/main/cpp/hoot/core/visitors/AddExportTagsVisitor.h
Using `callgrind` converting a dataset of 1.8M elements there were three areas that were running slow in a `hoot convert` command.  Each area was optimized with the following results:
```
STATUS ...ore/io/OsmMapReaderFactory.cpp( 191) Read 1,875,175 elements from input in: 00:41.      
INFO   ...p/hoot/core/ops/OpExecutor.cpp( 230) 	Merged 351,283 node pairs. in 00:30
INFO   ...ore/io/OsmMapWriterFactory.cpp( 149) Wrote 1,523,892 elements to output in: 00:28.
STATUS ...p/hoot/core/cmd/ConvertCmd.cpp( 140) Data conversion completed in 01:42.
STATUS ...ore/io/OsmMapReaderFactory.cpp( 191) Read 1,875,175 elements from input in: 00:37.      
INFO   ...p/hoot/core/ops/OpExecutor.cpp( 230) 	Merged 351,283 node pairs. in 00:17
INFO   ...ore/io/OsmMapWriterFactory.cpp( 149) Wrote 1,523,892 …
```
=> Duplicate node remover speedup 3710

scripts/tomcat/CopyWebAppsToTomcat.sh
In some instances on AWS the `CopyWebAppsToTomcat.sh` won't delete the old webapp causing builds to fail, use `root` to remove, copy, and then `chown` them.
Closes #4942
=> Valgrind not working with current hoot

hoot-core-test/src/test/cpp/hoot/core/io/OsmApiReaderTest.cpp, hoot-core-test/src/test/cpp/hoot/core/io/OsmApiWriterTest.cpp
The `OsmApiReaderTest` and `OsmApiWriterTest` classes have intermittent failing tests that seem to only appear in the Jenkins pipeline.  Disable them in the main branch and work on a fix in a feature branch to stabilize the CI pipeline.
=> Disable intermittent failing tests for now.

translations/package-lock.json
I wanted to update y18n to the latest version since older versions are vulnerable to Prototype Pollution. Affecting y18n package, versions <3.2.2 || >=4.0.0 <4.0.1 || >=5.0.0 <5.0.5
PoC:
```
const y18n = require('y18n')();
y18n.setLocale('__proto__');
y18n.updateLocale({polluted: true});
console.log(polluted); // true
```
**Remote Code Execution:**
Remote code execution is generally only possible in cases where the codebase evaluates a specific attribute of an object, and then executes that evaluation.
For example: eval(someobject.someattr). In this case, if the attacker pollutes Object.prototype.someattr they are likely to be able to leverage this in order to execute code.
=> updating y18n to the latest version

hoot-test/src/main/cpp/hoot/test/ProcessPool.cpp, hoot-test/src/main/cpp/hoot/test/ProcessPool.h, hoot-test/src/main/cpp/hoot/test/main.cpp
Serial conflate tests weren't being run in the serial thread and weren't being run at the end.  This caused some problems were the test osm api database was being corrupted.
=> Fix serial conflate tests to run at the end of the serial tests

docs/Makefile
Certain doc files have been added to the repo and shouldn't get deleted now during 'clean-all'
=> Fix `make clean-all`

conf/core/ConfigOptions.asciidoc, conf/services/importTypes.json, docs/user/Translation.asciidoc, hoot-core/src/main/cpp/hoot/core/io/DataConverter.cpp, hoot-core/src/main/cpp/hoot/core/io/DataConverter.h, hoot-services/src/test/java/hoot/services/controllers/ingest/ImportCommandTest.java, hoot-test/src/main/cpp/hoot/test/ProcessPool.cpp
Make a general setting for merge.nearby.nodes and simplify.complex.buildings and apply to OGR and GeoJSON.
@brianhatchl here is the fix.  The new options are:
`non.osm.convert.merge.nearby.nodes` and `non.osm.convert.simplify.complex.buildings`
JSON/GeoJSON conversions now can add building simplification is desired.
Closes #5135
=> Improve `merge.nearby.nodes` settings for UI

hoot-core/src/main/cpp/hoot/core/algorithms/extractors/poi-polygon/PoiPolygonDistanceExtractor.cpp, hoot-core/src/main/cpp/hoot/core/algorithms/extractors/poi-polygon/PoiPolygonDistanceExtractor.h
* Automagically create PoiPolygonInfoCache if it isn't provided, this
enables PoiPolygonDistanceExtractor in javascript
=> [#5144] Automagically create a PoiPolygonInfoCache

scripts/jenkins/Jenkinsfile
The code coverage steps in Jenkins aren't running nightly and it results in Sonar reporting 0% coverage.
=> Turn on the code coverage steps in Jenkins for the nightly build.

hoot-core/src/main/cpp/hoot/core/io/DataConverter.cpp, hoot-core/src/main/cpp/hoot/core/io/DataConverter.h, test-files/cmd/slow/ConvertCmdTest.sh
`DuplicateNodeRemover` was only being called on JSON files when there was a translation script provided.  It needs to be run by default unless turned off.
=> Enable non translation geojson duplicate node remover

hoot-services/src/main/java/hoot/services/controllers/grail/GrailResource.java
the bug was revealed when test@test.com email was tried to be used to read hoot db layers (vs osm files)
=> fix two-step diff so it doesn't break manual derive changeset

scripts/cover/coverGcov.sh
Simplify the code coverage generation script to use an array of directories to process and then process them all the same.
=> Simplify the coverage generation script

hoot-core/src/main/cpp/hoot/core/ops/DuplicateNodeRemover.cpp
Fix a crash in certain datasets during the DuplicateNodeRemover Hootenanny will crash.
=> DuplicateNodeRemover crash fixed

translations/ENCv311_to_OGR.js, translations/dnc_core.js, translations/ggdm30.js, translations/mgcp.js, translations/tds40.js, translations/tds61.js, translations/tds70.js, translations/test/osmtags.js
This change makes it so translations don't remove the osm tag `area=yes` when translating to schemas.  Instead it will map to the `OSMTAGS` catch-all so it can be restored in the round-trip translation.
=> Update translations to preserve area=yes and map to OSMTAGS

conf/core/ConfigOptions.asciidoc, conf/core/DifferentialConflation.conf, docs/algorithms/DifferentialConflation.asciidoc, docs/commands/conflate.asciidoc, docs/user/CommandLineExamples.asciidoc, docs/user/ConflationSteps.asciidoc, hoot-core/src/main/cpp/hoot/core/algorithms/changeset/NodeDensityTaskGridGenerator.cpp, hoot-core/src/main/cpp/hoot/core/cmd/BaseCommand.cpp, hoot-core/src/main/cpp/hoot/core/cmd/BoundedCommand.cpp, hoot-core/src/main/cpp/hoot/core/cmd/ConflateCmd.cpp, hoot-core/src/main/cpp/hoot/core/conflate/DiffConflator.h, hoot-core/src/main/cpp/hoot/core/io/IoUtils.cpp, hoot-core/src/main/cpp/hoot/core/io/IoUtils.h, hoot-core/src/main/cpp/hoot/core/io/OsmXmlReader.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmXmlReader.h, hoot-services/src/main/java/hoot/services/controllers/conflation/ConflateCommand.java, hoot-services/src/main/java/hoot/services/controllers/grail/RunDiffCommand.java, hoot-services/src/test/java/hoot/services/controllers/conflation/ConflateCommandTest.java, hoot-test/src/main/cpp/hoot/test/ConflateCaseTest.cpp, test-files/cases/differential/network/highway/roundabout-3580/Config.conf, test-files/cases/differential/unifying/highway/roundabout-3580/Config.conf, test-files/cmd/glacial/DiffConflateCmdTest.sh, test-files/cmd/glacial/DiffConflatePartialLinearMatchTest.sh, test-files/cmd/glacial/PowerLineDiffConflateTest.sh, test-files/cmd/glacial/RiverMaxSublineRecursionTest.sh, test-files/cmd/slow/DiffConflateTagChangeDifferingGeometriesTest.sh, test-files/cmd/slow/NetworkConflateCmdRelationEdgeTest.sh, test-files/cmd/slow/RiverDiffConflateTest.sh, test-files/cmd/slow/serial/RailwayDiffConflateTest.sh, test-files/cmd/slow/serial/ServiceDiffRoadSnapTest.sh.off
Move differential conflation from a command line argument `--differential`, `--include-tags`, and `--separate-output` to a config options.  Updated `DifferentialConflation.conf` to enable `conflate.differential`.  Updated all affected unit tests.
Closes #5084
=> Replace Diff Conflate CLI options with config options

hoot-core-test/src/test/cpp/hoot/core/io/OsmApiReaderTest.cpp, hoot-core/src/main/cpp/hoot/core/conflate/highway/HighwayMatchCreator.cpp, hoot-core/src/main/cpp/hoot/core/conflate/highway/HighwayMatchCreator.h, hoot-core/src/main/cpp/hoot/core/conflate/matching/MatchCreator.cpp, hoot-core/src/main/cpp/hoot/core/conflate/matching/MatchCreator.h, hoot-core/src/main/cpp/hoot/core/criterion/InBoundsCriterion.cpp, hoot-core/src/main/cpp/hoot/core/criterion/InBoundsCriterion.h, hoot-core/src/main/cpp/hoot/core/elements/MapProjector.cpp, hoot-core/src/main/cpp/hoot/core/elements/MapProjector.h, hoot-core/src/main/cpp/hoot/core/geometry/GeometryUtils.cpp, hoot-core/src/main/cpp/hoot/core/geometry/GeometryUtils.h, hoot-core/src/main/cpp/hoot/core/io/OsmApiReader.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiReader.h, hoot-core/src/main/cpp/hoot/core/io/OsmXmlReader.cpp, hoot-core/src/main/cpp/hoot/core/util/ConfigUtils.cpp, hoot-core/src/main/cpp/hoot/core/util/ConfigUtils.h, hoot-core/src/main/cpp/hoot/core/visitors/RemoveElementsVisitor.cpp, hoot-core/src/main/cpp/hoot/core/visitors/RemoveElementsVisitor.h, test-files/cmd/slow/serial/ServiceDiffRoadSnapTest.sh.off, test-files/io/OsmApiReaderTest/PolygonBoundsTestExpected.osm, test-files/io/OsmApiReaderTest/ToyTestBboxBounds.osm, test-files/io/OsmApiReaderTest/ToyTestPolyBounds.osm
Anywhere that `bounds` or `bounds.input.filename` are used they can now be converted into a polygon `Geometry` to be used for cropping, etc.
Closes #5207
=> Add support for polygon bounds in OsmApiReader

VagrantProvisionVars.sh, configure.ac
Updated GEOS version didn't require any code changes.
Closes #5211
=> Upgrade GEOS to 3.9.2

hoot-core/src/main/cpp/hoot/core/criterion/InBoundsCriterion.cpp, hoot-core/src/main/cpp/hoot/core/elements/OsmMap.cpp, hoot-core/src/main/cpp/hoot/core/elements/OsmMap.h
Retry the `Geometry::contains()` or `Geometry::intersects()` functions when a `geos::util::TopologyException` is thrown
Closes #5217
=> TopologyException in Highway Diff

conf/core/ConfigOptions.asciidoc, conf/core/NodeExport.conf, hoot-core/src/main/cpp/hoot/core/io/OgrWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/OgrWriter.h
Add flag to force ignoring (and editing) of incomplete relations in OGR-type output files. `ogr.writer.skip.failed.relations` defaults to false but is set to `true` in the export config file.
@mattjdnv I think that the Javascript translations should be modified so that the `ManyFeatures: Should get to here` message is changed to something more meaningful and set as a debug message or just removed completely.  What do you think?
Closes #5223
=> Convert PBF to GDB fails on incomplete relations

hoot-core-test/src/test/cpp/hoot/core/io/OgrReaderTest.cpp, hoot-core-test/src/test/cpp/hoot/core/io/ServiceOsmApiDbSqlChangesetApplierTest.cpp, hoot-core/src/main/cpp/hoot/core/io/ApiDbSqlStatementFormatter.cpp, hoot-core/src/main/cpp/hoot/core/io/OgrReader.cpp, hoot-core/src/main/cpp/hoot/core/io/OgrReader.h, hoot-core/src/main/cpp/hoot/core/io/OgrWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmGbdxXmlWriter.cpp, hoot-core/src/main/cpp/hoot/core/util/DateTimeUtils.cpp
`OgrReader` used `delete` to free GDAL created objects in memory instead of using `CPLFree()`.  It was also reformatted and all sonar findings removed.
`QDateTime::currentDateTime().toUTC()` is deprecated in favor of `QDateTime::currentDateTimeUtc()`.  All instances were updated.
=> Ogr reader updates

hoot-core/src/main/cpp/hoot/core/io/ApiDb.cpp, hoot-core/src/main/cpp/hoot/core/io/ApiDb.h, hoot-core/src/main/cpp/hoot/core/io/HootApiDb.cpp, hoot-core/src/main/cpp/hoot/core/io/HootApiDb.h, hoot-core/src/main/cpp/hoot/core/io/OgrReader.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiDb.cpp, hoot-core/src/main/cpp/hoot/core/io/SqlBulkInsert.cpp, hoot-core/src/main/cpp/hoot/core/ops/DuplicateNodeRemover.cpp
The `DuplicateNodeRemover` would hit a corner case in certain inputs where some nodes would be deleted but not all parent ways would be updated.
=> Hoot api db crash

hoot-core/src/main/cpp/hoot/core/io/ElementStreamer.cpp, hoot-core/src/main/cpp/hoot/core/io/OgrReader.cpp
Streaming input from an OGR source needs translation script set.
Closes #5238
=> OGR streaming discards translation

Vagrantfile, docs/install/Vagrant.asciidoc
In working on Windows, the vagrant file sync between host and guest was pretty rough.  I tried to use OpenSSH's FTP server initially and it was impossibly slow, this NFS plugin was much much better.  For anyone forced to be on Windows I think this should be a bit of an upgrade using a vagrant plugin and an environment variable that switches the mount options to something that works for that plugin (at least I know it must be NFS vers 3, and the rest of the mount options I used were the recommendation).
=> updated vagrantfile and instructions to include NFS option for windows

hoot-core-test/src/test/cpp/hoot/core/geometry/RelationToMultiPolygonConverterTest.cpp, hoot-core/src/main/cpp/hoot/core/geometry/RelationToMultiPolygonConverter.cpp, hoot-core/src/main/cpp/hoot/core/geometry/RelationToMultiPolygonConverter.h
Manually deleted any `geos::Geometry` objects that didn't have their ownership transferred to another object and were being leaked.
Closes #5256
=> RelationToMultiPolygonConverter memory leaks

hoot-core/src/main/cpp/hoot/core/algorithms/LongestCommonNodeString.cpp, hoot-core/src/main/cpp/hoot/core/algorithms/LongestCommonNodeString.h, hoot-core/src/main/cpp/hoot/core/algorithms/NonIntersectionWayJoiner.cpp, hoot-core/src/main/cpp/hoot/core/algorithms/ProbabilityOfMatch.cpp, hoot-core/src/main/cpp/hoot/core/algorithms/ProbabilityOfMatch.h, hoot-core/src/main/cpp/hoot/core/algorithms/RdpWayGeneralizer.cpp, hoot-core/src/main/cpp/hoot/core/algorithms/RdpWayGeneralizer.h, hoot-core/src/main/cpp/hoot/core/algorithms/WayJoiner.cpp, hoot-core/src/main/cpp/hoot/core/elements/OsmMap.cpp, hoot-core/src/main/cpp/hoot/core/elements/OsmMap.h, hoot-core/src/main/cpp/hoot/core/index/ClosePointHash.cpp, hoot-core/src/main/cpp/hoot/core/index/ClosePointHash.h, hoot-core/src/main/cpp/hoot/core/ops/DuplicateNodeRemover.cpp, test-files/cmd/quick/DuplicateNodeRemoverTest.sh, test-files/cmd/quick/DuplicateNodeRemoverTest/crossing_input.osm, test-files/cmd/quick/DuplicateNodeRemoverTest/crossing_test.osm, test-files/cmd/slow/SplitLongWaysTest.sh
The real slow down wasn't in the use of the `ClosePointHash` but in the way that we replaced nodes, one at a time searching all relations and ways for that node, replacing it and reindexing the `OsmMapIndex`.  Here we iterate the relations, ways, and nodes only once looking for all replacements and doing all of them in one fell swoop.
Closes #3710
=> Come up with a faster algorithm for `DuplicateNodeRemover`

conf/core/ConfigOptions.asciidoc, rules/Railway.js, rules/River.js, test-files/cmd/slow/serial/RailwayAttributeConflateTest/output.osm, test-files/cmd/slow/serial/RailwayConflateTest/output.osm, test-files/cmd/slow/serial/RailwayDiffConflateTest/output-partial.osm
Updated Railway and River conflation scripts to use the weighted distance extractor just like Powerlines.
In the unit tests there was no change in the river tests but railway tests removed some "extra" lines that didn't conflate right.
=> See if distance weighting helps other linear script conflators

translations/ggdm30.js, translations/mgcp.js, translations/tds40.js, translations/tds61.js, translations/tds70.js, translations/tds71.js, translations/test/railway_gauge.js, translations/translate.js
the tags get modified in this method and a way with both railway
and bridge will get sent through this methodapplyToOgrPreProcessing twice,
so the gauge may have already converted to number
fixes #5302
=> Make sure the gauge tag is not already a number during translation

hoot-core-test/src/test/cpp/hoot/core/geometry/RelationToMultiPolygonConverterTest.cpp, hoot-core/src/main/cpp/hoot/core/Hoot.cpp, hoot-core/src/main/cpp/hoot/core/Hoot.h, hoot-core/src/main/cpp/hoot/core/geometry/RelationToMultiPolygonConverter.cpp, hoot-core/src/main/cpp/hoot/core/geometry/RelationToMultiPolygonConverter.h
Fixed function to classify all unknown rings and fixed crash.
Closes #5255
=> Re-enable RelationToMultiPolygonConverter::_classifyRings() function and test if it is needed

hoot-core/src/main/cpp/hoot/core/algorithms/WayJoiner.cpp, hoot-core/src/main/cpp/hoot/core/algorithms/WayJoiner.h
Fixes #4631
Add a mapping of parentIDs to ways, to facilitate faster way joining. For the large road datasets I was using, this change reduced way re-joining from 46 seconds to 1 second.
=> Way rejoin perf 4631

hoot-core/src/main/cpp/hoot/core/util/Settings.cpp, hoot-core/src/main/cpp/hoot/core/util/Settings.h, hoot-js/src/main/cpp/hoot/js/util/SettingsJs.cpp, hoot-js/src/main/cpp/hoot/js/util/SettingsJs.h, translations/test/SettingsJs.js
This is mostly to facilitate unit testing, but could be useful in other circumstances as well.
Fixes #5308
=> Add clear(), push(), pop() manipulations to the Settings and Settingsjs objects

hoot-core-test/src/test/cpp/hoot/core/ops/DuplicateNodeRemoverTest.cpp, hoot-core-test/src/test/cpp/hoot/core/schema/ExactTagDifferencerTest.cpp, hoot-core/src/main/cpp/hoot/core/elements/Status.cpp, hoot-core/src/main/cpp/hoot/core/io/HootNetworkRequest.cpp, hoot-core/src/main/cpp/hoot/core/io/HootNetworkRequest.h, hoot-core/src/main/cpp/hoot/core/io/OsmApiReader.cpp, hoot-core/src/main/cpp/hoot/core/io/ParallelBoundedApiReader.cpp, hoot-core/src/main/cpp/hoot/core/io/ParallelBoundedApiReader.h
Catch the `std::bad_alloc` exception, divide the area, and retry.  Also make `hoot:status` parsing more fault tolerant for bad data with two or more valid statuses, take the first and ignore the rest.
Closes #5333
=> `ParallelBoundedReader` throws `std::bad_alloc`

hoot-core/src/main/cpp/hoot/core/io/OgrUtilities.cpp
FGDB and geopackages are zipped directories that sometimes don't work correctly
=> FGDB and GeoPackage error

scripts/sonar/sonar-scan.sh
Sonar documentation indicates that a thread count larger than `nproc` can degrade performance, test that statement.  Currently the last three runs took 34:44, 32:46, and 31:33.
=> Test parallelism in sonar scan

hoot-services/src/main/java/hoot/services/controllers/grail/WaitOverpassUpdate.java, hoot-services/src/main/java/hoot/services/utils/DbUtils.java, hoot-services/src/test/java/hoot/services/utils/DbUtilsTest.java
=> bobby magic wait overpass step should short circuit if no changesets uploaded

translations/GGDMv30.js, translations/MGCP_TRD4.js, translations/TDSv40.js, translations/TDSv61.js, translations/TDSv70.js, translations/TDSv71.js, translations/TranslationServer.js, translations/test/TranslationServer.js
This PR removes the translation server dependency on the "English" versions of the translation scripts.  The `translation_assistant.js` script still references them, but maybe it to could be made to work without them.
=> Translation server remove dependency on "English" version of translations

hoot-core/src/main/cpp/hoot/core/io/OgrUtilities.cpp
NOTE: this is added as an overall GDAL option. The Shapefile driver dies if it is given to it.
refs: #5340
=> Added GDAL config variable

conf/core/ConfigOptions.asciidoc, hoot-core/src/main/cpp/hoot/core/io/OgrUtilities.cpp, hoot-core/src/main/cpp/hoot/core/io/OgrUtilities.h, hoot-core/src/main/cpp/hoot/core/io/OgrWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/OgrWriter.h
Added transactions to GPKG, and added `OGR_SQLITE_CACHE`, `OGR_SQLITE_SYNCHRONOUS`, `SQLITE_USE_OGR_VFS` settings.
On sample data of substantial size, the approximate speed up of these changes was 25%.
Closes #5346
=> GPKG writing is slow

hoot-services/src/main/java/hoot/services/controllers/ogr/ExtractAttributesCommand.java, hoot-services/src/test/java/hoot/services/controllers/ogr/ExtractAttributesCommandTest.java
this used to be a default but got refactored here
ba4f8342799ea94a26c6f0470f40362a1ffb3895
to be no limit
this was causing performance problems in the Translations Assistant UI
when inputs had 10k+ unique attribute values
=> Add a tag limit of 30 when getting attribute info for translation assistant

docker/hoot_external_command_nightly/scripts/RunCommandsAcrossContainers.sh
- This PR is for sherlock to retain the original IDs from the data source when running the conflation (match only) command
=> Update sherlock match conflation command for IDs

LocalConfig.pri.orig, VagrantProvisionCentOS7.sh
Adding libasan and flags for the DEBUG build
=> Added support for ASAN

conf/core/ConfigOptions.asciidoc, hoot-core-test/src/test/cpp/hoot/core/io/OsmJsonReaderTest.cpp, hoot-core-test/src/test/cpp/hoot/core/io/ParallelBoundedApiReaderTest.cpp, hoot-core/src/main/cpp/hoot/core/elements/ElementId.cpp, hoot-core/src/main/cpp/hoot/core/elements/ElementId.h, hoot-core/src/main/cpp/hoot/core/index/OsmMapIndex.cpp, hoot-core/src/main/cpp/hoot/core/index/OsmMapIndex.h, hoot-core/src/main/cpp/hoot/core/io/HootNetworkRequest.cpp, hoot-core/src/main/cpp/hoot/core/io/HootNetworkRequest.h, hoot-core/src/main/cpp/hoot/core/io/OsmJsonReader.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmJsonReader.h, hoot-core/src/main/cpp/hoot/core/io/ParallelBoundedApiReader.cpp, hoot-core/src/main/cpp/hoot/core/io/ParallelBoundedApiReader.h, hoot-core/src/main/cpp/hoot/core/ops/RemoveWayByEid.cpp, test-files/io/OsmJsonReaderTest/overpass_query.oql
Refs #5398 
Parses overpass data.  Loads queries from file or from URL.  `OsmJsonReader` can now authenticate using PKCS-12 credentials.
NOTE:  Does not allow for polygon bounds yet.
=> Add Overpass API to ParallelBoundedReader

hoot-core-test/src/test/cpp/hoot/core/algorithms/WayJoinerConflateTest.cpp, hoot-core/src/main/cpp/hoot/core/conflate/matching/ScoreMatchesDiff.cpp, hoot-core/src/main/cpp/hoot/core/conflate/matching/ScoreMatchesDiff.h, hoot-core/src/main/cpp/hoot/core/elements/WayUtils.cpp, hoot-core/src/main/cpp/hoot/core/elements/WayUtils.h, hoot-core/src/main/cpp/hoot/core/io/ArffWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/ImplicitTagRulesSqliteReader.cpp, hoot-core/src/main/cpp/hoot/core/io/ImplicitTagRulesSqliteReader.h, hoot-core/src/main/cpp/hoot/core/io/IoUtils.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiDbBulkInserter.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiDbBulkInserter.h, hoot-core/src/main/cpp/hoot/core/io/OsmApiReader.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiReader.h, hoot-core/src/main/cpp/hoot/core/io/OsmJsonReader.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmJsonReader.h, hoot-core/src/main/cpp/hoot/core/io/ParallelBoundedApiReader.cpp, hoot-core/src/main/cpp/hoot/core/io/ParallelBoundedApiReader.h, hoot-core/src/main/cpp/hoot/core/ops/ReuseNodeIdsOnWayOp.cpp, hoot-core/src/main/cpp/hoot/core/schema/AttributeCoOccurrence.cpp, hoot-core/src/main/cpp/hoot/core/scoring/MatchFeatureExtractor.cpp, hoot-core/src/main/cpp/hoot/core/scoring/MatchFeatureExtractor.h, hoot-josm/src/main/cpp/hoot/josm/ops/JosmMapCleaner.h, test-files/cmd/quick/ScoreMatchesDiffCmdTest/output, tgs/src/main/cpp/tgs/Interpolation/DelaunayInterpolator.cpp
Allow the `ParallelBoundedApiReader` and derived classes to take in a polygon (file or text) as boundaries.  For simplicity the envelope of the bounds is queried and then the polygon is filtered.
Closes #5398
=> Polygon boundaries for overpass reader

hoot-services/src/main/java/hoot/services/controllers/auth/OAuth2Resource.java, hoot-services/src/main/java/hoot/services/controllers/auth/UserManager.java, hoot-services/src/main/java/hoot/services/controllers/auth/UserManagerImpl.java, hoot-services/src/test/java/hoot/services/controllers/auth/UserManagerTest.java
This PR adds more detailed error messages when the OAuth2 handshake doesn't complete successfully, most likely due to a misconfiguration in oauth2-client.properties.
If the redirect-uri is incorrect (or not registered with the oauth provider for this client key) the oauth popup will report the error `The requested redirect uri is malformed or doesn't match client redirect URI.`
If the oauth client id is incorrect the oauth popup will report the error `Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method.`
If the oauth client secret or the token uri is incorrect the UI alerts `Failed to retrieve access token from OAuth provider`.
If the authorization uri is incorrect the remote oauth provider will show an unknown route …
=> Improve OAuth error messages (mostly from server misconfiguration)

node-export-server/config.json, node-export-server/server.js
else the code continues and can cause a crash because a response has already been sent
>Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
=> Add geopackage to export formats, validate params needs to return on error

translations/TranslationServer.js, translations/checkAllFeatures.js, translations/checkTranslations.js
Added more utility functions to the NodeJS Schema test scripts.
=> More schema test helper functions

VagrantProvisionVars.sh, configure.ac
After testing there were no changes required by the unit tests.
=> Updated GEOS from 3.9.2 to 3.9.3 available from geoint-deps

sonar-project.properties
Updated sonar-project.properties to ignore the `enum class` rule and reformatted the file.
=> SONAR: Ignore `enum class` rule

docker/hoot_external_command_nightly/scripts/RunCommandsAcrossContainers.sh
- This PR updates the Sherlock-hoot capabilities to allow for automatic translation of a single file if building footprints have been extracted and need to be compared
=> sherlock hoot updates for translation

translations/ggdm30.js, translations/tds40.js, translations/tds61.js, translations/tds70.js, translations/tds71.js
In TDS && GGDM Vineyards (EA050) only have one Crop value (grape) and no option for `NoInformation` or `Other`. 
The translation was throwing an error when it tried to assign an `Other` value to the attribute
=> Fixed Vineyards

hoot-core-test/src/test/cpp/hoot/core/geometry/GeometryUtilsTest.cpp, hoot-core/src/main/cpp/hoot/core/algorithms/changeset/BoundsStringTaskGridGenerator.cpp, hoot-core/src/main/cpp/hoot/core/algorithms/changeset/ChangesetTaskGridReplacer.cpp, hoot-core/src/main/cpp/hoot/core/algorithms/changeset/UniformTaskGridGenerator.cpp, hoot-core/src/main/cpp/hoot/core/cmd/ExtentCmd.cpp, hoot-core/src/main/cpp/hoot/core/conflate/ConflateUtils.cpp, hoot-core/src/main/cpp/hoot/core/conflate/tile/NodeDensityTileBoundsCalculator.cpp, hoot-core/src/main/cpp/hoot/core/conflate/tile/TileUtils.cpp, hoot-core/src/main/cpp/hoot/core/elements/Way.cpp, hoot-core/src/main/cpp/hoot/core/geometry/GeometryUtils.cpp, hoot-core/src/main/cpp/hoot/core/geometry/GeometryUtils.h, hoot-core/src/main/cpp/hoot/core/io/ApiDbReader.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmJsonReader.cpp, hoot-core/src/main/cpp/hoot/core/io/ParallelBoundedApiReader.cpp, hoot-core/src/main/cpp/hoot/core/io/ParallelBoundedApiReader.h, hoot-core/src/main/cpp/hoot/core/ops/RandomMapCropper.cpp, hoot-core/src/main/cpp/hoot/core/util/Log.h, hoot-core/src/main/cpp/hoot/core/util/NodeDensityPlotter.cpp, test-files/cmd/quick/ExtentCmdTest.sh.stdout
Overpass UI does a bit of substitution for queries with embedded `{{bbox}}` bounding boxes, so in order for Hoot to work with those types of queries it needs to perform the same type of substitution.
Closes #5478
=> Overpass queries fail

hoot-core/src/main/cpp/hoot/core/io/ApiDb.cpp, hoot-core/src/main/cpp/hoot/core/io/HootApiDb.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiDbSqlChangesetApplier.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmJsonReader.cpp
All of the node/way/relation insert SQL statements in `SqlBulkInsert` appended the SQL magic of `ON CONFLICT DO NOTHING` to keep from inserting duplicate nodes/ways/relations into the database tables.  This, however, wasn't the case for the relation members table.  So when a duplicate relation was inserted that had the same exact relation members that query would fail (silently for some reason) and then the next insertion would crash Hootenanny.
Closes #5485
=> Merging multiple datasets in database causes crash

LocalConfig.pri.orig, hoot-core-test/src/test/cpp/hoot/core/io/OsmApiReaderTest.cpp, hoot-core-test/src/test/cpp/hoot/core/io/OsmApiReaderTestServer.cpp, hoot-core-test/src/test/cpp/hoot/core/io/OsmApiReaderTestServer.h, hoot-core-test/src/test/cpp/hoot/core/io/OsmApiWriterTestServer.cpp, hoot-core/src/main/cpp/hoot/core/io/ElementInputStream.h, hoot-core/src/main/cpp/hoot/core/io/ElementStreamer.cpp, hoot-core/src/main/cpp/hoot/core/io/ElementStreamer.h, hoot-core/src/main/cpp/hoot/core/io/HootNetworkRequest.cpp, hoot-core/src/main/cpp/hoot/core/io/HootNetworkRequest.h, hoot-core/src/main/cpp/hoot/core/io/IoUtils.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiReader.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiReader.h, hoot-core/src/main/cpp/hoot/core/io/OsmApiWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmXmlReader.h, hoot-core/src/main/cpp/hoot/core/io/ParallelBoundedApiReader.cpp, hoot-core/src/main/cpp/hoot/core/io/ParallelBoundedApiReader.h, hoot-core/src/main/cpp/hoot/core/util/HootNetworkUtils.h, hoot-core/src/main/cpp/hoot/core/util/OsmApiUtils.h, test-files/io/OsmApiReaderTest/ToyTestAOverpass1.osm, test-files/io/OsmApiReaderTest/ToyTestAOverpass2.osm
Converted `OsmApiReader` to actually stream data from the API.
Closes #5489
=> Including `bounds` parameter with `ParallelBoundedReader` should still stream

hoot-services/pom.xml
Soon as I updated to 2.13.4 I got another dependabot finding.
Reading through the [issue](https://github.com/FasterXML/jackson-databind/issues/3590) for fasterxml there are patch `2.12.7.1` releases in some package manager that is not the maven [repo](https://repo.maven.apache.org/maven2/com/fasterxml/jackson/core/jackson-core/) is reading from. Issue also describes updating to greater than or equal to 2.14.0 should remove the vulnerability
=> update fasterxml to 2.14.1

node-export-server/config.json, node-export-server/server.js
when POSTing an Overpass query result to the node-export server, it uses the <datasource> path param "Overpass".  A while ago parameter validation was added, but when using the POST endpoint (data is provided in the payload) the datasource param should just be ignored.
=> Don't require a node-export datasource named "Overpass"

hoot-core-test/src/test/cpp/hoot/core/io/ParallelBoundedApiReaderTest.cpp, hoot-core/src/main/cpp/hoot/core/io/ParallelBoundedApiReader.cpp
Update error handling for XML responses in `_isQueryError` and unit tests.
Closes #5545
=> Update `ParallelBoundedReader::_isQueryError()` to handle XML responses

hoot-core/src/main/cpp/hoot/core/io/OsmApiReader.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmJsonReader.cpp, hoot-core/src/main/cpp/hoot/core/io/ParallelBoundedApiReader.cpp, hoot-core/src/main/cpp/hoot/core/util/DateTimeUtils.h
Load overpass queryfile in `ParallelBoundedReader` instead of `OsmJsonReader` so that both XML and JSON Overpass queries use the query.
Closes #5543
=> Overpass queries in XML failing

conf/core/ConfigOptions.asciidoc, hoot-core/src/main/cpp/hoot/core/elements/Tags.cpp
Update the name matching in the Tags class to ignore street types
Expand the address.street.types to include drive
Closes #5549
=> Attribute Conflation Errors

conf/core/ConfigOptions.asciidoc, hoot-core/src/main/cpp/hoot/core/io/OgrWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/OgrWriter.h, test-files/cmd/slow/ConvertCmdTest.sh
Added `ogr.writer.crop.features.crossing.bounds` option (defaults to false) to control the OGR writer's cropping code.
Closes #5552
=> Add option to turn on/off OGR writer polygon cropping

hoot-core-test/src/test/cpp/hoot/core/io/ParallelBoundedApiReaderTest.cpp, hoot-core/src/main/cpp/hoot/core/io/OgrWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/ParallelBoundedApiReader.cpp
Using a regex instead of parsing the JSON/XML to speed up error detection and the regex didn't take into account a `remark` tag.  This fixes the remark tag issue.
Closes #5554
=> `Remark` tags cause Hoot to parse Overpass JSON incorrectly

hoot-core/src/main/cpp/hoot/core/algorithms/changeset/ChangesetTaskGridReplacer.cpp, hoot-core/src/main/cpp/hoot/core/elements/ExternalMergeElementSorter.cpp, hoot-core/src/main/cpp/hoot/core/geometry/ElementToGeometryConverter.cpp, hoot-core/src/main/cpp/hoot/core/geometry/RelationToMultiPolygonConverter.cpp, hoot-core/src/main/cpp/hoot/core/io/ApiDbReader.cpp, hoot-core/src/main/cpp/hoot/core/io/DataConverter.cpp, hoot-core/src/main/cpp/hoot/core/io/DataConverter.h, hoot-core/src/main/cpp/hoot/core/io/IoUtils.cpp, hoot-core/src/main/cpp/hoot/core/io/IoUtils.h, hoot-core/src/main/cpp/hoot/core/io/OgrWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmJsonReader.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmMapReaderFactory.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmMapReaderFactory.h, hoot-core/src/main/cpp/hoot/core/io/OsmXmlDiskCache.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmXmlReader.cpp, hoot-core/src/main/cpp/hoot/core/io/TranslationInterface.cpp, hoot-core/src/main/cpp/hoot/core/util/Boundable.cpp, hoot-core/src/main/cpp/hoot/core/util/Boundable.h
Cropping calls to `geos::geom::Geometry::intersection()` can throw a `geos::util::TopologyException` when the geometry is self-intersecting and cannot calculate the intersection.  This needs to be caught and dealt with.  Also when reading with `OsmXmlReader` into an OGR output file with cropping turned on, the reader shouldn't do any cropping, just let the `OgrWriter` do the cropping.
Closes #5561
=> Self-intersecting Geometry Issue

hoot-core/src/main/cpp/hoot/core/conflate/address/Address.cpp, hoot-core/src/main/cpp/hoot/core/conflate/address/Address.h
`Address::removeStreetTypes()` didn't remove abbreviations so when names were compared `Bryan Street == Bryan` but `Bryan Street != Bryan St`
Refs #5549
=> Attribute conflation fix

docker/hoot_external_command_nightly/scripts/RunCommandsAcrossContainers.sh
This PR resolves issues Sherlock was having interpreting hoot tags after conflation in complex matching scenarios.
=> Allow longer hoot tags with more complex matching scenarios

sonar-project.properties
Ignore `cpp:S3628` "Raw Strings" rule in Sonar.
=> Sonar: Ignore 'Raw Strings' rule

hoot-core/src/main/cpp/hoot/core/io/OsmApiReader.cpp
Fix the `OsmApiReader` to replace the `OsmMap` in the polygon criterion for bounds.
Closes #5589
=> Overpass XML error

hoot-core/src/main/cpp/hoot/core/io/CachedElementWriterInterface.cpp, hoot-core/src/main/cpp/hoot/core/io/CachedElementWriterInterface.h, hoot-core/src/main/cpp/hoot/core/io/OgrWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/OgrWriter.h
Move element cache from `OgrWriter` to a shared interface for other writer classes that need it.
=> Cached element writer interface

hoot-core-test/src/test/cpp/hoot/core/io/OverpassReaderInterfaceTest.cpp, hoot-core/src/main/cpp/hoot/core/io/OverpassReaderInterface.cpp, hoot-core/src/main/cpp/hoot/core/io/OverpassReaderInterface.h, hoot-core/src/main/cpp/hoot/core/io/ParallelBoundedApiReader.cpp
In some cases the overpass query file load function wasn't being called, fix that.
=> Load overpass query file through interface in all cases

hoot-services/src/main/java/hoot/services/command/ExternalCommandRunnerImpl.java
The bug we are seeing 
```
2023-03-14 19:17:53,864 INFO  ExternalCommandRunnerImpl:192 - Command hoot.bin info --tag-mergers --json started at: [2023-03-14T19:17:53.864]
Unexpected token RIGHT BRACE(}) at position 0.
at org.json.simple.parser.JSONParser.parse(JSONParser.java:257)
at org.json.simple.parser.JSONParser.parse(JSONParser.java:81)
at org.json.simple.parser.JSONParser.parse(JSONParser.java:75)
at hoot.services.controllers.conflation.AdvancedConflationOptionsResource.addGeneralMemberData(AdvancedConflationOptionsResource.java:357)
at hoot.services.controllers.conflation.AdvancedConflationOptionsResource.cacheTemplates(AdvancedConflationOptionsResource.java:188)
at hoot.services.HootServletContext.contextInitialized(HootServletContext.java:68)
at …
```
=> resolve logoutputstream nuance

conf/services/grailOverpassQuery.overpassql
The traverse up was meant to grab any relations containing the coastline or admin boundary.  These "extensive" features (can be part of very large areas) are not amenable to conflation so are then excluded from the dataset pulled in from Overpass.  However in a recent examination of the data by @maxgrossman it seemed that the untagged nodes of coastline ways were being left in the output.
Not sure why this would be unless traversing up to no parent relation then breaks the traverse down.
Edit:
I find that union'ing with `(   );` after tranversing up fixes this.
```
[out:json];
(node({{bbox}});<;>;)->.all;
(
relation({{bbox}})[natural=coastline];>;
(way({{bbox}})[natural=coastline];<;);>;
relation({{bbox}})[boundary=administrative];>;
(way({{bbox}})[boundary=administrative];<;);>; …
```
=> make overpass grail query only traverse down

VagrantProvisionCentOS7Rpm.sh, scripts/tomcat/configure_oauth_8443.sh, scripts/yum/update-hoot.sh
url needs to be https to auth with OSM OAuth2 provider
=> update echo msg and filename to reflect port 8443 when using hoot_centos7_rpm vm

hoot-core/src/main/cpp/hoot/core/io/CachedElementInterface.cpp, hoot-core/src/main/cpp/hoot/core/io/CachedElementInterface.h, hoot-core/src/main/cpp/hoot/core/io/ElementStreamer.cpp, hoot-core/src/main/cpp/hoot/core/io/OgrWriter.h, hoot-core/src/main/cpp/hoot/core/io/OsmApiReader.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiReader.h, hoot-core/src/main/cpp/hoot/core/io/OsmGeoJsonWriter.h, hoot-core/src/main/cpp/hoot/core/io/OsmXmlDiskCache.cpp
Renamed `CachedElementWriterInterface` to `CachedElementInterface` for use in readers.  Share the cache if streaming from a reader to a writer that both implement the interface.  `OsmApiReader` needed the interface to check the polygon bounds.
=> Cached element interface in `OsmApiReader`

conf/core/ConfigOptions.asciidoc, docs/commands/convert.asciidoc, hoot-core/src/main/cpp/hoot/core/cmd/ConvertCmd.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmXmlDiskCache.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmXmlReader.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmXmlReader.h, hoot-core/src/main/cpp/hoot/core/io/OsmXmlWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmXmlWriter.h, tgs/src/main/cpp/tgs/DelaunayTriangulation/DelaunayTriangulation.cpp
Added `--autoconfig-cache` to `hoot convert` that finds the amount of available memory and calculates an approximate maximum for nodes/ways/relations (overrides `element.cache.size.*` settings).
Closes #5542
=> Add option to auto-config element-cache sizes

translations/TranslationServer.js
This fixes an issue when translated presets are switched from one to another, and the code must remove the tags conferred by the old preset.  If there is an equivalent OSM preset for the tags, the old preset gets removed.  But if there is not, then the old translated schema preset remain and the feature now appears like two things (e.g. both sidewalk and trail).
=> Add OSM tags for FCODE to translated preset

hoot-core/src/main/cpp/hoot/core/io/ParallelBoundedApiReader.cpp
Fix Overpass error `runtime error: open64: 12 Cannot allocate memory /usr/share/overpass-api/db/relation_tags_global.bin`
=> Catch Overpass memory error

hoot-js/src/main/cpp/hoot/js/schema/JsonOsmSchemaLoader.cpp, hoot-js/src/main/cpp/hoot/js/schema/OsmSchemaJs.cpp, hoot-js/src/main/cpp/hoot/js/schema/OsmSchemaJs.h, rules/Polygon.js, test-files/cases/misc/network/roundabout-connector-conflate-merged-1/Expected.osm, test-files/cases/misc/unifying/roundabout-connector-conflate-merged-1/Expected.osm
For unifying conflation, "circular" roads match for both the `HighwayMatcher` and `Polygon.js` matcher thus causing a conflict and keeping both matches from conflating.  Updated the polygon matcher to not match against highways to remedy this.
Closes #5634
=> Boston Conflate - Circular road error

translations/TranslationServer.js
it is also called via the /schema code path
which in rare cases may be called before /translateFrom
=> TranslationServer init this createUuid global at the top

hoot-core/src/main/cpp/hoot/core/io/FlatGeobufWriter.h, hoot-core/src/main/cpp/hoot/core/io/OgrMultifileWriter.cpp, hoot-core/src/main/cpp/hoot/core/io/OgrMultifileWriter.h, hoot-core/src/main/cpp/hoot/core/io/ShapefileWriter.h
Create a multipolygon for all polygons so they can be in one layer together for FlatGeobuf files only.  Shapefiles allow for multi and polys in the same layer already, this creates a multipolygon with only one polygon in it and makes the layer a multipolygon layer.
=> Combine FlatGeobuf polygon layers into one layer

conf/core/ImportOverpass.conf
Need to match GrailIngest.conf when grail pull was refactored to be a hoot only command #5593 and no longer uses PushToDbCommand
=> Restore important hoot params when importing from Overpass API

hoot-core/src/main/cpp/hoot/core/io/TranslationInterface.cpp, hoot-core/src/main/cpp/hoot/core/io/TranslationInterface.h
Some relations aren't parsing correctly, don't fail, just skip
=> Skip bad geometries that throw `TopologyException` errors

hoot-core/src/main/cpp/hoot/core/io/ParallelBoundedApiReader.cpp, hoot-core/src/main/cpp/hoot/core/io/ParallelBoundedApiReader.h
Previously Overpass parse errors printed an error message but the executable returns `0` instead of an error code `-1`.  Fix that.
=> Error out on Overpass parse errors

hoot-core-test/src/test/cpp/hoot/core/algorithms/changeset/ChangesetCreatorTest.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmBaseXmlChangesetFileWriter.cpp, test-files/algorithms/changeset/ChangesetCreatorTest/ChangesetDeriveEmpty.osm, test-files/algorithms/changeset/ChangesetCreatorTest/ChangesetDeriveEmpty_expected.osc
Empty maps caused `hoot changeset-derive` to fail spectacularly.
=> Changeset derive empty map

translations/TranslationServer.js
some situations seem to have the osm json payload
escaped like "{\"version\":\"0.6\"...
and it misses the naive test and gets an xml parse error better for clients to set an application/json content-type
=> Add check for Content-Type header in addition to naive payload check for json starting with curly brace

hoot-core-test/src/test/cpp/hoot/core/index/metric-hybrid/FqTreeTest.cpp, hoot-core-test/src/test/cpp/hoot/core/index/metric-hybrid/RFqHybridTreeTest.cpp, hoot-core/src/main/cpp/hoot/core/geometry/PolygonCompare.cpp, hoot-core/src/main/cpp/hoot/core/geometry/PolygonCompare.h, hoot-core/src/main/cpp/hoot/core/io/OsmBaseXmlChangesetFileWriter.cpp, hoot-core/src/main/cpp/hoot/core/schema/OsmSchema.cpp, hoot-core/src/main/cpp/hoot/core/visitors/DecomposeBuildingRelationsVisitor.cpp
Newer GCC compilers come with deeper compile time analysis and errors.  Fix those errors in preparation to upgrade the compiler.
=> Compiler errors for `devtoolset-11`

conf/core/ConfigOptions.asciidoc, hoot-test/src/main/cpp/hoot/test/ProcessPool.cpp, hoot-test/src/main/cpp/hoot/test/ScriptTest.cpp, hoot-test/src/main/cpp/hoot/test/ScriptTest.h, hoot-test/src/main/cpp/hoot/test/main.cpp
Shorten glacial unit test max time and recover from hanging script error
=> Recover from random hanging unit test script

conf/core/ConfigOptions.asciidoc, hoot-core-test/src/test/cpp/hoot/core/io/ApiElementRetrievalInterfaceTest.cpp, hoot-core-test/src/test/cpp/hoot/core/ops/MissingElementRetrievalOpTest.cpp
Switch from `www.openstreetmap.org/api/*` to `api.openstreetmap.org/api/*` when using OpenstreetMaps API.
Was only found in a couple of unit tests and a comment in the configuration options but was requested by the community.
Closes #5720
=> Switch to api.openstreetmap.org API host

hoot-core-test/src/test/cpp/hoot/core/io/ParallelBoundedApiReaderTest.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmApiReader.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmJsonReader.cpp, hoot-core/src/main/cpp/hoot/core/io/OsmJsonReader.h, hoot-core/src/main/cpp/hoot/core/io/ParallelBoundedApiReader.cpp, hoot-core/src/main/cpp/hoot/core/io/ParallelBoundedApiReader.h, hoot-core/src/main/cpp/hoot/core/util/FileUtils.cpp, hoot-core/src/main/cpp/hoot/core/util/FileUtils.h, hoot-test/src/main/cpp/hoot/test/main.cpp
Remove `QString` and `QByteArray` conversions that throw 'bad_alloc' exceptions.
Closes #5728
=> Bad Allocation Exception in API Reader

node-export-server/server.js
Adds an append option.  This is ignored if the output isn't a FGDB.
It expects to see `appendFgdb=true`
=> Added an "appendFgdb" option to the node export server

node-export-server/server.js
there was a bug in Hoot's node export server that if a user requested an export for a GeoPackage in OSM Schema, the user would get an error about an invalid writer.
I found the bug was caused because the export command wasn't appending the translation script option.  I added a new scenario check that if the schema is OSM and format is GeoPackage to add all necessary params to the command
I have this deployed in testing if you want to test:
https://testing.vgihub.geointservices.io/export#map=17/38.81165/-77.62058
=> add scenario to fix bug in GeoPackage exports in OSM Schema

translations/tds71.js, translations/tds71_rules.js
- natural=beach now translates to a Soil Surface Region feature
- appropriate fields are assigned SRD (terrain morphology) = 1, TSM (terrain surface material) = 13 
- https://maxar.atlassian.net/browse/VGI-4893
=> update TDSv71 for natural=beach to soil surface region
